### ISSUE TITLE
Opt-out request for dfontenot

### ISSUE THREAD

**Issue by dfontenot** [bigcode-project/opt-out-v2#1]
I request that the following data is removed from The Stack:

 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by AverseABFun** [comment]
Go [here](https://huggingface.co/datasets/bigcode/the-stack?report=true) and report the stack model for legal/ethical issues. It might require you to enter your email first though(groan).

**Comment by AverseABFun** [comment]
Also, apparently NONE of the opt-out requests have been addressed. I'm also getting the feeling that this is only for the next version of the stack, which is its own problem. Who's with me in issuing a DMCA takedown?

**Comment by AverseABFun** [comment]
Sorry for all the comments, but everyone follow [this](https://huggingface.co/content-guidelines#:~:text=If%20you%20have%20any%20claims,flagging%20the%20allegedly%20infringing%20Content.)

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.0.1 of The Stack and all future versions. Also your data was not used for the training of StarCoder2.

[PROCESSED]
