### ISSUE TITLE
Opt-out request for willnorris

### ISSUE THREAD

**Issue by willnorris** [bigcode-project/opt-out-v2#1007]
I request that the following data is removed from The Stack and StackOverflow:

 - all
 - Commits
 - GitHub issue
 - willnorris/acme
 - willnorris/bundler-cache-test
 - willnorris/check-my-repo
 - willnorris/dotfiles
 - willnorris/gabenorris.com
 - willnorris/gcpsecret
 - willnorris/go-github
 - willnorris/go-webmention
 - willnorris/gomfweb
 - willnorris/gum
 - willnorris/imageproxy
 - willnorris/jekyll-clean-urls
 - willnorris/mail-manager
 - willnorris/microformats
 - willnorris/microformats-parser-website-go
 - willnorris/newbase60
 - willnorris/pdx-theme
 - willnorris/perkeep
 - willnorris/plus-profile-link
 - willnorris/repolinter-action
 - willnorris/rfcdash
 - willnorris/rootdir
 - willnorris/simpleproxy
 - willnorris/template-modules
 - willnorris/todogroup-dotgithub
 - willnorris/todogroup.org
 - willnorris/tools
 - willnorris/webmention
 - willnorris/willnorris.com
 - willnorris/willnorris.com-wordpress
 - willnorris/wordpress-analytics
 - willnorris/wordpress-google-plus
 - willnorris/wordpress-hum
 - willnorris/wordpress-opengraph
 - willnorris/wordpress-sermons
 - willnorris/wordpress-snowflake
 - willnorris/wordpress-snowstorm

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
