### ISSUE TITLE
Opt-out request for scheckley

### ISSUE THREAD

**Issue by scheckley** [bigcode-project/opt-out-v2#1016]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - scheckley/ProgrammingAssignment2
 - scheckley/alpine_ds
 - scheckley/cmapPy
 - scheckley/deSolve
 - scheckley/drug_modelling
 - scheckley/geonames-python
 - scheckley/journal_club_slides
 - scheckley/kaggle_expedia
 - scheckley/matlab-cobaltized
 - scheckley/matlab-palenight
 - scheckley/moc_eqsets
 - scheckley/pocketchip
 - scheckley/pyspark_vgsales
 - scheckley/shiny_mm
 - scheckley/shiny_pres
 - scheckley/srep13545

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
