### ISSUE TITLE
Opt-out request for Ladsgroup

### ISSUE THREAD

**Issue by Ladsgroup** [bigcode-project/opt-out-v2#1023]
I request that the following data is removed from The Stack:

- Commits: all
- GitHub issue: all
- All of my repos:
  - Ladsgroup/Bad-Words-Detection-System
  - Ladsgroup/Building-automated-vandalism-detection-tool-for-Wikidata
  - Ladsgroup/Editing-movement-metrics
  - Ladsgroup/Kian
  - Ladsgroup/Kian-web
  - Ladsgroup/MP3-cleaner
  - Ladsgroup/ORES-IRC-Wikidata-bot
  - Ladsgroup/PEP257fier
  - Ladsgroup/Phabricator-Reporter
  - Ladsgroup/Pywikibot-nightly-creator
  - Ladsgroup/Snowball
  - Ladsgroup/TF-on-ORES
  - Ladsgroup/WikiEduDashboard
  - Ladsgroup/WikimediaMeetAuth
  - Ladsgroup/WikipediaTech
  - Ladsgroup/change-propagation
  - Ladsgroup/mediawiki-extensions-WikibaseLexeme
  - Ladsgroup/primarysources
  - Ladsgroup/sync_github_bot
  - Ladsgroup/tofawiki
  - Ladsgroup/wikipedia-react-components
  - Ladsgroup/zimmerbot

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
