### ISSUE TITLE
Opt-out request for mkacer

### ISSUE THREAD

**Issue by mkacer** [bigcode-project/opt-out-v2#1026]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: mkacer
 - mkacer/emacs-config
 - mkacer/awesome-gemini
 - mkacer/dotfiles
 - mkacer/emacs-config
 - All

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
