### ISSUE TITLE
Opt-out request for DrewHans555

### ISSUE THREAD

**Issue by DrewHans** [bigcode-project/opt-out-v2#1035]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - DrewHans555/C-AwayWithExtendedASCII
 - DrewHans555/HuffmanCompression
 - DrewHans555/Illinois-Judici-Web-Scraper
 - DrewHans555/Kana2Romaji-File-Renamer
 - DrewHans555/MALwaRe
 - DrewHans555/Neuronmancer
 - DrewHans555/Pr0Ca1
 - DrewHans555/PythonMazeCode
 - DrewHans555/Tired-Of-Losing-My-Configs
 - DrewHans555/UntanglingRacket
 - DrewHans555/dotfiles
 - DrewHans555/shellscripts
 - DrewHans555/txtfiles
 - all

Note: my username was changed two years ago, but the code is still mine

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
