### ISSUE TITLE
Opt-out request for qwertmax

### ISSUE THREAD

**Issue by qwertmax** [bigcode-project/opt-out-v2#1039]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - qwertmax/angular_profiles_selector
 - qwertmax/app1
 - qwertmax/app2
 - qwertmax/cv
 - qwertmax/deployer_ssh
 - qwertmax/docker-drupal
 - qwertmax/docker-wkhtmltopdf
 - qwertmax/fingerprint
 - qwertmax/go-app-k8s
 - qwertmax/go-aws-lambda
 - qwertmax/go-crm
 - qwertmax/go-streaming
 - qwertmax/golang-basic-authentication-jwt
 - qwertmax/helm-kubectl
 - qwertmax/http-keep-alive
 - qwertmax/jenkins-with-docker
 - qwertmax/keyczar
 - qwertmax/kubectl-tips
 - qwertmax/log_parser
 - qwertmax/lstorage
 - qwertmax/movie_search
 - qwertmax/multi_curl
 - qwertmax/npm-ci-postinstall
 - qwertmax/opencv-car-detection-video
 - qwertmax/pages
 - qwertmax/puppeter
 - qwertmax/qr-code
 - qwertmax/qr-code-library
 - qwertmax/quiz-go
 - qwertmax/retirement_calculator
 - qwertmax/sitemap-generator
 - qwertmax/terraform
 - qwertmax/terraform-digitalocean
 - qwertmax/test-semver
 - qwertmax/understanding-arrow-function-context
 - qwertmax/vcard
 - qwertmax/vpn-netextender
 - qwertmax/wercker-mesosphere

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
