### ISSUE TITLE
Opt-out request for jckarter

### ISSUE THREAD

**Issue by jckarter** [bigcode-project/opt-out-v2#104]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - jckarter/BattleMints
 - jckarter/CalTalk
 - jckarter/Footsie
 - jckarter/Megacanvas
 - jckarter/Sokoban.html
 - jckarter/Trixel
 - jckarter/WinDock
 - jckarter/cat-psychiatrist
 - jckarter/ch5-flag
 - jckarter/clang
 - jckarter/clay-lua
 - jckarter/clay-sqlite
 - jckarter/dgen-sdl
 - jckarter/durians
 - jckarter/graphs.js
 - jckarter/llvm
 - jckarter/newclay
 - jckarter/ocaml-objc
 - jckarter/rowsdower
 - jckarter/shinobi
 - jckarter/swift-evolution
 - jckarter/swift-generics-experiments
 - jckarter/zissou

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
