### ISSUE TITLE
Opt-out request for sebastian-palma

### ISSUE THREAD

**Issue by sebastian-palma** [bigcode-project/opt-out-v2#1042]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - sebastian-palma/asyncapi-react
 - sebastian-palma/brutal
 - sebastian-palma/doctest
 - sebastian-palma/generator-filters
 - sebastian-palma/i_m_freezing
 - sebastian-palma/liam
 - sebastian-palma/sebastian-palma.github.io
 - sebastian-palma/skunk
 - sebastian-palma/yaasql
 - sebastian-palma/yesql
 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
