### ISSUE TITLE
Opt-out request for scruss

### ISSUE THREAD

**Issue by scruss** [bigcode-project/opt-out-v2#1046]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - scruss/1pw2kpxxml
 - scruss/AmigaTraces-GFA_Source
 - scruss/DXFlaserutils
 - scruss/FreeBASIC_Blink
 - scruss/Gurney-7B
 - scruss/ICQuestionBank2csv
 - scruss/IRTowerFanExample
 - scruss/KeySwitch
 - scruss/LCM1602-14_LCD_Library
 - scruss/MeterEmulator
 - scruss/OptrexLCD
 - scruss/Powermon433
 - scruss/TO-dinesafe-xslt
 - scruss/Vax_Empire
 - scruss/brainpad-micropython
 - scruss/cpx_chord_guitar
 - scruss/ieso_xslt
 - scruss/ihsctrl
 - scruss/mcp4131
 - scruss/shutdown_button
 - scruss/taflmunge

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
