### ISSUE TITLE
Opt-out request for sirensolutions

### ISSUE THREAD

**Issue by andrewgdotcom** [bigcode-project/opt-out-v2#1057]
I request that the following data is removed from The Stack:

 - all

**Comment by lvwerra** [comment]
Hi @andrewgdotcom, thanks for submitting an opt-out request. Could you specify your affiliation with `sirensolutions`? From a quick glance it seems that you are not the main maintainer/contributor of the project.

**Comment by andrewgdotcom** [comment]
sirensolutions is not a project, it's an organisation, and I'm the admin.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
