### ISSUE TITLE
Opt-out request for eBerdnA

### ISSUE THREAD

**Issue by eBerdnA** [bigcode-project/opt-out-v2#1060]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - eBerdnA/70483
 - eBerdnA/ExploBitmask
 - eBerdnA/FuncDataSink
 - eBerdnA/MetaMarkdownDnx
 - eBerdnA/PowerShellCollection
 - eBerdnA/ScaffoldTestDnx
 - eBerdnA/azure-policies
 - eBerdnA/cloudscribe.SimpleContent
 - eBerdnA/cloudscribe.Syndication
 - eBerdnA/commonmark-ext-prepend-image
 - eBerdnA/eberdna.github.io
 - eBerdnA/jekylltest
 - eBerdnA/misc-helper
 - eBerdnA/mysite
 - eBerdnA/saf
 - eBerdnA/tale-hugo
 - eBerdnA/tinyserv

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
