### ISSUE TITLE
Opt-out request for lukereichold

### ISSUE THREAD

**Issue by lukereichold** [bigcode-project/opt-out-v2#1064]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - lukereichold/ASCII-Pro
 - lukereichold/AoC_2019
 - lukereichold/Asteroids-3D
 - lukereichold/Coding-Challenges
 - lukereichold/HealthViewer
 - lukereichold/JOSESwift
 - lukereichold/Portfolio
 - lukereichold/SpeechTimestamper
 - lukereichold/Surge
 - lukereichold/VisualActionKit
 - lukereichold/adventofcode
 - lukereichold/box-setup
 - lukereichold/coremltools
 - lukereichold/haskell-exercises
 - lukereichold/http-server
 - lukereichold/iSLUH
 - lukereichold/machinelearning
 - lukereichold/oauth1-signer-swift
 - lukereichold/prolog-exercises
 - lukereichold/stellar-ios-mac-sdk
 - lukereichold/stjoe-ios
 - lukereichold/swift-models
 - lukereichold/swift-multiaddr
 - lukereichold/swiftweekly.github.io
 - lukereichold/turicreate
 - lukereichold/visual-speech-separation
 - lukereichold/website

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
