### ISSUE TITLE
Opt-out request for Cipscis

### ISSUE THREAD

**Issue by Cipscis** [bigcode-project/opt-out-v2#1066]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: Cipscis
 - Cipscis/ASA-Data-Vis
 - Cipscis/NodeGraph
 - Cipscis/Papyrus_Assembly
 - Cipscis/PatchedConics
 - Cipscis/Vector
 - Cipscis/Vector2D
 - Cipscis/audio-dashboard
 - Cipscis/blog-features
 - Cipscis/connect-4
 - Cipscis/csv
 - Cipscis/debounce
 - Cipscis/dnd-helper
 - Cipscis/expander
 - Cipscis/gizmobot
 - Cipscis/keybinding
 - Cipscis/modal
 - Cipscis/oia-guide
 - Cipscis/throttle
 - Cipscis/tkdaction

I am frankly disgusted that I found out about this data source purely by chance. An "opt out" model where the onus is left on people whose data has been scraped to discover that the project even exists in the first place is absolutely not a consensual process. Given how difficult or impossible it can be to un-train "AI" models, an "opt out" model like this also doesn't allow people like me to actually prevent stolen data from being used to train models even if we do opt out.

My GitHub repositories often have licences that would not allow them to be used to train "AI" models.

You should be ashamed of your work, and you should delete this entire project immediately and tell everyone who used it to train their models to delete those models.

When I create new repos on GitHub, don't you dare scrape them for training "AI" tools.

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
