### ISSUE TITLE
Opt-out request for cygnuson

### ISSUE THREAD

**Issue by cygnuson** [bigcode-project/opt-out-v2#1069]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - cygnuson/Card-Game-Of-26
 - cygnuson/Console
 - cygnuson/Console-Library
 - cygnuson/Examples
 - cygnuson/Examples_shunting-yard-algorithm_WindowsConsoleController_with_debugServer
 - cygnuson/Just-Another-Block-Game
 - cygnuson/Mathpp
 - cygnuson/MattsLibrary
 - cygnuson/Physics_Box2d_Example
 - cygnuson/Project-11
 - cygnuson/Project-12
 - cygnuson/SFMLApp_pimpl-with-polymorphism_cpp
 - cygnuson/SFMLApplication_with_networking
 - cygnuson/Serializer_with_all_containers_tuple_polymorphic_support
 - cygnuson/SortedLinkedListExample
 - cygnuson/TheDevice
 - cygnuson/Tile-MMO-Java
 - cygnuson/UNITY_CygnusCams
 - cygnuson/c_list_demo
 - cygnuson/wxAuthProviderDialog

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
