### ISSUE TITLE
Opt-out request for sparkfun

### ISSUE THREAD

**Issue by nseidle** [bigcode-project/opt-out-v2#1072]
I own and represent username sparkfun.
 
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - sparkfun/APDS-9301_Breakout
 - sparkfun/Addressable-LED-Neon-Flex-Rope
 - sparkfun/Apollo3_Uploader_ASB
 - sparkfun/Arduino_Apollo3
 - sparkfun/Arduino_Boards
 - sparkfun/Artemis-Firmware-Upload-GUI
 - sparkfun/Arudino_Release_Form.io
 - sparkfun/BAC_Lager
 - sparkfun/BadgerHack_Demos
 - sparkfun/Big_GPS_Clock
 - sparkfun/CherryMX-Chord-Keyer
 - sparkfun/Conference_Room_Signs
 - sparkfun/Current_Sensor_Breakout-ACS723-Low_Current
 - sparkfun/Cyber_Monday_IoT_Hobby_Kit
 - sparkfun/DE2120_Py
 - sparkfun/ESP32_Power_Control_Shield
 - sparkfun/ESP8266_Thing_Dev_4H
 - sparkfun/ESP8266_WiFi_IR_Blaster
 - sparkfun/EiBotBoard
 - sparkfun/Electrocute_ETextile_Projects
 - sparkfun/Fidget_Spinners
 - sparkfun/Flask_Tutorial
 - sparkfun/FreeSoC2_Keysynth
 - sparkfun/GlitchBooth
 - sparkfun/Graphical_Datasheets
 - sparkfun/IR-Control-Kit
 - sparkfun/Inventors_Kit_For_Photon_Experiments
 - sparkfun/KickScraper
 - sparkfun/LSM303C_6_DOF_IMU_Breakout
 - sparkfun/LilyPad_LED_Rainbow
 - sparkfun/LilyPad_ProtoSnap_Development_Board_Activity_Guide
 - sparkfun/LilyPad_ProtoSnap_Plus_Activity_Guide
 - sparkfun/MiP_Proto-Back
 - sparkfun/Nerf-Atrium-Defense-System
 - sparkfun/Non-Addressable_RGB_LED_Strip_Code
 - sparkfun/Photon_Weather_Shield
 - sparkfun/PiServoHat_Py
 - sparkfun/QuickLogic_QTPlus
 - sparkfun/Qwiic-Kit-for-Pi
 - sparkfun/QwiicBus_MidPoint
 - sparkfun/Qwiic_ADXL313_Py
 - sparkfun/Qwiic_AS6212_Py
 - sparkfun/Qwiic_Air_Quality_Sensor_SGP40
 - sparkfun/Qwiic_Alphanumeric_Py
 - sparkfun/Qwiic_Button_Py
 - sparkfun/Qwiic_CCS811_Py
 - sparkfun/Qwiic_EEPROM_Py
 - sparkfun/Qwiic_GPS_Clock_Project
 - sparkfun/Qwiic_Haptic_Driver_DA7280
 - sparkfun/Qwiic_I2C_Py
 - sparkfun/Qwiic_KX13X
 - sparkfun/Qwiic_Keypad_Py
 - sparkfun/Qwiic_MultiPort
 - sparkfun/Qwiic_PIR_Py
 - sparkfun/Qwiic_Proximity_Py
 - sparkfun/Qwiic_Py
 - sparkfun/Qwiic_RFID_Py
 - sparkfun/Qwiic_Relay_Py
 - sparkfun/Qwiic_SCMD_Py
 - sparkfun/Qwiic_SGP40_Py
 - sparkfun/Qwiic_SHIM_Kit
 - sparkfun/Qwiic_SerLCD_Py
 - sparkfun/Qwiic_Shield_for_Thing_Plus
 - sparkfun/Qwiic_Soil_Moisture_Sensor_Py
 - sparkfun/Qwiic_TCA9548A_Py
 - sparkfun/Qwiic_TMP102_Py
 - sparkfun/Qwiic_Template_Py
 - sparkfun/Qwiic_Titan_Gps_Py
 - sparkfun/Qwiic_VL53L1X_Py
 - sparkfun/RPi_PanTilt_Camera_Kit
 - sparkfun/Reaction_Timer
 - sparkfun/Resistance_Combinator_Calculator
 - sparkfun/SFE-Lunchbox
 - sparkfun/SFE_LFS
 - sparkfun/SIK_Guide
 - sparkfun/SillyString_Shooter
 - sparkfun/SparkFun-KiCad-Libraries
 - sparkfun/SparkFun-Live-Analog-Audio
 - sparkfun/SparkFun_APDS9301_Library
 - sparkfun/SparkFun_Apollo3_AmbiqSuite_BSPs
 - sparkfun/SparkFun_Bio_Sensor_Hub_Library
 - sparkfun/SparkFun_Eagle_Settings
 - sparkfun/SparkFun_GridEYE_Arduino_Library
 - sparkfun/SparkFun_HM01B0_Camera_ArduinoLibrary
 - sparkfun/SparkFun_HyperDisplay-wiki
 - sparkfun/SparkFun_LSM303C_6_DOF_IMU_Breakout_Arduino_Library
 - sparkfun/SparkFun_LSM9DS1_Particle_Library
 - sparkfun/SparkFun_MG2639_Cellular_Shield_Arduino_Library
 - sparkfun/SparkFun_MLX90614_Arduino_Library
 - sparkfun/SparkFun_MPL3115A2_Particle_Library
 - sparkfun/SparkFun_MS5637_Arduino_Library
 - sparkfun/SparkFun_PL-N823_Arduino_Library
 - sparkfun/SparkFun_Pulsed_Radar_A111_Example_Code
 - sparkfun/SparkFun_QwiicRF_Library
 - sparkfun/SparkFun_Qwiic_Digital_Capacitor_Arduino_Library
 - sparkfun/SparkFun_Qwiic_Power_Switch_Arduino_Library
 - sparkfun/SparkFun_Qwiic_RFID_Arduino_Library
 - sparkfun/SparkFun_Qwiic_Step_Arduino_Library
 - sparkfun/SparkFun_SX1509_Arduino_Library
 - sparkfun/SparkFun_VL53L1X_Arduino_Library
 - sparkfun/Spectacle_Audio_Output_Board
 - sparkfun/Spectacle_Button_Input_Board
 - sparkfun/Spectacle_Motion_Board
 - sparkfun/Speed_Trap
 - sparkfun/Stranger_Things_Wall
 - sparkfun/Top_pHAT_Button_Py
 - sparkfun/USB_Bit_Whacker-18F2553
 - sparkfun/USB_Weather_Board
 - sparkfun/USB_microB_Breakout_Board
 - sparkfun/VReg_Temp_Mobile_App
 - sparkfun/Vox_Imperium
 - sparkfun/Wireless-RC-Robot-with-Arduino-and-XBee
 - sparkfun/according-to-pete
 - sparkfun/artemis_dev_platform
 - sparkfun/artmbed
 - sparkfun/author_application
 - sparkfun/eng_application
 - sparkfun/freedom-e-sdk
 - sparkfun/jetbot_ros
 - sparkfun/mbed-os-example-blinky-baremetal
 - sparkfun/nRF52832_Breakout_Demo
 - sparkfun/phant-docs
 - sparkfun/phant-monitor
 - sparkfun/pxt-gamer-bit
 - sparkfun/pxt-gator-UV
 - sparkfun/pxt-gator-environment
 - sparkfun/pxt-gator-light
 - sparkfun/pxt-gator-log
 - sparkfun/pxt-gator-microphone
 - sparkfun/pxt-gator-particle
 - sparkfun/pxt-gator-rtc
 - sparkfun/pxt-gator-soil
 - sparkfun/pxt-moto-bit
 - sparkfun/pxt-tmp36
 - sparkfun/pxt-weather-bit
 - sparkfun/samd_windows7_installer
 - sparkfun/spectacleapp
 - sparkfun/sysadmin-application
 - sparkfun/tetrixMotor

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
