### ISSUE TITLE
Opt-out request for deuxpi

### ISSUE THREAD

**Issue by deuxpi** [bigcode-project/opt-out-v2#1074]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: deuxpi
 - deuxpi/advent2019
 - deuxpi/bitcoin-otc
 - deuxpi/daft
 - deuxpi/demo
 - deuxpi/dotfiles
 - deuxpi/dotvim
 - deuxpi/home-assistant-cookbook
 - deuxpi/mtlpy57
 - deuxpi/odj2txt
 - deuxpi/passwordcard
 - deuxpi/pyramid_auth_demo
 - deuxpi/pyramid_royal
 - deuxpi/redshift-hue
 - deuxpi/shopify-ruby-notebook
 - deuxpi/silvertiger
 - deuxpi/wip

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
