### ISSUE TITLE
Opt-out request for dougwritescode

### ISSUE THREAD

**Issue by dougwritescode** [bigcode-project/opt-out-v2#1076]
I request that the following data be removed from The Stack and StackOverflow:

 - dougwritescode/PyCAH
 - dougwritescode/PyNigma
 - dougwritescode/boardslice
 - dougwritescode/pyCAH
 - dougwritescode/pystickbuglol
 - dougwritescode/xkcdpassword

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
