### ISSUE TITLE
Opt-out request for rgm

### ISSUE THREAD

**Issue by rgm** [bigcode-project/opt-out-v2#1088]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - rgm/BarbaryWatchService
 - rgm/Noisy
 - rgm/Paw-MountebankGenerator
 - rgm/bidi-pushy-example
 - rgm/big-monkey-safari
 - rgm/bin
 - rgm/canary
 - rgm/clojure-experiments
 - rgm/dotfiles
 - rgm/fork
 - rgm/hello-lagrangian
 - rgm/marionette
 - rgm/meteor-flipper
 - rgm/meteor-flipper-ruby
 - rgm/meteor-smalot-bootstrap-2-datetimepicker
 - rgm/miniature-hipster
 - rgm/read52
 - rgm/reframe-template
 - rgm/statusboard
 - rgm/vectorscript-vim
 - rgm/vectorscript.tmbundle
 - rgm/vectorworks
 - rgm/vectorworks-mysql
 - rgm/vectorworks-postgres
 - rgm/vim-meteor

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
