### ISSUE TITLE
Opt-out request for jamesnvc

### ISSUE THREAD

**Issue by jamesnvc** [bigcode-project/opt-out-v2#1096]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: jamesnvc
 - jamesnvc/Color
 - jamesnvc/DiploBot
 - jamesnvc/DropChef
 - jamesnvc/IronSports
 - jamesnvc/MiscellaneousWritingStuff
 - jamesnvc/MusashiClient
 - jamesnvc/SkuleVote
 - jamesnvc/Thesis-serverside
 - jamesnvc/brubeck
 - jamesnvc/brubeck-example
 - jamesnvc/caves
 - jamesnvc/cljs-toolreader-debugging
 - jamesnvc/clojurenorth-2020-functional-programming-workshop
 - jamesnvc/comicnav
 - jamesnvc/css_write
 - jamesnvc/currmap-sesame
 - jamesnvc/debug_adapter
 - jamesnvc/discourse-linkify-prolog-predicates
 - jamesnvc/dotfiles
 - jamesnvc/flax
 - jamesnvc/git-util
 - jamesnvc/highlight-vimscript
 - jamesnvc/http2_client
 - jamesnvc/inotify
 - jamesnvc/julian_lang_en
 - jamesnvc/lsp_server
 - jamesnvc/mealplan
 - jamesnvc/msgpack
 - jamesnvc/pluuid
 - jamesnvc/potion
 - jamesnvc/skule-auth
 - jamesnvc/tailwind_pl
 - jamesnvc/tconnect
 - jamesnvc/terfblocklist
 - jamesnvc/terminus-client-clojure
 - jamesnvc/tree-sitter-prolog
 - jamesnvc/uuid
 - jamesnvc/vim-penyocomic
 - jamesnvc/vim-scraper.github.com
 - jamesnvc/watdo
 - jamesnvc/whiteboarding-notes
 - jamesnvc/www_fdw
 - all

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
