### ISSUE TITLE
Opt-out request for michelp

### ISSUE THREAD

**Issue by michelp** [bigcode-project/opt-out-v2#1098]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - michelp/0pl
 - michelp/Daphony
 - michelp/GraphBLAS
 - michelp/LAGraph
 - michelp/cmmap
 - michelp/cudafor
 - michelp/emacsd
 - michelp/glaph
 - michelp/know-sql
 - michelp/mmparse
 - michelp/nancy
 - michelp/nerve
 - michelp/pgexpanded
 - michelp/pgjwt
 - michelp/pgsodium
 - michelp/postgrest-gis-demo
 - michelp/pygraphblas
 - michelp/python-suitesparse-graphblas
 - michelp/ssgbcpp
 - michelp/ssgetpy
 - michelp/structchunk
 - michelp/thdnn
 - michelp/wikiparser
 - michelp/xodb
 - michelp/xodb2
 - michelp/zerocat
 - michelp/zypre
 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
