### ISSUE TITLE
opt out request

### ISSUE THREAD

**Issue by Fauli1221** [bigcode-project/opt-out-v2#11]
I request that the following data is removed from The Stack:

 - all
 
_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.
...

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.0.1 of The Stack and all future versions. Also your data was not used for the training of StarCoder2.

[PROCESSED]
