### ISSUE TITLE
Remove my data

### ISSUE THREAD

**Issue by snake-biscuits** [bigcode-project/opt-out-v2#110]
I request that the following data is removed from The Stack:

 - Commits
 - GitHub issue
 - snake-biscuits/vmf_tool
 - snake-biscuits/advent-of-code-2020
 - all
 
As well as any contributions attributed to my username, regardless of GitHub organisation.
And all future contributions I make, including wiki pages, GitHub discussions, pull requests & comments

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
