### ISSUE TITLE
Opt-out request for tcyrus

### ISSUE THREAD

**Issue by tcyrus** [bigcode-project/opt-out-v2#1100]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: tcyrus
 - tcyrus/BlindJoker-Startpage
 - tcyrus/Clion
 - tcyrus/DatPart
 - tcyrus/Iodine-Bellschedule-Pebble
 - tcyrus/IodineSSOAPI
 - tcyrus/PPaaS
 - tcyrus/RCOS-MM-Bot
 - tcyrus/ServerToolkit
 - tcyrus/Submitty
 - tcyrus/SwitchRPC
 - tcyrus/TikTokLink-Downloader
 - tcyrus/WiringPi-Go
 - tcyrus/aim-final-project
 - tcyrus/apm-badges
 - tcyrus/apt-cyg
 - tcyrus/clevis-decrypt-zfs
 - tcyrus/collectd-eos
 - tcyrus/craig
 - tcyrus/diamond
 - tcyrus/dokuwiki-infobox
 - tcyrus/eden
 - tcyrus/electron-packager-interactive
 - tcyrus/fpx
 - tcyrus/glass-browser
 - tcyrus/go-ds-badger
 - tcyrus/gpp
 - tcyrus/grav-theme-rca
 - tcyrus/hackaday-io-badges
 - tcyrus/hacktj2016
 - tcyrus/hackwheel
 - tcyrus/hashbase
 - tcyrus/heroku-escobar
 - tcyrus/hosts-daemon
 - tcyrus/hrqr
 - tcyrus/hubot-minecraft
 - tcyrus/image-generation
 - tcyrus/ipfs-pin
 - tcyrus/ipfs-podcasts
 - tcyrus/jsonb_set_lax
 - tcyrus/lambda-compile
 - tcyrus/language-lolcode
 - tcyrus/manga-ipfs-front
 - tcyrus/material-foundation
 - tcyrus/md2mla
 - tcyrus/musescore-rich-presence
 - tcyrus/my-punch-card
 - tcyrus/nerd-merit-badges
 - tcyrus/parallel-final-project
 - tcyrus/photon-boilerplate
 - tcyrus/portis
 - tcyrus/python
 - tcyrus/random
 - tcyrus/renpy-encyclopaedia
 - tcyrus/russian-poster
 - tcyrus/russian-project
 - tcyrus/s4-ipfs
 - tcyrus/sheethub
 - tcyrus/signin-for-pebble
 - tcyrus/stackathon
 - tcyrus/swiss-army-spoon
 - tcyrus/tcyrus
 - tcyrus/tcyrus-elements
 - tcyrus/tcyrus.github.io
 - tcyrus/tj-csl-esoteric
 - tcyrus/tjTimeFaceC
 - tcyrus/tjhsst-electron-dayschedule
 - tcyrus/unix-adventure
 - tcyrus/vpa17.github.io
 - tcyrus/whats-a-hackathon
 - tcyrus/wistfulbooks
 - tcyrus/xkcd-simplewriter
 - tcyrus/xterm-tui
 - tcyrus/zircon

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
