### ISSUE TITLE
Opt-out request for cemelo

### ISSUE THREAD

**Issue by cemelo** [bigcode-project/opt-out-v2#1105]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: Carlos Melo
 - cemelo/anygrade-platform
 - cemelo/anygrade-web-client
 - cemelo/appcues-incr
 - cemelo/aurora-charts
 - cemelo/codin-bot
 - cemelo/dependent
 - cemelo/duna-core-kotlin
 - cemelo/duna-java
 - cemelo/duna-project
 - cemelo/hydra2java
 - cemelo/inflector
 - cemelo/mockito
 - cemelo/mulimodule-main
 - cemelo/node-irc-dcc
 - cemelo/persistence-utils
 - cemelo/quill-contrib
 - cemelo/siop-commons
 - cemelo/siop-receita
 - cemelo/siop-ui
 - cemelo/tcc-rosana
 - cemelo/thrift-gradle-plugin
 - cemelo/ws-commons

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
