### ISSUE TITLE
Opt-out request for YinYin-Falcon

### ISSUE THREAD

**Issue by YinYin-Falcon** [bigcode-project/opt-out-v2#1110]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - YinYin-Falcon/Heed-Etyliv
 - YinYin-Falcon/QRGOAL
 - YinYin-Falcon/VDC
- all

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
