### ISSUE TITLE
Opt-out request for vii1

### ISSUE THREAD

**Issue by vii1** [bigcode-project/opt-out-v2#1111]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: vii
 - vii1/DIV2Help
 - vii1/DIVcompo2020-devlog
 - vii1/Ecstatic
 - vii1/ExplosionGenerator
 - vii1/KuruEngine2
 - vii1/Letra
 - vii1/Main
 - vii1/Scavengers
 - vii1/SubculturaMobile
 - vii1/boom3
 - vii1/cobaya
 - vii1/docker-archlinux-multibuild
 - vii1/dungeon
 - vii1/functions
 - vii1/gameboy-cpu-reference
 - vii1/gb2001
 - vii1/ghost.dll
 - vii1/madmix
 - vii1/msvc
 - vii1/play3d
 - vii1/vsbuild
 - vii1/vscode-div
 - vii1/wasi

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
