### ISSUE TITLE
Opt-out request for undergroundmonorail

### ISSUE THREAD

**Issue by undergroundmonorail** [bigcode-project/opt-out-v2#1118]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: undergroundmonorail
 - undergroundmonorail/BudgetBuster
 - undergroundmonorail/KeepUp
 - undergroundmonorail/RhythmSurgeon
 - undergroundmonorail/advent-of-code-2019
 - undergroundmonorail/advent-of-code-2020
 - undergroundmonorail/brainfuck-debug
 - undergroundmonorail/easyreply
 - undergroundmonorail/floodfill
 - undergroundmonorail/fs_stats
 - undergroundmonorail/git-append
 - undergroundmonorail/input-display
 - undergroundmonorail/pb-lang
 - undergroundmonorail/toolbox.py
 - undergroundmonorail/youtube-time-bot

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
