### ISSUE TITLE
Opt-out request for bzinberg

### ISSUE THREAD

**Issue by bzinberg** [bigcode-project/opt-out-v2#1119]
I request that the following data is removed from The Stack and StackOverflow:

 - all
 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - bzinberg/MCS
 - bzinberg/Memoize.jl
 - bzinberg/anagrams_with_fiends
 - bzinberg/buildpaper
 - bzinberg/calibrate_debounce
 - bzinberg/chinese_melnyk
 - bzinberg/github_rendering_sandbox
 - bzinberg/guichat
 - bzinberg/hello
 - bzinberg/invcomp
 - bzinberg/invcomp_proposal
 - bzinberg/jupyter-vim
 - bzinberg/meng_thesis
 - bzinberg/playvx_progchal
 - bzinberg/pp_debug_tips
 - bzinberg/regex-combinator

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
