### ISSUE TITLE
Opt-out request for vgXhc

### ISSUE THREAD

**Issue by vgXhc** [bigcode-project/opt-out-v2#1124]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - all
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - vgXhc/10-meeting
 - vgXhc/ACS_1y_Madison
 - vgXhc/ACS_commute_Madison_demographics
 - vgXhc/SSSS_words
 - vgXhc/alder_census_explorer
 - vgXhc/alder_zoning
 - vgXhc/bike_counts_climate
 - vgXhc/bike_gaps_madison
 - vgXhc/bus_rapid_transit
 - vgXhc/cyclists_of_msn
 - vgXhc/datenecke
 - vgXhc/dist_26_elections
 - vgXhc/housing_permits
 - vgXhc/lodes_od
 - vgXhc/madison-commute-demographics
 - vgXhc/madison_elevation
 - vgXhc/madison_referendum_2021
 - vgXhc/metro_boardings
 - vgXhc/presidential_elections_2020
 - vgXhc/property_tax_msn
 - vgXhc/property_value_change
 - vgXhc/reproducibility-CA
 - vgXhc/twitter_scraping
 - vgXhc/vgXhc.github.io

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
