### ISSUE TITLE
Please remove my repositories from The Stack

### ISSUE THREAD

**Issue by frougon** [bigcode-project/opt-out-v2#1125]
I request that the following data is removed from The Stack:

- [frougon/CondConfigParser](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/frougon/CondConfigParser)
- [frougon/FFGo](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/frougon/FFGo)
- [frougon/TeX-stuff](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/frougon/TeX-stuff)
- [frougon/examwsolns](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/frougon/examwsolns)
- [frougon/expsagetex](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/frougon/expsagetex)
- [frougon/flo-check-homework](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/frougon/flo-check-homework)
- [frougon/latex3](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/frougon/latex3)
- all

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
