### ISSUE TITLE
Opt-out request for simson

### ISSUE THREAD

**Issue by simson** [bigcode-project/opt-out-v2#1128]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - simson/LanguageTool
 - simson/basic_vernmq_plugin
 - simson/deoplete.nvim
 - simson/dotfiles
 - simson/echodoc.vim
 - simson/esp-32_rbg
 - simson/freeelectrons-training
 - simson/homeconfig
 - simson/mamie
 - simson/mqtt_test
 - simson/repetiteur
 - simson/rustlings-idiomatic-solutions
 - simson/streamstudio-plugins
 - simson/tpl1
 - simson/vim-printf
 - simson/vinarise.vim

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
