### ISSUE TITLE
Hey dickheads,

### ISSUE THREAD

**Issue by ShinySaana** [bigcode-project/opt-out-v2#113]
I demand that the following data is removed from The Stack:

 - all

scumbags.

**Comment by midnya** [comment]
@lvwerra Was I not clear enough? You included software that was published publicly without an explicit license. Do you need a refresher on open source licensing to know what this means?

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
