### ISSUE TITLE
Opt-out request for andypiper

### ISSUE THREAD

**Issue by andypiper** [bigcode-project/opt-out-v2#1130]
I request that the following data is removed from The Stack and StackOverflow:

 - StackOverflow: https://stackoverflow.com/users/262478/andy-piper
 - GitHub: https://github.com/andypiper
 - all 
 - andypiper/3dstxt
 - andypiper/Android-ListMQTT
 - andypiper/Dotfiles
 - andypiper/ExampleMQTTclient
 - andypiper/MQTT-c-pub-sub
 - andypiper/PiRingo
 - andypiper/SnowBotDev
 - andypiper/TweetJSON
 - andypiper/TwitterDotNetCore
 - andypiper/andy-house
 - andypiper/andypiper.github.com
 - andypiper/andypiper.github.io
 - andypiper/apnodestarter-bluemix
 - andypiper/authinvi
 - andypiper/background
 - andypiper/barnard-castle
 - andypiper/brb
 - andypiper/bucket-list
 - andypiper/cards-demos
 - andypiper/cf-scale-demo
 - andypiper/cf-vagrant-installer
 - andypiper/cf-workshop-lab1
 - andypiper/fccRandomQuote
 - andypiper/fsc_flogr
 - andypiper/ggideas
 - andypiper/gnippy
 - andypiper/gochat-mqtt
 - andypiper/hackdaymanifesto.github.com
 - andypiper/hackference-2014
 - andypiper/haskell-buildpack-demo
 - andypiper/homebrew-tap
 - andypiper/hubot-cf
 - andypiper/initializr
 - andypiper/iterm-twitter-info
 - andypiper/justdelete.me
 - andypiper/karma
 - andypiper/marvellous
 - andypiper/mongoProjectsList
 - andypiper/mows
 - andypiper/mqtt
 - andypiper/mqtt-chat
 - andypiper/mqtt_message_server
 - andypiper/mqttorg-dokuwiki
 - andypiper/mqtts-tools
 - andypiper/myMac
 - andypiper/myenergi2mqtt
 - andypiper/nancy-on-mono
 - andypiper/nanode-flash-led
 - andypiper/node-red-nodes
 - andypiper/nyamuk
 - andypiper/ohlohapp
 - andypiper/openapi-directory
 - andypiper/pgProjectsList
 - andypiper/pipes_ebooks
 - andypiper/pistate
 - andypiper/play2-cloudfront
 - andypiper/pythonista-scripts
 - andypiper/scribe
 - andypiper/sinatra-cf-twitter
 - andypiper/sinatra-static-web
 - andypiper/spring-boot
 - andypiper/stackato-cli
 - andypiper/statusnet-openshift-quickstart
 - andypiper/subway
 - andypiper/twauth-web
 - andypiper/tweetgo
 - andypiper/twemoji
 - andypiper/twemoji-parser
 - andypiper/twitter-alexa-skill-apl
 - andypiper/twitter-platform-demos
 - andypiper/twitter-replies-parser
 - andypiper/twitter-webhook-boilerplate-python
 - andypiper/twitteroauth-demo
 - andypiper/twprofile
 - andypiper/twurl
 - andypiper/visual-developer-guides
 - andypiper/vscode-twitter
 - andypiper/webhooks
 - andypiper/yrs2012-site

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
