### ISSUE TITLE
Opt-out request for halberom

### ISSUE THREAD

**Issue by halberom** [bigcode-project/opt-out-v2#1135]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - halberom/ansible-goapp
 - halberom/ansible-role-go
 - halberom/ansible_foo
 - halberom/ansible_role
 - halberom/ansible_role_iptables
 - halberom/blog
 - halberom/docker-ansible
 - halberom/docker-dpl
 - halberom/docker_git
 - halberom/docker_hiera-eyaml
 - halberom/docker_hugo
 - halberom/docker_weechat
 - halberom/dotfiles
 - halberom/gbt
 - halberom/goapp
 - halberom/host-redirect-microservice
 - halberom/step-gh-pages
 - halberom/terraform-aws-dynamodb
 - halberom/terraform-aws-tfstate-backend

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
