### ISSUE TITLE
Opt-out request for Nasina7

### ISSUE THREAD

**Issue by Nasina7** [bigcode-project/opt-out-v2#1138]
I request that the following data is removed from The Stack:

 - All

...
This goes for both Nasina7, and Tails2600, which is my old username that some projects (Tails2600/AGBE and Tails2600/nopNES) are listed under.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
