### ISSUE TITLE
Opt-out request for lamarqua

### ISSUE THREAD

**Issue by lamarqua** [bigcode-project/opt-out-v2#1144]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - lamarqua/App-Lamp
 - lamarqua/F3DAudio_tool
 - lamarqua/FACT
 - lamarqua/MCGJ
 - lamarqua/Woog
 - lamarqua/dotloverc
 - lamarqua/glFast
 - lamarqua/hasquelle
 - lamarqua/hexrs
 - lamarqua/hlml
 - lamarqua/le3d
 - lamarqua/mandelbrot-sdl-cpu
 - lamarqua/p5js-experiments
 - lamarqua/plasma-cpp-sdl
 - lamarqua/relisp
 - lamarqua/rust-quine
 - lamarqua/rust-reaction-diffusion-SDL

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
