### ISSUE TITLE
Opt-out request for n4kama

### ISSUE THREAD

**Issue by n4kama** [bigcode-project/opt-out-v2#1146]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - n4kama/Dolphin
 - n4kama/bittorrent
 - n4kama/malloc
 - n4kama/spider
 - n4kama/tigerCompiler

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
