### ISSUE TITLE
Stop stealing my code

### ISSUE THREAD

**Issue by TheLastProject** [bigcode-project/opt-out-v2#1149]
This is not a request. A request for removal would imply you ever had permission in any way. You do not. Stop stealing my code. Current, past and future. You may NOT include ANY of my code in ANY of your "projects". That includes all my code in organisations too.

Anyway, here is your stupid template:

---

I request that the following data is removed from The Stack and StackOverflow:

 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
