### ISSUE TITLE
Opt-out request for neverpanic

### ISSUE THREAD

**Issue by neverpanic** [bigcode-project/opt-out-v2#1151]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - neverpanic/MoCOCrW
 - neverpanic/MoCOCrW-build-env
 - neverpanic/cabal2port
 - neverpanic/cctrie
 - neverpanic/cmake-rpath-link-example
 - neverpanic/co2-fe2o3
 - neverpanic/co2monitor
 - neverpanic/coffeestats
 - neverpanic/coffeestats-cli
 - neverpanic/coffeestats-django
 - neverpanic/debian-yubikey-server
 - neverpanic/dokuwiki-template-acquia-marina
 - neverpanic/dotwatch
 - neverpanic/imapfetch-idle
 - neverpanic/langchristian.de
 - neverpanic/ma
 - neverpanic/macports-mp-buildbot
 - neverpanic/macports-ports
 - neverpanic/macports-user-cal
 - neverpanic/macports-user-devans
 - neverpanic/macports-user-eborisch
 - neverpanic/macports-user-jmr
 - neverpanic/macports-user-khindenburg
 - neverpanic/macports-user-mojca
 - neverpanic/macports-user-pguyot
 - neverpanic/macports-user-raimue
 - neverpanic/macports-user-rhwood
 - neverpanic/macports-user-ryandesign
 - neverpanic/macports-www-maintenance
 - neverpanic/maxcdn-ssl-client
 - neverpanic/metarbot
 - neverpanic/mod_wsgi_debian
 - neverpanic/mod_wsgi_docker_build
 - neverpanic/moodlight
 - neverpanic/mp-vote
 - neverpanic/revbump-ports
 - neverpanic/serienempfehlungen
 - neverpanic/simpleid-yubikey
 - neverpanic/smoothlio
 - neverpanic/svn2git
 - neverpanic/test-meson-libraries
 - neverpanic/timetrack
 - neverpanic/trac-ccme
 - neverpanic/trac-configurable-ctu
 - neverpanic/uname

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
