### ISSUE TITLE
Opt-out request for rahimftd

### ISSUE THREAD

**Issue by rahimftd** [bigcode-project/opt-out-v2#1153]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - rahimftd/EloquentJSExercises
 - rahimftd/IntroHTMLCSS
 - rahimftd/ResponsiveFundamentals
 - rahimftd/accountifie-svc
 - rahimftd/aws-test-deploy
 - rahimftd/chatterbox-client
 - rahimftd/chatterbox-server
 - rahimftd/data-structures
 - rahimftd/data-tracker
 - rahimftd/databases
 - rahimftd/ddr-chess
 - rahimftd/express-heroku-test
 - rahimftd/js-async
 - rahimftd/julie
 - rahimftd/linear_algebra
 - rahimftd/mytunes
 - rahimftd/n-queens
 - rahimftd/ncaa-mens-bball-data
 - rahimftd/pomodoro
 - rahimftd/recast.ly
 - rahimftd/recursion
 - rahimftd/recursion-extra-practice
 - rahimftd/shortly-angular
 - rahimftd/shortly-deploy
 - rahimftd/subclass-dance-party
 - rahimftd/twittler
 - rahimftd/underscore-js-simplified
 - rahimftd/visualizr
 - rahimftd/watchout
 - rahimftd/web-historian

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
