### ISSUE TITLE
Opt-out request for eldang

### ISSUE THREAD

**Issue by eldang** [bigcode-project/opt-out-v2#1155]
I request that the following data is removed from The Stack:

 - all
 
I also request that all of my future repositories be excluded.

And I further urge you to please reconsider your approach.  You claim that one of your goals is to give people agency, but apparently my data has been included since at least 2018 with no notification to me, so how was I supposed to have agency over it?  It's pure luck that I happened to see a social media post today warning me of this problem.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
