### ISSUE TITLE
Opt-out request for taavi

### ISSUE THREAD

**Issue by taavi** [bigcode-project/opt-out-v2#1157]
I request that the following data is removed from The Stack and StackOverflow:

 - all
 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - taavi/500lines
 - taavi/Overwrite-Fixtures
 - taavi/PyOhio2011SponsorLogoSlideshow
 - taavi/StringDecimal
 - taavi/advent_of_code
 - taavi/dirt
 - taavi/hclq
 - taavi/ipython_nose
 - taavi/janus
 - taavi/job_spreader
 - taavi/kirstensandwich.ca
 - taavi/minecraft_commands
 - taavi/nose-blockage
 - taavi/pyconca
 - taavi/redblue3d
 - taavi/vgarduino
 - taavi/vocal_keys

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
