### ISSUE TITLE
Opt-out request for cassidyjames

### ISSUE THREAD

**Issue by cassidyjames** [bigcode-project/opt-out-v2#1167]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: 5335564
 - cassidyjames/ColourPicker
 - cassidyjames/appage
 - cassidyjames/apps
 - cassidyjames/appstream-redirect
 - cassidyjames/bash-aliases
 - cassidyjames/blaede.family
 - cassidyjames/blaedesign.com
 - cassidyjames/configurator
 - cassidyjames/dark-demo
 - cassidyjames/dosr.club
 - cassidyjames/dotfiles
 - cassidyjames/elementary-light-ui
 - cassidyjames/floursandchocolate.co
 - cassidyjames/fresh-install
 - cassidyjames/grid.css
 - cassidyjames/grimoire
 - cassidyjames/jp-site
 - cassidyjames/juan_saga
 - cassidyjames/katieandcass.us
 - cassidyjames/launchpad-styles
 - cassidyjames/lickable
 - cassidyjames/modern
 - cassidyjames/nav
 - cassidyjames/nimbus
 - cassidyjames/open
 - cassidyjames/pinebook-pro-skin
 - cassidyjames/sam
 - cassidyjames/samanddagan.us
 - cassidyjames/simple-dropdowns
 - cassidyjames/slacketron
 - cassidyjames/tabs-on-headerbar
 - cassidyjames/talks
 - cassidyjames/terminal.js
 - cassidyjames/theme-reset
 - cassidyjames/wallpapers
 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
