### ISSUE TITLE
Opt-out request for derekmorr

### ISSUE THREAD

**Issue by derekmorr** [bigcode-project/opt-out-v2#1178]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - derekmorr/SoDA-Workshop-Series-Introduction-to-Data-Science
 - derekmorr/acibparser
 - derekmorr/athena-test
 - derekmorr/bowling-kata-scala
 - derekmorr/browse-everything
 - derekmorr/ciris
 - derekmorr/exercism-rust
 - derekmorr/fasta-sort
 - derekmorr/gradle-scalastyle-plugin
 - derekmorr/helloactor
 - derekmorr/knuth-primes-haskell
 - derekmorr/marc-parser
 - derekmorr/partest
 - derekmorr/refined-playground
 - derekmorr/ruby-bowling-kata
 - derekmorr/ruby-immutable
 - derekmorr/rust-rc
 - derekmorr/semantic_analysis
 - derekmorr/server_demo
 - derekmorr/shopping-cata-haskell
 - derekmorr/simsphere
 - derekmorr/tennis
 - derekmorr/webconf2015

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
