### ISSUE TITLE
Opt-out request for fizbin

### ISSUE THREAD

**Issue by fizbin** [bigcode-project/opt-out-v2#118]
I request that the following data is removed from The Stack and StackOverflow:

 - fizbin/4michael
 - fizbin/GraphOptiTest
 - fizbin/cabal-demo-backflip
 - fizbin/capnproto
 - fizbin/cryptopals-solutions
 - fizbin/killfile-extension
 - fizbin/parsing_experiment
 - fizbin/pe100challenge
 - fizbin/python-inspector
 - fizbin/tinytest
 - fizbin/unicode_inspector

Thank you for your attention.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
