### ISSUE TITLE
Opt-out request for ukscone

### ISSUE THREAD

**Issue by ukscone** [bigcode-project/opt-out-v2#1183]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - ukscone/Camputers-Lynx
 - ukscone/CurlHttp
 - ukscone/Dockered-VirtualT
 - ukscone/Flick
 - ukscone/PaPiRus
 - ukscone/SenseHAT
 - ukscone/ZipitZ2
 - ukscone/ezasoket-svn-to-git
 - ukscone/marklomas_chuckie-egg
 - ukscone/oldravenblack
 - ukscone/palesdl128k
 - ukscone/serial-repl-in-browser
 - ukscone/serialterm
 - ukscone/set_overscan
 - ukscone/telehash-c
 - ukscone/tweep
 - ukscone/ukscone.github.io
 - ukscone/unicornhat
 - ukscone/warberry
 - ukscone/wiringPi-for-euphoria

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
