### ISSUE TITLE
Opt-out request for gyordanov

### ISSUE THREAD

**Issue by gyordanov** [bigcode-project/opt-out-v2#1186]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - gyordanov/jslint-v8
 - gyordanov/sequel_extjs
 - gyordanov/sinatra-ca
 - gyordanov/trinidad
 - all

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
