### ISSUE TITLE
Opt-out request for uliwitness

### ISSUE THREAD

**Issue by uliwitness** [bigcode-project/opt-out-v2#1188]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: uliwitness
 - uliwitness/AGIconFamily
 - uliwitness/AdairNetworking
 - uliwitness/AngelPlayer
 - uliwitness/AngelTemplate
 - uliwitness/BlackArtEngine
 - uliwitness/BugmaticX
 - uliwitness/CAHMaker
 - uliwitness/CardSharp
 - uliwitness/Circuitous
 - uliwitness/CodingService
 - uliwitness/CodingTaskMapApp
 - uliwitness/CppVariants
 - uliwitness/CreepyCrawly
 - uliwitness/CutTheCord
 - uliwitness/FakeNestedWindows
 - uliwitness/Filie
 - uliwitness/ForgeDebugger
 - uliwitness/GamePlusPlus
 - uliwitness/HexClock
 - uliwitness/HexFiend
 - uliwitness/IFFReader
 - uliwitness/Interconnect2D
 - uliwitness/KNAppGuide
 - uliwitness/KVOWithBlocks
 - uliwitness/Lanyon
 - uliwitness/Leonie
 - uliwitness/LiquidTestApp
 - uliwitness/MacSVNServer
 - uliwitness/Macoun2018FromIOSToMac
 - uliwitness/MapRotationTest
 - uliwitness/MarlynsWorld
 - uliwitness/ModernGLTestApp
 - uliwitness/MotVMovieMaker
 - uliwitness/MovieTheatre
 - uliwitness/NSTimer-Blocks
 - uliwitness/ObjectiveK
 - uliwitness/RootlessForEmulators
 - uliwitness/ShadowCopy
 - uliwitness/SimpleMakefile
 - uliwitness/Sparkle
 - uliwitness/Stacksmith
 - uliwitness/SwiftExamples-Dice
 - uliwitness/SwiftExamples-HelpWindow
 - uliwitness/SwiftExamples-MasterDetailSourceListWindow
 - uliwitness/SwiftExamples-ProgressSheet
 - uliwitness/SwiftExamples-RTFViewController
 - uliwitness/SwiftyMacTableView
 - uliwitness/TADSWorkbench
 - uliwitness/TEXAS
 - uliwitness/Thikrya
 - uliwitness/TrackStorer
 - uliwitness/UKDiffView
 - uliwitness/UKDistributedView
 - uliwitness/UKFileWatcher
 - uliwitness/UKInterface
 - uliwitness/UKSoundFileRecorder
 - uliwitness/ULICrashReporter
 - uliwitness/ULIGUIPluginHost
 - uliwitness/ULIMelodyQueue
 - uliwitness/ULINetSocket
 - uliwitness/ULIProxies
 - uliwitness/ULIResourceFork
 - uliwitness/ULISyntaxColoringController
 - uliwitness/ULITearOffMenu
 - uliwitness/ULITextClipping
 - uliwitness/ULIThemeKit
 - uliwitness/ULITwitchbot
 - uliwitness/ULIWebArchiveUnpacker
 - uliwitness/UliKit
 - uliwitness/UnDecidedProgram
 - uliwitness/ValueConverter
 - uliwitness/WideningBezierPathTest
 - uliwitness/XBlockFile
 - uliwitness/XFromApp
 - uliwitness/bugmatic
 - uliwitness/chirp
 - uliwitness/classic-finder-app
 - uliwitness/codeport
 - uliwitness/commando
 - uliwitness/cpptoswift
 - uliwitness/dans-shell
 - uliwitness/dans-xml
 - uliwitness/eleven
 - uliwitness/file_disk
 - uliwitness/fool
 - uliwitness/guides.cocoapods.org
 - uliwitness/iTunesCantComplain
 - uliwitness/intercombatsystem
 - uliwitness/interconnectgame
 - uliwitness/linelessdiff
 - uliwitness/mulle-clang
 - uliwitness/mushy
 - uliwitness/nimue
 - uliwitness/objc
 - uliwitness/ocimages
 - uliwitness/ocpre
 - uliwitness/ocstoryboards
 - uliwitness/ocstrings
 - uliwitness/r0ketmap
 - uliwitness/snd2wav
 - uliwitness/streamNgin
 - uliwitness/talkingmoose
 - uliwitness/tinymarkdown
 - uliwitness/vanguardbot
 - uliwitness/velocity
 - uliwitness/winner

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
