### ISSUE TITLE
Opt-out request for Ekdohibs

### ISSUE THREAD

**Issue by Ekdohibs** [bigcode-project/opt-out-v2#119]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - Ekdohibs/PVSCodegen
 - Ekdohibs/autovideo
 - Ekdohibs/camlboot
 - Ekdohibs/coq-proofs
 - Ekdohibs/coq_hanoi
 - Ekdohibs/foundations-of-proof-systems-project
 - Ekdohibs/llama
 - Ekdohibs/mesecons.net
 - Ekdohibs/netlist-simulator
 - Ekdohibs/noisegrid
 - Ekdohibs/partial
 - Ekdohibs/prologin2014
 - Ekdohibs/pscala
 - Ekdohibs/technic_tutorial
 - Ekdohibs/toy-smt
 - Ekdohibs/tsp
 - Ekdohibs/why3-toposort

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
