### ISSUE TITLE
Opt-out request for mcantelon

### ISSUE THREAD

**Issue by mcantelon** [bigcode-project/opt-out-v2#1196]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - mcantelon/advanced-search-query-creator
 - mcantelon/async-archivematica-presentation
 - mcantelon/atom-migration-presentation
 - mcantelon/backbone-file-explorer
 - mcantelon/cablescrape
 - mcantelon/catland
 - mcantelon/chatrooms-basic
 - mcantelon/clockify-tool
 - mcantelon/dotfiles
 - mcantelon/dotfiles-old
 - mcantelon/dpd-event-extension
 - mcantelon/elasticsearch-resource
 - mcantelon/goxtone
 - mcantelon/grout
 - mcantelon/node-calais
 - mcantelon/node-deja
 - mcantelon/node-elflord
 - mcantelon/node-intro
 - mcantelon/node-uam
 - mcantelon/node-uam-example
 - mcantelon/node-unhosted-intro
 - mcantelon/redmein
 - mcantelon/rest-to-websocket-presentation
 - mcantelon/scrumpal
 - mcantelon/socket-talk
 - mcantelon/spa-example
 - mcantelon/static-spa-example
 - mcantelon/twaids
 - mcantelon/weblate-test2
 - mcantelon/weblatetest
 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
