### ISSUE TITLE
Opt-out request for acdha

### ISSUE THREAD

**Issue by acdha** [bigcode-project/opt-out-v2#1205]
I request that the following data is removed from The Stack and StackOverflow:

 - all
 - Commits
 - GitHub issue
 - StackOverflow: chris-adams 
 - acdha/NativeImaging
 - acdha/Varnish-Cache
 - acdha/bagit-java
 - acdha/bagit-python
 - acdha/benchmark-harness
 - acdha/bitly-exporter
 - acdha/caniusepython3.com
 - acdha/centrify-aws-cli-utilities
 - acdha/cg-deck
 - acdha/chris.improbable.org
 - acdha/chronam
 - acdha/cloud-image-analysis
 - acdha/concordia
 - acdha/dev-environment
 - acdha/django-akamai
 - acdha/django-basic-apps
 - acdha/django-bittersweet
 - acdha/django-celery
 - acdha/django-flags
 - acdha/django-glossary
 - acdha/django-haystack
 - acdha/django-haystack-bench
 - acdha/django-i18n-utils
 - acdha/django-inlines
 - acdha/django-mingus
 - acdha/django-modeltranslation
 - acdha/django-performance-tools
 - acdha/django-queryset-transform
 - acdha/django-social-bookmarking
 - acdha/django-speedcenter
 - acdha/django-speedtracer
 - acdha/django-vacuum
 - acdha/django-versions
 - acdha/djangocon-internationalization-tutorial
 - acdha/easy-bag-store
 - acdha/fabric
 - acdha/fabric-graphite-quickstart
 - acdha/feincms
 - acdha/flake8-codeclimate
 - acdha/html5-media-synchronized-subtitles
 - acdha/i18n-tutorial-example
 - acdha/impphp
 - acdha/jp2-polyfill
 - acdha/lc-wikipedia-links
 - acdha/lesscss.org
 - acdha/microdata-extractor
 - acdha/migrate-trac-issues-to-github
 - acdha/mountstatus
 - acdha/nose-congestion
 - acdha/openseadragon-thatcher
 - acdha/packaginator
 - acdha/phantomjs-mixed-content-scan
 - acdha/photo-utils
 - acdha/pre-commit-docker
 - acdha/pymaging
 - acdha/python-django.tmbundle
 - acdha/python-performance-tools
 - acdha/python_sparse_list
 - acdha/range-polyfill
 - acdha/redbot
 - acdha/remoteobjects
 - acdha/restful-bag-server
 - acdha/scribeAPI
 - acdha/sentry
 - acdha/simple-cloud-site
 - acdha/slack-utils
 - acdha/tokei
 - acdha/ucss
 - acdha/unix_tools
 - acdha/wasm-hashing
 - acdha/webcompare
 - acdha/webfont-experiments
 - acdha/webtoolbox
 - acdha/windows-vm-utilities
 - acdha/yubikeylockd

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
