### ISSUE TITLE
Opt-out request for NovaSquirrel

### ISSUE THREAD

**Issue by NovaSquirrel** [bigcode-project/opt-out-v2#1207]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - NovaSquirrel/CathyDiscordBot
 - NovaSquirrel/CharCounter
 - NovaSquirrel/DABG
 - NovaSquirrel/DDR-NES
 - NovaSquirrel/DPCMDumper
 - NovaSquirrel/GameBoyFALSE
 - NovaSquirrel/GameBoyFHBG
 - NovaSquirrel/GameBoyLife
 - NovaSquirrel/HexQuest
 - NovaSquirrel/Miuchiz-Emulator
 - NovaSquirrel/NES-CHIP-8
 - NovaSquirrel/NESLife
 - NovaSquirrel/NESMicrogameTool
 - NovaSquirrel/Nova-Action-53
 - NovaSquirrel/NovaTheSquirrel.wiki.git
 - NovaSquirrel/SNESMicrogameTool
 - NovaSquirrel/Sea16
 - NovaSquirrel/SlidingBlaster
 - NovaSquirrel/SparklesBot2
 - NovaSquirrel/Squirrel-stuff
 - NovaSquirrel/TilemapTown
 - NovaSquirrel/TilemapTownScripting
 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
