### ISSUE TITLE
Opt-out request for lpar

### ISSUE THREAD

**Issue by lpar** [bigcode-project/opt-out-v2#1208]
I request that the following data be removed from The Stack and StackOverflow:

 - lpar/AdventOfCode
 - lpar/backup
 - lpar/calendar
 - lpar/date
 - lpar/debtclock
 - lpar/docopt.java
 - lpar/domino2syslog
 - lpar/gender-free-names
 - lpar/golang-handler-patterns
 - lpar/gzipped
 - lpar/hello-bluemix-golang
 - lpar/hemingway
 - lpar/jsonseq
 - lpar/log
 - lpar/mage
 - lpar/pdf2text
 - lpar/template

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
