### ISSUE TITLE
Opt-out request for RONNCC

### ISSUE THREAD

**Issue by RONNCC** [bigcode-project/opt-out-v2#1212]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - RONNCC/67250-JBShoes
 - RONNCC/Autolab
 - RONNCC/AutomatedFBMessenger
 - RONNCC/Books
 - RONNCC/CampusConnect
 - RONNCC/Duplicate-Deleter
 - RONNCC/Error-Correcting
 - RONNCC/Fall-2019-Career-Exploration
 - RONNCC/Gitstructions
 - RONNCC/Heroku_GraphVis
 - RONNCC/Heroku_OnTheSide
 - RONNCC/Heroku_sghose
 - RONNCC/Math
 - RONNCC/MututallyFree_Prototype
 - RONNCC/Sandbox
 - RONNCC/Spring-2020-Career-Exploration
 - RONNCC/_Dogs_Angular_Velocity
 - RONNCC/binder-app
 - RONNCC/bumps
 - RONNCC/calaphioPHP
 - RONNCC/chromeext_nicknamer
 - RONNCC/doge
 - RONNCC/findLongestCompoundWord
 - RONNCC/gvoicebot_2
 - RONNCC/hyperopt-sklearn
 - RONNCC/jekyller
 - RONNCC/mygithubpage
 - RONNCC/ngram_word_distro
 - RONNCC/notable-challenge
 - RONNCC/numjs
 - RONNCC/peuler
 - RONNCC/practicing
 - RONNCC/py_animal_exceptions
 - RONNCC/randomnn
 - RONNCC/ronncc.github.io
 - RONNCC/scikit-image.github.com
 - RONNCC/scikit-learn
 - RONNCC/startbox
 - RONNCC/store
 - RONNCC/treode_rubyClient
 - RONNCC/twss-classifier

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
