### ISSUE TITLE
Opt-out request for cscorley

### ISSUE THREAD

**Issue by cscorley** [bigcode-project/opt-out-v2#1221]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - cscorley/2010-reu-poster
 - cscorley/StringSimilarity.NET
 - cscorley/StupidNetworkLogger
 - cscorley/base16-summerfruit-scheme
 - cscorley/bubg
 - cscorley/changeset-feature-location
 - cscorley/christop.club
 - cscorley/columbus_vanguards
 - cscorley/cscorley.github.io
 - cscorley/dissertation
 - cscorley/dotfiles
 - cscorley/ergodox
 - cscorley/gitbuglink
 - cscorley/hotdogbun
 - cscorley/ieee-pandoc-template
 - cscorley/killer-queen
 - cscorley/kq-cab-relay
 - cscorley/kqstats-heroku
 - cscorley/ladder-league
 - cscorley/mainsite
 - cscorley/mud2014-modeling-changeset-topics
 - cscorley/obs-scoreboard-assistant
 - cscorley/occasionally-exclusive-actions
 - cscorley/ohm
 - cscorley/papers
 - cscorley/post2lite
 - cscorley/schedulers
 - cscorley/send.py
 - cscorley/summerfruit256.vim
 - cscorley/swindle
 - cscorley/triage
 - cscorley/ugrad_8puzzle
 - cscorley/ugrad_ada
 - cscorley/ugrad_chat
 - cscorley/ugrad_recognizer
 - cscorley/whatthepatch
 - cscorley/wordbank
 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
