### ISSUE TITLE
Opt-out request for felixphew

### ISSUE THREAD

**Issue by felixphew** [bigcode-project/opt-out-v2#1222]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: felixphew
 - felixphew/bnf
 - felixphew/felixphew.github.io
 - felixphew/osx-profiles
 - felixphew/pokepaste
 - felixphew/pokepaste2
 - all

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
