### ISSUE TITLE
Opt-out request for dcr8898

### ISSUE THREAD

**Issue by dcr8898** [bigcode-project/opt-out-v2#1224]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - dcr8898/311_by_the_hour
 - dcr8898/cbra_book_code
 - dcr8898/clique
 - dcr8898/css-exercises
 - dcr8898/dcr2048
 - dcr8898/dcr8898.github.io
 - dcr8898/dragon
 - dcr8898/kool-cards
 - dcr8898/ooSudoku
 - dcr8898/rossneyn
 - dcr8898/turtle-overflow
 - dcr8898/turtlebay
 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
