### ISSUE TITLE
opt-out 

### ISSUE THREAD

**Issue by rscmbbng** [bigcode-project/opt-out-v2#1227]
I request that the following data is removed from The Stack:

 - all Commits
 - all GitHub issues
- all repositories
-  all PRs
- [rscmbbng/badgy-python](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/rscmbbng/badgy-python)
- [lowtechmag/solar-plugins](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/lowtechmag/solar-plugins)

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
