### ISSUE TITLE
Opt-out request for teganjetton

### ISSUE THREAD

**Issue by teganjetton** [bigcode-project/opt-out-v2#1233]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - teganjetton/mainSite

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

My note: This should be opt-in, not opt-out. 😡

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
