### ISSUE TITLE
Opt-out request for zkamvar

### ISSUE THREAD

**Issue by zkamvar** [bigcode-project/opt-out-v2#1234]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - zkamvar/365papers2016
 - zkamvar/CV
 - zkamvar/CardTrick
 - zkamvar/Data_management
 - zkamvar/ELI2017
 - zkamvar/EpiEstim
 - zkamvar/EpiEstimApp
 - zkamvar/Genotype-ID
 - zkamvar/PiG_Multitool
 - zkamvar/Presentation-APS2015
 - zkamvar/ReCon_Rcourse
 - zkamvar/RecursionHomework
 - zkamvar/Regression_practical
 - zkamvar/SDC-BIDS-dMRI
 - zkamvar/SLURM_Array
 - zkamvar/academic-kickstart
 - zkamvar/actions
 - zkamvar/ade4
 - zkamvar/advent-of-code-2018
 - zkamvar/advent-of-code-2019
 - zkamvar/apex
 - zkamvar/app-test
 - zkamvar/bench
 - zkamvar/blog-source
 - zkamvar/blotr
 - zkamvar/bpmodels
 - zkamvar/carpentries-docker-test
 - zkamvar/cautious-octo-chainsaw
 - zkamvar/challenges-manuscript-figures
 - zkamvar/citest
 - zkamvar/coarseDataTools
 - zkamvar/config-files
 - zkamvar/cookie
 - zkamvar/csszengarden
 - zkamvar/curriculum-development
 - zkamvar/datacarpentry.github.io
 - zkamvar/diaper
 - zkamvar/digroot
 - zkamvar/dissertation
 - zkamvar/drat.builder
 - zkamvar/epicontacts
 - zkamvar/feeds.carpentries.org
 - zkamvar/followup
 - zkamvar/forcats
 - zkamvar/genoid_infestans
 - zkamvar/geospatial-capstone
 - zkamvar/getting-rusty
 - zkamvar/glosario
 - zkamvar/glowing-chainsaw
 - zkamvar/glowing-octo-system
 - zkamvar/glowing-spork
 - zkamvar/grosbeak
 - zkamvar/hagis
 - zkamvar/haven
 - zkamvar/ida-energy
 - zkamvar/incidence-manuscript
 - zkamvar/inheritest
 - zkamvar/labtools
 - zkamvar/learning-js
 - zkamvar/learning-supercollider
 - zkamvar/legendary-octo-enigma
 - zkamvar/lesson-example
 - zkamvar/lesson-sprint-recommendations
 - zkamvar/maintainer-resources
 - zkamvar/makinde2007
 - zkamvar/mcg-mlh-graph
 - zkamvar/miniature-octo-waffle
 - zkamvar/miniature-snake-waffle
 - zkamvar/mwe_eigen_segfault
 - zkamvar/new-programming-with-r
 - zkamvar/new-site
 - zkamvar/notes-template
 - zkamvar/old.zkamvar.github.io
 - zkamvar/openrefineder
 - zkamvar/pkgcache
 - zkamvar/poppr
 - zkamvar/poppr-devel-docker
 - zkamvar/poppr_frontiers
 - zkamvar/poppr_msn_shiny
 - zkamvar/poppr_rnw2rmd
 - zkamvar/popprxl
 - zkamvar/postmaul
 - zkamvar/python_scripts
 - zkamvar/r-yaml
 - zkamvar/regolith
 - zkamvar/repvar
 - zkamvar/rstackdeque
 - zkamvar/scifigure
 - zkamvar/simupop-example
 - zkamvar/srvyr
 - zkamvar/strataG
 - zkamvar/symmetrical-spoon
 - zkamvar/symmetrical-train
 - zkamvar/test-2021-03-16-1
 - zkamvar/test-apt-intstall-binder
 - zkamvar/testme
 - zkamvar/testrelease2
 - zkamvar/tic
 - zkamvar/tic.drat
 - zkamvar/toot-docker-compose
 - zkamvar/toot-docker-networking
 - zkamvar/toscr
 - zkamvar/useR-2019
 - zkamvar/website
 - zkamvar/zkamvar.github.io
 - zkamvar/znk-bibliography
 - zkamvar/znksillysnail
 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
