### ISSUE TITLE
Opt-out request for Nobody-86

### ISSUE THREAD

**Issue by Nobody-86** [bigcode-project/opt-out-v2#1242]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - Nobody-86/BeamerThemes
 - Nobody-86/DataManipulation
 - Nobody-86/TestRepo

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
