### ISSUE TITLE
Opt-out request for mischif

### ISSUE THREAD

**Issue by mischif** [bigcode-project/opt-out-v2#1253]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: Mischif
 - mischif/PORTALofPi
 - mischif/nfsn-tools
 - mischif/nightshade
 - mischif/resume

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
