### ISSUE TITLE
Opt-out request for membermatters

### ISSUE THREAD

**Issue by jabelone** [bigcode-project/opt-out-v2#1255]
I request that the following data is removed from The Stack:

 - Commits
 - GitHub issue
 - membermatters/ESP-RFID
 - membermatters/UniFiVideoSnapshotGetter
 - membermatters/urdm6300
 - all

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
