### ISSUE TITLE
Opt-out request for judemille

### ISSUE THREAD

**Issue by judemille** [bigcode-project/opt-out-v2#1256]
I request that the following data is removed from The Stack and StackOverflow:

 - Any and all commits made by me, under the following email addresses:
`me AT jdemille DOT com`
`jtdemille AT demilletech DOT net`

 - Any and all GitHub pull requests and issues associated with me
 - GitHub repositories:
   - judemille/argon2_cffi
   - judemille/jmap
   - judemille/rspamd-rpm
   - Any and all GitHub repositories owned by me, not otherwise listed.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
