### ISSUE TITLE
Opt-out request for SolraBizna

### ISSUE THREAD

**Issue by SolraBizna** [bigcode-project/opt-out-v2#1257]
I request that the following data is removed from The Stack and StackOverflow:

 - all

I do not consent to the use of any of my works for training artificial intelligence. I consider such use to be an obvious violation of copyright law. Current safeguards against automatic, mass-scale license violation are inadequate, and in my opinion, this is an inherent limitation of all current AI technologies—one which cannot be safeguarded against or "trained out".

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
