### ISSUE TITLE
Opt-out request for griffi-gh

### ISSUE THREAD

**Issue by griffi-gh** [bigcode-project/opt-out-v2#1260]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - griffi-gh/CaveDig
 - griffi-gh/CaveDig2
 - griffi-gh/LOVE2d-raytracing
 - griffi-gh/Minecraft2Krunker
 - griffi-gh/Principia
 - griffi-gh/SURV2
 - griffi-gh/albox
 - griffi-gh/brainfast
 - griffi-gh/gdApi
 - griffi-gh/lgui
 - griffi-gh/logisim-cpu
 - griffi-gh/loveChess
 - griffi-gh/loveChip8
 - griffi-gh/modularbf
 - griffi-gh/ocsand
 - griffi-gh/pokesav
 - griffi-gh/powderbox
 - griffi-gh/raymarching
 - griffi-gh/surv
 - griffi-gh/voxelman
 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
