### ISSUE TITLE
Opt-out request for jamesemoody

### ISSUE THREAD

**Issue by jamesemoody** [bigcode-project/opt-out-v2#1262]
I request that the following data is removed from The Stack and StackOverflow:

 - All commits by jamesemoody
 - GitHub issues created by me
 - jamesemoody/geomapping
 - jamesemoody/homeassistant
 
It's appalling that this is opt-out.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
