### ISSUE TITLE
Opt-out request for lyonsinbeta

### ISSUE THREAD

**Issue by lyonsinbeta** [bigcode-project/opt-out-v2#1265]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: lyonsinbeta
 - lyonsinbeta/Pinkman-the-Web
 - lyonsinbeta/canvas-global-nav-lti
 - lyonsinbeta/canvas-module-filters
 - lyonsinbeta/canvas-section-search
 - lyonsinbeta/canvas-tools
 - lyonsinbeta/davidpaullyons.com
 - lyonsinbeta/howdoi
 - lyonsinbeta/resume-schema
 - lyonsinbeta/rubybeginnerstrack.github.io
 - lyonsinbeta/sakai-scripts
 - lyonsinbeta/simple_blackjack
 - lyonsinbeta/table-flip
 - lyonsinbeta/vod2html

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
