### ISSUE TITLE
Opt-out request for nishchalb

### ISSUE THREAD

**Issue by nishchalb** [bigcode-project/opt-out-v2#1267]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - nishchalb/TrafficGame
 - nishchalb/img-ditto
 - nishchalb/nishchalb.github.io
 - nishchalb/rouge-breaker
 - nishchalb/secret-wizard-corporation
 - nishchalb/sigmanuweb
 - nishchalb/sweet-spots
 - all

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
