### ISSUE TITLE
Opt-out request for mauriciomc

### ISSUE THREAD

**Issue by mauriciomc** [bigcode-project/opt-out-v2#127]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - mauriciomc/EDA
 - mauriciomc/GIT_CHARRUA
 - mauriciomc/GIT_DLX
 - mauriciomc/GIT_FIFO
 - mauriciomc/GIT_FIR
 - mauriciomc/GIT_FIR_N
 - mauriciomc/GIT_FPGA_TESTER
 - mauriciomc/GIT_MULTIPLIER
 - mauriciomc/GIT_OPENSATELLITE
 - mauriciomc/GIT_PAPERS
 - mauriciomc/GIT_PB
 - mauriciomc/GIT_VALID
 - mauriciomc/GIT_VM
 - mauriciomc/MySoC
 - mauriciomc/authenticator
 - mauriciomc/emailer
 - mauriciomc/frontend
 - mauriciomc/loca
 - mauriciomc/microrealestate
 - mauriciomc/pdfgenerator

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
