### ISSUE TITLE
Opt-out request for jayblunt

### ISSUE THREAD

**Issue by jayblunt** [bigcode-project/opt-out-v2#1271]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - jayblunt/ESI_Flask_Authlib_SSO
 - jayblunt/EveSkillQueue
 - jayblunt/yamlloader
 - all

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
