### ISSUE TITLE
Opt-out request for younata

### ISSUE THREAD

**Issue by younata** [bigcode-project/opt-out-v2#1277]
I request that the following data is removed from The Stack and StackOverflow:

- all
 - Commits
 - GitHub issue
 - younata/Autonoe
 - younata/CFirmata
 - younata/CZeroMQ
 - younata/Dawn
 - younata/Deimos
 - younata/Descartes
 - younata/Elara
 - younata/ElaraExample
 - younata/Firmata
 - younata/Flask-Starter
 - younata/FuelTransferModule
 - younata/FutureHTTP
 - younata/HatThemedWarSimulator
 - younata/HeartMonitor
 - younata/Hydrant
 - younata/HyperjumpSystem
 - younata/IRCClient
 - younata/InterPlanetaryTravelCalculator
 - younata/Inviscid-Open-Source
 - younata/IsBartFucked
 - younata/JWTService
 - younata/KDTree
 - younata/LFLoginController
 - younata/Lepton
 - younata/LocationTracker
 - younata/LocationTracker-Realm
 - younata/MacFloatingText
 - younata/MathKit
 - younata/Mir
 - younata/MockHTTP
 - younata/Pasiphae
 - younata/Phobos
 - younata/ProceduralKit
 - younata/Project-Euler-Swift
 - younata/QuickSnippets
 - younata/RBCategories
 - younata/RBHelp
 - younata/ROSViewer
 - younata/RSBAutocompleteTextView
 - younata/RSBDragMenu
 - younata/RSSClient
 - younata/Ra
 - younata/Raptor
 - younata/RealmPlayground
 - younata/Sake
 - younata/SimpleWatchface
 - younata/Sinope
 - younata/SpecHelperKit
 - younata/SpellingBeeSolver
 - younata/Sponde
 - younata/StatusBoard
 - younata/Swift-Crossing
 - younata/SwiftCraft
 - younata/SwiftOpenStreetMap
 - younata/SwiftZMQ
 - younata/TOBrowserActivityKit
 - younata/TaskList
 - younata/TelescopeControl
 - younata/Tollan
 - younata/UIKitNimbleMatchers
 - younata/URLMonitor
 - younata/URLSchemeRedirector
 - younata/VaporTestHelpers
 - younata/WITOSXExample
 - younata/WorkFlow
 - younata/XSS-Example-app
 - younata/accounting
 - younata/applescripts
 - younata/ardrone_apps
 - younata/arpping
 - younata/cedar
 - younata/concourse
 - younata/concourse_pypi_resource
 - younata/concourse_tasks
 - younata/forgetMeNot
 - younata/hy-invoice
 - younata/hyBot
 - younata/iOS-joy
 - younata/isCaltrainFucked
 - younata/jlisp
 - younata/luna
 - younata/markov
 - younata/mdbook-api
 - younata/mdbook-chapter-path
 - younata/mdbook-generate-summary
 - younata/mdbook-section-validator
 - younata/muninn
 - younata/notes
 - younata/phoebe
 - younata/planetGen
 - younata/planetGenerator
 - younata/python-tox-dockerimage
 - younata/python_shared_context
 - younata/rCAD
 - younata/rclSwift
 - younata/retort
 - younata/rosswift
 - younata/scripts
 - younata/second_brain
 - younata/spreadsheet-to-latex
 - younata/terragenParser
 - younata/tesla_analytics
 - younata/test_realm_swift3_regression
 - younata/tricopter
 - younata/wit-ios-sdk
 - younata/wit-objc
 - younata/wit-osx
 - younata/younata.github.io

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
