### ISSUE TITLE
Opt-out request for zanshin

### ISSUE THREAD

**Issue by zanshin** [bigcode-project/opt-out-v2#1278]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - zanshin/Calculator
 - zanshin/Calculator-old
 - zanshin/DisplayIP
 - zanshin/DomainHost
 - zanshin/HostedBy
 - zanshin/PhotoWheelPrototype
 - zanshin/RPNCalculator
 - zanshin/StrutsMovie
 - zanshin/Uber11_android
 - zanshin/adventofcode
 - zanshin/android
 - zanshin/ansible
 - zanshin/bin
 - zanshin/books
 - zanshin/cello
 - zanshin/chef_logstash
 - zanshin/cs193p_winter2013
 - zanshin/data-structures
 - zanshin/dockerfiles
 - zanshin/dotfiles
 - zanshin/elfenbein
 - zanshin/etude
 - zanshin/findi
 - zanshin/geek
 - zanshin/gitcheatsheet
 - zanshin/gollum
 - zanshin/growl
 - zanshin/health
 - zanshin/jtoh-bash
 - zanshin/lab
 - zanshin/library
 - zanshin/lilypond
 - zanshin/markhnichols
 - zanshin/monkey-interpreter
 - zanshin/neuepunkte
 - zanshin/practice
 - zanshin/queens
 - zanshin/sites
 - zanshin/strutsmovie-maven
 - zanshin/test
 - zanshin/update_adium_eids
 - zanshin/windows-test
 - zanshin/wordpress-chef-repo
 - zanshin/yt
 - zanshin/zanshin
 - zanshin/zanshin-archive
 - zanshin/zanshin-octopress

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
