### ISSUE TITLE
Opt-out request for masahir0y

### ISSUE THREAD

**Issue by masahir0y** [bigcode-project/opt-out-v2#1282]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - masahir0y/build-gcc
 - masahir0y/ddr-doc
 - masahir0y/gschem_garbage
 - masahir0y/haribote_linux
 - masahir0y/junk_pages
 - masahir0y/junkbox
 - masahir0y/masahir0y.github.com
 - masahir0y/my-docker-runner
 - masahir0y/xlnx-doc

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
