### ISSUE TITLE
opt-out for "scrottie"

### ISSUE THREAD

**Issue by scottwalters** [bigcode-project/opt-out-v2#1285]
"scrottie" is a GitHub "organization" that I own.

I request that the following data is removed from The Stack:

- scrottie/2600lava
- scrottie/HomeworkAssignment3
- scrottie/ProgrammingAssignment2
- scrottie/WWW-Workflowy
- scrottie/autobox-Closure-Attributes
- scrottie/bitcoin-pl
- scrottie/botrally
- scrottie/config-json
- scrottie/datasciencecoursera
- scrottie/mario-boulderdash-mashup
- scrottie/mutt-taggedmail-to-workflowy
- scrottie/paricart
- scrottie/scabble
- scrottie/sinus
- scrottie/tekroids

 
_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.
...

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
