### ISSUE TITLE
Opt-out request for manodeep

### ISSUE THREAD

**Issue by manodeep** [bigcode-project/opt-out-v2#1286]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - manodeep/2LPTic
 - manodeep/ConvertCTrees
 - manodeep/Corrfunc
 - manodeep/GadgetFileSplitter
 - manodeep/Gadget_REU
 - manodeep/HWSA2020
 - manodeep/LHaloTreeReader
 - manodeep/TesseRACt
 - manodeep/TreeFrog
 - manodeep/astropy
 - manodeep/astropy-benchmarks
 - manodeep/benchmark-leapfrog
 - manodeep/churn-analysis
 - manodeep/clusterfunc
 - manodeep/first
 - manodeep/fpc
 - manodeep/friendlyVRI
 - manodeep/gbpCode
 - manodeep/gender-decoder
 - manodeep/genesis
 - manodeep/groupmeeting
 - manodeep/hcts
 - manodeep/hermit
 - manodeep/hinge
 - manodeep/interactions
 - manodeep/lightcone
 - manodeep/mentari_web
 - manodeep/nmatcher
 - manodeep/nonGaussLike
 - manodeep/organisation
 - manodeep/pairwise
 - manodeep/pairwise_indices
 - manodeep/parse_ctrees
 - manodeep/rse-aunz.github.io
 - manodeep/sage
 - manodeep/sage-analysis
 - manodeep/sage-sed
 - manodeep/sglib-openmp
 - manodeep/simple-corr
 - manodeep/sort_forests
 - manodeep/subsampleGadget
 - manodeep/test_repo
 - manodeep/tex-resume
 - manodeep/uchuutools
 - manodeep/vaex
 - manodeep/yymao-abundancematching
 - manodeep/yymao-helpers

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
