### ISSUE TITLE
opt-out "scottwalters"

### ISSUE THREAD

**Issue by scottwalters** [bigcode-project/opt-out-v2#1288]
I request that the following data is removed from The Stack:

 - Commits
- scottwalters/ExData_Plotting1
- scottwalters/Forth
- scottwalters/PyReveng3
- scottwalters/RepData_PeerAssessment1
- scottwalters/princeton_algs4

 
_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.
...

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
