### ISSUE TITLE
Opt-out request for dvanic

### ISSUE THREAD

**Issue by dvanic** [bigcode-project/opt-out-v2#1294]
I request that the following data is removed from The Stack and StackOverflow:

All of the below:

 - dvanic/18ResBazPresentation
 - dvanic/19_11_CarpentriesInstructorNotes
 - dvanic/19_resbazSydGIS
 - dvanic/2016-08-10-pyconau
 - dvanic/2017_UTSsample
 - dvanic/2017_swcUTS
 - dvanic/2018-07-03-ResbazSydney
 - dvanic/2018-summer-camp
 - dvanic/DL4NLP_Monash
 - dvanic/HiC-Pro
 - dvanic/IRFinder
 - dvanic/academic-kickstart
 - dvanic/automatedclockify
 - dvanic/blogdown
 - dvanic/collection
 - dvanic/configs
 - dvanic/csiroData
 - dvanic/distillpocket
 - dvanic/dvanic
 - dvanic/dvanicGithubIoOldJekyll
 - dvanic/gage
 - dvanic/ggboxplots
 - dvanic/gghdr
 - dvanic/htmlwebsite
 - dvanic/m101p
 - dvanic/metalinks
 - dvanic/oldwebsitedvanic
 - dvanic/opctranscriptome
 - dvanic/praisme
 - dvanic/quickBiomaRt
 - dvanic/r4dsPrivate
 - dvanic/reporttemplate
 - dvanic/resbaz2019signup
 - dvanic/resume
 - dvanic/rstudiodemo
 - dvanic/training-course
 - dvanic/wwc2018

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
