### ISSUE TITLE
Opt-out request for NeilHanlon

### ISSUE THREAD

**Issue by NeilHanlon** [bigcode-project/opt-out-v2#1296]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issues
 - StackOverflow: neil-hanlon
 - NeilHanlon/COMP201
 - NeilHanlon/COMP278-2014
 - NeilHanlon/COMP285
 - NeilHanlon/COMP3070
 - NeilHanlon/COMP310-2014
 - NeilHanlon/COMP310project
 - NeilHanlon/COMP355
 - NeilHanlon/CPU-2014
 - NeilHanlon/GVNotifierWPF
 - NeilHanlon/HDTools
 - NeilHanlon/NoPolitics
 - NeilHanlon/Skillbotv2
 - NeilHanlon/Vaccine_Appointment_Tracker
 - NeilHanlon/almalinux.org
 - NeilHanlon/andro
 - NeilHanlon/battery_warning
 - NeilHanlon/discretemath
 - NeilHanlon/distribution-gpg-keys
 - NeilHanlon/franz-plugins
 - NeilHanlon/imgur-heart
 - NeilHanlon/loseit
 - NeilHanlon/loseitbot
 - NeilHanlon/mbta-predictions
 - NeilHanlon/openstack-ansible-os_tempest
 - NeilHanlon/potatoesare.love
 - NeilHanlon/puppet-r
 - NeilHanlon/shrug.pw
 - NeilHanlon/texteditor
 - NeilHanlon/tryregex
 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
