### ISSUE TITLE
Opt-out request for leonyuhanov

### ISSUE THREAD

**Issue by leonyuhanov** [bigcode-project/opt-out-v2#1300]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - leonyuhanov/AbletonToOSC
 - leonyuhanov/AnimationSimulator
 - leonyuhanov/ArtNet_UVMatrix
 - leonyuhanov/ESP-NOW-Remote
 - leonyuhanov/ESP-NOW-TX-RX
 - leonyuhanov/ESP32_ESPIDF_ESPNOW
 - leonyuhanov/LED-Pixel-Rullers
 - leonyuhanov/MPU6050_ESP8266
 - leonyuhanov/NeopixelsVia_ESP32_RMT
 - leonyuhanov/TOFnode
 - leonyuhanov/VL530l0X_ESP8266
 - leonyuhanov/esp8266apa102driver
 - leonyuhanov/rpi_apa102driver

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
