### ISSUE TITLE
Opt-out request for pyrox0

### ISSUE THREAD

**Issue by pyrox0** [bigcode-project/opt-out-v2#1305]
I request that the following data is removed from The Stack:

 - ModdedGamers/.config
 - ModdedGamers/Generic_Game
 - ModdedGamers/ModdedGamers
 - ModdedGamers/alfred-workflows
 - ModdedGamers/brew-easy-install
 - ModdedGamers/dotfiles
 - ModdedGamers/freeCodeCamp-projects
 - ModdedGamers/homebrew-nyxt
 - ModdedGamers/homebrew-retro-tools
 - ModdedGamers/ohmyzsh
 - ModdedGamers/rust-resources
 - ModdedGamers/timer-comp.nvim
 - ModdedGamers/NativeScript
 - ModdedGamers/alejandra
 - ModdedGamers/android-webinstall
 - ModdedGamers/bitburner-vscode
 - ModdedGamers/docker.github.io
 - ModdedGamers/docs
 - ModdedGamers/electron
 - ModdedGamers/home-manager
 - ModdedGamers/homebrew-cask-versions
 - ModdedGamers/homebrew-core
 - ModdedGamers/homebrew-dot-brew
 - ModdedGamers/homebrew-emacs-plus
 - ModdedGamers/homebrew-retro-tools
 - ModdedGamers/macports-ports
 - ModdedGamers/nixpkgs
 - ModdedGamers/node2nix
 - ModdedGamers/rust-snippets
 - ModdedGamers/sherlock
 - ModdedGamers/simple-caddy-install
 - ModdedGamers/swot
 - ModdedGamers/taskwarrior-tui
 - ModdedGamers/ublacklist
 - ModdedGamers/website
 - theHedgehog0/timer.nvim
 - all
- All data for the gctaa github organization
- All data for the code4nova github organization.
- I am a qualified representative of both of the above organizations.
 

These are all under previous aliases of mine. In fact, many of these repositories were made after I had changed my username, first to `theHedgehog0`, and then to my current username, `pyrox0`. I am disappointed that you would not put any thought into quality assurance and at least making sure that this information was up-to-date and accurate. You also never reached out to me for any sort of consent handling whatsoever. I am incredibly disappinted, and once again, an 'AI' company shows that it will disregard the interests of developers and those who simply do not like AI in favor of a quick buck.

**Comment by pyrox0** [comment]
Also, none of my code should be added to this project in the future. I do not appreciate this.

**Comment by lvwerra** [comment]
Hi @pyrox0, thank you for submitting an opt-out request. Under what username did you contribute to `gctaa`? I am working on verifying your opt-out request there.

Sorry for the inconvenience and thank you.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
