### ISSUE TITLE
Opt-out request for ryancheley

### ISSUE THREAD

**Issue by ryancheley** [bigcode-project/opt-out-v2#1315]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - ryancheley/MapGenerator
 - ryancheley/PyBites
 - ryancheley/StadiumTrackerAPI
 - ryancheley/StadiumTrackerAPIPublic
 - ryancheley/bottle
 - ryancheley/datasette-plugin
 - ryancheley/django
 - ryancheley/django-sql-dashboard
 - ryancheley/drf_project
 - ryancheley/fizz-buzz
 - ryancheley/markdown-to-sqlite
 - ryancheley/rpi-dodgers
 - ryancheley/rpi-kings
 - ryancheley/rpicamera-hummingbird
 - ryancheley/sunrise_sunset
 - ryancheley/tptm
 - ryancheley/tryceratops
 - ryancheley/wizard_battle_app
 - ryancheley/workflow_testing

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

Also, FU for making this an opt out. It’s some mad BS that you think it’s ok to ask people to opt out instead of asking them to opt in. I hope your project is an abject failure and that the VC vultures that thought it was a good idea pull your funding and stuff it in a F&$?ing mattress instead.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
