### ISSUE TITLE
Opt-out request for markstory

### ISSUE THREAD

**Issue by markstory** [bigcode-project/opt-out-v2#1318]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: n/a
 - markstory/CodeSniffer_CakePHP
 - markstory/Phing_d51PearPkg2Task
 - markstory/Z-Ray-CakePHP
 - markstory/app
 - markstory/asset_compress
 - markstory/beedoc
 - markstory/cakefest-workshop-2019
 - markstory/cakefest2021
 - markstory/cakephp
 - markstory/cakephp-docs
 - markstory/cakephp-docs_search
 - markstory/cakephp-fixture-factories
 - markstory/cakephp-fractal-entities
 - markstory/cakephp-multi-db-demo
 - markstory/cakephp-perf
 - markstory/cakephp-phpbenchmarks-app
 - markstory/cakephp-spekkoek
 - markstory/cakephp-typescript-react
 - markstory/cakephp_geshi
 - markstory/cakephp_menu_component
 - markstory/commcare-hq
 - markstory/dotfiles
 - markstory/flask-pundit
 - markstory/go-consumer
 - markstory/hashgrid
 - markstory/hubot
 - markstory/hubot-scripts
 - markstory/jerkbot
 - markstory/lint-review
 - markstory/lint-review-packer
 - markstory/lint-test
 - markstory/maplebot
 - markstory/mini-asset
 - markstory/mongoDB-Datasource
 - markstory/mvc-refinement
 - markstory/rector
 - markstory/rector-cakephp
 - markstory/rust-statsd
 - markstory/rustfmt
 - markstory/sentry-laravel-demo
 - markstory/solarized
 - markstory/sphinxcontrib-phpdomain
 - markstory/support-requests
 - markstory/vim-airline
 - markstory/vim-files
 - markstory/vim-zoomwin

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
