### ISSUE TITLE
Opt-out request for rhalkyard

### ISSUE THREAD

**Issue by rhalkyard** [bigcode-project/opt-out-v2#1330]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - rhalkyard/128boot64
 - rhalkyard/PiTubeControl
 - rhalkyard/browsecups
 - rhalkyard/c128-chkin-bug
 - rhalkyard/durexforth
 - rhalkyard/homebrew-c64tools
 - rhalkyard/puppet-visualstudio

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
