### ISSUE TITLE
Opt-out request for joffotron

### ISSUE THREAD

**Issue by joffotron** [bigcode-project/opt-out-v2#1332]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - joffotron/PLIBMTTBHGATY_Elixir
 - joffotron/alpine-ruby
 - joffotron/alpine-smelly-baron
 - joffotron/aws-kms
 - joffotron/elixir-deployment-talk
 - joffotron/espec
 - joffotron/go-servicechain-experiments
 - joffotron/gwt-contacts
 - joffotron/imagencasa
 - joffotron/k8s-scratch
 - joffotron/magick
 - joffotron/mq-test
 - joffotron/osgi-muck
 - joffotron/pixeltwister
 - joffotron/powerline-shell
 - joffotron/puppet-authy
 - joffotron/puppet-istatmenus5
 - joffotron/sqs-dead-letter-handling
 - joffotron/superlumic-config
 - joffotron/xspf2spotify

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
