### ISSUE TITLE
Opt-out request for gs0510

### ISSUE THREAD

**Issue by gs0510** [bigcode-project/opt-out-v2#1334]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - gs0510/99problems
 - gs0510/Competitive-Programming
 - gs0510/Compiler-101
 - gs0510/Euler-golang
 - gs0510/Exercism
 - gs0510/GimmeHaiku-bot
 - gs0510/Network-Programming
 - gs0510/Operating-Systems
 - gs0510/Parallel-OR
 - gs0510/Trivial-File-Transfer-Protocol
 - gs0510/Women-are-technical
 - gs0510/advent-of-code
 - gs0510/containerust
 - gs0510/cryptopals
 - gs0510/cs-implementing-a-hashtable-lab-codeU
 - gs0510/cs-wikipedia-philosophy-lab-codeU
 - gs0510/current-bench
 - gs0510/dns-server
 - gs0510/dune
 - gs0510/dune-bench
 - gs0510/galentines
 - gs0510/go-dibba
 - gs0510/gol
 - gs0510/gophercises
 - gs0510/gs0510.github.io
 - gs0510/hangwoman
 - gs0510/index
 - gs0510/index-benchmark-data
 - gs0510/index-benchmarks
 - gs0510/interpreter
 - gs0510/irmin
 - gs0510/java-symbol-solver
 - gs0510/little_schemer
 - gs0510/mapReduce
 - gs0510/ministrace
 - gs0510/ocaml-ci
 - gs0510/ocaml-conduit
 - gs0510/ocaml-interop
 - gs0510/ocaml-mooc
 - gs0510/ocaml-rs
 - gs0510/ocamlformat
 - gs0510/odoc
 - gs0510/ofronds
 - gs0510/presentations
 - gs0510/purely-functional-ds
 - gs0510/reddit_cluster_scripts
 - gs0510/repr
 - gs0510/rosalind
 - gs0510/syscalls-for-rustaceans
 - gs0510/ticpp

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
