### ISSUE TITLE
Opt-out request for nd1

### ISSUE THREAD

**Issue by nd1** [bigcode-project/opt-out-v2#1338]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 
 - nd1/CMIS_141
 - nd1/CMIS_242
 - nd1/DCInspections
 - nd1/DSI-DC1_project1
 - nd1/DSI-git_lab
 - nd1/DSI_git_lab_items
 - nd1/DocSummarizer
 - nd1/ExData_Plotting1
 - nd1/Intro-to-Decision-Trees---sample-teach
 - nd1/ProgrammingAssignment2
 - nd1/Scrapy
 - nd1/ThinkJavaCode
 - nd1/dc_traffic_data
 - nd1/georgetown-data-science
 - nd1/hackerrank
 - nd1/hellowebapp
 - nd1/logistic_regression_lab
 - nd1/model-tuning-lab
 - nd1/nd1.github.io
 - nd1/odds-and-ends
 - nd1/open_data_day_dc
 - nd1/repo20160206
 - nd1/science-bookclub
 - nd1/tiamat
 - nd1/tlh4_workshop
 - nd1/voter
 - nd1/wdsdc

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
