### ISSUE TITLE
Opt-out request for rohitsharma06596

### ISSUE THREAD

**Issue by rohitsharma06596** [bigcode-project/opt-out-v2#1346]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - rohitsharma06596/Assignment1Network
 - rohitsharma06596/Assignment3
 - rohitsharma06596/CorbaLibraryClient
 - rohitsharma06596/CorbaLibraryServer
 - rohitsharma06596/Distributed_Library
 - rohitsharma06596/Practice
 - rohitsharma06596/Stock-Price-Prediction-Using-LSTM-Project
 - rohitsharma06596/Suicide_Prediction
 - rohitsharma06596/rohitsharma06596.github.io

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
