### ISSUE TITLE
Opt-out request for AsamiT

### ISSUE THREAD

**Issue by AsamiT** [bigcode-project/opt-out-v2#135]
I request that the following data is removed from The Stack and StackOverflow:

 - all
 
_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

Not sure why in the name of God you'd want a bunch of failed emulator projects, personal dotfiles, and a bunch of useless college busywork, but I'd rather you'd have asked for opt-in rather than opt-out. Leave my things alone.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
