### ISSUE TITLE
Opt-out request for mqsoh

### ISSUE THREAD

**Issue by mqsoh** [bigcode-project/opt-out-v2#1353]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: mqsoh
 - mqsoh/an-intelligent-beginners-guide-to-webgl
 - mqsoh/datomic-freec2
 - mqsoh/django-gfklookupwidget
 - mqsoh/dotfiles
 - mqsoh/erlang-buildpack
 - mqsoh/game-of-life-in-rust
 - mqsoh/lfe
 - mqsoh/lfe-watcher
 - mqsoh/mon
 - mqsoh/nohubs
 - mqsoh/pm
 - mqsoh/tenper
 - mqsoh/toy-editor-in-rust
 - mqsoh/watcherl

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
