### ISSUE TITLE
Opt-out request for elena-v2

### ISSUE THREAD

**Issue by elena-v2** [bigcode-project/opt-out-v2#136]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - elena-v2/OverlayPlugin
 - elena-v2/df-succubus
 - elena-v2/kaomojify
 - elena-v2/xiv-sim
 - elena-v2/yaaz
 - all

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
