### ISSUE TITLE
Opt-out request for aitorres

### ISSUE THREAD

**Issue by aitorres** [bigcode-project/opt-out-v2#1365]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - aitorres/20-liners
 - aitorres/Compushow19-Front
 - aitorres/aws-s3-delete-bucket
 - aitorres/bootwrap
 - aitorres/c_made_easy
 - aitorres/ccs-game-jam-2019
 - aitorres/ceic-site
 - aitorres/ci3661-haskell
 - aitorres/ci3661-prolog
 - aitorres/ci3715-tarea3
 - aitorres/ci3815-proyecto2
 - aitorres/competitive-programming
 - aitorres/data-structures
 - aitorres/django-xlsx-import
 - aitorres/graciela
 - aitorres/hermit
 - aitorres/internet-watch
 - aitorres/jus_for_laughs
 - aitorres/ludovico
 - aitorres/marco
 - aitorres/patata
 - aitorres/priSBD
 - aitorres/redes-sample
 - aitorres/rockstar-lexer
 - aitorres/sip-online
 - aitorres/usersettings

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
