### ISSUE TITLE
Opt-out request for manuel-covas

### ISSUE THREAD

**Issue by manuel-covas** [bigcode-project/opt-out-v2#1366]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - manuel-covas/TCPserial
 - manuel-covas/arduino-pwm-throttle
 - manuel-covas/bluetunnel
 - manuel-covas/commentMe1ST
 - manuel-covas/esp32_rc552_tcp
 - manuel-covas/lcsc-product-fetch
 - manuel-covas/messenger-cloud
 - manuel-covas/sokoban
 - manuel-covas/sokoban-server

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
