### ISSUE TITLE
Opt-out request for jamalalaseer

### ISSUE THREAD

**Issue by jamalalaseer** [bigcode-project/opt-out-v2#1368]
I request that the following data is removed from  ALL 'The Stack':

 - Commits
 - GitHub issues or Any Data Period that is jamalalaseer as shown in Github Repo's please.
1. jamalalaseer/bgp-daemon
2. jamalalaseer/bgpview
3. jamalalaseer/hello-world

[jamalalaseer/bgp-daemon]
(https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/jamalalaseer/bgp-daemon)

[jamalalaseer/bgpview]
(https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/jamalalaseer/bgpview)

[jamalalaseer/hello-world]
(https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/jamalalaseer/hello-world)

Please Kindly Remove All  @bigcode-project - Thank you team

Please delete this pull request also too once the work has completed PLEASE

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
