### ISSUE TITLE
Opt-out request for Merovius

### ISSUE THREAD

**Issue by Merovius** [bigcode-project/opt-out-v2#1371]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: 9384701/axel-wagner
 - Merovius/Blotto
 - Merovius/Spacegoo-1
 - Merovius/android-davsync
 - Merovius/aoc18
 - Merovius/aoc_2020
 - Merovius/bor
 - Merovius/breakglass
 - Merovius/brightness
 - Merovius/bulkSMS
 - Merovius/c128-kasse
 - Merovius/cgolf
 - Merovius/chickenwrap
 - Merovius/cocktailbank
 - Merovius/crazycatlady
 - Merovius/diff
 - Merovius/etcdfs
 - Merovius/frank
 - Merovius/go-misc
 - Merovius/go-mysql-server
 - Merovius/go-talks
 - Merovius/go-tap
 - Merovius/insulterr
 - Merovius/merovius.github.io
 - Merovius/nbd
 - Merovius/notary
 - Merovius/qp
 - Merovius/robustirc
 - Merovius/simsim
 - Merovius/sing_notes
 - Merovius/spacegoo
 - Merovius/srvfb
 - Merovius/static-binaries
 - Merovius/terst
 - Merovius/tictactoe
 - Merovius/website
 - Merovius/xgb
 - Merovius/yarpnarp
 - Merovius/zkj-nas-tools
 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
