### ISSUE TITLE
Opt-out request for juergh

### ISSUE THREAD

**Issue by juergh** [bigcode-project/opt-out-v2#1377]
I request that the following data is removed from The Stack and StackOverflow:

- all
 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - juergh/dash-sdk
 - juergh/digispark
 - juergh/dns323-fw
 - juergh/dns323-fw-tools
 - juergh/dwarf
 - juergh/dwarf-debian
 - juergh/dwarf-fedora
 - juergh/jvncviewer
 - juergh/kernel-test
 - juergh/lm3s811
 - juergh/maria
 - juergh/ptdump
 - juergh/pykdumplib
 - juergh/qplayer
 - juergh/raspi-image
 - juergh/raspi-kidz
 - juergh/rxb6
 - juergh/tools
 - juergh/znc-awaynick

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
