### ISSUE TITLE
Opt-out request for Ceda-EI

### ISSUE THREAD

**Issue by Ceda-EI** [bigcode-project/opt-out-v2#1379]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: 6257358/ceda-ei
 - Ceda-EI/Ceda-EI
 - Ceda-EI/TeMiCross
 - Ceda-EI/Vagrantfiles
 - Ceda-EI/bin
 - Ceda-EI/draft
 - Ceda-EI/mark
 - Ceda-EI/probe-desktop
 - Ceda-EI/time

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
