### ISSUE TITLE
Opt-out request for yumaikas

### ISSUE THREAD

**Issue by yumaikas** [bigcode-project/opt-out-v2#139]
I request that the following data is removed from The Stack:

 - yumaikas/AzureSiteForFinal
 - yumaikas/BindingListFailExample
 - yumaikas/CogNotes
 - yumaikas/DataStruc
 - yumaikas/FGCU-SoftwareEngineeringProject.github.io
 - yumaikas/Gills
 - yumaikas/HomeWork
 - yumaikas/PISC
 - yumaikas/PISC-mirror
 - yumaikas/PizzaPOS
 - yumaikas/PythonHomework
 - yumaikas/Reimann-Sums
 - yumaikas/RiemannSums
 - yumaikas/Tangent
 - yumaikas/WateryArena
 - yumaikas/add-software-license
 - yumaikas/anno
 - yumaikas/anno-server
 - yumaikas/blogserv
 - yumaikas/cartnet
 - yumaikas/choring
 - yumaikas/chrono
 - yumaikas/clok-rb
 - yumaikas/comic-trakr
 - yumaikas/dale
 - yumaikas/dirx
 - yumaikas/erlang_markdown
 - yumaikas/eye
 - yumaikas/fnl
 - yumaikas/golang-die
 - yumaikas/golden-master
 - yumaikas/gotob-docs
 - yumaikas/hello-four-ways-go
 - yumaikas/janet-assertx
 - yumaikas/janet-datex
 - yumaikas/janet-errs
 - yumaikas/janet-globals
 - yumaikas/janet-stringx
 - yumaikas/janet-tempfiles
 - yumaikas/janitor
 - yumaikas/jester-docs
 - yumaikas/jumper-scripts
 - yumaikas/kb-financial-tracker
 - yumaikas/kb-web-bible
 - yumaikas/kbwiki
 - yumaikas/knn-partition-prototype
 - yumaikas/ld38-bullet-surfing
 - yumaikas/libdiff
 - yumaikas/ludumdare
 - yumaikas/newt
 - yumaikas/ogdenstudios.xyz
 - yumaikas/oil
 - yumaikas/outdoor
 - yumaikas/paib
 - yumaikas/praxis
 - yumaikas/psi
 - yumaikas/route-helpers
 - yumaikas/rumination
 - yumaikas/site-check
 - yumaikas/spry
 - yumaikas/tabulaScripta
 - yumaikas/tally
 - yumaikas/tree-sitter-janet
 - yumaikas/vue-crm-lite
 - yumaikas/werewolf
 - yumaikas/zed

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
