### ISSUE TITLE
Opt-out request for terrific-morphemes

### ISSUE THREAD

**Issue by terrific-morphemes** [bigcode-project/opt-out-v2#140]
I request that the following data is removed from The Stack and StackOverflow:

 - terrific-morphemes/acnh_trees
 - terrific-morphemes/camr_ne
 - terrific-morphemes/conlang_app
 - terrific-morphemes/conlang_creator
 - terrific-morphemes/thesis
 - terrific-morphemes/thesis-camr
 - terrific-morphemes/vocab_app

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
