### ISSUE TITLE
Opt-out request for phreaknerd

### ISSUE THREAD

**Issue by phreaknerd** [bigcode-project/opt-out-v2#1403]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - phreaknerd/KnpIpsum-for-symfony
 - phreaknerd/RedpillLinproNosqlBundle
 - phreaknerd/WebExtensionFrontendBugs
 - phreaknerd/findwise
 - phreaknerd/sensel-api-arduino
 - phreaknerd/symfony2-submodules
 - phreaknerd/termslides-git-submodules

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
