### ISSUE TITLE
Opt-out request for soluri

### ISSUE THREAD

**Issue by luringens** [bigcode-project/opt-out-v2#1407]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issues
 - soluri/Blood-Vessel-Visualizer-Web
 - soluri/Maze-Solver
 - soluri/Year-In-Pixels
 - soluri/citybike-parser
 - soluri/dungeons_of_rust
 - soluri/rust_sankey

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
