### ISSUE TITLE
Opt-out request for QuentinRougemont

### ISSUE THREAD

**Issue by QuentinRougemont** [bigcode-project/opt-out-v2#1408]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - QuentinRougemont/DemographicInference
 - QuentinRougemont/MicrosatDemogInference
 - QuentinRougemont/PiNPiS
 - QuentinRougemont/abc_inferences_data
 - QuentinRougemont/coho_salmon_recomb
 - QuentinRougemont/fsc_modelling
 - QuentinRougemont/fwd_sims
 - QuentinRougemont/gatk_haplotype
 - QuentinRougemont/poolseq_workflow
 - QuentinRougemont/singletons_analysis
 - QuentinRougemont/smcpp_input
 - QuentinRougemont/spacemix_workflow
 - QuentinRougemont/stacks_v2_workflow
 - QuentinRougemont/tmux_cheatsheet
 - QuentinRougemont/utility_scripts

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
