### ISSUE TITLE
Opt-out request for stisol

### ISSUE THREAD

**Issue by luringens** [bigcode-project/opt-out-v2#1414]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - stisol/Horace
 - stisol/INF319
 - stisol/INF319-Backend
 - stisol/Maze-Solver
 - stisol/Open-Anatomical-Human
 - stisol/Open-Anatomy-Explorer-Backend
 - stisol/RegistryNuker
 - stisol/Year-In-Pixels
 - stisol/particles
 - stisol/rust_sankey
 - stisol/rust_snmp
 - stisol/stisol.github.io
 - stisol/tinyrenderer

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
