### ISSUE TITLE
Opt-out request for paupowpow

### ISSUE THREAD

**Issue by paupowpow** [bigcode-project/opt-out-v2#1415]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - paupowpow/MyFirstP2PApp
 - paupowpow/P2P
 - paupowpow/ScalaExercises
 - paupowpow/classify-it
 - paupowpow/fotohop
 - paupowpow/just-dada-it
 - paupowpow/p2pkit-quickstart-android
 - paupowpow/p2pkit-quickstart-ios
 - paupowpow/paulahaertel.com
 - paupowpow/paupowpow.github.io
 - paupowpow/stolpersteine
 - paupowpow/template-webdev

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
