### ISSUE TITLE
Opt-out request for krfsm

### ISSUE THREAD

**Issue by krfsm** [bigcode-project/opt-out-v2#142]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - krfsm/krfsm
 - krfsm/nordicrando-commissioner
 - krfsm/whatsplaying
 - krfsm/alttp_vt_randomizer
 - krfsm/aoc2020
 - krfsm/api-testing
 - krfsm/api-xmlhttp-testing
 - krfsm/diffimg
 - krfsm/img

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
