### ISSUE TITLE
Opt-out request for maxheadroom

### ISSUE THREAD

**Issue by maxheadroom** [bigcode-project/opt-out-v2#1423]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - maxheadroom/LeonidasCMS
 - maxheadroom/MPL115A2-Arduino-Library
 - maxheadroom/Mosquitto
 - maxheadroom/algorecruit
 - maxheadroom/chunky
 - maxheadroom/cloud-blender-render
 - maxheadroom/ganglia-add-ons
 - maxheadroom/gphoto-upload-cli
 - maxheadroom/helpers
 - maxheadroom/mini_minecraft
 - maxheadroom/minigame_texturepack
 - maxheadroom/raok
 - maxheadroom/spark_nest
 - maxheadroom/temp_logger
 - maxheadroom/weather-node
 - maxheadroom/willie-fortune

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
