### ISSUE TITLE
Opt-out request for mutax

### ISSUE THREAD

**Issue by mutax** [bigcode-project/opt-out-v2#1426]
I request that all data derived from my GitHub account, including especially, but not limited to the following data is removed from The Stack and  #StackOverflow:

 - Commits
 - GitHub issue
 - mutax/IPv6-Address-checks
 - mutax/PyGNAD
 - mutax/can-i-snooze
 - mutax/dnspython-clientsubnetoption
 - mutax/ircbgp
 - mutax/mysql-study-group
 - mutax/screenselector
 - mutax/soundpad

THIS ALSO INCLUDES ALL FUTURE DATA I PUBLISH UNDER THIS GITHUB ACCOUNT OR ANYWHERE ELSE.

I never have given consent to this usage and never will. Legal action might be taken to enforce this decision on my side.

Confirm i written form that this data has been removed. In addition I request in accordance to GDPR a list of all data you have stored, processed or forwarded regarding my account and/or my person.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
