### ISSUE TITLE
Opt-out request for nikku

### ISSUE THREAD

**Issue by nikku** [bigcode-project/opt-out-v2#1429]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - nikku/.github
 - nikku/2021-token-simulation
 - nikku/2021-token-simulation-internals
 - nikku/action_annotation
 - nikku/amvn
 - nikku/angular-data-depend
 - nikku/annotation_security
 - nikku/async-didi
 - nikku/awesome-maven
 - nikku/bpmn-js-cli-modeling-dsl
 - nikku/bpmn-js-copy-paste-example
 - nikku/bpmn2-modeler
 - nikku/bpmnlint-loader
 - nikku/bpmnlint-pack-config
 - nikku/camunda-bpm-community-day-2013
 - nikku/camunda-bpm-elasticsearch
 - nikku/camunda-modeler-self-signed-root-ca-test
 - nikku/camunda-playground
 - nikku/camunda-worker-java
 - nikku/carbon-test
 - nikku/co-emitter
 - nikku/cockpit-sample-plugin
 - nikku/continuous-delivery-without-jenkins-tm
 - nikku/create-bpmnlint-plugin
 - nikku/create-camunda-modeler-plugin
 - nikku/custom-elements-not-workin
 - nikku/debugger-xml
 - nikku/didi
 - nikku/docpad-plugin-links
 - nikku/dotfiles
 - nikku/eslint-plugin-license-header
 - nikku/feel-playground
 - nikku/feelin
 - nikku/file-drops
 - nikku/hplayer
 - nikku/hugo-cli
 - nikku/image-gallery
 - nikku/invisibleTower
 - nikku/jquery-tagit
 - nikku/js-sax-parser-tests
 - nikku/kickr.io
 - nikku/lefedt.de
 - nikku/lezer-el
 - nikku/lezer-feel
 - nikku/lezer-generator
 - nikku/merge-me
 - nikku/merge-me-app
 - nikku/mons
 - nikku/nashorn-async
 - nikku/neenee
 - nikku/ng-simple-dialog
 - nikku/nixis-commons
 - nikku/node-project
 - nikku/node-xsd-schema-validator
 - nikku/nunjucks
 - nikku/order-demo-camundacon-2019
 - nikku/pegjs
 - nikku/pegjs-backtrace
 - nikku/play-2.1.1-testing-samples
 - nikku/probot-1475-repro
 - nikku/process-engine-async-test
 - nikku/react-form
 - nikku/roll-your-own-bpmn-editor
 - nikku/rollup-plugin-bpmnlint
 - nikku/run-camunda
 - nikku/saxen
 - nikku/selection-ranges
 - nikku/selection-update
 - nikku/silent-disco
 - nikku/simple-dialog
 - nikku/skaat
 - nikku/skaat-deck
 - nikku/software-architecture-toolbelt-talk-2019
 - nikku/split-require-jsx-text
 - nikku/stock-stats
 - nikku/sublime-eslint-test
 - nikku/sublime-gitignorer
 - nikku/svelte-slot-fill
 - nikku/testtest
 - nikku/testtest-actions
 - nikku/testtest-checks
 - nikku/testtest-merge
 - nikku/testtest-review-teams
 - nikku/todolist-review-2019
 - nikku/tsify
 - nikku/types-without-typescript
 - nikku/virtual-dom-web-test
 - nikku/webjar-bpmn-js
 - nikku/wuffle
 - nikku/wuffle-sync
 - nikku/zb-viz

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
