### ISSUE TITLE
Opt-out request for HoraceRIBOUT

### ISSUE THREAD

**Issue by HoraceRIBOUT** [bigcode-project/opt-out-v2#1432]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - HoraceRIBOUT/ACalmWorld
 - HoraceRIBOUT/BoundMask
 - HoraceRIBOUT/CatAclysme
 - HoraceRIBOUT/Forme
 - HoraceRIBOUT/GodessOfSea
 - HoraceRIBOUT/LudumDare45
 - HoraceRIBOUT/MageBoy
 - HoraceRIBOUT/OverSlash
 - HoraceRIBOUT/SMS
 - HoraceRIBOUT/SoulBodyAndSpirit
 - HoraceRIBOUT/StaySafeJam
 - HoraceRIBOUT/TouhouJam2019
 - HoraceRIBOUT/Vinyl
 - HoraceRIBOUT/YoureALoop

And in general, I never consent to let my data be used by AI. I do not wish to have to "opt-out" any data to be scavange by AI. My repo are open to other developer or game creator, not for machine learning or to be part of data.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
