### ISSUE TITLE
Opt-out request for simonracz

### ISSUE THREAD

**Issue by simonracz** [bigcode-project/opt-out-v2#1434]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - simonracz/Artemis-Cpp
 - simonracz/DaftTest
 - simonracz/DetoxSample
 - simonracz/EventView
 - simonracz/FPChallenge
 - simonracz/FyberChallenge
 - simonracz/Hazel
 - simonracz/Paxos
 - simonracz/TCTest
 - simonracz/async-save
 - simonracz/athene
 - simonracz/detox
 - simonracz/detox-android-tester
 - simonracz/dlang-sandbox
 - simonracz/euler
 - simonracz/isometric-libgdx-game-template
 - simonracz/keepalive-bug
 - simonracz/machine-learning-course
 - simonracz/pathfinding
 - simonracz/prezi-access-android
 - simonracz/sdl-jewel
 - simonracz/subtitle-adjuster
 - simonracz/wm-sample

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
