### ISSUE TITLE
Opt-out request for swiftcoder

### ISSUE THREAD

**Issue by swiftcoder** [bigcode-project/opt-out-v2#1437]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: https://stackoverflow.com/users/1232666/swiftcoder
 - swiftcoder/aevum
 - swiftcoder/ashima-iv
 - swiftcoder/bittorrent-protocols
 - swiftcoder/cargo-lipo
 - swiftcoder/cgajam2017
 - swiftcoder/clown
 - swiftcoder/cpp-lru-cache
 - swiftcoder/gfx-rs-sdl-emscripten-demo
 - swiftcoder/glsl-to-spirv-macros
 - swiftcoder/glypherator
 - swiftcoder/isosurface
 - swiftcoder/mini-collide-rs
 - swiftcoder/mini-math-rs
 - swiftcoder/pulsate
 - swiftcoder/resources
 - swiftcoder/rockson
 - swiftcoder/ruble
 - swiftcoder/rust-vpx
 - swiftcoder/sprite-collision
 - swiftcoder/vulkano
 - all

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
