### ISSUE TITLE
Opt-out request for gregersn

### ISSUE THREAD

**Issue by gregersn** [bigcode-project/opt-out-v2#1440]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - gregersn/EasyServo
 - gregersn/HDDVD2MKV
 - gregersn/Sherilyn
 - gregersn/Super-SloMo
 - gregersn/celltools
 - gregersn/csg2d
 - gregersn/cvs2sqlite
 - gregersn/dvdprofiler2xbmc
 - gregersn/gedapi
 - gregersn/gensplorer
 - gregersn/grutils
 - gregersn/gsnlib
 - gregersn/gsnmesh
 - gregersn/matchmatcher
 - gregersn/mystudio
 - gregersn/newpy
 - gregersn/outpost
 - gregersn/p5js-template
 - gregersn/react-native-svg-renderer
 - gregersn/shady
 - gregersn/utils

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
