### ISSUE TITLE
Opt-out request for bvdputte

### ISSUE THREAD

**Issue by bvdputte** [bigcode-project/opt-out-v2#1453]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - bvdputte/getkirby.com
 - bvdputte/gulptest
 - bvdputte/inuit.css
 - bvdputte/kirby-authenticator
 - bvdputte/kirby-autopublish
 - bvdputte/kirby-bettersearch
 - bvdputte/kirby-countries
 - bvdputte/kirby-fingerprint
 - bvdputte/kirby-floc-off
 - bvdputte/kirby-google-analytics
 - bvdputte/kirby-gtm
 - bvdputte/kirby-headershift
 - bvdputte/kirby-ical
 - bvdputte/kirby-log
 - bvdputte/kirby-meta-tags
 - bvdputte/kirby-pdfcover
 - bvdputte/kirby-queue
 - bvdputte/kirby-redirect
 - bvdputte/kirby-scheduler
 - bvdputte/kirby-taxonomy
 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
