### ISSUE TITLE
Opt-out request for SiebenCorgie

### ISSUE THREAD

**Issue by SiebenCorgie** [bigcode-project/opt-out-v2#1456]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: Siebencorgie
 - SiebenCorgie/KochApp
 - SiebenCorgie/Siebencorgie-Main
 - SiebenCorgie/first-rs-engine
 - SiebenCorgie/jakar-engine
 - SiebenCorgie/jakar-threadpool
 - SiebenCorgie/jakar-tree
 - SiebenCorgie/ori-engine

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
