### ISSUE TITLE
Opt-out request for halkyonio

### ISSUE THREAD

**Issue by metacosm** [bigcode-project/opt-out-v2#1460]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - halkyonio/api
 - halkyonio/community-operators
 - halkyonio/container-images
 - halkyonio/exposedapp.old
 - halkyonio/halkyonio-site
 - halkyonio/kubedb-capability
 - halkyonio/operator-framework
 - halkyonio/plugin-example-capability
 - halkyonio/plugins
 - halkyonio/project
 - halkyonio/r-d
 - halkyonio/rest-component-capability
 - halkyonio/sbo-capability

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
