### ISSUE TITLE
Opt-out request for gdude2002

### ISSUE THREAD

**Issue by gdude2002** [bigcode-project/opt-out-v2#1463]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - gdude2002/AoC2019
 - gdude2002/CMS
 - gdude2002/Calc
 - gdude2002/ChocoServ
 - gdude2002/Dumblin
 - gdude2002/FabricWaystones
 - gdude2002/Favourites
 - gdude2002/HerobrineAI
 - gdude2002/InfoBot
 - gdude2002/IssueManager
 - gdude2002/JSONAPI-IRCbot
 - gdude2002/JythonMod
 - gdude2002/Limitless-2
 - gdude2002/LotteryBox
 - gdude2002/MCBlockItPythonAPI
 - gdude2002/MojangAuth
 - gdude2002/MysticMod
 - gdude2002/NoJARsBot
 - gdude2002/Pippi
 - gdude2002/PyBalance
 - gdude2002/Quiz
 - gdude2002/RSSTicker
 - gdude2002/Simply-Conveyors
 - gdude2002/Smithy
 - gdude2002/StopServer
 - gdude2002/StopServerSponge
 - gdude2002/TeamRocketHotel
 - gdude2002/Training
 - gdude2002/WatchBlock
 - gdude2002/WordWarning
 - gdude2002/ZNC-Modules
 - gdude2002/code-jam-4-qualifier
 - gdude2002/discord-irc
 - gdude2002/gdude2002.github.io
 - gdude2002/glowstone-website
 - gdude2002/gserv.me-django
 - gdude2002/selfbot
 - gdude2002/site
 - gdude2002/twistifier
 - Kord-Extensions/template
 - Kord-Extensions/docs
 - Kord-Extensions/kord-extensions
 - Kord-Extensions/experiments
 - Kord-Extensions/intellij-plugin
 - Kord-Extensions/.github
 - Kord-Extensions/community
 - Kord-Extensions/docgen

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
