### ISSUE TITLE
Opt-out request for gabboman

### ISSUE THREAD

**Issue by gabboman** [bigcode-project/opt-out-v2#1468]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - gabboman/HolaGTK
 - gabboman/IssiSeptiembre
 - gabboman/MinecraftAntiIlegales
 - gabboman/aia_trabajo_2016
 - gabboman/api_auto-meet
 - gabboman/automeet_client
 - gabboman/fucklagg
 - gabboman/gabboman.github.io
 - gabboman/ipsimulator
 - gabboman/my-shopping-list-backend
 - gabboman/my-shopping-list-front
 - gabboman/plugin_mmondry
 - gabboman/secretbook
 - gabboman/sp00ky-chrome
 - gabboman/ssii_p1
 - gabboman/steghide_tests
 - gabboman/taller
 - gabboman/test_android_api_client
 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
