### ISSUE TITLE
Opt-out request for herrbischoff

### ISSUE THREAD

**Issue by herrbischoff** [bigcode-project/opt-out-v2#1469]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - herrbischoff/country-ip-blocks
 - herrbischoff/fish-ssh-agent
 - herrbischoff/iterm2-gruvbox
 - herrbischoff/nerdbar.widget
 - herrbischoff/simple-svg-brand-logos
 - herrbischoff/terminal.css
 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

Also, fuck you.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
