### ISSUE TITLE
Opt-out request for johnnoel

### ISSUE THREAD

**Issue by johnnoel** [bigcode-project/opt-out-v2#1472]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - johnnoel/AdventOfCode2019
 - johnnoel/CommentSpam
 - johnnoel/archive.chaostangent.com
 - johnnoel/blocks
 - johnnoel/blog-media-pump
 - johnnoel/chaostangent.media
 - johnnoel/dotfiles
 - johnnoel/ebmlreader
 - johnnoel/fansubebooks.chaostangent.com
 - johnnoel/ffxiii-episodezero-ebook
 - johnnoel/imagehasher
 - johnnoel/images.chaostangent.com
 - johnnoel/maps.chaostangent.com
 - johnnoel/php-ass
 - johnnoel/reliquary
 - johnnoel/ricochet-robots-solver
 - johnnoel/uk-parliamentary-constituency-postcode-lookup
 - johnnoel/wasd-keyboard-layout
 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
