### ISSUE TITLE
Opt-out request for andrzej3393

### ISSUE THREAD

**Issue by andrzej3393** [bigcode-project/opt-out-v2#1489]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: andrzej3393
 - andrzej3393/at-date
 - andrzej3393/avr_asm
 - andrzej3393/big-bang-py
 - andrzej3393/cookiecutter_python_package
 - andrzej3393/dicks_api
 - andrzej3393/dotfiles
 - andrzej3393/mangopay2-python-sdk
 - andrzej3393/mileages_in_poland
 - andrzej3393/packtrss
 - andrzej3393/presentations
 - andrzej3393/slunskigit
 - andrzej3393/static_homepage
 - andrzej3393/tymbarki
 - andrzej3393/vf60-vfd-display
 - andrzej3393/xchat_scripts

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
