### ISSUE TITLE
Opt-out request for MatteoPiovanelli-Laser

### ISSUE THREAD

**Issue by MatteoPiovanelli-Laser** [bigcode-project/opt-out-v2#1490]
I request that the following data is removed from The Stack:

 - MatteoPiovanelli-Laser
 
I would like all my repositories to be removed from all versions of the Stack, past, present and future.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
