### ISSUE TITLE
Opt-out request for allanwalpy

### ISSUE THREAD

**Issue by allanwalpy** [bigcode-project/opt-out-v2#1494]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - allanwalpy/01-19-vacancy-task-1
 - allanwalpy/hh-vacancy-view
 - allanwalpy/kaluga_astral
 - allanwalpy/mitheti
 - any other information of user `allan walpy`, `allanwalpy` and `allan_walpy` - or produced by that user, be it github, gitlab, twitter or any other platform, system of content managing, or what have you

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

Since I was never notified by any means of my inclusion I consider that inclusion a violation, and `opt out` model meaningless, since a lot people like me, surely was not notified either and still do not know of their inclusion

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
