### ISSUE TITLE
Opt-out request: joyeusenoelle

### ISSUE THREAD

**Issue by joyeusenoelle** [bigcode-project/opt-out-v2#150]
I request that the following data is removed from The Stack:

- joyeusenoelle/Beth
- joyeusenoelle/GuideToMastodon
- joyeusenoelle/KAcademe
- joyeusenoelle/MUSHBot
- joyeusenoelle/Maya
- joyeusenoelle/MegaUpload
- joyeusenoelle/MovieDraft.Net
- joyeusenoelle/NoelleAnthony.com
- joyeusenoelle/PACARDO
- joyeusenoelle/Resume
- joyeusenoelle/TDW
- joyeusenoelle/WPPlugins
- joyeusenoelle/adventofcode
- joyeusenoelle/adventofcode2018
- joyeusenoelle/agora-meteor-demo
- joyeusenoelle/api-example-django
- joyeusenoelle/assorted-scripts
- joyeusenoelle/dart-ddchar
- joyeusenoelle/dart-inchar
- joyeusenoelle/go-inchar
- joyeusenoelle/happinessjam2020
- joyeusenoelle/in-nomine-quickplay
- joyeusenoelle/maplebot17
- joyeusenoelle/masto-bot
- joyeusenoelle/mux-per-ass
- joyeusenoelle/nodegame
- joyeusenoelle/p8cypk
- joyeusenoelle/pico8
- joyeusenoelle/pykrete
- joyeusenoelle/pyris
- joyeusenoelle/realm-mod
- joyeusenoelle/simple-procgen
- joyeusenoelle/stitchify
- joyeusenoelle/vgmdb
 
_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.
...

This request is effective for all versions of The Stack past, present, and future, and is in effect in perpetuity.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
