### ISSUE TITLE
Opt-out request for MrConorAE

### ISSUE THREAD

**Issue by MrConorAE** [bigcode-project/opt-out-v2#1501]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: MrConorAE
 - all

p. s. Consent is not opt-out. The fact that I only found out about this from a Mastodon post is shocking. If it wasn't clear, I do not consent for any of my work, past, present, or future, to be used for training AI models or similar.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
