### ISSUE TITLE
Opt-out request for leightonthomas

### ISSUE THREAD

**Issue by leightonthomas** [bigcode-project/opt-out-v2#1508]
I request that the following data is removed from The Stack:

- leightonthomas/arrayclass
- leightonthomas/esp
- leightonthomas/idle-rs
- leightonthomas/manifest
- leightonthomas/mythos
- leightonthomas/obloader
- leightonthomas/symfony-console-promptable-options
- leightonthomas/symfony3-certification-helper
- leightonthomas/xkcd_slack

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
