### ISSUE TITLE
Remove my stuff.

### ISSUE THREAD

**Issue by 4censord** [bigcode-project/opt-out-v2#1510]
I request that the following data is removed from The Stack:

 - Commits
 - Issues
 - Pullrequests
 - Anything involving my user e.g. comments and reviews
 - 4censord/*
 
_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.
...

At least one of the repos that is listed in `the stack` was under an `all rights reserved` license (if my memory serves me correctly, the repo is deleted since years now).
You really should be more carefull, next time it will be someone that has the time and the laywers to litigate against this.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]

**Comment by 4censord** [comment]
What about previous versions?
