### ISSUE TITLE
Opt-out request for brouberol

### ISSUE THREAD

**Issue by brouberol** [bigcode-project/opt-out-v2#1513]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - brouberol/BS-BDD
 - brouberol/Coffee-Break
 - brouberol/Flask-FeatureFlags
 - brouberol/Generate-Monty-Pyhon-Dialog
 - brouberol/Gstreamer-webcam-tool
 - brouberol/ImageTools
 - brouberol/OpenChest
 - brouberol/PPH
 - brouberol/PythonMiscScripts
 - brouberol/Ravenant-Light
 - brouberol/WonderPaulo
 - brouberol/Yerba
 - brouberol/brigit
 - brouberol/capytal
 - brouberol/carrots_demo
 - brouberol/cdiff
 - brouberol/celeryex
 - brouberol/chronos
 - brouberol/cleanup-dungeondraft-asset-packs
 - brouberol/dotfiles
 - brouberol/erlpg
 - brouberol/frensh
 - brouberol/gotalks
 - brouberol/grand-cedre
 - brouberol/infrastructure
 - brouberol/izk
 - brouberol/jumpbox-tools
 - brouberol/kresus
 - brouberol/kubectl-fzf
 - brouberol/mojo
 - brouberol/myip
 - brouberol/nicetypes
 - brouberol/ovh-dockeraas-demo
 - brouberol/prezto
 - brouberol/puppet-as-a-service-wrapper
 - brouberol/python_REST_API_slides
 - brouberol/readme
 - brouberol/remotec
 - brouberol/research-lbc
 - brouberol/resume
 - brouberol/srtoffset
 - brouberol/sublime-text-themes
 - brouberol/tatsamon
 - brouberol/timer-context-manager
 - brouberol/twenga-crawling
 - brouberol/twitter_timeline
 - brouberol/web-crawling-presentation
 - brouberol/yurplan-cli
 - brouberol/zeroclickinfo-fathead
 - brouberol/zeroclickinfo-goodies

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
