### ISSUE TITLE
Opt-out request for ltlollo

### ISSUE THREAD

**Issue by ltlollo** [bigcode-project/opt-out-v2#1520]
I request that the following data is removed from The Stack and StackOverflow:

 - ltlollo/algos
 - ltlollo/dwario
 - ltlollo/instr
 - ltlollo/kdr
 - ltlollo/lattice
 - ltlollo/mathexp
 - ltlollo/polly-rs
 - ltlollo/sake
 - ltlollo/sat
 - ltlollo/se
 - ltlollo/spac
 - ltlollo/ste

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
