### ISSUE TITLE
Opt-out request for mdennehy

### ISSUE THREAD

**Issue by mdennehy** [bigcode-project/opt-out-v2#1530]
I request that the following data is removed from The Stack:

 - mdennehy/AS3935
 - mdennehy/PIC12F
 - mdennehy/PiCO2
 - mdennehy/PingPongPi
 - mdennehy/andi-servo
 - mdennehy/arma
 - mdennehy/dotfiles
 - mdennehy/folkarps.com
 - mdennehy/python-client
 - mdennehy/ws2812

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
