### ISSUE TITLE
Opt-out request for duarteocarmo

### ISSUE THREAD

**Issue by duarteocarmo** [bigcode-project/opt-out-v2#1533]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - duarteocarmo/BacteriaData
 - duarteocarmo/BigData_WikipediaInspector
 - duarteocarmo/BookmarkManager
 - duarteocarmo/CervicalCancer
 - duarteocarmo/GradingStudents
 - duarteocarmo/ProjectManagement
 - duarteocarmo/advent_of_code_2020
 - duarteocarmo/assembleia
 - duarteocarmo/canigohome
 - duarteocarmo/coronabar
 - duarteocarmo/dba_scam
 - duarteocarmo/devtuga-news
 - duarteocarmo/dotfiles
 - duarteocarmo/dotfiles_old
 - duarteocarmo/duarteocarmo
 - duarteocarmo/duarteocarmo.github.io
 - duarteocarmo/flatten-dict
 - duarteocarmo/hacking-on-my-finances
 - duarteocarmo/my-personal-zen
 - duarteocarmo/nbhub_webservice
 - duarteocarmo/nvim-treesitter
 - duarteocarmo/pokedex-demo
 - duarteocarmo/reddit_activity
 - duarteocarmo/technological_capabilities
 - duarteocarmo/tinder-coffee-chat
 - duarteocarmo/whatsapp-visualizations
 - duarteocarmo/world-cup-twitter-bot-portugal-2018

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
