### ISSUE TITLE
Opt-out request for johnmcfarlane

### ISSUE THREAD

**Issue by johnmcfarlane** [bigcode-project/opt-out-v2#1536]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: https://stackexchange.com/users/341106/john-mcfarlane
 - johnmcfarlane/HalfSize
 - johnmcfarlane/bin
 - johnmcfarlane/cdsp
 - johnmcfarlane/cheatsheets
 - johnmcfarlane/cmerian
 - johnmcfarlane/cnl
 - johnmcfarlane/cnl_ci_images
 - johnmcfarlane/cnl_example
 - johnmcfarlane/compiler-explorer-image
 - johnmcfarlane/dsp
 - johnmcfarlane/eg-error-handling
 - johnmcfarlane/ehct
 - johnmcfarlane/epic-arcade-game
 - johnmcfarlane/fixed_point
 - johnmcfarlane/france.thecayo.com
 - johnmcfarlane/ghost-invaders
 - johnmcfarlane/intersections
 - johnmcfarlane/iso-cpp-breaking-UB
 - johnmcfarlane/john.mcfarlane.name
 - johnmcfarlane/mandelbrot
 - johnmcfarlane/mars-helicopter
 - johnmcfarlane/nico-john-pong
 - johnmcfarlane/presentations
 - johnmcfarlane/realistic-car-simulator
 - johnmcfarlane/reveal.js
 - johnmcfarlane/ringo
 - johnmcfarlane/safe_numerics
 - johnmcfarlane/sibling-rename
 - johnmcfarlane/slides
 - johnmcfarlane/unformat
 - johnmcfarlane/uninitialized
 - johnmcfarlane/wss
 - everything under johnmcfarlane/ in perpetuity
 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
