### ISSUE TITLE
Opt-out request for fracai

### ISSUE THREAD

**Issue by fracai** [bigcode-project/opt-out-v2#1539]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: fracai
 - fracai/Backup-Bouncer
 - fracai/handbrake-sync
 - fracai/homebridge-philipshue
 - fracai/media-density
 - fracai/plex-reanalyze
 - fracai/pushTransmission
 - fracai/pushover_complete
 - fracai/zoneminder2flickr
 - all

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
