### ISSUE TITLE
Opt-out request for minego

### ISSUE THREAD

**Issue by minego** [bigcode-project/opt-out-v2#154]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - minego/KCSS
 - minego/PwdHash-HD
 - minego/PwdHash-HD2
 - minego/WeightLog
 - minego/cowerpoint
 - minego/dwm-customized
 - minego/dwmstatus
 - minego/minego.github.io
 - minego/mwd
 - minego/pmux
 - minego/tt-rssenyo
 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by minego** [comment]
Your entire project is based on theft, and is immoral.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
