### ISSUE TITLE
Opt-out request for SaschaWillems

### ISSUE THREAD

**Issue by SaschaWillems** [bigcode-project/opt-out-v2#1544]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - SaschaWillems/SPIRV-VSExtension
 - SaschaWillems/Vulkan
 - SaschaWillems/Vulkan-LoaderAndValidationLayers
 - SaschaWillems/Vulkan-RenderDoc-API
 - SaschaWillems/Vulkan-Samples
 - SaschaWillems/Vulkan-Samples-Assets
 - SaschaWillems/VulkanCapsViewerGenerator
 - SaschaWillems/VulkanDeviceSimulation
 - SaschaWillems/VulkanExamplesLauncher
 - SaschaWillems/VulkanPlayground
 - SaschaWillems/VulkanSamples
 - SaschaWillems/delphi
 - SaschaWillems/glTF
 - SaschaWillems/stuff
 - SaschaWillems/swiftshader
 - SaschaWillems/vulkan_slim

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
