### ISSUE TITLE
Opt-out request for simul

### ISSUE THREAD

**Issue by rvkennedy** [bigcode-project/opt-out-v2#1546]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - simul/Assets
 - simul/SimulQtWidgets
 - simul/basis_universal
 - simul/beingingoodvoice
 - simul/cruise_control
 - simul/efp
 - simul/efp_old
 - simul/icu
 - simul/teleport-unreal
 - simul/vsjenkinsmanager

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
