### ISSUE TITLE
Opt-out request for rtucker

### ISSUE THREAD

**Issue by rtucker** [bigcode-project/opt-out-v2#155]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - rtucker/ambassador
 - rtucker/aprs-car-monitor
 - rtucker/bladeRF-buildbot
 - rtucker/bsr-rfbadge
 - rtucker/django-mediastream
 - rtucker/dnsbl-tools
 - rtucker/expect-strip-proxy
 - rtucker/gdata-captcha
 - rtucker/herpderp
 - rtucker/jsonapi
 - rtucker/keepassx2csv
 - rtucker/lcd_temperature_display
 - rtucker/linode-recent-jobs
 - rtucker/localwiki-import-wikis
 - rtucker/mail-git-status
 - rtucker/mastodon-followings
 - rtucker/mastodon-unthreader
 - rtucker/mastopruner
 - rtucker/munin-cablemodem-monitor
 - rtucker/munin-dehumid-status
 - rtucker/munin-imapcount
 - rtucker/munin-ip6
 - rtucker/munin-surfboard6120
 - rtucker/nios_codebreaker
 - rtucker/plspictures-autoscraper
 - rtucker/printcal
 - rtucker/pyaprsfi
 - rtucker/pyvue
 - rtucker/raspi-fridge-overseer
 - rtucker/recentpostr
 - rtucker/rgeoutages
 - rtucker/scrobbletooter
 - rtucker/torcheck
 - rtucker/twit2masto
 - rtucker/webbymail
 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
