### ISSUE TITLE
Opt-out request for volkanto

### ISSUE THREAD

**Issue by volkanto** [bigcode-project/opt-out-v2#1550]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - volkanto/AngularJS-Music-Rate
 - volkanto/GoEuroTest
 - volkanto/IC_project
 - volkanto/LambStatus
 - volkanto/MoneyConversion
 - volkanto/MoneyExampleProject
 - volkanto/SpringMVC-WebStore
 - volkanto/StreamAndOptional
 - volkanto/angular-gulp-structure
 - volkanto/api
 - volkanto/billboard.js
 - volkanto/bmo-qr-code-generator
 - volkanto/codewars
 - volkanto/data-vis
 - volkanto/date-fns
 - volkanto/dropbox-api
 - volkanto/goeuro-test
 - volkanto/goodreads-kitap-koala
 - volkanto/gtop
 - volkanto/hackerrank-solutions
 - volkanto/issue-tracker
 - volkanto/java-oca-ocp-study
 - volkanto/jsoup-example
 - volkanto/mayfly-talks
 - volkanto/ngScopeStorage
 - volkanto/pg-batch
 - volkanto/project-euler-solutions
 - volkanto/recaptcha-spring-boot-starter-samples
 - volkanto/sample-io-website
 - volkanto/spring-boot-react
 - volkanto/spring-mvc-samples
 - volkanto/spring-security-jwt-1
 - volkanto/thymeleaf-layout-dialect
 - volkanto/toys_dev
 - volkanto/vbb-telegram
 - volkanto/volkanto.github.io
 - volkanto/zalenium

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
