### ISSUE TITLE
Opt-out request for ron-wolf

### ISSUE THREAD

**Issue by ron-wolf** [bigcode-project/opt-out-v2#1559]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: ron-wolf
 - ron-wolf/Advent-2018
 - ron-wolf/ArduinoDocs
 - ron-wolf/Dual-Screen-Setup-for-Rocket-League
 - ron-wolf/benjamin-hodgson.github.io
 - ron-wolf/dolfn
 - ron-wolf/e2db
 - ron-wolf/fastcat
 - ron-wolf/haskeuler
 - ron-wolf/ipd
 - ron-wolf/lobsters-constitution
 - ron-wolf/syntax_sugar_python
 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
