### ISSUE TITLE
Opt-out request for koutsie

### ISSUE THREAD

**Issue by koutsie** [bigcode-project/opt-out-v2#156]
I request that the following data is removed from The Stack and StackOverflow:

 - koutsie/7xx-plusplus
 - koutsie/AIOdroid
 - koutsie/AlwaysOnTop
 - koutsie/ArduinoSerialAnalogWires
 - koutsie/AutoKeyStuff
 - koutsie/BashHVH
 - koutsie/CitrOS
 - koutsie/Citros
 - koutsie/Dinstaller
 - koutsie/GhettoPi
 - koutsie/Mindstorms
 - koutsie/android
 - koutsie/anverysafewebsiteforkidsandadultsalike-microsoft-slash-mojang-plsfixthis-ok
 - koutsie/bash
 - koutsie/coinhive-custom-ui
 - koutsie/colour4
 - koutsie/csgo-with-koutsie
 - koutsie/dotfilez
 - koutsie/hacktoberfestbot
 - koutsie/houston
 - koutsie/i-dont-know
 - koutsie/krunken-stuff
 - koutsie/kucs
 - koutsie/nightmode-lwss.github.io
 - koutsie/notes
 - koutsie/pasted-microsoft-website-spinner
 - koutsie/repo
 - koutsie/rythm.fm
 - koutsie/space-hook
 - koutsie/steamlink-stuff
 - koutsie/suicidal.tech
 - koutsie/vac.fail
 - koutsie/vacban.today
 - koutsie/vita
 - koutsie/vitastuff
 - koutsie/wilmas-vicarious-visions
 - koutsie/www.async.fi

**Comment by koutsie** [comment]
Any updates?

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]

**Comment by koutsie** [comment]
I wish consent wasn't this hard.
