### ISSUE TITLE
Opt-out request for DfKimera

### ISSUE THREAD

**Issue by DfKimera** [bigcode-project/opt-out-v2#1564]
I request that the following data is removed from The Stack:

 - Commits
 - GitHub issue
 - DfKimera/GumpTheDragonrunner
 - DfKimera/PaperWars
 - DfKimera/ahoy
 - DfKimera/arcgis-js-demo
 - DfKimera/campjam12
 - DfKimera/clay-backend-assessment
 - DfKimera/droplr-backup
 - DfKimera/gameofur
 - DfKimera/ggj14-childrens-candy-saga
 - DfKimera/ggj2016
 - DfKimera/ggj2018
 - DfKimera/gmail-contact-extractor
 - DfKimera/iconmaker
 - DfKimera/icros
 - DfKimera/or-tools
 - DfKimera/phpconf16-ratchet
 - DfKimera/phpconf17-collections
 - DfKimera/phpconf17-ffmpeg
 - DfKimera/spjam2017
 - DfKimera/ticketswap-backend-assessment
 - DfKimera/vonq-assignment-symfony
 - all
 
_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.
...

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
