### ISSUE TITLE
Opt-out request for Siuolplex

### ISSUE THREAD

**Issue by Siuolplex** [bigcode-project/opt-out-v2#1566]
I request that the following data is removed from The Stack:

 - Commits
 - GitHub issues
 - Siuolplex/Colorful-Cut
 - Siuolplex/Hidden-Menu-gfiles
 - Siuolplex/MusicController
 - Siuolplex/Project-Cornerstone
 - Siuolplex/Unlimiter
 - Siuolplex/fabric-language-kotlin
 - Siuolplex/mcpnp-1
 - Siuolplex/quilt-installer
 - all

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
