### ISSUE TITLE
Opt-out request for fthevenet

### ISSUE THREAD

**Issue by fthevenet** [bigcode-project/opt-out-v2#1570]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - fthevenet/AptRepository
 - fthevenet/Eclair
 - fthevenet/HelloWindowAbuse
 - fthevenet/binjr
 - fthevenet/binjr-adapter-elitebgs
 - fthevenet/binjr-update-test
 - fthevenet/changelog-maker
 - fthevenet/fthevenet.github.io
 - fthevenet/gitblit
 - fthevenet/github-release-gradle-plugin
 - fthevenet/jrds
 - fthevenet/logViewer
 - fthevenet/mattermost-utils
 - fthevenet/openjfx-runtime-image
 - fthevenet/run-binjr
 - fthevenet/snapshot-perf-meter

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
