### ISSUE TITLE
Opt-out request for lmpn

### ISSUE THREAD

**Issue by lmpn** [bigcode-project/opt-out-v2#1582]
I request that the following data is removed from The Stack:

 - Commits
 - GitHub issue
 - lmpn/advanced-architectures
 - lmpn/deeploy
 - lmpn/esc-npb-benchmark
 - lmpn/flink-demo
 - lmpn/gauss-seidel
 - lmpn/graphic-computing
 - lmpn/heapsort
 - lmpn/kmeans-clustering
 - lmpn/playground
 - lmpn/product-manager
 - lmpn/reverse-proxy
 - lmpn/travelling-salesman
 - lmpn/wrap-cl

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
