### ISSUE TITLE
Opt-out request for iskrisis

### ISSUE THREAD

**Issue by iskrisis** [bigcode-project/opt-out-v2#1583]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - iskrisis/anotherkit
 - iskrisis/editor
 - iskrisis/fujitsu-j550n-opencore-hackintosh
 - iskrisis/kirby-block-preview-demo
 - iskrisis/kirby-bouncer
 - iskrisis/kirby-imageradio
 - iskrisis/kirby-modules
 - iskrisis/krisa.cz
 - iskrisis/laravel-mix-jigsaw
 - iskrisis/notidet
 - iskrisis/tenancy-docs
 - iskrisis/vector-electron-desktop

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
