### ISSUE TITLE
Opt-out request for piperhaywood

### ISSUE THREAD

**Issue by piperhaywood** [bigcode-project/opt-out-v2#1591]
I request that the following data is removed from The Stack and StackOverflow:

 - piperhaywood/beata-viscera
 - piperhaywood/books
 - piperhaywood/distributaries
 - piperhaywood/jekyll-cms
 - piperhaywood/lilypond-boilerplate
 - piperhaywood/netlify-cms-test
 - piperhaywood/quick-compositions
 - piperhaywood/rdio-data

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
