### ISSUE TITLE
Opt-out request for JWorthe

### ISSUE THREAD

**Issue by JWorthe** [bigcode-project/opt-out-v2#1594]
I request that the following data is removed from The Stack:

 - Commits
 - GitHub issue
 - JWorthe/Botinator
 - JWorthe/InteractivePacbot
 - JWorthe/SpaceInvaders-Bot-Cpp
 - JWorthe/advent_of_code_2017
 - JWorthe/adventofcode2016
 - JWorthe/gate
 - JWorthe/lo-ra-mac-node-rs
 - JWorthe/rust_channels_example
 - JWorthe/rust_git_hooks
 - JWorthe/rusty_microphone
 - JWorthe/worthe_signals
 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
