### ISSUE TITLE
Opt-out request for ProjectPhysX

### ISSUE THREAD

**Issue by ProjectPhysX** [bigcode-project/opt-out-v2#1598]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: ProjectPhysX
 - ProjectPhysX/*

Don't include any of my GitHub repositories, I explicitly forbid AI usage in my licenses and you don't want a copyright infringement lawsuit.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
