### ISSUE TITLE
Opt-out request for slapcat

### ISSUE THREAD

**Issue by slapcat** [bigcode-project/opt-out-v2#1616]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - slapcat/Community-Emergency-Response-Network
 - slapcat/Shell-Script-Card-Catalog
 - slapcat/stegify-web

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
