### ISSUE TITLE
Opt-out request for ghisvail

### ISSUE THREAD

**Issue by ghisvail** [bigcode-project/opt-out-v2#1617]
I request that the following data is removed from The Stack and StackOverflow:

 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by ghisvail** [comment]
Additionally I hereby request deletion of all data related to me under the GDPR. If you don't follow this request I reserve the rights to take further legal actions against you.

**Comment by ghisvail** [comment]
You folks should reconsider what _consent_ means. This is quite frankly disgusting.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
