### ISSUE TITLE
Opt-out request for andrewwillmott

### ISSUE THREAD

**Issue by andrewwillmott** [bigcode-project/opt-out-v2#1618]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - andrewwillmott/andrewwillmott.github.io
 - andrewwillmott/arg-spec
 - andrewwillmott/colour-blind-tests
 - andrewwillmott/distribute-lib
 - andrewwillmott/ev
 - andrewwillmott/fitting
 - andrewwillmott/halcyon
 - andrewwillmott/height-map-shadow
 - andrewwillmott/homebrew-stuff
 - andrewwillmott/rift
 - andrewwillmott/sh-lib
 - andrewwillmott/stl-extras

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
