### ISSUE TITLE
Opt-out request for steve-sienk

### ISSUE THREAD

**Issue by steve-sienk** [bigcode-project/opt-out-v2#1631]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - steve-sienk/ar-js-angular-test
 - steve-sienk/backstage
 - steve-sienk/bluetooth-music-visualizer
 - steve-sienk/docker-nodejs-examples
 - steve-sienk/flash-cat
 - steve-sienk/foo
 - steve-sienk/gcs-resource
 - steve-sienk/ipvgreen
 - steve-sienk/k8s-testing
 - steve-sienk/key-mime-pi
 - steve-sienk/keyboard_unlocker
 - steve-sienk/moonPhaser-avr
 - steve-sienk/napi-cpp-example
 - steve-sienk/nextjs-tesla-splash-page
 - steve-sienk/ng-lottie-animation-example
 - steve-sienk/pulse-fft
 - steve-sienk/sienk-light
 - steve-sienk/simple-electron-flask
 - steve-sienk/simple-nodejs-mocha-chai
 - steve-sienk/socks-sample
 - steve-sienk/swarm-and-something-something

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
