### ISSUE TITLE
Opt-out request for Agfct

### ISSUE THREAD

**Issue by Agfct** [bigcode-project/opt-out-v2#1641]
I request that the following data is removed from The Stack only:

 - Commits
 - GitHub issue
 - StackOverflow: Agfct
 - Agfct/AdvProgUI
 - Agfct/Fellesprosjekt
 - Agfct/KundestyrtG11
 - Agfct/MagicaeLudos
 - Agfct/PoeteneTest
 - Agfct/PyGameCards
 - Agfct/SharedSwing
 - Agfct/TestHelicopter2
 - Agfct/fellesprosjekt_g18
 - Agfct/gitKursTest

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
