### ISSUE TITLE
Opt-out request for neuroanatomy

### ISSUE THREAD

**Issue by katjaq** [bigcode-project/opt-out-v2#1643]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - neuroanatomy/34primates
 - neuroanatomy/BrainBox
 - neuroanatomy/FerretDiffusionTractTracingComparison
 - neuroanatomy/GWPC
 - neuroanatomy/GuerrillaPLI
 - neuroanatomy/MeMoDEvo
 - neuroanatomy/MeshSurgery
 - neuroanatomy/NeuroWebLab
 - neuroanatomy/NeuroWebLab-app
 - neuroanatomy/NeuroWebLab-server
 - neuroanatomy/QCApp-Cb
 - neuroanatomy/QCApp-vsub
 - neuroanatomy/StereotaxicRAMON
 - neuroanatomy/SurfaceRAMON
 - neuroanatomy/autism-challenge
 - neuroanatomy/brain-covid
 - neuroanatomy/brainspell2
 - neuroanatomy/challenge-engine
 - neuroanatomy/eslint-config-naat
 - neuroanatomy/fiind
 - neuroanatomy/flattener
 - neuroanatomy/foldgraph
 - neuroanatomy/genomic-architecture
 - neuroanatomy/histology-db
 - neuroanatomy/marching_cubes
 - neuroanatomy/meshgeometry
 - neuroanatomy/microdraw-tutorials
 - neuroanatomy/microdraw.py
 - neuroanatomy/mrijs
 - neuroanatomy/naat-eslintrc
 - neuroanatomy/neuroanatomy.github.com
 - neuroanatomy/neurodevelop-challenge
 - neuroanatomy/neuroimaging-sharing-tools
 - neuroanatomy/nwl-components
 - neuroanatomy/paper-reorient
 - neuroanatomy/thresholdmann
 - neuroanatomy/trainable_segmentation
 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
