### ISSUE TITLE
Opt-out request for shinze

### ISSUE THREAD

**Issue by shinze** [bigcode-project/opt-out-v2#1647]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - shinze/Collaborate
 - shinze/DTA
 - shinze/EDD-wskills2015
 - shinze/Exo-Flex
 - shinze/KevinLeProjet
 - shinze/Projet-2020
 - shinze/Test-integration-sm
 - shinze/Toto67
 - shinze/exotypo
 - shinze/galaxyline.nvim
 - shinze/git-draw
 - shinze/gulp-config
 - shinze/hyde-shinze
 - shinze/kb
 - shinze/kevin
 - shinze/oozui
 - shinze/plus-nantes
 - shinze/shinze.github.io
 - shinze/svgomg
 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
