### ISSUE TITLE
Opt-out request for bkuhlmann

### ISSUE THREAD

**Issue by bkuhlmann** [bigcode-project/opt-out-v2#1648]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - bkuhlmann/db
 - bkuhlmann/git-cop
 - bkuhlmann/go_setup
 - bkuhlmann/growl
 - bkuhlmann/heroku_plus
 - bkuhlmann/lineage
 - bkuhlmann/linguist
 - bkuhlmann/log_plus
 - bkuhlmann/npm_setup
 - bkuhlmann/number_to_fraction
 - bkuhlmann/rails_api_template
 - bkuhlmann/rails_dummy_template
 - bkuhlmann/rails_setup_template
 - bkuhlmann/rails_slim_template
 - bkuhlmann/resourcer
 - bkuhlmann/ruby_setup
 - bkuhlmann/sessioner
 - bkuhlmann/sorter
 - bkuhlmann/style_guides
 - bkuhlmann/test
 - bkuhlmann/thor_plus
 - bkuhlmann/tokener
 - bkuhlmann/yarn_setup

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
