### ISSUE TITLE
Opt-out request for gdog2u

### ISSUE THREAD

**Issue by gdog2u** [bigcode-project/opt-out-v2#1650]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: bee-h
 - gdog2u/Advent2017
 - gdog2u/Advent2018
 - gdog2u/Advent2019
 - gdog2u/Advent2020
 - gdog2u/CipherTech_Protobuf_Parser
 - gdog2u/Earnest
 - gdog2u/GenesEngine
 - gdog2u/JSTools
 - gdog2u/PersonalSite
 - gdog2u/ProtocolBufferParser
 - gdog2u/gdog2u.github.io

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
