### ISSUE TITLE
Opt-out request for aseroff

### ISSUE THREAD

**Issue by aseroff** [bigcode-project/opt-out-v2#1656]
I request that the following data is removed from The Stack and StackOverflow:

 - aseroff/cfdb
 - aseroff/eventapp
 - aseroff/membryo

cause they're just bad and you dont want that garbage

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
