### ISSUE TITLE
Opt-out request for jarek

### ISSUE THREAD

**Issue by jarek** [bigcode-project/opt-out-v2#1659]
I request that the following data is removed from The Stack:

 - Commits
 - GitHub issue
 - jarek/aoc2023
 - jarek/babykarte.github.io
 - jarek/climate-graph
 - jarek/dmt
 - jarek/electric2go
 - jarek/electricitymap
 - jarek/lime
 - jarek/name-suggestion-index
 - jarek/pb
 - jarek/php-mysqli-wrapper
 - jarek/sinfest-rss
 - jarek/subways
 - jarek/take-the-grt
 - jarek/ttc-nextbus-scraper
 - jarek/where-does-that-train-go
 - jarek/xltrtr
 
_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.
...

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
