### ISSUE TITLE
Opt-out request for DrGoldfire

### ISSUE THREAD

**Issue by DrGoldfire** [bigcode-project/opt-out-v2#166]
I request that the following data is removed from The Stack and StackOverflow:

 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.0.1 of The Stack and all future versions. Also your data was not used for the training of StarCoder2.

[PROCESSED]

**Comment by lvwerra** [comment]
Please disregard the above comment. As per #39 we removed the following data from v2.0.1:

- Commits
- GitHub issue
- DrGoldfire/Z80.js

This data was also not used for StarCoder2 training. However, your request to remove `all` as not been applied yet and we'll remove **ALL** your data in the next release. Sorry for the confusion!
