### ISSUE TITLE
Opt-out request for player-03

### ISSUE THREAD

**Issue by player-03** [bigcode-project/opt-out-v2#1661]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: player_03 (user ID 804200)
 - player-03/API_Specs
 - player-03/AS3Utils
 - player-03/Daydream
 - player-03/Entropy
 - player-03/ExtensionBoilerplate
 - player-03/Haxe-Template-UI
 - player-03/HaxeAnalytics
 - player-03/ICallHaxeDemos
 - player-03/Ludum-Dare-32
 - player-03/MarkdownParser
 - player-03/SDKGenerator
 - player-03/Singleton
 - player-03/TinyDiceSimulator
 - player-03/advanced-layout
 - player-03/android6permissions
 - player-03/ash-display
 - player-03/controls
 - player-03/echo
 - player-03/ecso
 - player-03/google-play-services
 - player-03/haxelib
 - player-03/haxeutils
 - player-03/hxrandom
 - player-03/iterators
 - player-03/lime-ios-dependencies
 - player-03/openfl.org
 - player-03/recursive-layout
 - player-03/relative-layout
 - player-03/trace-view
 - player-03/vertex-data

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
