### ISSUE TITLE
Opt-out request for lgatto

### ISSUE THREAD

**Issue by lgatto** [bigcode-project/opt-out-v2#1668]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - lgatto/10-simple-rules
 - lgatto/2014-11-06-UZH
 - lgatto/2014_10_HUPO_Madrid
 - lgatto/2015-09-10-CAM
 - lgatto/2016-10-rbioc-prot-Stellenbosch
 - lgatto/2017-03-30-OSC-peerreview
 - lgatto/2017-05-03-RstatsIntro-NEU
 - lgatto/2017-spatialmap-robin
 - lgatto/2017_06_08_osio_London
 - lgatto/2017_06_09_RDMF_London
 - lgatto/2017_06_23_PMF_Oxford
 - lgatto/2017_09_25_OpenScience_EPFL
 - lgatto/2017_11_08_FLI_Jena
 - lgatto/2017_11_09_Rcourse_Jena
 - lgatto/2017_11_12_OpenCon_Berlin
 - lgatto/2017_11_16_OpenConCam
 - lgatto/2018-12-spalprot-biophys
 - lgatto/2018_01_09_EuBIC_Ghent
 - lgatto/2018_01_15_TSL_Norwich
 - lgatto/2018_01_31_MGM_CMS
 - lgatto/2018_06_07_BSU_Cambridge
 - lgatto/2018_07_09_CSAMA_Brixen
 - lgatto/2018_09_24_INM_Rome
 - lgatto/2018_09_26_f-TALES_Gent
 - lgatto/2018_11_30_IB2_Bxl
 - lgatto/2018_12_07_EuroBioc18_Munich
 - lgatto/2019_03_22_LIBST_LLN
 - lgatto/2019_03_29_STATS_LLN
 - lgatto/2019_05_14_Compomics_Gent
 - lgatto/2019_05_16_rr_Delft
 - lgatto/2019_07_18_ISCB_KULeuven
 - lgatto/2019_08_30_protfold_ULG
 - lgatto/2020-02-17-RProt-Berlin
 - lgatto/2020-msnbase-v2
 - lgatto/2020_02_12_ABLS_Leuven
 - lgatto/2020_05_07_MayInstitute
 - lgatto/2020_07_15_ISMB
 - lgatto/2020_12_04_RSG_online
 - lgatto/2021_05_13_MayInstitute
 - lgatto/2021_08_31_RProtAZ_online
 - lgatto/2021_12_08_BePA_Liege
 - lgatto/2022-10-06-biocintro-uclouvain
 - lgatto/2022_06_23_CSAMA_Brixen
 - lgatto/2022_10_18_RNASeq_UCL
 - lgatto/BayesTwin
 - lgatto/Bioc2013-poster
 - lgatto/BiocMassSpecWorkingGroup
 - lgatto/Bioconductor20YearsSlides
 - lgatto/BrowserVizDemo2
 - lgatto/EuroBioc2017
 - lgatto/EuroBioc2019-Poster
 - lgatto/GHA_hpar_update
 - lgatto/GHA_knit_README
 - lgatto/MLInterfaces
 - lgatto/MSnID
 - lgatto/MSnbase
 - lgatto/MayInstituteRstatsIntro
 - lgatto/N14N15
 - lgatto/OmaDB
 - lgatto/OpenRefine-ecology
 - lgatto/PXD000001
 - lgatto/Pbase
 - lgatto/ProCoNA
 - lgatto/ProtGenerics
 - lgatto/ProteomicsAnnotationHubData
 - lgatto/ProteomicsBioc2014Workshop
 - lgatto/ProteomicsBioc2016Workshop
 - lgatto/R-ecology
 - lgatto/RforMassSpectrometry
 - lgatto/SCOPE2SCMM
 - lgatto/Spectrum
 - lgatto/TREG
 - lgatto/TeachingMaterial.wiki.git
 - lgatto/UniProt.REST
 - lgatto/VisualisingBiomolecularData
 - lgatto/WSBIM1207
 - lgatto/WSBIM2122
 - lgatto/biobroom
 - lgatto/bioc-isobaric-proteomics-workflow
 - lgatto/bioc-ms-prot
 - lgatto/bioc-pRolocGUI-workflow
 - lgatto/bioconductor-teaching
 - lgatto/bioconductor.org
 - lgatto/bioconductor.org-1
 - lgatto/biocpkgs
 - lgatto/camweather
 - lgatto/compomics-paper
 - lgatto/desiR
 - lgatto/discover-combine-data-software
 - lgatto/engine-mode
 - lgatto/github-paper
 - lgatto/group10
 - lgatto/hdxstats
 - lgatto/hpar
 - lgatto/jekyll-scholar
 - lgatto/joinSpectraData
 - lgatto/js-and-d3-class
 - lgatto/lazydata_test
 - lgatto/lgatto.github.io
 - lgatto/lmsimp.github.io
 - lgatto/lopims
 - lgatto/marts
 - lgatto/masserstein
 - lgatto/ms-coding-standards
 - lgatto/msidmatching
 - lgatto/msproteomicstools
 - lgatto/msqrob2
 - lgatto/mstut
 - lgatto/my-r-packages
 - lgatto/myp
 - lgatto/network-norm-exple
 - lgatto/pRoloc
 - lgatto/pRolocGUI
 - lgatto/pRolocdata
 - lgatto/pancakes
 - lgatto/pda
 - lgatto/pride-metadata-standard
 - lgatto/proteowizard
 - lgatto/pwizsandbox
 - lgatto/qcmetrics
 - lgatto/r-bioc-ms-challenges
 - lgatto/rbc
 - lgatto/rmd_github
 - lgatto/robinsonlabuzh.github.io
 - lgatto/rols
 - lgatto/rpx
 - lgatto/rr-rmarkdown-intro-slides
 - lgatto/rtslprot
 - lgatto/shinyMA
 - lgatto/shogun
 - lgatto/spreadsheet-ecology-lesson
 - lgatto/sticker
 - lgatto/stirling_numbers
 - lgatto/sugsvarsel
 - lgatto/synapter
 - lgatto/ten-simple-rules-dockerfiles
 - lgatto/testvigcovr
 - lgatto/tgac-component-class
 - lgatto/tidies
 - lgatto/tiny_queuing_system
 - lgatto/tipsntRicks
 - lgatto/trackeR
 - lgatto/tweenr
 - lgatto/webdata-paper
 - lgatto/wishes
 - lgatto/yagop

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
