### ISSUE TITLE
Opt-out request for lucsorel

### ISSUE THREAD

**Issue by lucsorel** [bigcode-project/opt-out-v2#1671]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - lucsorel/ProgrammingAssignment2
 - lucsorel/breizhcamp-schedule
 - lucsorel/cheeses-holder
 - lucsorel/config-complete
 - lucsorel/datasciencecoursera
 - lucsorel/diaporamas-webpack
 - lucsorel/energiencrypt
 - lucsorel/i18n-express
 - lucsorel/i18n-website
 - lucsorel/platform
 - lucsorel/pymonad
 - lucsorel/socket-io-ng-service
 - lucsorel/ui-router-menu-service
 - lucsorel/watts-app
 - lucsorel/web-content-analysis
 - lucsorel/zeromq-bindings

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
