### ISSUE TITLE
Opt-out request for adamhotep

### ISSUE THREAD

**Issue by adamhotep** [bigcode-project/opt-out-v2#1688]
I request that the following data is removed from The Stack and StackOverflow:

 - all
 - Commits
 - GitHub issue
 - StackExchange: user:674651 (Adam Katz)
   - all
   - StackOverflow: user:519360 (Adam Katz)
   - Super User: user:300293 (Adam Katz)
   - Server Fault: user:209449 (Adam Katz)
   - Ask Ubuntu: user:260416 (Adam Katz)
   - security.StackExchange: user:42391 (Adam Katz)
   - unix.StackExchange: user:87770 (Adam Katz)
   - codegolf.StackExchange: user:43035 (Adam Katz)
 - adamhotep/.dotfiles
 - adamhotep/8ball
 - adamhotep/Firefox-Tweaks
 - adamhotep/grc

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
