### ISSUE TITLE
Opt-out request for nsfmc

### ISSUE THREAD

**Issue by nsfmc** [bigcode-project/opt-out-v2#169]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: https://stackoverflow.com/users/470756/marcos
 - nsfmc/ESLint-Formatter
 - nsfmc/FAIR
 - nsfmc/Mabel
 - nsfmc/Stumblr
 - nsfmc/atoll.js
 - nsfmc/backbone-starter-kit
 - nsfmc/binario
 - nsfmc/cat
 - nsfmc/chartjunk
 - nsfmc/clipblur
 - nsfmc/dbn.js
 - nsfmc/dotfiles
 - nsfmc/elephante
 - nsfmc/este-todomvc
 - nsfmc/extract-text-test
 - nsfmc/flow-bugtest
 - nsfmc/generic-cx-content
 - nsfmc/hamlets-ghost
 - nsfmc/hivemind
 - nsfmc/khan-boxen
 - nsfmc/khan-dotfiles
 - nsfmc/kiln-review
 - nsfmc/less-extractor
 - nsfmc/log-lister
 - nsfmc/meatglue
 - nsfmc/notp
 - nsfmc/oh-my-zsh
 - nsfmc/peril
 - nsfmc/ploddables
 - nsfmc/plotdevice-manual
 - nsfmc/prosemirror
 - nsfmc/puzzler
 - nsfmc/royal-crown
 - nsfmc/sanitarium
 - nsfmc/svg-sketch
 - nsfmc/voxpop
 - studiosnack/brews-clues
 - studiosnack/ffff
 - studiosnack/loudland
 - studiosnack/on-air
 - studiosnack/peril-config
 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
