### ISSUE TITLE
Opt-out request for akash-joshi

### ISSUE THREAD

**Issue by akash-joshi** [bigcode-project/opt-out-v2#1695]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - akash-joshi/ADCAT-myHack
 - akash-joshi/Convention
 - akash-joshi/DC-comics-logo-classifier
 - akash-joshi/Felix-Apology-Services
 - akash-joshi/HCAHPS-Hospital-Rating
 - akash-joshi/Leaf-classification-web-app
 - akash-joshi/Poker-3
 - akash-joshi/Portfolio-Website
 - akash-joshi/Sciblr
 - akash-joshi/SiteSeer
 - akash-joshi/SiteSeer-Website-Changes-Tracker
 - akash-joshi/Today-I-Liked
 - akash-joshi/abell
 - akash-joshi/abell-starter-minima
 - akash-joshi/absurdify
 - akash-joshi/accessible-hn
 - akash-joshi/adversarial-comparer
 - akash-joshi/akash-joshi.github.io
 - akash-joshi/auth-wiki-public
 - akash-joshi/avstream.js
 - akash-joshi/blogproject
 - akash-joshi/bluejack
 - akash-joshi/chat-dabba
 - akash-joshi/complex-pg-queries
 - akash-joshi/conway-game-of-life
 - akash-joshi/covid-heatmap
 - akash-joshi/dailyhack
 - akash-joshi/deno-react-tutorial
 - akash-joshi/deno-url-shortener
 - akash-joshi/docs
 - akash-joshi/firebase-funcs
 - akash-joshi/functions-without-borders
 - akash-joshi/gatsby-theme-neuromancer
 - akash-joshi/gigindia
 - akash-joshi/github-pages-api-experiment
 - akash-joshi/gummybear-reviews
 - akash-joshi/hackathon
 - akash-joshi/homvery
 - akash-joshi/mdm
 - akash-joshi/metacall-SSR-react-example
 - akash-joshi/metacall-ml-example
 - akash-joshi/morse-translator
 - akash-joshi/my-own-writing-app
 - akash-joshi/nodejs-express-example
 - akash-joshi/note
 - akash-joshi/notes-app-for-blog
 - akash-joshi/notion-podcast
 - akash-joshi/open-dashboards
 - akash-joshi/pennywise-plus
 - akash-joshi/pewds-app
 - akash-joshi/pickedtweets
 - akash-joshi/pwa-repo
 - akash-joshi/react-dogs-app
 - akash-joshi/react-pune-hooks-talk
 - akash-joshi/redir
 - akash-joshi/respond
 - akash-joshi/sentiment-cloud
 - akash-joshi/socket-blog-client
 - akash-joshi/socket-server
 - akash-joshi/stylish
 - akash-joshi/super-search
 - akash-joshi/superhero
 - akash-joshi/tell-about
 - akash-joshi/upcheck
 - akash-joshi/use-twind-with
 - akash-joshi/wall
 - akash-joshi/website
 - akash-joshi/www-redirect

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
