### ISSUE TITLE
Opt-out request for pathunstrom

### ISSUE THREAD

**Issue by pathunstrom** [bigcode-project/opt-out-v2#1703]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - pathunstrom/2016-web
 - pathunstrom/DragonWarrior
 - pathunstrom/PyPet
 - pathunstrom/PygameTutorial
 - pathunstrom/Pygotham-Pygame
 - pathunstrom/Tic-Tac-Toe
 - pathunstrom/academictours
 - pathunstrom/academictours-flask
 - pathunstrom/accepting-your-success
 - pathunstrom/advent2018
 - pathunstrom/alchemy-market
 - pathunstrom/arena
 - pathunstrom/blog
 - pathunstrom/blogkit
 - pathunstrom/book-fizz-buzz
 - pathunstrom/breakout
 - pathunstrom/candyjam-snake
 - pathunstrom/challenge-wat-tor
 - pathunstrom/code-or-die
 - pathunstrom/creeps
 - pathunstrom/daily
 - pathunstrom/destiny-meme-roller
 - pathunstrom/dragons
 - pathunstrom/dungeonpet
 - pathunstrom/feet
 - pathunstrom/fireworks
 - pathunstrom/first-game
 - pathunstrom/flora
 - pathunstrom/game-blink
 - pathunstrom/game-jam-gmtk-2020
 - pathunstrom/game-mech-builder
 - pathunstrom/game-min-rts
 - pathunstrom/game-survival-remake
 - pathunstrom/game-symbiotes
 - pathunstrom/gameengine
 - pathunstrom/ghostbowl
 - pathunstrom/humblepeasant
 - pathunstrom/isittoolatetotransition
 - pathunstrom/lcah
 - pathunstrom/ld41
 - pathunstrom/llrmanager
 - pathunstrom/making-games-ppb
 - pathunstrom/makinggames
 - pathunstrom/misbehave
 - pathunstrom/monkeypatch-life
 - pathunstrom/neverlandlibrary
 - pathunstrom/nyc-python-materials
 - pathunstrom/onebitclicker
 - pathunstrom/passgen
 - pathunstrom/pathunstrom.github.io
 - pathunstrom/ppb-vector
 - pathunstrom/ppb-zombie-survival
 - pathunstrom/pyeks
 - pathunstrom/pysweeper
 - pathunstrom/pyweek-8bit
 - pathunstrom/pyweek29
 - pathunstrom/random-quote
 - pathunstrom/resume
 - pathunstrom/review
 - pathunstrom/santadrop
 - pathunstrom/shmup-survival-game
 - pathunstrom/talk-bear-and-a-briefcase
 - pathunstrom/talk-itertools
 - pathunstrom/talk-moving-boxes
 - pathunstrom/talk-principles-driven-dev
 - pathunstrom/talk-python-gaming-rocks
 - pathunstrom/tetris
 - pathunstrom/text-adventure
 - pathunstrom/timelord
 - pathunstrom/tutorial-making-games-ppb

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
