### ISSUE TITLE
Opt-out request for quiram

### ISSUE THREAD

**Issue by quiram** [bigcode-project/opt-out-v2#1707]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - quiram/VillagePaymentAgent
 - quiram/address-book
 - quiram/bash-utils
 - quiram/bowling-game
 - quiram/build-hotspots
 - quiram/fizzbuzz
 - quiram/foodit-javatest
 - quiram/html-unit-driver-visibility-issue
 - quiram/java-test-utils
 - quiram/java-utils
 - quiram/pseudotwitter
 - quiram/quiram.github.io
 - quiram/surefire-retry-failed-tests-issue

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
