### ISSUE TITLE
Opt-out request for amazingant and allykzam

### ISSUE THREAD

**Issue by allykzam** [bigcode-project/opt-out-v2#1726]
I request that the following data is removed from The Stack:

- amazingant/&lt;all repositories&gt;
- allykzam/&lt;all repositories&gt;

These accounts are both me, and I want them removed from the dataset.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
