### ISSUE TITLE
Opt-out request for andy-gray

### ISSUE THREAD

**Issue by andy-gray** [bigcode-project/opt-out-v2#1729]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - andy-gray/TicTacToe
 - andy-gray/java-seq
 - andy-gray/ld-graph
 - andy-gray/ldap-filters
 - andy-gray/planner
 - andy-gray/todone

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
