### ISSUE TITLE
Opt-out request for xale

### ISSUE THREAD

**Issue by xale** [bigcode-project/opt-out-v2#173]
I request that the following data is removed from The Stack and StackOverflow:

 - all
 - xale/BitTide
 - xale/CNF-Router
 - xale/FPGALab-ALU
 - xale/FPGALab-PLL
 - xale/FPGALab-PLL2
 - xale/FPGALab-PS2Mem
 - xale/FPGALab-ShiftRegister
 - xale/OOSE-invasion
 - xale/TinyControl
 - xale/Widget-Maker
 - xale/bzflag-mapvote
 - xale/bzflag-spreetracker
 - xale/derpisearch

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
