### ISSUE TITLE
Opt-out request for pixelmaid

### ISSUE THREAD

**Issue by pixelmaid** [bigcode-project/opt-out-v2#1733]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - pixelmaid/DataBrushesLatex
 - pixelmaid/DrawDetect_Processing
 - pixelmaid/JotUI
 - pixelmaid/SwiftKVC
 - pixelmaid/crosslogic
 - pixelmaid/dbn
 - pixelmaid/dresscodechi
 - pixelmaid/evodraw
 - pixelmaid/fancytree
 - pixelmaid/generative_experiment
 - pixelmaid/mitsite
 - pixelmaid/p5.js-editor
 - pixelmaid/piper
 - pixelmaid/shape-recog
 - pixelmaid/shopbot_server
 - pixelmaid/shopbotmanual

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
