### ISSUE TITLE
Opt-out request for danielmkarlsson

### ISSUE THREAD

**Issue by danielmkarlsson** [bigcode-project/opt-out-v2#1736]
I request that the following data is removed from The Stack:

 - Commits
 - GitHub issue
 - danielmkarlsson/ThunderDome
 - danielmkarlsson/a-collapse-of-structures
 - danielmkarlsson/a_loss_of_self
 - danielmkarlsson/amh
 - danielmkarlsson/an-artisan-static-netlify-site
 - danielmkarlsson/arrangements-for-voice
 - danielmkarlsson/danielmkarlsson.com
 - danielmkarlsson/danielmkarlsson.github.io
 - danielmkarlsson/dotfiles
 - danielmkarlsson/library
 - danielmkarlsson/mapping-the-valleys-of-the-uncanny
 - danielmkarlsson/rpp
 - danielmkarlsson/sc4reaper
 - danielmkarlsson/tidal
 - danielmkarlsson/traditional-musics-in-established-styles
 - danielmkarlsson/vim-tidal

I also request that you *fuck all of the off* with your *fucking nonsense* making me jump through hoops "opting out" of your *fucking automated theft*.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
