### ISSUE TITLE
Opt-out request for dmorgan-github

### ISSUE THREAD

**Issue by dmorgan-github** [bigcode-project/opt-out-v2#1738]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - dmorgan-github/CacheCow
 - dmorgan-github/ExData_Plotting1
 - dmorgan-github/ProgrammingAssignment2
 - dmorgan-github/StatsView
 - dmorgan-github/WebApiContrib.Formatting.CollectionJson
 - dmorgan-github/droptableuser
 - dmorgan-github/getandcleandata
 - dmorgan-github/java-template
 - dmorgan-github/miniml
 - dmorgan-github/node-seleniumgrid
 - dmorgan-github/node-skeleton
 - dmorgan-github/scynapse
 - dmorgan-github/skflow
 - dmorgan-github/workspaces

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
