### ISSUE TITLE
Opt-out request for smammy

### ISSUE THREAD

**Issue by smammy** [bigcode-project/opt-out-v2#1739]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: smammy
 - ALL REPOS, PAST PRESENT AND FUTURE, UNDER THE GITHUB USERNAME `smammy` INCLUDING BUT NOT LIMITED TO:
 - smammy/Backup-Bouncer
 - smammy/Firefox-Useful-New-Tab-Page
 - smammy/dnscheckip
 - smammy/h897-comparison
 - smammy/heat-meteo
 - smammy/homebrew-cask
 - smammy/restic-wrapper-b2

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
