### ISSUE TITLE
Opt-out request for VileLasagna

### ISSUE THREAD

**Issue by VileLasagna** [bigcode-project/opt-out-v2#1748]
I request that the following data is removed from The Stack and StackOverflow:

 - all
 - Commits
 - GitHub issue
 - VileLasagna/Experimental_ROC
 - VileLasagna/WarpDrive
 - VileLasagna/clspv
 - VileLasagna/hipSYCL
 - VileLasagna/legacy-AnimationClass
 - VileLasagna/legacy-Blackrock
 - VileLasagna/legacy-Bloxtris
 - VileLasagna/legacy-ChessGameGraphical
 - VileLasagna/legacy-ChessGameTXT
 - VileLasagna/legacy-CollisionMesh
 - VileLasagna/legacy-FracGen
 - VileLasagna/legacy-Octree101
 - VileLasagna/legacy-RollingField
 - VileLasagna/legacy-SceneGraph101
 - VileLasagna/qG13d
 - VileLasagna/qmakeandroidclang

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
