### ISSUE TITLE
Opt-out request for Nincodedo

### ISSUE THREAD

**Issue by Nincodedo** [bigcode-project/opt-out-v2#1756]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - Nincodedo/.github
 - Nincodedo/BetterRecords
 - Nincodedo/CreepersFire
 - Nincodedo/Goodbot
 - Nincodedo/JoanBot
 - Nincodedo/Morph-o-Tool
 - Nincodedo/Ninbot
 - Nincodedo/SmallsOnline.Subnetting
 - Nincodedo/maven-springbatch-archetype
 - Nincodedo/nincodedo.com
 - Nincodedo/nincraft.com
 - Nincodedo/rpg-core
 - all

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
