### ISSUE TITLE
Opt-out request for matthiask, feinheit, feincms, django-mptt, django-ckeditor and jazzband

### ISSUE THREAD

**Issue by matthiask** [bigcode-project/opt-out-v2#1762]
I request that the following data is removed from The Stack:

- All data from the following users and organizations:
- https://github.com/matthiask/
- https://github.com/feinheit/
- https://github.com/feincms/
- https://github.com/django-mptt/
- https://github.com/django-ckeditor/
- https://github.com/jazzband/
 - all

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
