### ISSUE TITLE
Opt-out request for jneubrand

### ISSUE THREAD

**Issue by jneubrand** [bigcode-project/opt-out-v2#1772]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - jneubrand/Falling-Stripes
 - jneubrand/Markovy-Christmas
 - jneubrand/chromabar
 - jneubrand/clay
 - jneubrand/dotfiles
 - jneubrand/eclipse-config
 - jneubrand/elliptical
 - jneubrand/homebridge-bluesound
 - jneubrand/jneubrand.github.io
 - jneubrand/locale_framework
 - jneubrand/negative-squares
 - jneubrand/neues
 - jneubrand/pb-build
 - jneubrand/pb-completions
 - jneubrand/pb-package-list
 - jneubrand/pb-run
 - jneubrand/pdc-inspect
 - jneubrand/pdc-js
 - jneubrand/pebble-battery-bar
 - jneubrand/pfont-inspect
 - jneubrand/special-draw
 - jneubrand/special-draw-dither
 - jneubrand/special-draw-mask
 - jneubrand/special-draw-transform
 - jneubrand/svba-null-ist
 - jneubrand/tum.fyi
 - jneubrand/vibration-sandbox

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
