### ISSUE TITLE
Opt-out request for stwind

### ISSUE THREAD

**Issue by stwind** [bigcode-project/opt-out-v2#1776]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - stwind/Cinder-ImGui
 - stwind/FSHP
 - stwind/amqp_client
 - stwind/ansible-freight
 - stwind/callbag-animation-frames
 - stwind/dockersnoop
 - stwind/dotfiles
 - stwind/dstwkr
 - stwind/ecli
 - stwind/ehrpc
 - stwind/elise
 - stwind/erl_common.mk
 - stwind/erlvue
 - stwind/erlvue-web
 - stwind/erlwamp
 - stwind/exercises-in-style
 - stwind/forest
 - stwind/gan-experiments
 - stwind/gen_service
 - stwind/gitit-ui
 - stwind/gohttpsnoop
 - stwind/graphite
 - stwind/hosi
 - stwind/kiwii-s-wp-theme
 - stwind/kubewatch.py
 - stwind/labyrinth-and-dead-sea
 - stwind/lasse
 - stwind/lls-test
 - stwind/lucent
 - stwind/monstats
 - stwind/notebooks
 - stwind/onaji
 - stwind/physical-text
 - stwind/prcno-conf
 - stwind/prcno-ui
 - stwind/pusherman
 - stwind/stwind
 - stwind/stwind.github.io
 - stwind/syntaxerl
 - stwind/umbrella
 - stwind/usagi
 - stwind/virtual-dom-loader
 - stwind/vmstats
 - stwind/yokogao
 - stwind/zerpc
 - stwind/zipstream
 - stwind/zstd-wasm

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
