### ISSUE TITLE
Opt-out request for murl-digital

### ISSUE THREAD

**Issue by murl-digital** [bigcode-project/opt-out-v2#1778]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: sorenneedscoffee
 - murl-digital/FrozenBushes
 - murl-digital/OofMeter
 - murl-digital/ThatHurleyGurleys_image_challenge
 - murl-digital/crypto-stupidness
 - murl-digital/electrons
 - murl-digital/elemental-4-server
 - murl-digital/physim
 - murl-digital/rsattempt
 - murl-digital/simple-block
 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
