### ISSUE TITLE
Opt-out request for sganondorf

### ISSUE THREAD

**Issue by sabrinagannon** [bigcode-project/opt-out-v2#1786]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - sganondorf/Alpha-Blog
 - sganondorf/LonelyTwitterRefactoring
 - sganondorf/cuddly-octo-computing-machine
 - sganondorf/dotfiles
 - sganondorf/finance-tracker
 - sganondorf/ink-syntax
 - sganondorf/language-ink
 - sganondorf/sgannon1-expense_claim
 - sganondorf/sganondorf.github.io

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
