### ISSUE TITLE
Opt-out request for awilfox

### ISSUE THREAD

**Issue by awilfox** [bigcode-project/opt-out-v2#1797]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: [A. Wilcox](https://stackoverflow.com/users/640296/a-wilcox)
 - foxkit-us/PyIRC
 - wilcox-tech/ActiveReport
 - wilcox-tech/aerospike-py
 - wilcox-tech/furry-hipster
 - wilcox-tech/libmowgli-wt
 - wilcox-tech/spark
 - AdelieLinux/apk-tools
 - AdelieLinux/aports
 - AdelieLinux/gettext-tiny
 - AdelieLinux/marl
 - awilfox/FreeBSD-fixes
 - awilfox/ModalVCsFromActionSheets
 - awilfox/PkgConfig-LibPkgConf
 - awilfox/RServ
 - awilfox/SwitchTableViewBuster
 - awilfox/TableSectionHeaderTest
 - awilfox/enya
 - awilfox/eviluni
 - awilfox/fcp
 - awilfox/gb-rom-utils
 - awilfox/glorircd
 - awilfox/irclib
 - awilfox/libucontext
 - awilfox/m2m_nested_form_test
 - awilfox/pinkeen-prototype
 - awilfox/protocol
 - awilfox/real-git-rcmp
 - awilfox/rstexample
 - awilfox/rublets
 - awilfox/slabbed-or-not
 - awilfox/tablefactory

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
