### ISSUE TITLE
Opt-out request for decathorpe

### ISSUE THREAD

**Issue by decathorpe** [bigcode-project/opt-out-v2#1802]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - decathorpe/elementary-appcenter-rpms
 - decathorpe/elementary-rpms
 - decathorpe/elementary-rpms-stable
 - decathorpe/elementary-stable-rpms
 - decathorpe/elementary-staging-rpms
 - decathorpe/fedora-pkgs
 - decathorpe/mock-elementary-nightly
 - decathorpe/pandora-wallpapers
 - decathorpe/pantheon-session-settings
 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
