### ISSUE TITLE
Opt-out request for FuzzyLitchi

### ISSUE THREAD

**Issue by FuzzyLitchi** [bigcode-project/opt-out-v2#1804]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - FuzzyLitchi/3A03
 - FuzzyLitchi/BulletStorm
 - FuzzyLitchi/ITUleethax
 - FuzzyLitchi/InitBotKappa
 - FuzzyLitchi/NeuroCar
 - FuzzyLitchi/PhaserMobile
 - FuzzyLitchi/RubikGang
 - FuzzyLitchi/Smaragdine
 - FuzzyLitchi/abs
 - FuzzyLitchi/boos-and-spirits
 - FuzzyLitchi/chat
 - FuzzyLitchi/ddu2020
 - FuzzyLitchi/dr_hack4dk
 - FuzzyLitchi/fuzz_os
 - FuzzyLitchi/gymbilletter
 - FuzzyLitchi/img-util-fs
 - FuzzyLitchi/love-graph
 - FuzzyLitchi/lovehighscore
 - FuzzyLitchi/lua
 - FuzzyLitchi/ncpc2020
 - FuzzyLitchi/ncpc2020-warmup
 - FuzzyLitchi/p2p-chess
 - FuzzyLitchi/passtally-rs
 - FuzzyLitchi/pop-11g
 - FuzzyLitchi/psychic-pancake
 - FuzzyLitchi/salmon-rat
 - FuzzyLitchi/sodavand
 - FuzzyLitchi/solo-canon
 - FuzzyLitchi/speed-jam
 - FuzzyLitchi/teknik-uge-projekt

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
