### ISSUE TITLE
Opt-out request for jlink

### ISSUE THREAD

**Issue by jlink** [bigcode-project/opt-out-v2#1807]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: johanneslink
 - jlink/ConcurrencyOnJvmAndElsewhere
 - jlink/Functional-TDD-Workshop
 - jlink/JUnitMin
 - jlink/Parallel2013
 - jlink/Parse4SJM
 - jlink/Rechnerzeit
 - jlink/codea
 - jlink/contract-testing
 - jlink/efs2014
 - jlink/functional-tdd
 - jlink/gmonads
 - jlink/how-to-specify-it
 - jlink/intellij-kotlin-function-names-bug
 - jlink/intellij-missing-run-decorator
 - jlink/intellij-organize-imports-bug
 - jlink/jax2017
 - jlink/jqwik-example
 - jlink/junit5-the-platform
 - jlink/kata-bootstraps
 - jlink/katas
 - jlink/kotlin-java-annotation-bug
 - jlink/legacybank
 - jlink/mockme
 - jlink/pbt-etffm21
 - jlink/pbt-workshop
 - jlink/property-based-testing
 - jlink/property-driven-development
 - jlink/qstag-2018
 - jlink/quadratic-equation
 - jlink/random-numbers
 - jlink/scoreboard
 - jlink/tailrec
 - jlink/tdd-fau
 - jlink/test-quickcheck
 - jlink/the-game-of-tak
 - jlink/web-boot-spike

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
