### ISSUE TITLE
remove everything

### ISSUE THREAD

**Issue by adryzz** [bigcode-project/opt-out-v2#1814]
I request that the following data is removed from The Stack:

 - Commits
 - GitHub issue
- adryzz/2DTestRendering
- adryzz/AdryzzPlugins
- adryzz/AnimeLib
- adryzz/ArduinoOBSReceiver
- adryzz/Attributer
- adryzz/AudioSpeedUp-1
- adryzz/BlynkPingGraph
- adryzz/Clay-Ottimo-Direi
- adryzz/Clipboards
- adryzz/CodeScheduler
- adryzz/Cookie-deleter
- adryzz/DaniEventProgram
- adryzz/DisplayAPI
- adryzz/DisplayAPITestApp
- adryzz/FakeDiskDrive
- adryzz/FileSystemWatcher
- adryzz/OTDHardwareMouse
- adryzz/OpenTabletWrapper
- adryzz/PrivacyTools
- adryzz/RemoteControlV3
- adryzz/ServerInfo
- adryzz/TrojanTest1
- adryzz/VirtualDesktopToolBox
- adryzz/VirtualDeviceAPI
- adryzz/WSBManager
- adryzz/YouTubeDesktop
- adryzz/adryyyy.github.io
- adryzz/animelib-updater
- adryzz/docs
- adryzz/game1
- adryzz/lol
- adryzz/osu-MapRandomizer
- adryzz/osu-api
- adryzz/pico-kappa-pad
- adryzz/shootinggame_ALPHA
- adryzz/simple_clock
- adryzz/test
- adryzz/usblocker
- everything
 
_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.
...

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
