### ISSUE TITLE
Opt-out request for pcdevil

### ISSUE THREAD

**Issue by pcdevil** [bigcode-project/opt-out-v2#1822]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: [pcdevil](https://stackoverflow.com/users/1423815/pcdevil)
 - pcdevil/cv
 - pcdevil/fs-promise
 - pcdevil/g
 - pcdevil/gameoflife
 - pcdevil/huqwerty
 - pcdevil/moneythink-mobile-lp
 - pcdevil/node-example-project
 - pcdevil/pcdevil.github.io
 - pcdevil/random-coderproverb
 - pcdevil/telegram-dr-ziegler-theme

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
