### ISSUE TITLE
Opt-out request for NickleDave

### ISSUE THREAD

**Issue by NickleDave** [bigcode-project/opt-out-v2#1825]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: NickleDave
 - NickleDave/ALIFexNet
 - NickleDave/APATHY
 - NickleDave/BAM
 - NickleDave/BEST-contacts
 - NickleDave/BEST-data-science-short-course
 - NickleDave/DMN_by_SGD
 - NickleDave/DPrimeLearning
 - NickleDave/EWIN-coding-bootcamp
 - NickleDave/IttiKochNieburNengo
 - NickleDave/KLFromRecordingDays
 - NickleDave/ML-comparison-birdsong
 - NickleDave/MetaNickleDave
 - NickleDave/Nicholson-Prinz-JOV-DNNs-bio-vis
 - NickleDave/NickleDave.github.io
 - NickleDave/PPI_analysis
 - NickleDave/app-tatertot
 - NickleDave/aver
 - NickleDave/birdsong-recognition-dataset
 - NickleDave/birdsong-resources
 - NickleDave/compare-seg-models
 - NickleDave/continual-learning
 - NickleDave/cosyne2018-synaptic-computation
 - NickleDave/course-v3
 - NickleDave/evfuncs
 - NickleDave/fcn-syl-seg
 - NickleDave/flask-dance-figshare
 - NickleDave/generative-neural-nets-tutorial-scipy2020
 - NickleDave/hybrid-deep-finch
 - NickleDave/hybrid-vocal-classifier
 - NickleDave/intro-ml-sklearn
 - NickleDave/ipfreely
 - NickleDave/learning-curves
 - NickleDave/make-vis-search-stim-pygame
 - NickleDave/my-first-blog
 - NickleDave/nengo.github.io
 - NickleDave/notetate
 - NickleDave/open-analysis-atlanta
 - NickleDave/pomma
 - NickleDave/pyclist
 - NickleDave/pyfigshare
 - NickleDave/pyopensci.github.io
 - NickleDave/pyvanot
 - NickleDave/recurrent-visual-attention
 - NickleDave/scicode-learn
 - NickleDave/searchstims
 - NickleDave/slidebox
 - NickleDave/songdeck-old
 - NickleDave/songdkl
 - NickleDave/textgrid
 - NickleDave/thrillington
 - NickleDave/vak
 - NickleDave/vak_test_net
 - NickleDave/visual-search-nets
 - NickleDave/vocal-behavior-resources
 - NickleDave/warblePy
 - NickleDave/williams
 - NickleDave/winterschool

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
