### ISSUE TITLE
Opt-out request for kstateome

### ISSUE THREAD

**Issue by zanshin** [bigcode-project/opt-out-v2#1830]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - kstateome/awscli-login
 - kstateome/canvas-countdown-clock
 - kstateome/django-cas
 - kstateome/django-p3p
 - kstateome/django-ping
 - kstateome/django-piston-ical-emitter
 - kstateome/django-piston-rss-emitter
 - kstateome/fabric
 - kstateome/kstateome.github.com
 - kstateome/kubeadm
 - kstateome/office365-and-azure-ad-grouper-provisioner
 - kstateome/scantron-dev
 - kstateome/spymemcached
 - kstateome/userscript

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
