### ISSUE TITLE
Opt-out request for egonw

### ISSUE THREAD

**Issue by egonw** [bigcode-project/opt-out-v2#1833]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - egonw/ACS-Twitter-Visualization
 - egonw/AZOrange
 - egonw/BBB-Prediction
 - egonw/BFO-2020
 - egonw/BMUSE
 - egonw/BSL-explained
 - egonw/BioHackathon
 - egonw/ChEBI
 - egonw/ChemIdConvert
 - egonw/ChemputerSoftware
 - egonw/CompoundDb
 - egonw/Drug_Disease_Target_Mapping
 - egonw/ELIXIR-Tox
 - egonw/InteractionDB
 - egonw/LipidProj
 - egonw/MassBank-web
 - egonw/MetaboLights
 - egonw/MetaboliteOntologyMapper
 - egonw/Metrics
 - egonw/MoaBox
 - egonw/NanoMaturityIndicators
 - egonw/NanoPHEAT
 - egonw/OBOFoundry.github.io
 - egonw/OLS-Config
 - egonw/OPS_AppNote
 - egonw/OPS_LinkedDataApi
 - egonw/OSDB
 - egonw/OSSRH-49593
 - egonw/OpenPaleo
 - egonw/PathwayAnalyser
 - egonw/PyShEx
 - egonw/RDMMP
 - egonw/RMassBank
 - egonw/RRDKit
 - egonw/RaMID
 - egonw/RanDepict
 - egonw/SARS-CoV-2-WikiPathways
 - egonw/SARS-CoV-2_PRJNA612766
 - egonw/SPARQLQueries
 - egonw/Smiles-TO-iUpac-Translator
 - egonw/WikiPathwaysComplexes
 - egonw/WikiPathwaysDataSummaries
 - egonw/WikiPathwaysSDF
 - egonw/Wikidata-Toolkit
 - egonw/Wikidata2Bridgedb
 - egonw/WikidataScholia_ICCS
 - egonw/acs2ioc
 - egonw/ambit
 - egonw/ambit-mirror
 - egonw/ambit2-all
 - egonw/biblatex-biomedcentral
 - egonw/bioc_notebooks
 - egonw/bioclipse.bigcatedu
 - egonw/bioclipse.bioinformatics
 - egonw/bioclipse.bridgedb
 - egonw/bioclipse.core
 - egonw/bioclipse.ds
 - egonw/bioclipse.experimental
 - egonw/bioclipse.openphacts
 - egonw/bioclipse.opentox
 - egonw/bioclipse.oscar
 - egonw/bioclipse.statistics
 - egonw/bioclipse.textmining
 - egonw/bioclipse.wikidata
 - egonw/bioclipse2wdchem
 - egonw/bioconductor.org
 - egonw/biomappings
 - egonw/biomarkers
 - egonw/biostar-central
 - egonw/bioversions
 - egonw/bodr
 - egonw/bridgedbjs
 - egonw/cacm-article
 - egonw/cdk-cxsmiles
 - egonw/cdk-migration
 - egonw/cdk-taverna-2
 - egonw/cdkcmd
 - egonw/cdkr
 - egonw/cff-generator
 - egonw/chemfig
 - egonw/chempaint
 - egonw/cinfony
 - egonw/citation-js
 - egonw/citation.js
 - egonw/citedin
 - egonw/citeulike
 - egonw/citeulike-export
 - egonw/citeuliker
 - egonw/cito-update
 - egonw/cito-wikidata-queries
 - egonw/civic-api-docs
 - egonw/cmnanotox
 - egonw/collaborative.cheminformatics
 - egonw/completeness
 - egonw/conferenceR
 - egonw/covid_kges
 - egonw/create-bridgedb-genedb
 - egonw/create-bridgedb-hmdb
 - egonw/create-bridgedb-lycocyc
 - egonw/create-bridgedb-metabolites
 - egonw/cytoscape2gpml
 - egonw/dbXP_BioclipsePlugin
 - egonw/dummy
 - egonw/dvn
 - egonw/edamontology
 - egonw/effectopedia-patches
 - egonw/egonw.github.com
 - egonw/enmSummaries
 - egonw/enmrdf
 - egonw/events
 - egonw/example
 - egonw/examples-ambit
 - egonw/examples-cdk
 - egonw/grant-api
 - egonw/groovy-citeulike
 - egonw/groovy-jcp
 - egonw/groovymarkdown-template
 - egonw/homepage
 - egonw/i4oc.github.io
 - egonw/icebear
 - egonw/inchi-cdk-bioclipse
 - egonw/index-submit-form
 - egonw/interactive-pvjs
 - egonw/jcheminform-author-guidelines
 - egonw/jmzTab-m
 - egonw/jqudt
 - egonw/khem
 - egonw/knime-wikipathways
 - egonw/knime-wikipathways-updatesite
 - egonw/label2datanode
 - egonw/larsgw.github.io
 - egonw/lavoisier
 - egonw/loom
 - egonw/lorentz-mibig-rdf
 - egonw/lychi
 - egonw/metaboigniter
 - egonw/metabolomics-practical
 - egonw/metabolomics-slides
 - egonw/metawinterschool-bigcat
 - egonw/models
 - egonw/msb1015_assignment1
 - egonw/mscpils
 - egonw/nanowiki
 - egonw/nardb2014index
 - egonw/nextprot-openapi-grlc
 - egonw/nextprot-queries
 - egonw/nichtich.github.io
 - egonw/nmdataparser
 - egonw/nmrshiftdb-rdf
 - egonw/nmsa
 - egonw/ons
 - egonw/ons-c4
 - egonw/ons-chebi
 - egonw/ons-theses
 - egonw/ons-wikidata
 - egonw/ons-wikipathways
 - egonw/openVirus
 - egonw/openapi-examples
 - egonw/openchemlib
 - egonw/openrisknet-registry
 - egonw/ops.js
 - egonw/orcid-affiliations
 - egonw/orn-ontology
 - egonw/oss-desc
 - egonw/pathvisio-1
 - egonw/pathvisio.github.io
 - egonw/pimp
 - egonw/plugin-template
 - egonw/pubchem-cdk
 - egonw/rWikiPathways
 - egonw/reply
 - egonw/roadmap
 - egonw/ron
 - egonw/rqudt
 - egonw/rrdf-paper
 - egonw/scheduled-bots
 - egonw/scholia-junit-selenium
 - egonw/seagrid-data
 - egonw/shapes-of-you
 - egonw/shexWorkingBio
 - egonw/simid
 - egonw/softpaper-citation-cff
 - egonw/specifications
 - egonw/specifications-2
 - egonw/spectra-hash
 - egonw/suppInfoFullerenol
 - egonw/swagger2BioTools
 - egonw/swat4hcls2018
 - egonw/swat4ls2016-art40
 - egonw/tag2link
 - egonw/toxbank-api-beans
 - egonw/toxbank-api-client
 - egonw/toxbank-api-server
 - egonw/unpaywall-data-website
 - egonw/wd
 - egonw/webchem
 - egonw/wikidata-item-size
 - egonw/wikidata-query-deploy
 - egonw/wikidata2pubchem
 - egonw/wikipathways-api-client-java
 - egonw/workshop
 - egonw/wp-rdf-api
 - egonw/wprdfLoadScripts
 - egonw/xmetdb-server
 - egonw/xproc-ebook-conv
 - egonw/zikaVirus

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
