### ISSUE TITLE
Opt-out request for dsekercioglu

### ISSUE THREAD

**Issue by jnlt3** [bigcode-project/opt-out-v2#1837]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - dsekercioglu/CelestialWars
 - dsekercioglu/Gravity
 - dsekercioglu/Sudoku
 - dsekercioglu/WildNature
 - dsekercioglu/WordLadder
 - dsekercioglu/Xenonn
 - dsekercioglu/carpet
 - dsekercioglu/doodlang
 - dsekercioglu/gonn
 - dsekercioglu/rage
 - dsekercioglu/tictactoe

These repositories are under my old username and apparently it wasn't taken into consideration that github usernames are in fact not static.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
