### ISSUE TITLE
Opt-out request for oscherler

### ISSUE THREAD

**Issue by oscherler** [bigcode-project/opt-out-v2#1842]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - oscherler/JeriveSchedulerBundle
 - oscherler/MidiWifi
 - oscherler/RetroCEDE
 - oscherler/TeamWorkPmPhpApi
 - oscherler/amazon-fbt-generator
 - oscherler/composer-basics
 - oscherler/cv-renderer
 - oscherler/erlang-indexer
 - oscherler/iReSign
 - oscherler/linux-xinmo-driver
 - oscherler/mister-scratch
 - oscherler/openphoto-python
 - oscherler/openphoto-wiki
 - oscherler/rabbitmq-delayed-sample
 - oscherler/sf-translation-loading-demonstrator
 - oscherler/snap
 - oscherler/xmlresume-build
 - - all
 
 Also, as many others have said: opt-out is not consent. Step on a Lego.

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
