### ISSUE TITLE
Opt-out request for lewiscowper

### ISSUE THREAD

**Issue by lewiscowper** [bigcode-project/opt-out-v2#1848]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - lewiscowper/QuickEncrypt
 - lewiscowper/backup
 - lewiscowper/brigade
 - lewiscowper/dot-proxy
 - lewiscowper/dotcrap
 - lewiscowper/dotfiles
 - lewiscowper/goshell
 - lewiscowper/hoodie-cli
 - lewiscowper/jsonrpc
 - lewiscowper/keycloak
 - lewiscowper/markdown-chalk
 - lewiscowper/nostromo
 - lewiscowper/schoolmapper
 - lewiscowper/star-wars
 - lewiscowper/swapi-scheme
 - lewiscowper/64sts
 - lewiscowper/CV
 - lewiscowper/ClinicCases
 - lewiscowper/OpenACalendar-Web-Core
 - lewiscowper/Sally-Yang-Jing-Ou.github.io
 - lewiscowper/academy
 - lewiscowper/adstex
 - lewiscowper/api
 - lewiscowper/approachable-project
 - lewiscowper/arc
 - lewiscowper/arss
 - lewiscowper/athens
 - lewiscowper/beakerbrowser.com
 - lewiscowper/bgpranking-redis-api
 - lewiscowper/bigdata.lol
 - lewiscowper/blocked-org-uk
 - lewiscowper/blog
 - lewiscowper/cape-baboon-1
 - lewiscowper/check-it
 - lewiscowper/class_advfrontend
 - lewiscowper/clonedepp
 - lewiscowper/config
 - lewiscowper/configs
 - lewiscowper/cssclasses-challenges
 - lewiscowper/czmj.github.io
 - lewiscowper/defshef.github.io
 - lewiscowper/devtip-of-the-day
 - lewiscowper/docs
 - lewiscowper/documentation
 - lewiscowper/echo-chamber-js
 - lewiscowper/ethereum-testbed
 - lewiscowper/expandable-input
 - lewiscowper/fantasy-game-project
 - lewiscowper/fieri
 - lewiscowper/fox-example
 - lewiscowper/get-hyped
 - lewiscowper/git-user
 - lewiscowper/gitpubsheff.github.io
 - lewiscowper/groovy-beaver
 - lewiscowper/hatersGonnaHate
 - lewiscowper/hello-world
 - lewiscowper/hello-world-client
 - lewiscowper/hexclock
 - lewiscowper/hoodie
 - lewiscowper/hoodie-app-skeleton
 - lewiscowper/hoodie-integration-test
 - lewiscowper/hoodie-plugin-stripe
 - lewiscowper/hoodie-plugin-users
 - lewiscowper/hoodie-store-and-account-tutorial
 - lewiscowper/hyperterm-slimline
 - lewiscowper/hyperterm-tinycursor
 - lewiscowper/hyrule
 - lewiscowper/ikettle.js
 - lewiscowper/inferno
 - lewiscowper/irccloud-cli
 - lewiscowper/isitfeierabend
 - lewiscowper/just-relax
 - lewiscowper/kind.js
 - lewiscowper/knowledge
 - lewiscowper/learnk8s.io
 - lewiscowper/lewiscowper
 - lewiscowper/lewiscowper.github.io
 - lewiscowper/marky-markdown
 - lewiscowper/moby
 - lewiscowper/mod_strip
 - lewiscowper/new-interval
 - lewiscowper/new-site
 - lewiscowper/node-lts-browser
 - lewiscowper/notes
 - lewiscowper/npm-basically-magic
 - lewiscowper/npm-by-the-numbers
 - lewiscowper/npm-camp
 - lewiscowper/npm-install
 - lewiscowper/pagespeed-cli
 - lewiscowper/parker-grunt
 - lewiscowper/pipe-yard
 - lewiscowper/pouchdb-hoodie-api
 - lewiscowper/pymarkdown
 - lewiscowper/qs-in-the-browser
 - lewiscowper/racing
 - lewiscowper/railstutorial-sample-app
 - lewiscowper/react-maskedinput
 - lewiscowper/reddit-reader
 - lewiscowper/redux-game
 - lewiscowper/remove-git-ignored
 - lewiscowper/rss-reader
 - lewiscowper/sc5-styleguide
 - lewiscowper/schemer
 - lewiscowper/scotlandcss
 - lewiscowper/semantic-create-module
 - lewiscowper/semantic-release
 - lewiscowper/serviceworker-demo
 - lewiscowper/sheffjsblog
 - lewiscowper/shitty.men
 - lewiscowper/snzypt
 - lewiscowper/sqwiggle-python
 - lewiscowper/status
 - lewiscowper/tiley
 - lewiscowper/twitter-favourite-to-pocket
 - lewiscowper/utility-opentype.kennethormandy.com
 - lewiscowper/visualising-npm
 - lewiscowper/vpnht-frontend
 - lewiscowper/webaudio-app
 - lewiscowper/webrtc-quiz-game
 - lewiscowper/welgo
 - lewiscowper/xmvn
 - lewiscowper/libtrace
 - lewiscowper/hoodie-camp
 - lewiscowper/emojilisp
 - lewiscowper/jaredly.github.io
 - lewiscowper/grunt-release-hoodie
 - lewiscowper/amas
 - lewiscowper/SimpleReactNativeExample
 - lewiscowper/clappr
 - lewiscowper/ashleygwilliams.github.io
 - lewiscowper/to-id
 - lewiscowper/fokus
 - lewiscowper/my-first-hoodie
 - lewiscowper/railstutorial-hello-world
 - lewiscowper/catserver
 - lewiscowper/amp-by-example
 - lewiscowper/wagtail
 - lewiscowper/personal-goals
 - lewiscowper/bostonml
 - lewiscowper/inspiring-online
 - lewiscowper/motivations
 - lewiscowper/hometi.me
 - lewiscowper/swapnalirohan
 - lewiscowper/hexo-renderer-scss
 - lewiscowper/recharts
 - lewiscowper/hyperreduce
 - lewiscowper/yeti.css
 - lewiscowper/hoodie-server
 - lewiscowper/development-osx
 - lewiscowper/DisabilityApplication
 - lewiscowper/SJSJ
 - lewiscowper/b2g-manifest
 - lewiscowper/sheffieldgeeks
 - lewiscowper/theintern.github.io
 - lewiscowper/prometheus-operator
 - lewiscowper/react-albus
 - lewiscowper/hexo-server
 - lewiscowper/hood.ie
 - lewiscowper/dev-cert-authority
 - lewiscowper/you-dont-know-npm
 - lewiscowper/gradle-groovy-jar-example
 - lewiscowper/greenkeeper-1
 - lewiscowper/highland
 - lewiscowper/ionic-app-lib
 - lewiscowper/react-uikit-components
 - lewiscowper/cli
 - lewiscowper/gettingstartedwithrails-blog
 - lewiscowper/1962
 - lewiscowper/upfront_ug
 - lewiscowper/mod-spdy
 - lewiscowper/Rocket.Chat
 - lewiscowper/slides-1
 - lewiscowper/xAPI-Spec
 - lewiscowper/nuka-carousel
 - lewiscowper/surge
 - lewiscowper/nodemon
 - lewiscowper/sheffgeeks.github.io
 - lewiscowper/modern-react-snippets
 - lewiscowper/hecto
 - lewiscowper/hood.ie-1
 - lewiscowper/sqwiggle-api-documentation
 - lewiscowper/SpaceVim
 - lewiscowper/grafana-influx-dashboard
 - lewiscowper/ux-suite-api
 - lewiscowper/level-store
 - lewiscowper/react-blessed-hot-motion
 - lewiscowper/stm32-sdram
 - lewiscowper/hyperterm-hyperline
 - lewiscowper/js-irc.github.io
 - lewiscowper/railstutorial-toy-app
 - lewiscowper/hoodie-template-app-map
 - lewiscowper/javascript-conferences
 - lewiscowper/awesome-styled-components
 - lewiscowper/KeyChanger
 - lewiscowper/npm-run-all
 - lewiscowper/gaia
 - lewiscowper/pouchdb-hoodie-sync
 - lewiscowper/proposal
 - lewiscowper/ServiceWorker
 - lewiscowper/javascrippies
 - lewiscowper/BTorrent
 - lewiscowper/FreeCAD_VidKit
 - lewiscowper/material-ui
 - lewiscowper/torvaney.github.io
 
_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
