### ISSUE TITLE
Opt-out request for awilkins

### ISSUE THREAD

**Issue by awilkins** [bigcode-project/opt-out-v2#185]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: https://stackoverflow.com/users/108753/adrian
 - awilkins/ModelGoon-UML4Java
 - awilkins/amazon-ecr-credential-helper
 - awilkins/apperta-open-platform
 - awilkins/atom-cucumber-autocomplete
 - awilkins/dotfiles
 - awilkins/jgit_cassandra
 - awilkins/linter-terraform-semantics
 - awilkins/liquid-feedback-installer
 - awilkins/markdown-preview-plus-opener
 - awilkins/opnote-rb
 - awilkins/pm2-syslog
 - awilkins/potted-ci
 - awilkins/redmine-mylyn-connector
 - awilkins/redmine_priority_mail_watcher
 - awilkins/ripple-eoi
 - awilkins/sainsburyscraper
 - awilkins/seatreservations
 - awilkins/terraform-bug-18891
 - awilkins/terraform-lsp
 - awilkins/testcafe-bug-2500
 - awilkins/tree-sitter-terraform

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
