### ISSUE TITLE
Opt-out request for wenkokke

### ISSUE THREAD

**Issue by wenkokke** [bigcode-project/opt-out-v2#1852]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - all
 - wenkokke/AutoInAgda
 - wenkokke/LogStreamer
 - wenkokke/UoE-MT3-NMT
 - wenkokke/agda-pregroup
 - wenkokke/dep2con
 - wenkokke/dipsy
 - wenkokke/koka
 - wenkokke/msla2014
 - wenkokke/plutus
 - wenkokke/realLambdaPunter
 - wenkokke/rusty-variation
 - wenkokke/sesh
 - wenkokke/FunFlow
 - wenkokke/UoE-MT1-PBT
 - wenkokke/UvA-MT1-IBM
 - wenkokke/UvA-MT2-PBT
 - wenkokke/agda-exec-tc
 - wenkokke/agda-prelude
 - wenkokke/agda-qelim
 - wenkokke/amethyst
 - wenkokke/blog-old
 - wenkokke/cedille
 - wenkokke/cubical
 - wenkokke/degobah
 - wenkokke/dopcg2016
 - wenkokke/easyccg
 - wenkokke/hcp
 - wenkokke/latex-template
 - wenkokke/pelican
 - wenkokke/plfa.github.io
 - wenkokke/programming-problems
 - wenkokke/projecteuler
 - wenkokke/sf
 - wenkokke/talk-a-tale-of-three-constructed-languages
 - wenkokke/talk-formalising-session-typed-languages-without-worries
 - wenkokke/talk-programming-programming-language-foundations-in-agda-in-agda
 - wenkokke/talk-robustness-as-a-refinement-type
 - wenkokke/talk-session-types
 - wenkokke/talk-this-talk-wont-help-you-steal
 - wenkokke/talon_configs
 - wenkokke/tlla2018
 - wenkokke/wenkokke
 - wenkokke/where-the-linear-lambdas-go
 - wenkokke/women-in-programming-languages-research

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
