### ISSUE TITLE
Opt-out request for jcolomb- this has to be opt-in if you want to have any credibility in the community

### ISSUE THREAD

**Issue by jcolomb** [bigcode-project/opt-out-v2#1854]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - jcolomb/Description-of-Rodents-in-Scientific-Publications
 - jcolomb/HCS_analysis
 - jcolomb/OpenConSwiss.github.io
 - jcolomb/Viewer-file-concatenator
 - jcolomb/faux
 - jcolomb/helping.funders
 - jcolomb/hugo-universal-theme
 - jcolomb/hugrid
 - jcolomb/preprint_JournalClub
 - jcolomb/r-yaml
 - jcolomb/reagentsio_website
 - jcolomb/scholarly-metadata
 - jcolomb/researchdata_archiving_guide
 - jcolomb/writing-R-packages
 - jcolomb/Buridan_5CS
 - jcolomb/EFAshiny
 - jcolomb/HCS_data_1
 - jcolomb/Open_Science_101
 - jcolomb/PEERREVIEW
 - jcolomb/RRROBOTS
 - jcolomb/Top-10-FAIR
 - jcolomb/csvy.github.io
 - jcolomb/datacurationwork
 - jcolomb/dataviz-timelinepeerreview
 - jcolomb/doopenscience_workshop
 - jcolomb/fig_pkcpaper
 - jcolomb/gintonic-blog
 - jcolomb/jams
 - jcolomb/learningdata
 - jcolomb/lecture_Behaviora_science
 - jcolomb/marchforscience2017
 - jcolomb/meta-open-database
 - jcolomb/ols3-cohort-talks-and-transcripts
 - jcolomb/opendataworkshop2017
 - jcolomb/openscienceskills
 - jcolomb/osfr
 - jcolomb/prodigenr
 - jcolomb/rflybase
 - jcolomb/tenzing
 - jcolomb/testingpurposes
 - jcolomb/rfigshare
 - jcolomb/Open-Science-Training-Handbook_EN
 - jcolomb/module1_taskblogpost_gh
 - jcolomb/twitteR
 - jcolomb/global-sprint-2016
 - jcolomb/noamross.net
 - jcolomb/elife-article-xml
 - jcolomb/Octopamine-and-Tyramine-play-a-role-in-the-counterregulatory-response-to-sugar-deficit-in-Drosophila
 - jcolomb/Module-4-Open-Research-Data

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
