### ISSUE TITLE
Opt-out request for open-science-promoters

### ISSUE THREAD

**Issue by jcolomb** [bigcode-project/opt-out-v2#1855]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - open-science-promoters/RDM-promotion
 - open-science-promoters/contibutor_manager
 - open-science-promoters/reagentsio_website
 - open-science-promoters/tenzing-website
 - open-science-promoters/BUAgrant_OSH
 - open-science-promoters/RDA_REP_webiste
 - open-science-promoters/dynamic_citation
 - open-science-promoters/workshop_notes

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
