### ISSUE TITLE
Opt-out request for warthog9

### ISSUE THREAD

**Issue by warthog9** [bigcode-project/opt-out-v2#1857]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - warthog9/ansible-role-nginx
 - warthog9/ansible-role-warthog9-sshd
 - warthog9/os-mysql-master
 - warthog9/os-mysql-slave
 - warthog9/Vending-Machine
 - warthog9/community
 - warthog9/liota
 - warthog9/lms-mobileskin
 - warthog9/minnow-max-extras
 - warthog9/znc-warty-contrib
 - warthog9/bandit
 - warthog9/Adafruit-Feather-ESP8266-HUZZAH-PCB
 - warthog9/mraa

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
