### ISSUE TITLE
Opt-out request for klausman

### ISSUE THREAD

**Issue by klausman** [bigcode-project/opt-out-v2#186]
I request that the following data is removed from The Stack:

- *ALL* my repos, including future ones
- Explicitly:
- klausman/bugbot
- klausman/euw
- klausman/golop
- klausman/hexdump
- klausman/hll_rcon_tool
- klausman/isotopp.github.io
- klausman/pafw
- klausman/qtlola
- klausman/rains
- klausman/rains-prototype
- klausman/scion
- klausman/scion-web

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
