### ISSUE TITLE
Opt-out request for aperezdc

### ISSUE THREAD

**Issue by aperezdc** [bigcode-project/opt-out-v2#1861]
I request that the following data is removed from The Stack and StackOverflow, plus complete removal of any of my code, present or future, from all versions of your LLM, present, past, and future:

 - Commits
 - GitHub issue
 - aperezdc/apicheck
 - aperezdc/autocleanup
 - aperezdc/brotli
 - aperezdc/cflag
 - aperezdc/dbuf
 - aperezdc/dmon
 - aperezdc/druid
 - aperezdc/dwt
 - aperezdc/galaxy-desktop
 - aperezdc/hipack
 - aperezdc/hipack-rs
 - aperezdc/intheam-python
 - aperezdc/libwpe
 - aperezdc/libxkbcommon
 - aperezdc/ljndpi
 - aperezdc/ltree
 - aperezdc/netdial
 - aperezdc/ngx-fancyindex
 - aperezdc/notmuch-addrlookup-c
 - aperezdc/perezdecastro.org
 - aperezdc/riot-web
 - aperezdc/ulid-c
 - aperezdc/vim-clorex
 - aperezdc/websnap
 - aperezdc/zsh-fzy
 - aperezdc/zz-top
 - aperezdc/signify
 - aperezdc/WPEBackend
 - aperezdc/WPEBackend-shm
 - aperezdc/WPEWebKitLauncher
 - aperezdc/XS
 - aperezdc/abtool
 - aperezdc/alexandria
 - aperezdc/android-studio-flatpak
 - aperezdc/aoc2017-rs
 - aperezdc/aoc2018-scm
 - aperezdc/bill
 - aperezdc/chateau
 - aperezdc/clog
 - aperezdc/connectical-web
 - aperezdc/cuacfmeego
 - aperezdc/doin
 - aperezdc/dotfiles
 - aperezdc/dyz-shm
 - aperezdc/eris-report
 - aperezdc/fightcode-bots
 - aperezdc/gnarl
 - aperezdc/gotmuch
 - aperezdc/groover
 - aperezdc/guru-runit
 - aperezdc/hipack-c
 - aperezdc/hipack-js.git
 - aperezdc/hipack-python
 - aperezdc/hipack-vim
 - aperezdc/icecc-rs
 - aperezdc/indicium
 - aperezdc/indicium-git
 - aperezdc/indicium-ldap
 - aperezdc/js-highlighters-shootout
 - aperezdc/levi-asher-memoir
 - aperezdc/libicecc-sys
 - aperezdc/lua-delog
 - aperezdc/lua-dotty
 - aperezdc/lua-eol
 - aperezdc/lua-itertools
 - aperezdc/lua-storefront
 - aperezdc/lua-wcwidth
 - aperezdc/microwl
 - aperezdc/mwerlin
 - aperezdc/nfwx
 - aperezdc/nihil
 - aperezdc/objectscript
 - aperezdc/omni
 - aperezdc/pebbletime-python
 - aperezdc/pkgbuilds
 - aperezdc/playgroundino
 - aperezdc/popsicle
 - aperezdc/portlandia
 - aperezdc/pto
 - aperezdc/python-cmdcmd
 - aperezdc/python-wcfg
 - aperezdc/qubrowse
 - aperezdc/rockz
 - aperezdc/safecat
 - aperezdc/serde-hipack
 - aperezdc/snabb
 - aperezdc/spooldir
 - aperezdc/tacitum
 - aperezdc/trac-webhook-plugin
 - aperezdc/vfand
 - aperezdc/vim-elrond
 - aperezdc/vim-lift
 - aperezdc/vim-lining
 - aperezdc/vim-template
 - aperezdc/vscode-eos-build
 - aperezdc/webkitgtk.org
 - aperezdc/wheel
 - aperezdc/wl-connect-bench
 - aperezdc/wpe-ci-images
 - aperezdc/matrix-react-sdk
 - aperezdc/v8
 - aperezdc/afew
 - aperezdc/sccache
 - aperezdc/package-query
 - aperezdc/Stache
 - aperezdc/uritemplate-cpp
 - aperezdc/matrix-bot
 - aperezdc/WPEBackend-fdo
 - aperezdc/libepoxy
 - aperezdc/notmuch-addrlookup-c.git

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
