### ISSUE TITLE
Opt-out request for cyberglot

### ISSUE THREAD

**Issue by cyberglot** [bigcode-project/opt-out-v2#1862]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - cyberglot/effectfuljs
 - cyberglot/elm-pages
 - cyberglot/jsonresume-theme-sceptile
 - cyberglot/CFRP
 - cyberglot/SPLV20
 - cyberglot/SettableArrow
 - cyberglot/afp
 - cyberglot/agda-categories
 - cyberglot/awesome-haskell-sponsorship
 - cyberglot/clrs
 - cyberglot/concurrent-actions
 - cyberglot/cyberglot
 - cyberglot/effects
 - cyberglot/elm-markdown
 - cyberglot/golb
 - cyberglot/gradual-typing-and-friends
 - cyberglot/iamworking
 - cyberglot/learning-plt-redex
 - cyberglot/markit
 - cyberglot/mxm
 - cyberglot/nature-of-code
 - cyberglot/ninetails
 - cyberglot/node-vs-elixir
 - cyberglot/papercode
 - cyberglot/searcher
 - cyberglot/static-program-analysis
 - cyberglot/superbird
 - cyberglot/typed-lvar
 - cyberglot/cacache
 - cyberglot/elm-companies
 - cyberglot/atom-language-idris
 - cyberglot/andromeda
 - cyberglot/rumbl
 - cyberglot/koka
 - cyberglot/funflow
 - cyberglot/elm-syntax-highlight
 - cyberglot/canvas-sketch-cli

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
