### ISSUE TITLE
Opt-out request for n1kdo

### ISSUE THREAD

**Issue by jotterson** [bigcode-project/opt-out-v2#1863]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - n1kdo/WorldClock
 - n1kdo/lotw-gridmapper
 - n1kdo/lotw-qso-analyzer
 - n1kdo/n1mm_view
 - n1kdo/npota_data
 - n1kdo/rptr.asm
 - n1kdo/tictactoe

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
