### ISSUE TITLE
Opt-out request for 5GameMaker

### ISSUE THREAD

**Issue by 5GameMaker** [bigcode-project/opt-out-v2#1865]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - 5GameMaker/VaultAPI
 - 5GameMaker/Project_GAME2
 - 5GameMaker/SNAFP
 - 5GameMaker/The-Lisp-Project
 - 5GameMaker/gsearch
 - 5GameMaker/mfpkg
 - 5GameMaker/netbot
 - 5GameMaker/vio-packages
 - 5GameMaker/allcraft

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
