### ISSUE TITLE
Opt-out request for QuinnStevens

### ISSUE THREAD

**Issue by QuantumBJump** [bigcode-project/opt-out-v2#1867]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - QuinnStevens/Noelle
 - QuinnStevens/tian
 - QuinnStevens/Simple-Interpreter
 - QuinnStevens/adv-programming
 - QuinnStevens/aoc2020
 - QuinnStevens/databases-coursework
 - QuinnStevens/dsa-coursework
 - QuinnStevens/only-war
 - QuinnStevens/programming-coursework
 - QuinnStevens/sdlc-coursework
 - QuinnStevens/testing-coursework
 - QuinnStevens/unity2d
 - QuinnStevens/testing-with-java
 - QuinnStevens/djangogirls
 - QuinnStevens/ethics-coursework
 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
