### ISSUE TITLE
Opt-out request for leemm

### ISSUE THREAD

**Issue by leemm** [bigcode-project/opt-out-v2#188]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: leemmccormick@gmail.com
 - leemm/7z-extract
 - leemm/bugherd.api
 - leemm/comic-info
 - leemm/console.dog
 - leemm/dapulse
 - leemm/last.fm.api
 - leemm/secure-url-manager
 - leemm/simple-cli-parser
 - leemm/unofficial-amazon-cloud-player

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
