### ISSUE TITLE
Opt-out request for jbrains

### ISSUE THREAD

**Issue by jbrains** [bigcode-project/opt-out-v2#1880]
I request that the following data is removed from The Stack and StackOverflow:

 - all
 - Commits
 - GitHub issue
 - StackOverflow: jbrains
 - jbrains/elm-webpack-starter
 - jbrains/lazygit
 - jbrains/opencsv-contrib
 - jbrains/incrementally-convert-to-roman-in-javascript
 - jbrains/20171120-TDD-Bratislava
 - jbrains/20171123-TDD-Bratislava
 - jbrains/2018-Brasov-Fraction-Java
 - jbrains/20181113-Bratislava-TDD
 - jbrains/20181115-Bratislava-LegacyCode-Java
 - jbrains/20181210-Riga-SurvivingLegacyCode
 - jbrains/20191025-tdd-vilnius
 - jbrains/20191125-Bratislava-TDD
 - jbrains/20210527-Surviving-Legacy-Code
 - jbrains/20210916-TDD
 - jbrains/20211014-SurvivingLegacyCode
 - jbrains/ArrrrUG-TDD-20111129
 - jbrains/BeyondTheBasics-Kyiv-AgileEE2011
 - jbrains/BeyondTheBasics-Tallinn-September2011
 - jbrains/CrystalfontzLcdDisplayDriver
 - jbrains/EclipseSettings
 - jbrains/Enero-String-Calculator
 - jbrains/IntroToTdd-PHP-Tallinn-September2011
 - jbrains/IntroToTdd-Tallinn-September2011
 - jbrains/IntroToTdd-Vilnius-October2011
 - jbrains/LegacyCode-20171127-Bratislava
 - jbrains/LegacyCode-20171129-Bratislava
 - jbrains/Maquina-de-Dulces
 - jbrains/ModularDesign-Madrid-October2016
 - jbrains/ModularDesignWorkshop-Stockholm-October2016
 - jbrains/Papaletas-de-Pago
 - jbrains/PointOfSale-Javascript-Bordeaux-2011
 - jbrains/PointOfSale-Python
 - jbrains/PointOfSale-Stockholm-20131211
 - jbrains/PointOfSale-php-August2013
 - jbrains/SimpleApproachToModularDesign-YowBrisbane2010
 - jbrains/SimpleApproachToModularDesign-YowMelbourne2010
 - jbrains/Spotify-June2012
 - jbrains/SurvivingLegacyCode-Annecy-September2014
 - jbrains/SurvivingLegacyCode-Copenhagen-September2014
 - jbrains/SurvivingLegacyCode-Edinburgh-September2014
 - jbrains/SurvivingLegacyCode-Malmo-September2014
 - jbrains/TDD-20171127-Bratislava
 - jbrains/Tallinn-November-2013-AddingFractions
 - jbrains/Tallinn-November-2013-PointOfSale
 - jbrains/Tdd-Bratislava-December2015-2
 - jbrains/TddAndBeyond-Bordeaux-2011
 - jbrains/TddAndBeyond-Helsinki-2011
 - jbrains/TddAndBeyond-Munich-February2012
 - jbrains/TestDrivingQualitySoftware-Karlsruhe-November2015
 - jbrains/TrackEveryPenny
 - jbrains/WBITDD-20161114
 - jbrains/WBITDD-20161121
 - jbrains/WBITDD-Live-Brasov-November2015-AddingFractions
 - jbrains/WBITDD-Live-Brasov-November2015-PointOfSale
 - jbrains/WorldsBestIntroToTdd-Kaunas-September2014
 - jbrains/WorldsBestIntroToTdd-Tallinn-February2012
 - jbrains/WorldsBestIntroToTdd-Tallinn-January2012
 - jbrains/WorldsBestIntroToTdd-Tallinn-March2012
 - jbrains/agileee-2010-java-pointOfSale
 - jbrains/agileee-2010-jbrains-pointOfSale
 - jbrains/cluj-20101018
 - jbrains/countdown-timer-elm
 - jbrains/demonstrate-flex-float-problem
 - jbrains/exampilistic
 - jbrains/extreme-fishbowl
 - jbrains/goos
 - jbrains/jbhc17-PointOfSale-java
 - jbrains/jbrains.github.io
 - jbrains/junitconverter
 - jbrains/maruku
 - jbrains/mistakes_in_mongoid
 - jbrains/ncphi.com
 - jbrains/oauth2-server
 - jbrains/obtiva-tdd-201009
 - jbrains/pubmob
 - jbrains/rack-auto-map-subdomains
 - jbrains/reykjavik-201105-PointOfSale
 - jbrains/tdd-training
 - jbrains/the-definitive-guide-to-mock-objects-book
 - jbrains/toto
 - jbrains/vimfiles
 - jbrains/wbitdd-20131203
 - jbrains/xp2012
 - jbrains/yose
 - jbrains/astro
 - jbrains/howilostweight
 - jbrains/PointOfSaleWithGmock
 - jbrains/atom
 - jbrains/20210609-TDD
 - jbrains/SetUpRubyEnvironment
 - jbrains/kakoune
 - jbrains/20181119-Bratislava-TDD
 - jbrains/20210517-TDD
 - jbrains/Fraction
 - jbrains/20191203-Prague-TDD
 - jbrains/bundler-site
 - jbrains/acm-ankara-ModularDesignCourse-20101014
 - jbrains/SetUpJavaEnvironment
 - jbrains/homebrew-versions
 - jbrains/20181126-Prague-TDD
 - jbrains/2018-Kosice-PointOfSale-Java
 - jbrains/rspec-core
 - jbrains/WBITDD-20161203
 - jbrains/TddAndBeyond-Bratislava-2012
 - jbrains/rust

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
