### ISSUE TITLE
Opt-out request for neodc

### ISSUE THREAD

**Issue by neodc** [bigcode-project/opt-out-v2#1885]
I request that the following data is removed from The Stack:

 - Commits
 - GitHub issue
 - neodc/ereader-server
 - neodc/mpd_dyn
 - neodc/quest-manager
 - neodc/Invade
 - neodc/danish
 - neodc/flash
 - neodc/scarlet-data-scraper
 - all

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
