### ISSUE TITLE
Opt-out request for green-coder

### ISSUE THREAD

**Issue by green-coder** [bigcode-project/opt-out-v2#1888]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - green-coder/TIS-100-Spec
 - green-coder/cdc
 - green-coder/cdc-rs
 - green-coder/re-frame
 - green-coder/advent-of-code-2020
 - green-coder/atom-project-view
 - green-coder/bip-rs
 - green-coder/gradle-annotation-bug
 - green-coder/green-coder.github.io
 - green-coder/greenDAO
 - green-coder/rabin
 - green-coder/shadow-cljs-hang-test-case
 - green-coder/shadow-cljs-namespace-party
 - green-coder/transducer-exercises
 - green-coder/unity-network-transform-demo
 - green-coder/vrac-simple-sample
 - green-coder/zerohosts
 - green-coder/awesome-rust

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
