### ISSUE TITLE
Opt-out request for robotsnowfall

### ISSUE THREAD

**Issue by robotsnowfall** [bigcode-project/opt-out-v2#1892]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - robotsnowfall/cavernetics
 - robotsnowfall/dotfiles
 - robotsnowfall/economancy
 - robotsnowfall/galaxique
 - robotsnowfall/intellij-settings
 - robotsnowfall/pseudoglot
 - robotsnowfall/robotsnowfall.github.io
 - robotsnowfall/squants

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
