### ISSUE TITLE
Opt-out request for danielquinn

### ISSUE THREAD

**Issue by danielquinn** [bigcode-project/opt-out-v2#1893]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: daniel-quinn
 - danielquinn/Pitchfork-ML
 - danielquinn/django-citytemperature
 - danielquinn/django-donations
 - danielquinn/django-factory
 - danielquinn/django-rest
 - danielquinn/docs
 - danielquinn/perfectstranger
 - danielquinn/pmac.io
 - danielquinn/sano-fsd-test
 - danielquinn/thebestmotherfuckingwebsite
 - danielquinn/django-controlcenter
 - danielquinn/gethttpsforfree
 - danielquinn/mycroft-core-documentation
 - danielquinn/auth0-python
 - danielquinn/MinistersUnderTheInfluence
 - danielquinn/pytest-django
 - danielquinn/gentoo
 - danielquinn/currencycloud-python
 - danielquinn/django-reversion
 - danielquinn/pyoidc
 - danielquinn/django-user-sessions

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
