### ISSUE TITLE
Opt-out request for mkroehnert

### ISSUE THREAD

**Issue by mkroehnert** [bigcode-project/opt-out-v2#1894]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: mkroehenert
 - mkroehnert/amber
 - mkroehnert/awesome-seed-rs
 - mkroehnert/grunt-init-amber
 - mkroehnert/httpexplorer
 - mkroehnert/seed
 - mkroehnert/AndroidSensors
 - mkroehnert/IoParser
 - mkroehnert/OnlyKey-Chrome-App
 - mkroehnert/SaneKit
 - mkroehnert/amber-repo-config
 - mkroehnert/bevy-assets
 - mkroehnert/git-tutorial
 - mkroehnert/amber-examples
 - mkroehnert/howtonode.org
 - mkroehnert/mac-notification-sys
 - mkroehnert/homebrew
 - mkroehnert/dat-photos-app

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

Additionally, please confirm that no future repositories will automatically be included in the training of your statistical mean producing products.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
