### ISSUE TITLE
Opt-out request for LeoVgr

### ISSUE THREAD

**Issue by LeoVgr** [bigcode-project/opt-out-v2#1898]
I request that the following data is removed from The Stack and StackOverflow:
 - LeoVgr/GestionProjet
 - LeoVgr/MonSuperDepot
 - LeoVgr/SpaceInvaders
 - LeoVgr/TPM3105
 - LeoVgr/batailleNavale
 - LeoVgr/serveur
 - LeoVgr/sixvoix
 - LeoVgr/QCM

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
