### ISSUE TITLE
Opt-out request for eskibars

### ISSUE THREAD

**Issue by eskibars** [bigcode-project/opt-out-v2#19]
I request that the following data is removed from The Stack:

 - Commits
 - GitHub issue
 - eskibars/PITM
 - eskibars/SoftEther-Config
 - eskibars/aerogarden-tools
 - eskibars/docs.konghq.com
 - eskibars/domoticz-scripts
 - eskibars/elasticsearch-ingest-hashfields
 - eskibars/hatchbabyble
 - eskibars/lmsensorsbeat
 - eskibars/sdr-ais-to-elasticsearch
 - eskibars/tasker-elasticsearch
 - eskibars/virtualroadtrip
 - eskibars/whirlpool-sixth-sense
 - eskibars/wmibeat

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.0.1 of The Stack and all future versions. Also your data was not used for the training of StarCoder2.

[PROCESSED]
