### ISSUE TITLE
Opt-out request for rask

### ISSUE THREAD

**Issue by rask** [bigcode-project/opt-out-v2#190]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: ojrask
 - rask/WordPressBehatExtension
 - rask/dummy-php-package
 - rask/gulp-yaml-data
 - rask/openid-connect-php
 - rask/ottorask.com
 - rask/php-coding-standard
 - rask/php-libload
 - rask/php-template
 - rask/phpstan-2661
 - rask/posts
 - rask/rust
 - rask/rust-finland.org

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
