### ISSUE TITLE
Opt-out request for tillprochaska

### ISSUE THREAD

**Issue by tillprochaska** [bigcode-project/opt-out-v2#1900]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - tillprochaska/accessible-select
 - tillprochaska/bundestag-wm
 - tillprochaska/edtrio
 - tillprochaska/honeypot
 - tillprochaska/kirby-plugin-api-helpers
 - tillprochaska/postcss-import-global
 - tillprochaska/svelte-animated-list
 - tillprochaska/embed
 - tillprochaska/hms-workshop-chrome-to-adafruit
 - tillprochaska/hpi-vdom
 - tillprochaska/hyperapp-mapbox-experiment
 - tillprochaska/kas-workshop
 - tillprochaska/kas-workshop-api
 - tillprochaska/kirby-plugin-social-import
 - tillprochaska/lunch-news-voiceflow
 - tillprochaska/markdown-latex-workflow
 - tillprochaska/mep-nebeneinkuenfte
 - tillprochaska/tactilenews-m5stack
 - tillprochaska/til
 - tillprochaska/www-virtual-dom-homework
 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
