### ISSUE TITLE
Opt-out request for fredix

### ISSUE THREAD

**Issue by fredix** [bigcode-project/opt-out-v2#1905]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - fredix/cli_http_post
 - fredix/fredix.xyz
 - fredix/geekast-cli
 - fredix/go-wsqueue
 - fredix/nodemail
 - fredix/nodeseed
 - fredix/somafm-qt

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
