### ISSUE TITLE
Opt-out request for dgonyeo

### ISSUE THREAD

**Issue by cgonyeo** [bigcode-project/opt-out-v2#1906]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - dgonyeo/adventofcode
 - dgonyeo/bingehack-docker
 - dgonyeo/blog-hasql-example
 - dgonyeo/brandrethstats
 - dgonyeo/brandskell-convert
 - dgonyeo/gohbase-slides
 - dgonyeo/humans-and-their-environment
 - dgonyeo/hydrazine
 - dgonyeo/lambdollars
 - dgonyeo/latestplex
 - dgonyeo/libmastodon
 - dgonyeo/linuxcon-na-2016-slides
 - dgonyeo/lmrs
 - dgonyeo/notomys
 - dgonyeo/presentations
 - dgonyeo/rcs
 - dgonyeo/regex
 - dgonyeo/rkt-workshop
 - dgonyeo/smugglers
 - dgonyeo/weekly-scans
 - dgonyeo/CSHFoodPortal
 - dgonyeo/DerSkyGameJam
 - dgonyeo/FPSCubes
 - dgonyeo/LyricsDisplayer
 - dgonyeo/RasPiTLC5947
 - dgonyeo/Tiff-Sorter
 - dgonyeo/abd
 - dgonyeo/acpush-orig
 - dgonyeo/blog
 - dgonyeo/bootengine
 - dgonyeo/brandreth2.0
 - dgonyeo/ceti-eel
 - dgonyeo/cf-paperclub-monads
 - dgonyeo/coreos-metadata
 - dgonyeo/cshnews2
 - dgonyeo/discourser
 - dgonyeo/discourser.hs
 - dgonyeo/discourser.js
 - dgonyeo/dotfiles
 - dgonyeo/encrypter
 - dgonyeo/fsdiffer
 - dgonyeo/functional-data-structs
 - dgonyeo/gohbase
 - dgonyeo/gpgget
 - dgonyeo/hasklight
 - dgonyeo/ioprogress
 - dgonyeo/irc-locator
 - dgonyeo/legowebservices
 - dgonyeo/mantle
 - dgonyeo/nix2aci
 - dgonyeo/odd
 - dgonyeo/photohunt-app
 - dgonyeo/pingmon
 - dgonyeo/resume
 - dgonyeo/rkt-monitor
 - dgonyeo/tailor
 - dgonyeo/terminal-parrot
 - dgonyeo/ttyvid
 - dgonyeo/weather
 - dgonyeo/fuze
 - dgonyeo/rkt
 - dgonyeo/neveragaindottech.github.io
 - dgonyeo/nixpkgs
 - dgonyeo/tftpboot
 - dgonyeo/acpush
 - dgonyeo/torus
 - dgonyeo/xattr
 - dgonyeo/docs
 - dgonyeo/docker2aci
 - dgonyeo/acbuild
 - dgonyeo/locksmith
 - dgonyeo/valico
 - dgonyeo/container-linux-userdata-validator

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

For context: dgonyeo is my old GitHub handle.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
