### ISSUE TITLE
Opt-out request for wizzy25

### ISSUE THREAD

**Issue by wizzy25** [bigcode-project/opt-out-v2#1907]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - wizzy25/InterWeather
 - wizzy25/comments-server
 - wizzy25/raml-js-client-codegen
 - wizzy25/single-emit
 - wizzy25/xml2json
 - wizzy25/Code-Test
 - wizzy25/FreeCodeCamp_Tutorials
 - wizzy25/PicturePuzzle
 - wizzy25/dominoes-sim
 - wizzy25/es6-workshop
 - wizzy25/underscore-mixins
 - wizzy25/will-eden-faces
 - wizzy25/willchat
 - wizzy25/wizzy25-YoutubeVideoViewer
 - wizzy25/biscotto
 - wizzy25/serve-https
 - wizzy25/commercetools-customer-export
 - wizzy25/streamtest

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
