### ISSUE TITLE
Opt-out request for ghickman

### ISSUE THREAD

**Issue by ghickman** [bigcode-project/opt-out-v2#1909]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: ghickman
 - ghickman/1pass
 - ghickman/Hat-Team-Generator
 - ghickman/Trackr
 - ghickman/ages
 - ghickman/banking-tools
 - ghickman/cake_autotest
 - ghickman/classify
 - ghickman/currency-converter
 - ghickman/django-amber
 - ghickman/django-cbv-inspector
 - ghickman/django-config-url
 - ghickman/django-template
 - ghickman/django-vcard
 - ghickman/djangular-rest-framework
 - ghickman/dotfiles-1
 - ghickman/excuses
 - ghickman/factory_boy
 - ghickman/framewirc
 - ghickman/ghickman.co.uk
 - ghickman/git-api-test
 - ghickman/google-api-access
 - ghickman/healthcare-house-share
 - ghickman/heroku-prototype
 - ghickman/hoard-cli
 - ghickman/hoard-web
 - ghickman/incuna-auth
 - ghickman/isjameswearingashirttoday
 - ghickman/itertools.js
 - ghickman/jekyll
 - ghickman/jekyll_contact
 - ghickman/libpydoc
 - ghickman/mobile-tvcal
 - ghickman/natsort
 - ghickman/nvim-parinfer.js
 - ghickman/oauthlib
 - ghickman/office-growl
 - ghickman/peekaboo
 - ghickman/pelican-picasa
 - ghickman/penderry.com
 - ghickman/proxy-shortcut
 - ghickman/pyconuk.github.io
 - ghickman/python-regex
 - ghickman/python-simple-hipchat
 - ghickman/raspbmc-installer
 - ghickman/rrsync
 - ghickman/secrets
 - ghickman/sendwithus_python
 - ghickman/sentry-groveio
 - ghickman/simplenote.vim
 - ghickman/stalker
 - ghickman/symlinker
 - ghickman/tetris
 - ghickman/textbase
 - ghickman/tvrd
 - ghickman/tvrenamr
 - ghickman/update_plex
 - ghickman/vim-files
 - ghickman/vmprof-server
 - ghickman/wakeonlan
 - ghickman/weblog
 - ghickman/xbmc-remote
 - ghickman/zen-of-python

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
