### ISSUE TITLE
Opt-out request for khinsen

### ISSUE THREAD

**Issue by khinsen** [bigcode-project/opt-out-v2#1911]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - khinsen/HYDROLIB
 - khinsen/PythonBridgeGToolkit
 - khinsen/TYRC-apple
 - khinsen/WikiForGToolkit
 - khinsen/ipfs-pharo
 - khinsen/ipython
 - khinsen/leibniz-pharo
 - khinsen/mittag-leffler
 - khinsen/pystokes
 - khinsen/quick-edit
 - khinsen/ImmutablePy
 - khinsen/leibniz-examples
 - khinsen/pharo-wiki
 - khinsen/rescience-ten-year-challenge-paper-3
 - khinsen/2015-04-13-leidenuniv
 - khinsen/A-test-for-exploring-the-folder-structure
 - khinsen/CS-LaTeX
 - khinsen/EqualityThroughVariablesTrait
 - khinsen/FdV-Computer-Aided-Research-2016
 - khinsen/FdV-ScientificComputing-2015
 - khinsen/HoneyGinger
 - khinsen/NMA-benchmarks
 - khinsen/ReDynELA
 - khinsen/ReScience-submission-test
 - khinsen/SingletonTrait
 - khinsen/WebNmoldyn
 - khinsen/activepapers-python
 - khinsen/blog
 - khinsen/chk
 - khinsen/cise-software-specifications
 - khinsen/computation-in-science
 - khinsen/computational-documents-with-gtoolkit
 - khinsen/container_precis2017
 - khinsen/cours-python-ed-s2im
 - khinsen/h5py
 - khinsen/khinsen.github.io
 - khinsen/leibniz-lisp
 - khinsen/mad-scientist
 - khinsen/megaparsack
 - khinsen/monads-in-clojure
 - khinsen/monoprocessing
 - khinsen/mooc-rr-intro
 - khinsen/next
 - khinsen/ob-ipython-async
 - khinsen/reproducibility-with-guix
 - khinsen/rescience-ten-year-challenge-paper-4
 - khinsen/workflow-stories
 - khinsen/pharo-project-proposals
 - khinsen/ReScience-article-2
 - khinsen/ObservableSlots
 - khinsen/reproducible-research-and-giscience
 - khinsen/test
 - khinsen/software-vs-data
 - khinsen/oldnumeric
 - khinsen/Gifa
 - khinsen/mosaic-viewer
 - khinsen/hy
 - khinsen/RSC_paper
 - khinsen/formation_python2017
 - khinsen/force11-scwg
 - khinsen/ScientificComputingForTheRestOfUs
 - khinsen/rescience-ten-year-challenge-paper-3.git
 - khinsen/articles
 - khinsen/rescience-ten-year-challenge-paper-4.git
 - khinsen/monky

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
