### ISSUE TITLE
Opt-out request for riton

### ISSUE THREAD

**Issue by riton** [bigcode-project/opt-out-v2#1915]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - riton/nft-gallery
 - riton/puppet_function_rspec
 - riton/remctl-tutorial
 - riton/sigal
 - riton/vim-puppetnewfile
 - riton/free_adsl_bill_fetcher
 - riton/go-http-tar-dir
 - riton/go-thruk-rest-api-harvester
 - riton/nagios-plugin-git-hosted-project-merge-requests
 - riton/puppet-environment-cache-invalidate
 - riton/vim-ansible-goto-resource
 - riton/HTTPsFS
 - riton/TmsHelper
 - riton/android_http_json_listadapter
 - riton/ansible_POC_include_role_max_recursion_depth_issue_23609
 - riton/checksum-calc
 - riton/docker-remctld
 - riton/morningopenstack.org
 - riton/naemon_servicedependencies_irc
 - riton/nagiosplugin
 - riton/postfix-monitor
 - riton/puppet-modulator
 - riton/puppetrspec
 - riton/made-mistakes-jekyll
 - riton/write-ups-2015
 - riton/goexif2
 - riton/tsmmaster_in2p3_android
 - riton/gin-gomonitor

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
