### ISSUE TITLE
Opt-out request for HemersonTacon

### ISSUE THREAD

**Issue by HemersonTacon** [bigcode-project/opt-out-v2#1916]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: HemersonTacon
 - HemersonTacon/keras-tensorflow-windows-installation
 - HemersonTacon/DSA-Resources
 - HemersonTacon/MiniMaxCheckers
 - HemersonTacon/VuforiaExperiments
 - HemersonTacon/cnn_action_pyramid
 - HemersonTacon/hello-world
 - HemersonTacon/hemersontacon.github.io
 - HemersonTacon/ufjf-dcc014-N-Queens
 - HemersonTacon/unity-platformer
 - HemersonTacon/yin_yang
 - HemersonTacon/Python-Books

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
