### ISSUE TITLE
Opt-out request for robertoostenveld

### ISSUE THREAD

**Issue by robertoostenveld** [bigcode-project/opt-out-v2#1920]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - robertoostenveld/HED-schema
 - robertoostenveld/OpenBCI_Hub
 - robertoostenveld/hackathon2020
 - robertoostenveld/hpc-qaas
 - robertoostenveld/openneuro
 - robertoostenveld/tictactoe
 - robertoostenveld/bids-specification
 - robertoostenveld/analysisRO
 - robertoostenveld/arled
 - robertoostenveld/cautious-tribble
 - robertoostenveld/dccn.DSC_3015000.00_677_v1
 - robertoostenveld/dcmn.DSC_4180000.18_502_v1
 - robertoostenveld/dcn.DSC_62001717_01_101_v1
 - robertoostenveld/dcn.DSC_626810_0006_072_v1
 - robertoostenveld/donders-institute.github.io
 - robertoostenveld/donders-research-data-management.github.io
 - robertoostenveld/elekta-beamformer
 - robertoostenveld/gpstrack
 - robertoostenveld/nad-d3020
 - robertoostenveld/playground
 - robertoostenveld/pymindaffectBCI
 - robertoostenveld/raspi
 - robertoostenveld/rdm-configurable-content-imr
 - robertoostenveld/rdr-configurable-content
 - robertoostenveld/reproducescript
 - robertoostenveld/rubus
 - robertoostenveld/snirf
 - robertoostenveld/software_dist
 - robertoostenveld/teensy_gps_temp_ttn
 - robertoostenveld/OpenTools
 - robertoostenveld/TransparencyChecklist
 - robertoostenveld/ConfigManager
 - robertoostenveld/matlab_kernel
 - robertoostenveld/matbids
 - robertoostenveld/opendefinition
 - robertoostenveld/SparkFun_MPU-9250_Breakout_Arduino_Library
 - robertoostenveld/idrop
 - robertoostenveld/pxt

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
