### ISSUE TITLE
Opt-out request for mbikovitsky

### ISSUE THREAD

**Issue by mbikovitsky** [bigcode-project/opt-out-v2#1924]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: michael-bikovitsky
 - mbikovitsky/AdventuresInDebugging
 - mbikovitsky/AssemblyBot
 - mbikovitsky/MassStorageDotNet
 - mbikovitsky/RenegadeImageToolkit
 - mbikovitsky/UTR-Seq
 - mbikovitsky/botcat
 - mbikovitsky/dev-metronome
 - mbikovitsky/littlefs-utils
 - mbikovitsky/native-rust
 - mbikovitsky/numbers-station
 - mbikovitsky/panopto-dl
 - mbikovitsky/structsize
 - mbikovitsky/tell-me-where-to-go
 - mbikovitsky/trustme
 - mbikovitsky/winbear
 - mbikovitsky/yesexcept
 - mbikovitsky/Carpenter
 - mbikovitsky/MagicBus
 - mbikovitsky/WinDbg
 - mbikovitsky/bikerm16.github.com
 - mbikovitsky/bikodbg
 - mbikovitsky/hackinparis-2016
 - mbikovitsky/incbin
 - mbikovitsky/jekyll-generic-archive
 - mbikovitsky/jekyll-notesil
 - mbikovitsky/mbikovitsky.github.io
 - mbikovitsky/shabak-challenge-2021
 - mbikovitsky/website
 - mbikovitsky/DFGameClubPlayer
 - mbikovitsky/styleguide
 - mbikovitsky/sdmmc-analyzer
 - mbikovitsky/compiler-explorer-image
 - mbikovitsky/flask

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
