### ISSUE TITLE
Opt-out request for swozniak

### ISSUE THREAD

**Issue by swozniak** [bigcode-project/opt-out-v2#1929]
I request that the following data is removed from The Stack and StackOverflow:
 - ALL DATA ASSOCIATED WITH MY ACCOUNT
 - swozniak/googlifier
 - swozniak/react-simple-share
 - swozniak/fest13-teaser
 - swozniak/ngt
 - swozniak/fest13

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
