### ISSUE TITLE
Opt-out request for kpinakula

### ISSUE THREAD

**Issue by kpinakula** [bigcode-project/opt-out-v2#193]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - kpinakula/FizzBuzzA
 - kpinakula/FizzBuzzArray
 - kpinakula/luisa
 - kpinakula/luisa-prototype
 - kpinakula/walk-talk
- all

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
