### ISSUE TITLE
Opt-out request for slwu89

### ISSUE THREAD

**Issue by slwu89** [bigcode-project/opt-out-v2#1932]
I request that the following data is removed from The Stack and StackOverflow:

 - all
 - Commits
 - GitHub issue
 - slwu89/benchmark
 - slwu89/fitexamples
 - slwu89/individual.network
 - slwu89/ranges
 - slwu89/sarscov2_unobserved_example
 - slwu89/Academics
 - slwu89/ActivitySpace_JRSI2014
 - slwu89/CTDE.jl
 - slwu89/ComputationalGeometry
 - slwu89/EBSpatCGAL
 - slwu89/EvoResistance
 - slwu89/GA
 - slwu89/InfectionSim
 - slwu89/MASH
 - slwu89/MASH-Main
 - slwu89/MCMC
 - slwu89/ML
 - slwu89/MicSim
 - slwu89/ModellingWithData
 - slwu89/NetworkEpidemics
 - slwu89/PH252E
 - slwu89/RACD
 - slwu89/RC
 - slwu89/R_repo
 - slwu89/RcppOMP
 - slwu89/RcppQueues
 - slwu89/Romp
 - slwu89/SMC_ParticleFilter
 - slwu89/SelfStudy
 - slwu89/Semi-Markov
 - slwu89/TemporalGillespie
 - slwu89/amosa
 - slwu89/cgalTest
 - slwu89/compbio293
 - slwu89/density-estimation
 - slwu89/dequer
 - slwu89/desr
 - slwu89/envestigate
 - slwu89/fwritetest
 - slwu89/greta.dynamics
 - slwu89/hiv_modelling
 - slwu89/hop-skip-bite
 - slwu89/mcfun
 - slwu89/mosquito_estimation
 - slwu89/nCoV
 - slwu89/popsim
 - slwu89/prev-est
 - slwu89/rcpp_ccb_seminar
 - slwu89/remarkPresentations
 - slwu89/s-vcom
 - slwu89/shareCpp
 - slwu89/slwu89.github.io
 - slwu89/slwu89package
 - slwu89/spatialFOI
 - slwu89/stat_phylogenetics
 - slwu89/testPkg
 - slwu89/vcom_optim
 - slwu89/voronoi
 - slwu89/voronoi_cgal
 - slwu89/scam
 - slwu89/randomgraph.js
 - slwu89/natureincode
 - slwu89/PiecewiseDeterministicMarkovProcesses.jl
 - slwu89/fitR
 - slwu89/TemporalGillespieAlgorithm
 - slwu89/RiDMC
 - slwu89/RcppMLPACK1
 - slwu89/smfsb

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
