### ISSUE TITLE
Opt-out request for dheavy

### ISSUE THREAD

**Issue by dheavy** [bigcode-project/opt-out-v2#1933]
I request that the following data is removed from The Stack:

 - Commits
 - GitHub issue
 - dheavy/RxJS-training
 - dheavy/adee3d
 - dheavy/clojure
 - dheavy/delegatecall
 - dheavy/quickr
 - dheavy/shader-school
 - dheavy/simple-java-calc-engine
 - dheavy/slack-night-mode
 - dheavy/solidity-training
 - dheavy/struqt
 - dheavy/unity-basic-fps-character
 - dheavy/unity-desert-robot
 - dheavy/GIVE.js
 - dheavy/attic
 - dheavy/autogram
 - dheavy/boutonniere
 - dheavy/cadence-starter
 - dheavy/cakefile
 - dheavy/case
 - dheavy/clementdauvent-layout-manager
 - dheavy/clementdauvent-public-swf
 - dheavy/coffeescript-work-env
 - dheavy/colorpicker
 - dheavy/cuicui
 - dheavy/dheavy.github.io
 - dheavy/dolman
 - dheavy/dpb-mean-empty
 - dheavy/factory-muff
 - dheavy/functional-javascript-workshop
 - dheavy/gis-django
 - dheavy/jpo2014
 - dheavy/kanban-app
 - dheavy/kitty-items
 - dheavy/laravel-react
 - dheavy/learning-near
 - dheavy/leromanderin
 - dheavy/mann
 - dheavy/mdfd-server
 - dheavy/mdfd-test-nodejs
 - dheavy/metamask-login
 - dheavy/ng2-testing
 - dheavy/nuxt-wp
 - dheavy/onceawake
 - dheavy/outrenuit-client
 - dheavy/outrenuit-server
 - dheavy/pari-grandir
 - dheavy/playing-with-flask
 - dheavy/rails3-bootstrap-devise-cancan
 - dheavy/rails3-devise-rspec-cucumber
 - dheavy/react-training
 - dheavy/redux-todo
 - dheavy/sample-crowdsale-dapp
 - dheavy/scheme
 - dheavy/scraper-cli
 - dheavy/shlisp
 - dheavy/sinatra-git-based-blog
 - dheavy/solidity-101
 - dheavy/solidity-poe
 - dheavy/springer-downloader
 - dheavy/sublime-text
 - dheavy/tddjs
 - dheavy/three-training
 - dheavy/threejs-training
 - dheavy/titanium-todolist-coffee
 - dheavy/unity-clock
 - dheavy/unity-fractal
 - dheavy/unity-maze
 - dheavy/unity-nucleus
 - dheavy/unity-object-pools
 - dheavy/voting-client
 - dheavy/voting-server
 - dheavy/vr-ar
 - dheavy/java-studies
 - dheavy/python-algorithms
 - dheavy/ionic-gallery-modal
 - dheavy/angular-tour-of-heroes
 - dheavy/confide
 - dheavy/otree-core
 - dheavy/microscope
 - dheavy/mnemonist
 - dheavy/DefinitelyTyped

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
