### ISSUE TITLE
Opt-out request for bpauld

### ISSUE THREAD

**Issue by bpauld** [bigcode-project/opt-out-v2#1936]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - bpauld/bpauld.github.io
 - bpauld/COMP302Language
 - bpauld/MVA_kernel_method_challenge
 - bpauld/comp550project
 - bpauld/fermat-weber
 - bpauld/summer2017research
 - bpauld/helloworld

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
