### ISSUE TITLE
Opt-out request for steely-glint

### ISSUE THREAD

**Issue by steely-glint** [bigcode-project/opt-out-v2#194]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - steely-glint/410_Gone
 - steely-glint/LegoDroid
 - steely-glint/PhonoChromeExten
 - steely-glint/PhonoSDK
 - steely-glint/PiPod
 - steely-glint/PipeApiDocs
 - steely-glint/PipeRemoteFX
 - steely-glint/TADHackMadrid
 - steely-glint/WebRTCDeviceWrangle
 - steely-glint/ascf-groovy-demo
 - steely-glint/baddtls
 - steely-glint/bm2012
 - steely-glint/bounce
 - steely-glint/certstream-java
 - steely-glint/distributedfutu.re-rss
 - steely-glint/fingersmith
 - steely-glint/iPhono
 - steely-glint/iost-brush
 - steely-glint/ipsecord
 - steely-glint/ipsehomespark
 - steely-glint/jiraphone
 - steely-glint/objiax
 - steely-glint/oldglory
 - steely-glint/pfhiaxdroid
 - steely-glint/phonoLabsConf
 - steely-glint/respoke
 - steely-glint/respoke-sdk-java-small
 - steely-glint/singathon
 - steely-glint/slice
 - steely-glint/solarbeagle
 - steely-glint/srtplight
 - steely-glint/staff
 - steely-glint/starlight
 - steely-glint/starway
 - steely-glint/stt
 - steely-glint/webbluetooth-edison-demo
 - steely-glint/webrtc-charter
 - steely-glint/webrtc-ips

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
