### ISSUE TITLE
Opt-out request for nazipov

### ISSUE THREAD

**Issue by nazipov** [bigcode-project/opt-out-v2#1940]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - nazipov/IDMPhotoBrowser
 - nazipov/ex_banking
 - nazipov/ch
 - nazipov/debug_sequel_polymorphic
 - nazipov/ds-24
 - nazipov/place_puppy
 - nazipov/sequel_polymorphic
 - nazipov/students_crm
 - nazipov/telemetry_metrics_cloudwatch
 - nazipov/ua_parser2-elixir
 - nazipov/tilt-jbuilder
 - nazipov/awesome-elixir

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
