### ISSUE TITLE
Opt-out request for Jaeoc

### ISSUE THREAD

**Issue by Jaeoc** [bigcode-project/opt-out-v2#1950]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - Jaeoc/CV-template-rmarkdown
 - Jaeoc/Code-review
 - Jaeoc/Screening-for-Statistical-Inconsistencies-in-COVID-19-Preprints
 - Jaeoc/heterogeneity-replications
 - Jaeoc/ml4
 - Jaeoc/more-binder

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
