### ISSUE TITLE
Opt-out request for Cratesmith

### ISSUE THREAD

**Issue by Cratesmith** [bigcode-project/opt-out-v2#1951]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - Cratesmith/Cratesmith.Actors
 - Cratesmith/Cratesmith.Actors.Effects
 - Cratesmith/Cratesmith.Actors.Pool
 - Cratesmith/Cratesmith.AssetIcons
 - Cratesmith/Cratesmith.Collections
 - Cratesmith/Cratesmith.Dispatcher
 - Cratesmith/Cratesmith.EditorUnplugged
 - Cratesmith/Cratesmith.InspectorTypes
 - Cratesmith/Cratesmith.OnOff
 - Cratesmith/Cratesmith.ScriptExecutionOrder
 - Cratesmith/Cratesmith.Timeslicer
 - Cratesmith/Cratesmith.Utils
 - Cratesmith/Cratesmith.Zinq
 - Cratesmith/CratesmithUnityLibrary
 - Cratesmith/GcapTalk2016
 - Cratesmith/GitDependencyResolverForUnity
 - Cratesmith/Jam06_04_18
 - Cratesmith/Learning-Unreal
 - Cratesmith/NewtonVR
 - Cratesmith/unity-build-system
 - **ANY FUTURE REPOS, WORKS OR ACTIVITY OF ANY KIND**

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
