### ISSUE TITLE
Opt-out request for dnno

### ISSUE THREAD

**Issue by dnno** [bigcode-project/opt-out-v2#1953]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - dnno/junit5
 - dnno/otter
 - dnno/codecentric-blog-junit5-parameterized-tests
 - dnno/demo-spring-boot-kotlin
 - dnno/jackson-serialization-problem
 - dnno/java11-lombok-plugin
 - dnno/jpa-docker-postgres
 - dnno/junit-examples
 - dnno/junit5-json-param-source
 - dnno/junit5-kotlin
 - dnno/junit5-presentation
 - dnno/junit5-springboot
 - dnno/springboot-junit4-migration
 - dnno/testcontainers-infinispan
 - dnno/testcontainers-postgres-demo
 - dnno/website
 - dnno/cookbook-php-fpm
 - dnno/learn-github-actions
 - dnno/azure-hello-world-function

And TBH, opt-out is a disgrace!

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
