### ISSUE TITLE
Opt-out request for bit-man

### ISSUE THREAD

**Issue by bit-man** [bigcode-project/opt-out-v2#1954]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: bit-man
 - bit-man/go-Salesforce-backup
 - bit-man/pushfish-android
 - bit-man/MyRedisChat
 - bit-man/SiteBrokenLinks
 - bit-man/YASQT
 - bit-man/algocity-fiuba-all-hail-the-king
 - bit-man/asciidoctor-intellij-plugin
 - bit-man/bamboo-status
 - bit-man/bit-tools
 - bit-man/cafeperl6
 - bit-man/dualcore
 - bit-man/email-change-notice
 - bit-man/fantasticfour
 - bit-man/fictional-vieira
 - bit-man/gereco
 - bit-man/input-generator-a2
 - bit-man/kanban-app-extras
 - bit-man/maraton
 - bit-man/p5-pod-stripper
 - bit-man/sqlf
 - bit-man/tridiagonal
 - bit-man/Twitter-Daily
 - bit-man/MiCar
 - bit-man/java-getting-started

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
