### ISSUE TITLE
Opt-out request for mzdravkov

### ISSUE THREAD

**Issue by mzdravkov** [bigcode-project/opt-out-v2#1962]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - mzdravkov/automata
 - mzdravkov/candies
 - mzdravkov/chunked-vector
 - mzdravkov/comori
 - mzdravkov/dotfiles
 - mzdravkov/elsys-ci-flask-demo
 - mzdravkov/elsys-ci-flask-example
 - mzdravkov/eridu
 - mzdravkov/glimmer
 - mzdravkov/kamino
 - mzdravkov/leak-of-legends
 - mzdravkov/lispetit
 - mzdravkov/nix-mzdravkov
 - mzdravkov/python-course
 - mzdravkov/python-lectures
 - mzdravkov/river_networks
 - mzdravkov/tedronai
 - mzdravkov/name-generator
 - mzdravkov/C-turtle
 - mzdravkov/ao-calendar
 - mzdravkov/arduino-switch
 - mzdravkov/beyond
 - mzdravkov/elsys-ci-demo
 - mzdravkov/evans
 - mzdravkov/file_sort
 - mzdravkov/hex
 - mzdravkov/keychord
 - mzdravkov/myrmidon
 - mzdravkov/passage
 - mzdravkov/robocup
 - mzdravkov/sinatra-plugins
 - mzdravkov/tharsis-core
 - mzdravkov/tharsis-full
 - mzdravkov/thesis
 - mzdravkov/videira
 - mzdravkov/engo
 - mzdravkov/go-homework
 - all

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
