### ISSUE TITLE
Opt-out request for benschwarz

### ISSUE THREAD

**Issue by benschwarz** [bigcode-project/opt-out-v2#1964]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - benschwarz/amnesia
 - benschwarz/choones
 - benschwarz/flickraw
 - benschwarz/merb-cache
 - benschwarz/metaquery
 - benschwarz/omniauth
 - benschwarz/openuri_recorder
 - benschwarz/rack-smoke
 - benschwarz/smoke
 - benschwarz/sprinkle
 - benschwarz/third-party-web
 - benschwarz/transcoder
 - benschwarz/HTML5.tmbundle
 - benschwarz/Hillegass-Macruby
 - benschwarz/ae
 - benschwarz/am-arrange
 - benschwarz/another_enum
 - benschwarz/attr-chain
 - benschwarz/benschwarz-site-v2
 - benschwarz/bom-weather
 - benschwarz/bonsai-site
 - benschwarz/bower-badges
 - benschwarz/cache.js.git
 - benschwarz/chrome-request-interception
 - benschwarz/developers.whatwg.org
 - benschwarz/devise
 - benschwarz/dotjs
 - benschwarz/faraday-stack
 - benschwarz/faraday_middleware
 - benschwarz/flickr-wrapper
 - benschwarz/fluent-plugin-influxdb
 - benschwarz/font-display-demo
 - benschwarz/gifcity
 - benschwarz/gitjour
 - benschwarz/gitnotify
 - benschwarz/grape
 - benschwarz/grid
 - benschwarz/homebrew-sassc
 - benschwarz/html5-workshop-site
 - benschwarz/kss
 - benschwarz/leonardo
 - benschwarz/mdc-api
 - benschwarz/movember-site
 - benschwarz/munch
 - benschwarz/ng-AustralianBusinessNumber
 - benschwarz/ngFx
 - benschwarz/perf.email
 - benschwarz/rack-client
 - benschwarz/railscamp_attendees
 - benschwarz/registry
 - benschwarz/site
 - benschwarz/skeet
 - benschwarz/smoke-manual
 - benschwarz/throne
 - benschwarz/tweet-tidy
 - benschwarz/webjam10
 - benschwarz/webtask-all-you-need-is-code
 - benschwarz/whoisjohnbarton.com
 - benschwarz/responsive-nav.js
 - benschwarz/package_control_channel
 - benschwarz/railscamps.com
 - benschwarz/bower.json-spec
 - benschwarz/lighthouse
 - benschwarz/css-modal
 - benschwarz/dotfiles
 - benschwarz/shopify_theme
 - benschwarz/mdx-docs
 - benschwarz/perf-tooling
 - benschwarz/bower
 - benschwarz/docker-selenium
 - benschwarz/JQuery-Extended-Selectors
 - benschwarz/sassc
 - benschwarz/Effeckt.css
 - benschwarz/campjs-v
 - benschwarz/stencil-site
 - benschwarz/force
 - benschwarz/sinatra.github.com
 - benschwarz/dnt-polyfill
 - benschwarz/dotfiles-1
 - benschwarz/lstoll.exposed
 - benschwarz/web.dev

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
