### ISSUE TITLE
Opt-out request for fershad

### ISSUE THREAD

**Issue by fershad** [bigcode-project/opt-out-v2#1969]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - fershad/template
 - fershad/11ty-csv-demo
 - fershad/crawler
 - fershad/ctta-tissa
 - fershad/energy-project
 - fershad/lazy-load-youtube-demo
 - fershad/my-eleventy-starter
 - fershad/taiwan-energy-cli
 - fershad/website-carbon-audit-landingpage
 - fershad/ECPayAIO_Node.js
 - fershad/eleventy-sanity-blog-boilerplate

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
