### ISSUE TITLE
Opt-out request for saneef

### ISSUE THREAD

**Issue by saneef** [bigcode-project/opt-out-v2#1970]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: saneef
 - saneef/FocusTheOutputPanel
 - saneef/SaveWorkspacesOnQuit
 - saneef/Solarized
 - saneef/affiliates-chrome-extension
 - saneef/app-exists
 - saneef/awesome-launchbar
 - saneef/dsgnrs.in
 - saneef/eleventy-netlify-boilerplate
 - saneef/eleventy-plugin-images-responsiver
 - saneef/eleventy_vite_starter
 - saneef/max31855
 - saneef/metalsmith-hyphenate
 - saneef/mu-gen
 - saneef/numeric-keypads
 - saneef/prezto-module-jump-to
 - saneef/prezto-module-web-developer
 - saneef/pug-postcss-webpack-starter
 - saneef/sublime-snippets-nunjucks
 - saneef/11ty-asciidoc-prototype
 - saneef/Sublime-svgo
 - saneef/accoutrement-color
 - saneef/activesphere.github.io
 - saneef/automator-apps
 - saneef/bookmarklets
 - saneef/debug-turbolinks-picture
 - saneef/debug-xo-import-no-extraneous-dependencies
 - saneef/eleventy-plugin-open-in-codepen
 - saneef/github-contributions-leaderboard
 - saneef/illustrator-svg-utils
 - saneef/keep-up-heat
 - saneef/laying-things-out-in-react
 - saneef/library-scripts
 - saneef/metalsmith-feed
 - saneef/metalsmith-layouts-test
 - saneef/phoenix-config
 - saneef/prezto
 - saneef/qgen-sample-file-append
 - saneef/reproduce-couldnt-find-template-for-digesting
 - saneef/search-suggestions-using-statecharts
 - saneef/storybook-addon-theme
 - saneef/stylable-vue-example
 - saneef/theming-imported-styled-component-debug
 - saneef/traffic-lights-using-xstate
 - saneef/type-tester-venice
 - saneef/video-annotations
 - saneef/webpack-4-starter
 - saneef/gulpsmith
 - saneef/sublime-maybs-quit
 - saneef/asciidoctor-cli.js
 - saneef/gulp-wordpress-boilerplate
 - saneef/awesome-scss

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
