### ISSUE TITLE
Opt-out request for darekkay

### ISSUE THREAD

**Issue by darekkay** [bigcode-project/opt-out-v2#1971]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - darekkay/a11yproject.com
 - darekkay/app-and-play
 - darekkay/awesome-a11y
 - darekkay/best-practices
 - darekkay/board-games
 - darekkay/darekkay-styles
 - darekkay/dashboard
 - darekkay/dev-tools
 - darekkay/dom-testing-library
 - darekkay/gc-mystery-tools
 - darekkay/gitgraph.js
 - darekkay/hexo-generator-feed
 - darekkay/kanbanist
 - darekkay/labyrinthz
 - darekkay/react-grid-layout
 - darekkay/react-super-select
 - darekkay/serpentchess
 - darekkay/static-marks-app
 - darekkay/tiny-helpers
 - darekkay/tip-of-the-day
 - darekkay/todoist-export
 - darekkay/what-the-commit
 - darekkay/amazon-parser
 - darekkay/config-files
 - darekkay/flexbox-cheatsheet
 - darekkay/git-some
 - darekkay/jest-coverage
 - darekkay/personalsit.es
 - darekkay/piles
 - darekkay/presentations
 - darekkay/static-marks
 - darekkay/userscripts
 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
