### ISSUE TITLE
Opt-out request for notabene

### ISSUE THREAD

**Issue by notabene** [bigcode-project/opt-out-v2#1973]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - notabene/wcag-process-matrix
 - notabene/ChallengeDuBerger
 - notabene/Data-Independence-Guidelines
 - notabene/Pairing-is-caring
 - notabene/atelier-svg
 - notabene/boris.schapira.dev
 - notabene/cafe.des-blogueurs.org_skin
 - notabene/fiches-gobelins
 - notabene/i18n-drafts
 - notabene/wai-bcase
 - notabene/wai-presentations2all
 - notabene/wcag-as-json
 - notabene/troisdoublev
 - notabene/wai-components
 - notabene/wai-statements
 - notabene/spoiled-people.github.io
 - notabene/wai-tutorials
 - notabene/wai-media-intro
 - notabene/notebook
 - notabene/karl-resume
 - notabene/wai-intro-wcag
 - notabene/wai-accessibility-principles
 - notabene/wai-website-data
 - notabene/wai-people-use-web
 - notabene/standards-track
 - notabene/ca.jquery.sticky
 - notabene/accessibility-intro
 - notabene/grunt-svg-sprite
 - notabene/wai-about-wai
 - notabene/wai-design-develop-overview

**Comment by notabene** [comment]
Up.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
