### ISSUE TITLE
Opt-out request for mrtazz

### ISSUE THREAD

**Issue by mrtazz** [bigcode-project/opt-out-v2#1976]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - mrtazz/AlertDesigner
 - mrtazz/BackoffTimer
 - mrtazz/admiral
 - mrtazz/checkmake
 - mrtazz/chef-deploy
 - mrtazz/chef-groveio-handler
 - mrtazz/disrupt
 - mrtazz/github-unreleased
 - mrtazz/go-statsd-proxy
 - mrtazz/homebrew-core
 - mrtazz/homebrew-oss
 - mrtazz/instapaper.py
 - mrtazz/instareader.py
 - mrtazz/irc-notifier
 - mrtazz/jekyll-layouts
 - mrtazz/knife-wip
 - mrtazz/kong-ini
 - mrtazz/leoric
 - mrtazz/minibashtest
 - mrtazz/notifo.py
 - mrtazz/osxzip-cookbook
 - mrtazz/pkgr
 - mrtazz/pocketcleaner
 - mrtazz/ramrod
 - mrtazz/simplenote.vim
 - mrtazz/statsd-traffic-loader
 - mrtazz/thingnatra
 - mrtazz/twanity
 - mrtazz/twsh
 - mrtazz/unwiredcouch.com
 - mrtazz/vim-plan
 - mrtazz/vim-stencil
 - mrtazz/vimfiles
 - mrtazz/zerigo_dyndns.sh
 - mrtazz/zshfiles
 - mrtazz/DoxygenToolkit.vim
 - mrtazz/GithubFeedFilter
 - mrtazz/bin
 - mrtazz/catbot
 - mrtazz/chinstrap
 - mrtazz/cocoa-currency-converter
 - mrtazz/coppergenie
 - mrtazz/couchapp-cucumber
 - mrtazz/dotfiles
 - mrtazz/emo.theme
 - mrtazz/fitbit-to-graphite
 - mrtazz/foodlist
 - mrtazz/gifs
 - mrtazz/gistapi.erl
 - mrtazz/groupmecat
 - mrtazz/guillotine
 - mrtazz/homebrew-misc
 - mrtazz/irssi-zeromq
 - mrtazz/jarvis
 - mrtazz/json-cpp
 - mrtazz/kangaroo
 - mrtazz/ketchupstatus
 - mrtazz/knife-node-attribute
 - mrtazz/leoric-skeletons
 - mrtazz/mime-extractor
 - mrtazz/network-tools
 - mrtazz/notify-by-opsgenie
 - mrtazz/notify-by-pushover
 - mrtazz/octonode
 - mrtazz/oh-my-zsh
 - mrtazz/php-dyndns
 - mrtazz/php-nagioseasier
 - mrtazz/povray-playground
 - mrtazz/reckon
 - mrtazz/requests
 - mrtazz/rubyosa
 - mrtazz/shouldigraphit.com
 - mrtazz/snyder
 - mrtazz/statsd
 - mrtazz/stz-hubot
 - mrtazz/thunkapi.py
 - mrtazz/towbar
 - mrtazz/troubagix
 - mrtazz/checks
 - mrtazz/znc-logstash-notifications
 - mrtazz/thoughtstradamus
 - mrtazz/knife-spork
 - mrtazz/gopen
 - mrtazz/ohai-plugins
 - mrtazz/smeagol
 - mrtazz/developer.github.com
 - mrtazz/beautiful-docs
 - mrtazz/hubot-irc
 - mrtazz/vagrant-monigusto
 - mrtazz/vim-zenroom2
 - mrtazz/graphite-golang
 - mrtazz/wee-slack
 - mrtazz/muttfiles

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
