### ISSUE TITLE
Opt-out request for baarkerlounger

### ISSUE THREAD

**Issue by baarkerlounger** [bigcode-project/opt-out-v2#198]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - baarkerlounger/Air-Quality
 - baarkerlounger/LosslessChecker
 - baarkerlounger/SAP-Compare-Object-Versions
 - baarkerlounger/baarkerlounger.github.io
 - baarkerlounger/benmaps.fr
 - baarkerlounger/chasing-pandas
 - baarkerlounger/engineer-ai-test
 - baarkerlounger/fb-editor
 - baarkerlounger/mhclg-data-collection-alpha
 - baarkerlounger/mhclg-data-collection-beta-infrastructure
 - baarkerlounger/resque-timeout
 - baarkerlounger/yabeda-prometheus

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
