### ISSUE TITLE
Opt-out request for pallix

### ISSUE THREAD

**Issue by pallix** [bigcode-project/opt-out-v2#1983]
It should be opt-in, not opt-out, you have no ethics.

I request that the following data is removed from The Stack and StackOverflow:

- All
 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - pallix/nixpkgs
 - pallix/opentelemetry-erlang
 - pallix/syslog
 - pallix/bug-ansible-apt-repository
 - pallix/bug_elixir_tortoise_schedulers
 - pallix/bug_prom_ex_two_folders
 - pallix/erlang_dns_under_stress
 - pallix/exprotobuf
 - pallix/exprotobuf_not_serializing
 - pallix/lunchbot
 - pallix/nerves_uart_bug
 - pallix/paas-analytics-api
 - pallix/paas-pseudonymity
 - pallix/purescript-simple-request
 - pallix/veth_network_namespaces_perf
 - pallix/telemetry_metrics_prometheus_core
 - pallix/ZODB-Documentation
 - pallix/sniff
 - pallix/policycompass
 - pallix/org-reveal
 - pallix/nerves_uart
 - pallix/purescript-argonaut-generic-codecs

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
