### ISSUE TITLE
Opt-out request for nosmo 

### ISSUE THREAD

**Issue by nosmo** [bigcode-project/opt-out-v2#1984]
I request that the following data is removed from The Stack:

 - all 
 - nosmo/change-propagation 
 - nosmo/cpp-driver  
 - nosmo/Approxihash  
 - nosmo/Linkdump  
 - nosmo/MSSF-tools  
 - nosmo/Twithey  
 - nosmo/Youtbh  
 - nosmo/dotfiles  
 - nosmo/fess_up  
 - nosmo/healthword  
 - nosmo/irc-log-sync  
 - nosmo/justDespair  
 - nosmo/nosmo.github.com  
 - nosmo/paasta  
 - nosmo/porick-flask  
 - nosmo/python-xmlrpcssl  
 - nosmo/swabber  
 - nosmo/tcpwhosts  
 - nosmo/toThingist  
 - nosmo/tooly  
 - nosmo/puppetlabs-rsync  
 - nosmo/pysensu  
 - nosmo/ooni-probe
 - 
_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.
...

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
