### ISSUE TITLE
Opt-out request for yob

### ISSUE THREAD

**Issue by yob** [bigcode-project/opt-out-v2#1985]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - yob/abn
 - yob/activemdb
 - yob/afm
 - yob/amber_electric
 - yob/barby
 - yob/buildkite-trace
 - yob/classifier
 - yob/css_counter
 - yob/cuecat
 - yob/debian-rubinius
 - yob/deflate
 - yob/dumb_quotes
 - yob/ean13.net
 - yob/ean8
 - yob/editx
 - yob/em-ftpd
 - yob/go-amber
 - yob/go-redisproto
 - yob/isbn10
 - yob/isni
 - yob/istc
 - yob/lean-trello
 - yob/mqttshim
 - yob/nestive
 - yob/pdf-reader
 - yob/puma-plugin-statsd
 - yob/puma-plugin-systemd
 - yob/raval
 - yob/replace_entities
 - yob/riddle
 - yob/roxml
 - yob/san
 - yob/stackdriver_simple
 - yob/subjct
 - yob/thinking-sphinx
 - yob/ts-delayed-delta
 - yob/wait-for-socket
 - yob/win-process-tree
 - yob/advent-of-code-2017
 - yob/advent2017
 - yob/babushka-deps
 - yob/buildkite-test
 - yob/cockroachdb-experiment
 - yob/csv2onix
 - yob/db2fog
 - yob/envprinter-buildkite-plugin
 - yob/gem-lint
 - yob/google-api-ruby-client
 - yob/hashbackup
 - yob/jswin
 - yob/lint_report
 - yob/lita-googleapps
 - yob/miniredis
 - yob/onix
 - yob/prawn-rails-xaccelredirect
 - yob/share-rb-demo
 - yob/share.rb
 - yob/sharego
 - yob/strip_control_chars
 - yob/symmetric_file
 - yob/trimdetector
 - yob/upc
 - yob/wedded-wives
 - yob/yob.github.com
 - yob/selenium-webdriver
 - yob/arboreal
 - yob/lita-time
 - yob/go-koans
 - yob/lita-asset-track
 - yob/brine
 - yob/rubocop-rspec

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
