### ISSUE TITLE
Opt-out request for adrianheine

### ISSUE THREAD

**Issue by adrianheine** [bigcode-project/opt-out-v2#1986]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: https://stackoverflow.com/users/55965/adrian-heine
 - adrianheine/builddocs
 - adrianheine/gitsh
 - adrianheine/hire-adrian-lang
 - adrianheine/node-in-words
 - adrianheine/style-mod
 - adrianheine/website-1
 - adrianheine/acorn5-object-spread
 - adrianheine/ada
 - adrianheine/adrianheine.de
 - adrianheine/allesatt
 - adrianheine/berlinjs.org
 - adrianheine/cozy-pm
 - adrianheine/dokuwiki-diffpreview
 - adrianheine/dokuwiki-plugin-lockdown
 - adrianheine/dokuwiki-releasestuff
 - adrianheine/dokuwiki-tpl-meena
 - adrianheine/getdocs
 - adrianheine/heckle
 - adrianheine/mw-wikibase-forms
 - adrianheine/openid-ldap
 - adrianheine/partial-js
 - adrianheine/pat-twitter
 - adrianheine/proposal-class-static-block
 - adrianheine/reverse-mustache
 - adrianheine/test262-stream
 - adrianheine/user-scripts
 - adrianheine/website
 - adrianheine/yblass
 - adrianheine/rustache
 - adrianheine/prosemirror
 - adrianheine/buble-demo
 - adrianheine/stryker-mutator.github.io
 - adrianheine/jsdom
 - adrianheine/acorn
 - adrianheine/array-query
 - adrianheine/rust
 - adrianheine/acorn-bigint
 - adrianheine/racer
 - adrianheine/node-jshint
 - adrianheine/rollup-plugin-commonjs
 - adrianheine/acorn-jsx
 - adrianheine/hyper
 - adrianheine/activityspam
 - adrianheine/stryker

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
