### ISSUE TITLE
Opt-out request for busticated

### ISSUE THREAD

**Issue by busticated** [bigcode-project/opt-out-v2#1989]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - busticated/example-multi-js
 - busticated/gatsby-env-vars
 - busticated/node-convict
 - busticated/01110000
 - busticated/AMD-Collection
 - busticated/AMDWTF
 - busticated/RequireJS_Halps
 - busticated/UnitTestingUsingRequireJSContext
 - busticated/ancient-bits
 - busticated/bbsandbox
 - busticated/bust-cli
 - busticated/bust-eslint-config
 - busticated/busticated.github.com
 - busticated/checksnap
 - busticated/rust-color
 - busticated/mississippi
 - busticated/heroku-cli-command
 - busticated/storybook-monorepo-repo

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
