### ISSUE TITLE
Opt-out request for USERNAME

### ISSUE THREAD

**Issue by juanfernandes** [bigcode-project/opt-out-v2#1993]
I request that the following data is removed from The Stack:

[juanfernandes/eleventy-plugin-cloudinary](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/juanfernandes/eleventy-plugin-cloudinary)

[juanfernandes/11ty.io](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/juanfernandes/11ty.io)

[juanfernandes/Arctic-Scroll](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/juanfernandes/Arctic-Scroll)

[juanfernandes/Sublime-Text](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/juanfernandes/Sublime-Text)

[juanfernandes/accessible-modal-dialog](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/juanfernandes/accessible-modal-dialog)

[juanfernandes/card](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/juanfernandes/card)

[juanfernandes/checklists](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/juanfernandes/checklists)

[juanfernandes/genesis](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/juanfernandes/genesis)

[juanfernandes/jquery-your-mom-should-know](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/juanfernandes/jquery-your-mom-should-know)

[juanfernandes/juanfernandes](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/juanfernandes/juanfernandes)

[juanfernandes/juanfernandes.github.io](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/juanfernandes/juanfernandes.github.io)

[juanfernandes/perchsnippets](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/juanfernandes/perchsnippets)

[juanfernandes/project](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/juanfernandes/project)

[juanfernandes/sublime-nunjucks](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/juanfernandes/sublime-nunjucks)

[juanfernandes/wilto-makes-food](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/juanfernandes/wilto-makes-food)

[juanfernandes/awesome-tech-blogs](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/juanfernandes/awesome-tech-blogs)

[juanfernandes/11ty-twitch-scenes](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/juanfernandes/11ty-twitch-scenes)

[juanfernandes/rwd-js-patterns](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/juanfernandes/rwd-js-patterns)

[juanfernandes/LikeMonitor](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/juanfernandes/LikeMonitor)

[juanfernandes/personalsit.es](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/juanfernandes/personalsit.es)

[juanfernandes/slider.css](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/juanfernandes/slider.css)

[juanfernandes/grid](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/juanfernandes/grid)

[juanfernandes/Bits](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/juanfernandes/Bits)

[juanfernandes/Style-Guides](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/juanfernandes/Style-Guides)
 
_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.
...

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
