### ISSUE TITLE
Opt-out request for shism2

### ISSUE THREAD

**Issue by juliocastilla** [bigcode-project/opt-out-v2#2]
I request that the following data is removed from The Stack:

 - Commits
 - GitHub issue
 - shism2/StyleGAN2
 - shism2/Timeseries-Prediction-Models
 - shism2/apebase
 - shism2/bitnami-docker-python
 - shism2/colab-ssh
 - shism2/examples
 - shism2/krane
 - shism2/ml-workspace
 - shism2/nixpkgs
 - shism2/seqio
 - shism2/template-nix
 - shism2/template-nixos
 - shism2/twint
 - shism2/zvt

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Hi @juliocastilla it looks like you opted out of repositories that are not under your username. Could you elaborate why you are opting out of @shism2's repositories?

**Comment by tealamore** [comment]
@lvwerra there's a lot of open opt-out requests in this repo but it seems like no action is being taken. are you or someone else the point of contact for getting these requests fulfilled?

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.0.1 of The Stack and all future versions. Also your data was not used for the training of StarCoder2.

[PROCESSED]
