### ISSUE TITLE
Opt-out request for markrwilliams

### ISSUE THREAD

**Issue by markrwilliams** [bigcode-project/opt-out-v2#20]
I request that the following data is removed from The Stack:

 - Commits
 - GitHub issue
 - markrwilliams/alchimia
 - markrwilliams/auditwheel
 - markrwilliams/bfa
 - markrwilliams/boltons
 - markrwilliams/capysicum
 - markrwilliams/dapper
 - markrwilliams/gidgethub
 - markrwilliams/pydivsufsort
 - markrwilliams/spyce
 - markrwilliams/stompest
 - markrwilliams/streamingjson
 - markrwilliams/synapse
 - markrwilliams/tectonic
 - markrwilliams/twisted
 - markrwilliams/txacme
 - markrwilliams/txsni

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.0.1 of The Stack and all future versions. Also your data was not used for the training of StarCoder2.

[PROCESSED]
