### ISSUE TITLE
Opt-out request for Frigyes06

### ISSUE THREAD

**Issue by Frigyes06** [bigcode-project/opt-out-v2#2006]
I request that the following data is removed from The Stack:

- Commits
- GitHub issue
- Frigyes06/MicroCoin-account-bot-python
- Frigyes06/OpenVerify
- Frigyes06/peacecoin
- Frigyes06/lora-demo
- Frigyes06/omniwheel
- Frigyes06/omniwheel-sensor-proj
- Frigyes06/pehartzbot
- Frigyes06/proto
- Frigyes06/python-prime-searcher
- Frigyes06/pygame
- Frigyes06/MicroCoin
- ALL

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.
...

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
