### ISSUE TITLE
Opt-out request for tjarksaul

### ISSUE THREAD

**Issue by tjarksaul** [bigcode-project/opt-out-v2#2011]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - tjarksaul/django-pgcrypto-fields
 - tjarksaul/seafile-docker
 - tjarksaul/tunneler
 - tjarksaul/Abrechnungssystem
 - tjarksaul/EquipSetUpdater
 - tjarksaul/HVA_DBKP
 - tjarksaul/PrintTrayChanger
 - tjarksaul/adventofcode
 - tjarksaul/airportmap
 - tjarksaul/chat
 - tjarksaul/dlrg-cloud-notifier
 - tjarksaul/jeopardy
 - tjarksaul/ldb-tankinfo
 - tjarksaul/libphonenumber-for-php
 - tjarksaul/mipushbox
 - tjarksaul/oc-counter
 - tjarksaul/postfix-tempmail
 - tjarksaul/raspberry-remote
 - tjarksaul/simple-auth
 - tjarksaul/tippspiel
 - tjarksaul/url-shortener
 - tjarksaul/wachplan-web
 - tjarksaul/weg-li
 - tjarksaul/docker-tinydns
 - tjarksaul/homebrew-cask
 - tjarksaul/anything.css
 - tjarksaul/imaputils
 - tjarksaul/mailpw_change
 - tjarksaul/unblock-us-updater
 - tjarksaul/appcastautomation
 - tjarksaul/ubirch-event-log
 - tjarksaul/cert-covid19
 - tjarksaul/tjarksaul
 - nichdu/Adafruit_Python_CharLCD
 - nichdu/secure-file-uploader
 - nichdu/array-utils
 - nichdu/Funktagebuch
 - nichdu/XcodeGhost
 - nichdu/dotfiles
 - nichdu/foodextractor
 - nichdu/ip-setter
 - nichdu/learn-c
 - nichdu/lehrgang
 - nichdu/misc
 - nichdu/pkk
 - nichdu/station-updater
 - dlrg-langen/beitrittserklaerung-web
 - dlrg-langen/dienstanweisung
 - dlrg-langen/infodisplay
 - dlrg-langen/satzung
_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
