### ISSUE TITLE
Opt-out request for aardrian

### ISSUE THREAD

**Issue by aardrian** [bigcode-project/opt-out-v2#2017]
I request that the following data is removed from The Stack:

 - [aardrian/select-css](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/aardrian/select-css)
- [aardrian/DoesYourSiteDeserveRecognition.com](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/aardrian/DoesYourSiteDeserveRecognition.com)
- [aardrian/soda-php](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/aardrian/soda-php)
- [aardrian/std-toast](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/aardrian/std-toast)
- [aardrian/top-people-to-follow-in-web-accessibility](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/aardrian/top-people-to-follow-in-web-accessibility)
- [aardrian/angular.js](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/aardrian/angular.js)
- [aardrian/tc39.github.io](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/aardrian/tc39.github.io)
- [aardrian/fukol-grids](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/aardrian/fukol-grids)
 - All issues I have filed on any repo.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
