### ISSUE TITLE
Opt-out request for piguicorn

### ISSUE THREAD

**Issue by piguicorn** [bigcode-project/opt-out-v2#2018]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - piguicorn/To-Do
 - piguicorn/alexa-game-capitales
 - piguicorn/appViajes6
 - piguicorn/arithmetic_arranger
 - piguicorn/basic-js
 - piguicorn/basic-python
 - piguicorn/cool-sites-repo
 - piguicorn/der-die-das
 - piguicorn/drowvoloper.github.io
 - piguicorn/elevator-saga
 - piguicorn/flat-ui-php-login
 - piguicorn/intro-ts
 - piguicorn/java-ejercicios-sencillos
 - piguicorn/java-tictactoe
 - piguicorn/js-challenges
 - piguicorn/magic-store
 - piguicorn/nuwe-htsv3
 - piguicorn/php-mysql-crud
 - piguicorn/portfolio-try
 - piguicorn/prueba-tecnica-repositorio-recetas
 - piguicorn/simple-API
 - piguicorn/todo-terminal
 - piguicorn/trying-godot
 - piguicorn/vanilla-js-pong
 - piguicorn/yargs-and-colorsjs
 - piguicorn/basic-angular
 - piguicorn/angular-gifs-app
 - piguicorn/python-web-browser

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
