### ISSUE TITLE
Opt-out request for christopherbowers

### ISSUE THREAD

**Issue by christopherbowers** [bigcode-project/opt-out-v2#2019]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - christopherbowers/Photography-Portfolio-v1
 - christopherbowers/hello-world

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
