### ISSUE TITLE
Opt-out request for cmkm

### ISSUE THREAD

**Issue by cmkm** [bigcode-project/opt-out-v2#2025]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - cmkm/2070
 - cmkm/accordion
 - cmkm/cmkm.github.io
 - cmkm/converter
 - cmkm/dotfiles
 - cmkm/javaquiz
 - cmkm/javaquizweb
 - cmkm/jquery_thumbs
 - cmkm/notes-fall-2014
 - cmkm/notes-fall-2015
 - cmkm/pasteldash
 - cmkm/resume
 - cmkm/snappy
 - cmkm/waffleiron
 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
