### ISSUE TITLE
opt-out requests being honored?

### ISSUE THREAD

**Issue by Lunarequest** [bigcode-project/opt-out-v2#2027]
as far as i can tell there are opt out requests as far back as december of last year with 0 input into weather they still are valid. Are these requests being honored?

**Comment by Lunarequest** [comment]
for example ptrlrd opened a request on december 5th of 2023, their repos are still present in the stack. Are these requests being honored?

**Comment by Goorzhel** [comment]
I prodded @lvwerra in https://github.com/bigcode-project/opt-out-v2/issues/177#issuecomment-2002955224, unsuccessfully.

**Comment by Goorzhel** [comment]
Two weeks ago, I prodded @lvwerra in https://github.com/bigcode-project/opt-out-v2/issues/177#issuecomment-2002955224, to no avail.

**Comment by Lunarequest** [comment]
I suspect since starcoder2 is complete they've stopped opt outs

**Comment by lvwerra** [comment]
We are currently processing opt-outs, hopefully a new version later this week or next week. Note that we updated all issues which we already removed for StarCoder2.

Updating the dataset is a significant effort, so we try to gather as many requests as possible at a time. There will be a comment on the issues once the opt-outs have been applied.

**Comment by Lunarequest** [comment]
we don't care if you are having training running, we want you to remove our data _now_ and not included in any future versions relative to the request's date

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]

**Comment by Lunarequest** [comment]
What about old versions. Will it be removed from old versions
