### ISSUE TITLE
Opt-out request for aerger

### ISSUE THREAD

**Issue by aerger** [bigcode-project/opt-out-v2#2028]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - aerger/1gam-september
 - aerger/Coursera-Intro-to-Python
 - aerger/GamerArduinoTools
 - aerger/LD33
 - aerger/LD42
 - aerger/af.com-site-banner-test
 - aerger/intfiction
 - aerger/aerger.github.io
 - all

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
