### ISSUE TITLE
Opt-out request for jl5000

### ISSUE THREAD

**Issue by jl5000** [bigcode-project/opt-out-v2#2033]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - jl5000/Rgmdn
 - jl5000/autoged
 - jl5000/barRacer
 - jl5000/geddown
 - jl5000/dynamic_rmarkdown_example
 - jl5000/jamie_lendrum_cv
 - jl5000/linux-video-scripts
 - jl5000/public-gedcoms
 - jl5000/r_ebooks
 - jl5000/swgoh-mods
 - jl5000/tidysearch
 - jl5000/tsb-banking-scripts
 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
