### ISSUE TITLE
Opt-out request for vnckppl

### ISSUE THREAD

**Issue by vnckppl** [bigcode-project/opt-out-v2#2034]
I request that the following data is removed from The Stack:
 - Commits
 - GitHub issue
 - vnckppl/niipre
 - vnckppl/para
 - vnckppl/pySpec
 - vnckppl/pymedwrapper
 - vnckppl/twilioScheduler
 - vnckppl/vnckppl.github.io
- all

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
