### ISSUE TITLE
Opt-out request for mattly

### ISSUE THREAD

**Issue by mattly** [bigcode-project/opt-out-v2#2036]
CONSENT IS NOT OPT-OUT.

I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - mattly/bitwig-soundplane
 - mattly/datagrammer
 - mattly/emacs-doom-themes
 - mattly/exegesis
 - mattly/iterm-colors-farmhouse
 - mattly/max-manta2midi
 - mattly/precog
 - mattly/advent-2018
 - mattly/alexandria
 - mattly/atom-colors-pencil-dark
 - mattly/atom-sector-one-syntax
 - mattly/colors-farmhouse
 - mattly/d3-tacobar.git
 - mattly/docker-assholes
 - mattly/dot-atom
 - mattly/dotfiles
 - mattly/dotfiles-email
 - mattly/emacs-akkala-themes
 - mattly/fuzzywysi
 - mattly/helvetichat
 - mattly/homebrew-core
 - mattly/hpreserve
 - mattly/lyonheart-hugo
 - mattly/lyonheart-us-metalsmith-archive
 - mattly/markstache
 - mattly/mattlymacs
 - mattly/maxlib
 - mattly/metalsmith-placeholder
 - mattly/nginx_config_generator
 - mattly/node-cache-advice
 - mattly/node-cache-advice-redis
 - mattly/nodepdx_music
 - mattly/pdx-clojure-frontend
 - mattly/pdxclj-cats-promesa
 - mattly/pilcrow
 - mattly/proceed
 - mattly/processing-computative-art
 - mattly/prototypes
 - mattly/pushy
 - mattly/react-pikaday
 - mattly/ssdug-generative-art
 - mattly/ssdug-graphql
 - mattly/tacosmith
 - mattly/talk-transcripts
 - mattly/tannat-themes
 - mattly/triplicate
 - mattly/vim-markdown-enhancements
 - mattly/nodepdx.github.com
 - mattly/hx
 - mattly/atom-colors-pencil-light
 - mattly/react-bootstrap
 - mattly/npm-neat
 - mattly/wintersmith-nunjucks
 - mattly/metalsmith-multimarkdown
 - mattly/clj-airbrake
 - mattly/homebrew-cask

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
