### ISSUE TITLE
Opt-out request for teh-maxh

### ISSUE THREAD

**Issue by teh-maxh** [bigcode-project/opt-out-v2#2037]
I request that the following data is removed from The Stack and StackOverflow:

 - all

Use of code for ML training cannot guarantee compliance with licences; therefore, to avoid inadvertent copyright infringement, please remove all code from this dataset.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
