### ISSUE TITLE
Opt-out request for wtee

### ISSUE THREAD

**Issue by nausicaa-rose** [bigcode-project/opt-out-v2#2038]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: wtee
 - wtee/Using-MARC-prediction-patterns
 - wtee/alma_enumerator
 - wtee/anesgesgi
 - wtee/battc
 - wtee/blot
 - wtee/germ
 - wtee/link_opener
 - wtee/markovmonster
 - wtee/pocket
 - wtee/simple-slides
 - wtee/yggdrasil
 - wtee/aoide
 - wtee/aquatic_hunter
 - wtee/ati-broadcastapp
 - wtee/bachelors_theses
 - wtee/beardbrarian
 - wtee/djogger
 - wtee/dotfiles
 - wtee/encorpulators
 - wtee/fill-in-quiz
 - wtee/germ-rb
 - wtee/gopher_guestbook
 - wtee/gvsu_demo
 - wtee/itunes-podcast-feed
 - wtee/learning_exercises
 - wtee/more-than-manuscripts
 - wtee/random_names
 - wtee/random_notebooks
 - wtee/rosetta_code_contributions
 - wtee/rpgdb
 - wtee/truecaser
 - wtee/tweet-it.git
 - wtee/weather
 - wtee/wikipedia-stuff
 - wtee/work_utilities
 - wtee/c4l18-keynote-statement
 - wtee/av_scua

Please note that while I have recently changed my github user name, I am the individual who created those repositories and they are all still accessible under my current username. The inclusion of private repositories like wtee/dotfiles in The Stack is extremely troubling and an absolute violation, as is the inclusion of public, but non-licensed (and thus not open source) repositories.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
