### ISSUE TITLE
Opt-out request for fgergo

### ISSUE THREAD

**Issue by fgergo** [bigcode-project/opt-out-v2#2039]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - fgergo/boringstreamer
 - fgergo/clive
 - fgergo/echotime
 - fgergo/fswalker
 - fgergo/ip100
 - fgergo/mp3
 - fgergo/naive
 - fgergo/rtgrep
 - fgergo/tailscale
 - fgergo/us2stdio
 - fgergo/etch
 - fgergo/goversion
 - fgergo/jstorus
 - fgergo/u9fs

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
