### ISSUE TITLE
Opt-out request for jgonggrijp

### ISSUE THREAD

**Issue by jgonggrijp** [bigcode-project/opt-out-v2#2041]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: https://stackoverflow.com/users/1166087/julian
 - jgonggrijp/backbone-bulma
 - jgonggrijp/backbone-machina
 - jgonggrijp/cookiecutter-webapp-deluxe
 - jgonggrijp/pip-review
 - jgonggrijp/TextMate.tmbundle
 - jgonggrijp/backbone-decorators
 - jgonggrijp/lapis
 - jgonggrijp/net-prove
 - jgonggrijp/rapidash
 - jgonggrijp/rich-typed-pointers
 - jgonggrijp/session-testcase
 - jgonggrijp/spamgourmet
 - jgonggrijp/XKCDForumUtility
 - jgonggrijp/underscore-debounce-test
 - all

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
