### ISSUE TITLE
Opt-out request for @ell1e and @Horse64 and @Spew3D

### ISSUE THREAD

**Issue by ell1e** [bigcode-project/opt-out-v2#2048]
I request that the following data is removed from The Stack:

 - [All](https://github.com/ell1e?tab=repositories), including these orgs I run [[1]](https://github.com/Horse64) ([admin proof](https://github.com/orgs/Horse64/people)), [[2]](https://github.com/Spew3D) ([admin proof](https://github.com/orgs/Spew3D/people)).

   The reason is I'm not sure 3rd party contributors would agree to be included unless licensing was always honored, which given history seems not necessarily to be the case. **In particular, [Star coder seems to possibly violate that](https://huggingface.co/blog/starcoder) for licenses that have attribution requirements.** But I wouldn't know, I'm not a legal person, ask your own council.
 
_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.
...

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
