### ISSUE TITLE
Removal of repositories

### ISSUE THREAD

**Issue by sgwilym** [bigcode-project/opt-out-v2#2050]
I request that the following data is removed from The Stack:

 - sgwilym (all repos under this username)
 - earthstar-project (all repos under this organisation)

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
