### ISSUE TITLE
Opt-out request for Murazaki

### ISSUE THREAD

**Issue by Murazaki** [bigcode-project/opt-out-v2#2051]
I request that the following data is removed from The Stack and StackOverflow:

 - all
 - Commits
 - GitHub issue
 - any other content from me from any other website, including but not limited to Bitbucket, Gitlab, etc.
 - StackOverflow: Murazaki
 - Murazaki/dendrite
 - Murazaki/helix-docker
 - Murazaki/Cours_Ionic_2
 - Murazaki/EmojiPanel
 - Murazaki/Isometry-Unity
 - Murazaki/LibGizmo
 - Murazaki/QtCanvas
 - Murazaki/RaptorLite
 - Murazaki/angular-eval1
 - Murazaki/angular-exercise1
 - Murazaki/angular-notes
 - Murazaki/esd-basic-api
 - Murazaki/frontend-boilerplate
 - Murazaki/gifgenerator
 - Murazaki/gulp-angular2
 - Murazaki/murazaki.github.io
 - Murazaki/naffka
 - Murazaki/nest-typescript-starter
 - Murazaki/processing-raptor
 - Murazaki/qmlPong
 - Murazaki/scoop
 - Murazaki/mean
 - ChromaTeam/Chroma

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
