### ISSUE TITLE
Opt-out request for pcorey

### ISSUE THREAD

**Issue by pcorey** [bigcode-project/opt-out-v2#2053]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - pcorey/SpeedReader
 - pcorey/agenda
 - pcorey/apollo-errors
 - pcorey/graphql-rabbitmq-subscriptions
 - pcorey/intro-to-security
 - pcorey/spacecamp
 - pcorey/.emacs.d
 - pcorey/4x
 - pcorey/ClairvoyanceServer
 - pcorey/JuliaSass
 - pcorey/Markovich
 - pcorey/PhoneGapTest
 - pcorey/SeniorProject
 - pcorey/Telescope
 - pcorey/admithub-scan
 - pcorey/advent_of_code_01
 - pcorey/advent_of_code_2017
 - pcorey/advent_of_code_2018
 - pcorey/affiliate_crawler
 - pcorey/beeradvocate-scraper
 - pcorey/bip39
 - pcorey/bip39_haiku
 - pcorey/block
 - pcorey/brainfuck.js
 - pcorey/check-checker
 - pcorey/chord
 - pcorey/chord-chart
 - pcorey/chronicler
 - pcorey/coffee-and-katas
 - pcorey/collatz
 - pcorey/commander
 - pcorey/commander-example
 - pcorey/count_the_divisible_numbers
 - pcorey/countwith.me
 - pcorey/dearestelle
 - pcorey/delete-occurrences-of-an-element-if-it-occurs-more-than-n-times
 - pcorey/east5th
 - pcorey/eigenfun
 - pcorey/elixir_poster
 - pcorey/flex-cantor
 - pcorey/glorious_voice_leader
 - pcorey/glorious_voice_leader.bak
 - pcorey/glorious_voice_leader.old
 - pcorey/hello-braintree
 - pcorey/hello-orion
 - pcorey/hello_absinthe
 - pcorey/hello_bitcoin
 - pcorey/hello_bitcoin_node
 - pcorey/hello_blockchain
 - pcorey/hello_lissajous
 - pcorey/hello_port_midi
 - pcorey/hello_proto
 - pcorey/hello_recurring
 - pcorey/hello_substitutions
 - pcorey/hello_yup
 - pcorey/julia-templeos
 - pcorey/life
 - pcorey/meteor-dictionary
 - pcorey/meteor-rails-devise
 - pcorey/meteor-shop
 - pcorey/meteor_auth
 - pcorey/minimum_viable_phoenix
 - pcorey/mock-meteor
 - pcorey/molecule-to-atoms
 - pcorey/msestellemarie-ratings
 - pcorey/nesting-structure-comparison
 - pcorey/network-only-reproduction
 - pcorey/no-cached-results
 - pcorey/orion-slingshot
 - pcorey/passwordless
 - pcorey/pcorey.github.io
 - pcorey/phoenix-graphql-absinthe-tutorial
 - pcorey/phoenix_leaderboard
 - pcorey/phoenix_react
 - pcorey/phoenix_todos
 - pcorey/point-in-polygon
 - pcorey/practicalmocha-repro
 - pcorey/recursive_discriminators
 - pcorey/secure_meteor
 - pcorey/snapshot-inconsistencies
 - pcorey/spiral
 - pcorey/sublime-hide-menu
 - pcorey/suffixer
 - pcorey/test
 - pcorey/the-captains-distance-request
 - pcorey/the-verge
 - pcorey/thisurlshortenertotallyandcompletely.rocks
 - pcorey/unit-testing-with-testdouble
 - pcorey/wiki
 - pcorey/workflow_test
 - pcorey/meteor-stale-session
 - pcorey/Clairvoyance
 - pcorey/node-oanda
 - pcorey/elixir
 - pcorey/test-pages
 - pcorey/nx
 - pcorey/apollo-client
 - pcorey/base
 - pcorey/meteor-composability-presentation
 - pcorey/package_control_channel
 - pcorey/hello-newrelic
 - pcorey/moneybot
 - pcorey/node-namecheap
 - pcorey/meteor-shared-auth
 - pcorey/materialize
 - pcorey/meteor-composability

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
