### ISSUE TITLE
Opt-out request for gbirke

### ISSUE THREAD

**Issue by gbirke** [bigcode-project/opt-out-v2#2057]
I request that the following data is removed from The Stack:

 - all

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
