### ISSUE TITLE
Opt-out request for h8f1z

### ISSUE THREAD

**Issue by h8f1z** [bigcode-project/opt-out-v2#2058]
I request that the following data is removed from The Stack and StackOverflow:

 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
