### ISSUE TITLE
Removal request

### ISSUE THREAD

**Issue by suetanvil** [bigcode-project/opt-out-v2#2059]
I request that the following data is removed from The Stack:

 - All data held by the account "suetanvil" (https://github.com/suetanvil)
 - All data held by the organization "relarn" (https://github.com/relarn)
 - All data held by the organization "suetanvil-misc" (https://huggingface.co/spaces/bigcode/in-the-stack)
 
Be advised that I do not own some of the code in these repositories and that while the various licenses allow me to host it here, they almost certainly **do not** allow this use of it.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
