### ISSUE TITLE
Opt-out request for mugshepherd

### ISSUE THREAD

**Issue by mugshepherd** [bigcode-project/opt-out-v2#2063]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - mugshepherd/carbon-website
 - mugshepherd/coffeeShopApp
 - mugshepherd/pg3ContactsAPI
 - mugshepherd/ALittleInaccuracy
 - mugshepherd/GA-Project4
 - mugshepherd/ProgrammingAssignment2
 - mugshepherd/StepStepStep
 - mugshepherd/WDI-DC_Project2
 - mugshepherd/WDInstagram
 - mugshepherd/api_response_broker
 - mugshepherd/blog_authenticated
 - mugshepherd/d3_smallMultiples
 - mugshepherd/d3jsMaps_practice
 - mugshepherd/datasciencecoursera
 - mugshepherd/disemvowel-trolls-kata
 - mugshepherd/final-countdown
 - mugshepherd/game-of-war
 - mugshepherd/grumbler2.0
 - mugshepherd/koboApi_broker_rails
 - mugshepherd/lets-practice-pull-requests
 - mugshepherd/letsMakeAMap
 - mugshepherd/mad-librarians
 - mugshepherd/mdg_tracker
 - mugshepherd/milk-and-cookies
 - mugshepherd/mugshepherd.github.io
 - mugshepherd/node-api-client
 - mugshepherd/node-rest-api
 - mugshepherd/node-starter-1
 - mugshepherd/pgWorkshop
 - mugshepherd/phonegapBuild_Test1
 - mugshepherd/pixart_js
 - mugshepherd/presentation_101
 - mugshepherd/restofy_api
 - mugshepherd/slidey-mcshowington
 - mugshepherd/stock-tracker
 - mugshepherd/trillo_bis
 - mugshepherd/wdiDC_Project3
 - mugshepherd/wdi_dc5_rails_quiz
 - mugshepherd/what-the-cow-says_api-test
 - mugshepherd/yo-yo-da
 - mugshepherd/Hogwartz
 - mugshepherd/studio-hiring
 - mugshepherd/play_depot
 - mugshepherd/dcjs-leaflet-beer-tracker
 - mugshepherd/d3
 - mugshepherd/sportsStore_routing
 - mugshepherd/phoneGap_initialTest
 - mugshepherd/material2-sample
 - mugshepherd/lets-practice-gitFlow
 - mugshepherd/grumblr

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
