### ISSUE TITLE
Opt-out request for annaswims

### ISSUE THREAD

**Issue by annaswims** [bigcode-project/opt-out-v2#2065]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - annaswims/annaswims.github.io
 - annaswims/docs
 - annaswims/mobiconf
 - annaswims/railsbridgeindy
 - annaswims/seamless_database_pool
 - annaswims/twitter_long_url
 - annaswims/vestal_versions
 - annaswims/ruby-pg
 - annaswims/suggestatron
 - annaswims/active_shipping
 - annaswims/reprap_prusai3_firmware

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
