### ISSUE TITLE
Opt-out request for dfintha

### ISSUE THREAD

**Issue by dfintha** [bigcode-project/opt-out-v2#2066]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - dfintha/gengine
 - dfintha/bme-doc-template
 - dfintha/dflib
 - dfintha/dfsys
 - dfintha/hq9plus
 - dfintha/listener
 - dfintha/magicmake
 - dfintha/neptundb
 - dfintha/pwgen
 - dfintha/systems
 - dfintha/szakmai-gyakorlat-dokumentumok
 - all

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
