### ISSUE TITLE
Opt-out request for aaribaud

### ISSUE THREAD

**Issue by aaribaud** [bigcode-project/opt-out-v2#2067]
I request that the following data is removed from The Stack:

 - Commits
 - GitHub issue
 - aaribaud/cli
 - aaribaud/certbot
 - aaribaud/gitea
 - aaribaud/mastotool
 - all

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
