### ISSUE TITLE
Opt-out request for ariasuni

### ISSUE THREAD

**Issue by ariasuni** [bigcode-project/opt-out-v2#210]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: ariasuni
 - ariasuni/RebeccaStevens
 - ariasuni/hunspell-inclusif
 - ariasuni/rust-number-prefix
 - ariasuni/smart-referer
 - ariasuni/statx-sys
 - ariasuni/webextensions
 - all

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
