### ISSUE TITLE
Opt-out request for tranzystorek-io

### ISSUE THREAD

**Issue by tranzystorekk** [bigcode-project/opt-out-v2#211]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - tranzystorek-io/Bingo
 - tranzystorek-io/FuzzyBird
 - tranzystorek-io/PROI1
 - tranzystorek-io/Trex
 - tranzystorek-io/aoc2019
 - tranzystorek-io/aoc2019-fsharp
 - tranzystorek-io/aoc2019-rust
 - tranzystorek-io/btree
 - tranzystorek-io/fractions-rs
 - tranzystorek-io/hexers
 - tranzystorek-io/langust
 - tranzystorek-io/mdofs
 - tranzystorek-io/misc
 - tranzystorek-io/roulette
 - tranzystorek-io/strata-solver
 - tranzystorek-io/tranzystorek-io.github.io

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
