### ISSUE TITLE
Opt-out request for medains

### ISSUE THREAD

**Issue by medains** [bigcode-project/opt-out-v2#212]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: colin-ameigh
 - medains/ansible
 - medains/basic-silex
 - medains/dotfiles
 - medains/eslint-test
 - medains/frontend-tdd-example1
 - medains/journal
 - medains/neural-learning
 - medains/node-poker-ranking
 - medains/node-poker-ranking-example
 - medains/notes
 - medains/php-mvc
 - medains/php-poker-ranking
 - medains/speaking
 - medains/spotify-control
 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
