### ISSUE TITLE
Opt-out request for mistydemeo

### ISSUE THREAD

**Issue by mistydemeo** [bigcode-project/opt-out-v2#213]
I request that the following data is removed from The Stack and StackOverflow:

 - all
 - Commits
 - GitHub issue
 - mistydemeo/A120LO-LUA
 - mistydemeo/DBTextWorks
 - mistydemeo/Pom-Gets-Wi-Fi
 - mistydemeo/Saturn-SDK-GCC-SH2
 - mistydemeo/Zzz
 - mistydemeo/acpk2avi
 - mistydemeo/ansr
 - mistydemeo/archivesspace
 - mistydemeo/artefactual_notes
 - mistydemeo/aventofcode
 - mistydemeo/bitrise
 - mistydemeo/blacklight-jetty
 - mistydemeo/cdrom_crc
 - mistydemeo/chihiro
 - mistydemeo/chrgfx
 - mistydemeo/courextool
 - mistydemeo/dotfiles
 - mistydemeo/dotfiles-1
 - mistydemeo/dpla-tool
 - mistydemeo/eb
 - mistydemeo/eternaldata
 - mistydemeo/exempi
 - mistydemeo/fasttrack
 - mistydemeo/ffmpeg4archivists
 - mistydemeo/fix_service_migration
 - mistydemeo/fontbuild
 - mistydemeo/freya-everywhere
 - mistydemeo/geodata
 - mistydemeo/good-dog
 - mistydemeo/google-emoji
 - mistydemeo/hackable-slack-client
 - mistydemeo/homebrew-brewfile
 - mistydemeo/homebrew-desc
 - mistydemeo/homebrew-digipres
 - mistydemeo/homebrew-emily
 - mistydemeo/homebrew-formulae
 - mistydemeo/homebrew-lunar
 - mistydemeo/homebrew-mplayer2
 - mistydemeo/homebrew-other
 - mistydemeo/homebrew-playstation
 - mistydemeo/homebrew-portable
 - mistydemeo/homebrew-saturn
 - mistydemeo/homebrew-science
 - mistydemeo/homebrew-tigerstage
 - mistydemeo/homebrew-tox
 - mistydemeo/homebrew-twine
 - mistydemeo/homebrew-xfig
 - mistydemeo/hotline
 - mistydemeo/imsplayer
 - mistydemeo/inlibraries.com
 - mistydemeo/jbig2enc
 - mistydemeo/kind
 - mistydemeo/launch_socket_server
 - mistydemeo/librarienne
 - mistydemeo/libyaul
 - mistydemeo/lunar-buildscripts
 - mistydemeo/lunardata
 - mistydemeo/macbinconv
 - mistydemeo/match
 - mistydemeo/megatome
 - mistydemeo/metadater
 - mistydemeo/mistydemeo.github.io
 - mistydemeo/moon-guide
 - mistydemeo/mscfb
 - mistydemeo/msoleps
 - mistydemeo/node-slack-sdk
 - mistydemeo/normarc2rdf
 - mistydemeo/north-american-hipster
 - mistydemeo/openssl-bundle-example
 - mistydemeo/paula
 - mistydemeo/pmdmini
 - mistydemeo/postcss-stronk
 - mistydemeo/pysha256
 - mistydemeo/rewrite-git-history
 - mistydemeo/rhea_menu_generator
 - mistydemeo/saturn-pademu
 - mistydemeo/saturn_recommendations
 - mistydemeo/signbot
 - mistydemeo/simutrans
 - mistydemeo/sssunpack
 - mistydemeo/strap
 - mistydemeo/sublime_freya
 - mistydemeo/sufia
 - mistydemeo/super_nes_classic_edition_oss
 - mistydemeo/supergameherm
 - mistydemeo/svg2raphael
 - mistydemeo/tigerbrew
 - mistydemeo/twitdog
 - mistydemeo/vox_explainer_history
 - mistydemeo/xenoglossia
 - mistydemeo/xmdp

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
