### ISSUE TITLE
Opt-out request for despens

### ISSUE THREAD

**Issue by despens** [bigcode-project/opt-out-v2#216]
I request that the following data is removed from The Stack:

 - all

**Comment by despens** [comment]
Hey @lvwerra, as evident above I asked for removal of my repositories from The Stack, yet I see that in the latest version 2.0.1 even more of my repositories have been added. If you don't plan to act on the requests, please close this repository and stop asking folks for filing requests. At this point that's just a distraction.

**Comment by lvwerra** [comment]
Hi @despens, sorry for the distraction. Note that v2.0.1 reflects the state of opt-out a few months ago that we just now released. Your opt-out will be applied in the following days with v2.1.

Sorry for the inconvenience. You will get notified here when the data is removed.

**Comment by despens** [comment]
@lvwerra Will I have to monitor if new repositories of mine will have been included in the The Stack?

**Comment by lvwerra** [comment]
No, if with `all` we'll remove all repositories under your username in all future versions.

**Comment by despens** [comment]
Alright. How long are the previous versions going to remain available?

**Comment by braids** [comment]
> Hi @despens, sorry for the distraction. Note that v2.0.1 reflects the state of opt-out a few months ago that we just now released. Your opt-out will be applied in the following days with v2.1.
> 
> Sorry for the inconvenience. You will get notified here when the data is removed.

That's funny, you didn't have any issues removing data from a request three weeks ago from v2.0.1. You got another excuse? Get our code out of your training data now.

https://github.com/bigcode-project/opt-out-v2/issues/1362#issuecomment-2015982386

**Comment by despens** [comment]
Look @lvwerra you ingested one of my repositories that has no explicitly stated license. How comes you're not rushing to remove it? 

Other repos I merely cloned, I don't think I can be made responsible for them ending up in The Stack, if the original authors are against that. Why do you ingest all this duplicate code when you could just go for the original location of the repo?

It's really easy to figure out on GitHub what license a project is under and if the actual repo is cloned from somewhere else.
