### ISSUE TITLE
Opt-out request for emenel

### ISSUE THREAD

**Issue by emenel** [bigcode-project/opt-out-v2#217]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: emenel
 - emenel/d3Samples
 - emenel/portfolio

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by emenel** [comment]
Also the included repositories were both private and were deleted last year. This is a serious breach of trust by both github and huggingface and i am spreading the word.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
