### ISSUE TITLE
Opt-out request for kittylyst

### ISSUE THREAD

**Issue by kittylyst** [bigcode-project/opt-out-v2#220]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - kittylyst/Bytecoder
 - kittylyst/ClassBook2018
 - kittylyst/CoStudy
 - kittylyst/CornwallCollegeJS
 - kittylyst/HYG-Database
 - kittylyst/SimpleFlatMapper
 - kittylyst/SuiteSpring
 - kittylyst/TeamDEV
 - kittylyst/adoptium.net
 - kittylyst/betleopard-web
 - kittylyst/garbagecat
 - kittylyst/hackathon_forex_trader
 - kittylyst/hazelcast-jet
 - kittylyst/intellij-apm-plugin
 - kittylyst/jackson-example
 - kittylyst/java11-http2checker
 - kittylyst/javacountdown
 - kittylyst/javanut7
 - kittylyst/jfr-parser_repro_case_graalvm_linkage_bug-bevans
 - kittylyst/jikes
 - kittylyst/jolikit
 - kittylyst/jvmperfexamples
 - kittylyst/kathik-adv-java8
 - kittylyst/kathik-java
 - kittylyst/minimal-opentelemetry-javaagent
 - kittylyst/native-image-test
 - kittylyst/ocelotter
 - kittylyst/opentelemetry-java
 - kittylyst/opentelemetry-java-instrumentation
 - kittylyst/panama-example
 - kittylyst/regions
 - kittylyst/training
 - kittylyst/vavr
 - kittylyst/vm-test-maker
 - kittylyst/wgjd-twitch-mar2021

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
