### ISSUE TITLE
Opt-out request for byteborg

### ISSUE THREAD

**Issue by byteborg** [bigcode-project/opt-out-v2#221]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: byteborg 
 - byteborg/household
 - byteborg/icinga2-influxdb-grafana
 - byteborg/mendelparts
 - byteborg/stringent
 - byteborg/ugrm-data
 - byteborg/v8-blinkenbox
 - byteborg/force-sensor-brake

I declare this opt-out as legally binding for all future commits and projects by me. This is backed by European law, according to my citizenship. 

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
