### ISSUE TITLE
Opt-out request for 404d

### ISSUE THREAD

**Issue by 404d** [bigcode-project/opt-out-v2#222]
I request that the following data is removed from The Stack and StackOverflow:

 - all

Additionally, I opt out from any future use of data from this account for repos that may or may not already exist at the time of this writing

This includes data that isn't explicitly listed above

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
