### ISSUE TITLE
Opt-out request for mdrews93

### ISSUE THREAD

**Issue by mdrews93** [bigcode-project/opt-out-v2#224]
I request that the following data is removed from The Stack and StackOverflow:

 - all

this being opt-out is insane. it's lazy. think of all the code authors who wouldn't consent if they were asked, and all the code authors who have no idea about this (like me, until now). opt-in is so simple, but I suspect it wasn't done that way because they knew not enough people would consent for them to get their desired value, so they chose to completely ignore _everyone's_ consent. 

from the very top of bigcode-project.org:

>BigCode is an open scientific collaboration working on the responsible development and use of large language models for code

it is not responsible development to scrape for dataset construction without consent.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
