### ISSUE TITLE
Opt-out request for pgorman

### ISSUE THREAD

**Issue by pgorman** [bigcode-project/opt-out-v2#226]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - pgorman/clockdash
 - pgorman/collaborative-adventures
 - pgorman/dangerjaunt
 - pgorman/encounterCalculator5e
 - pgorman/gsssg
 - pgorman/logring
 - pgorman/musicminder
 - pgorman/registarium
 - pgorman/rlist
 - pgorman/rollapp
 - pgorman/swcomplete
 - pgorman/swcore
 - pgorman/troublegarden
 - pgorman/txt-to-html
 - all

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
