### ISSUE TITLE
Opt-out request for mooli

### ISSUE THREAD

**Issue by ghost** [bigcode-project/opt-out-v2#229]
I request that the following data is removed from The Stack:

*Everything* related to my account "mooli". Repositories, commits, comments and issues raised against other repositories. Everything.

Do note that the licenses for some of my repositories do not permit AI training and so you are violating my copyright.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
