### ISSUE TITLE
Opt-out request for PoroCYon

### ISSUE THREAD

**Issue by PoroCYon** [bigcode-project/opt-out-v2#230]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - PoroCYon/4klang
 - PoroCYon/AvalonPrism
 - PoroCYon/Bonzomatic
 - PoroCYon/Geometric_Altercations
 - PoroCYon/GravityApplet
 - PoroCYon/IBNIZ
 - PoroCYon/ModAsmWithBF
 - PoroCYon/PokeApi.NET
 - PoroCYon/Pokedex
 - PoroCYon/PoroCYon.Extensions
 - PoroCYon/PoroCYon.Fml
 - PoroCYon/PoroCYon.WpfSettings
 - PoroCYon/Raboof8192
 - PoroCYon/RobCYon
 - PoroCYon/SharktopusMod
 - PoroCYon/SharpDX
 - PoroCYon/T130DataFetcher
 - PoroCYon/TGL
 - PoroCYon/Terraria-Music-Player
 - PoroCYon/WaveSabre
 - PoroCYon/Xbox-Controller-Controls
 - PoroCYon/bfc
 - PoroCYon/brismu
 - PoroCYon/dnload
 - PoroCYon/fr_public
 - PoroCYon/ictsblock
 - PoroCYon/idris-sdl2
 - PoroCYon/il-repack
 - PoroCYon/in4k.github.io
 - PoroCYon/lcn
 - PoroCYon/ld-preload-open
 - PoroCYon/liner
 - PoroCYon/melodygenerator
 - PoroCYon/pokeapi
 - PoroCYon/pwemu
 - PoroCYon/smol
 - PoroCYon/vim-comment

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
