### ISSUE TITLE
Opt-out request for npisanti

### ISSUE THREAD

**Issue by npisanti** [bigcode-project/opt-out-v2#231]
I request that the following data is removed from The Stack:

 - Commits
 - GitHub issue
 - npisanti/Orca-c
 - npisanti/bashcode
 - npisanti/clayblocks
 - npisanti/dotfiles
 - npisanti/fish_scripting_0
 - npisanti/graphicsrepo
 - npisanti/grimorio
 - npisanti/nebbie
 - npisanti/np-analyzer
 - npisanti/np-extra
 - npisanti/np-framework
 - npisanti/np-homography
 - npisanti/np-instruments
 - npisanti/np-kinectmotion
 - npisanti/np-microscript
 - npisanti/np-miscela
 - npisanti/np-patches
 - npisanti/np-pixelscript
 - npisanti/np-scrapbook
 - npisanti/np-stubs
 - npisanti/np-utilities
 - npisanti/npisanti-nocms
 - npisanti/of_cv_and_physics
 - npisanti/ofxAudioFile
 - npisanti/ofxClayblocks
 - npisanti/ofxDeferredShading
 - npisanti/ofxDmx
 - npisanti/ofxDotFrag
 - npisanti/ofxFixture
 - npisanti/ofxGuiPresetSelector
 - npisanti/ofxLaser
 - npisanti/ofxLaunchControllers
 - npisanti/ofxMidi
 - npisanti/ofxMorphImage
 - npisanti/ofxPDSP
 - npisanti/ofxPDSPPatches
 - npisanti/ofxRPiezos
 - npisanti/ofxRapidLib
 - npisanti/ofxSIMDFloats
 - npisanti/orca-snippets
 - npisanti/orcamenti
 - npisanti/oscworks
 - npisanti/pdsp-lessons
 - npisanti/pdsp-stress-tests
 - npisanti/processing_cellular_shapes
 - npisanti/shiftguard

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
