### ISSUE TITLE
Opt-out request for TBSliver

### ISSUE THREAD

**Issue by TBSliver** [bigcode-project/opt-out-v2#232]
I request that the following data is removed from The Stack and StackOverflow:

 - all

As many of the repositories listed in the automated scanner at https://huggingface.co/spaces/bigcode/in-the-stack contain no license, it is assumed that you are in breach of the implicit exclusive copyright.

https://choosealicense.com/no-permission/

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
