### ISSUE TITLE
Opt-out request for rozina-aamir

### ISSUE THREAD

**Issue by rozina-aamir** [bigcode-project/opt-out-v2#234]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - rozina-aamir/3-by-3
 - rozina-aamir/a-frame-web-vr-example
 - rozina-aamir/avoid
 - rozina-aamir/contagion
 - rozina-aamir/drawing-with-type
 - rozina-aamir/freecodecamp
 - rozina-aamir/in-the-dark
 - rozina-aamir/lowercase-monospace-typeface
 - rozina-aamir/may-the-4th-be-with-you
 - rozina-aamir/news-api-test
 - rozina-aamir/revolutionary-net-art
 - rozina-aamir/scythe
 - rozina-aamir/todays-colour

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
