### ISSUE TITLE
Opt-out request for a50397

### ISSUE THREAD

**Issue by a50397** [bigcode-project/opt-out-v2#235]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - a50397/GUI_maker
 - a50397/PeterSirka_jComponent
 - a50397/cff-map
 - a50397/documentation
 - a50397/drone-detection
 - a50397/dygraphs-dynamiczooming-example
 - a50397/kuzzle
 - a50397/kuzzle-plugin-cluster
 - a50397/node-simple-scheduler
 - a50397/openplatform
 - a50397/tm_gateway
 - a50397/totaljs_training
 - a50397/utils
 - a50397/vue-easy-mq
 - a50397/vue-plugin-kuzzle

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
