### ISSUE TITLE
opt out 

### ISSUE THREAD

**Issue by maeserichar** [bigcode-project/opt-out-v2#236]
I request that the following data is removed from The Stack:

 maeserichar/AdventOfCode2016

maeserichar/AdventOfCode2018

maeserichar/GDD-app

maeserichar/NpocoBulkInsertPerformance

maeserichar/PyPong

maeserichar/SipNot

maeserichar/SlashCleaner

maeserichar/VimeoThumbGetter

maeserichar/adventOfCode2017

maeserichar/adventofcode

maeserichar/maeserichar.github.io

maeserichar/mysqld_exporter

maeserichar/proxy_sql_tools
 
_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.
...

I just hope that you understand better how consent works, opting out as an option is taking advantage of people for your own benefit.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
