### ISSUE TITLE
Opt-out request for Yuubari

### ISSUE THREAD

**Issue by Yuubari** [bigcode-project/opt-out-v2#247]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issues
 - Yuubari/KanColleViewerTranslationsAPI
 - Yuubari/LayOff
 - Yuubari/SMSDumpConverter

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
