### ISSUE TITLE
Opt-out request for joshtriplett

### ISSUE THREAD

**Issue by joshtriplett** [bigcode-project/opt-out-v2#251]
Remove all of my data from "The Stack" (past, present, and future versions), including but not limited to:

 - all
 - Any commits I have ever written or will ever write
 - Any code I've written, whether committed or not
 - Any commit messages I've written
 - Any GitHub issues or pull requests or comments I have ever written or will ever write
 - Any repositories containing any code I have written, in any quantity
 - Any other material I have authored, in any form
 - Any AI models or other data trained using any of the above which is not in full compliance with the license of the code, which is the *only* permission granted to use the code, no matter how inconvenient it might be for AI to *actually respect the license of every single bit of input*.
 
Submitting this issue should not be interpreted as in any way acknowledging or consenting to the illegitimate "governance interface" that you are purporting to claim over the Open Source community. You are not the interface between Open Source and AI. Nobody consented to have you represent them, and your goals and values do not align with mine or with those of many others whose code you are including. Your data set does *not* have sufficient information to actually comply with the licenses of code you are including. And even if it did, you *know* that users of the resulting models will not in fact comply with the licenses.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]

**Comment by joshtriplett** [comment]
And presumably, from your phrasing, not from past versions, which for the record is still a problem.
