### ISSUE TITLE
Opt-out request for dbittman

### ISSUE THREAD

**Issue by dbittman** [bigcode-project/opt-out-v2#252]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - dbittman/basil
 - dbittman/chttp
 - dbittman/config-files
 - dbittman/cs-senior-thesis
 - dbittman/dbittman.github.io
 - dbittman/dbittman.github.ioa
 - dbittman/dbutil
 - dbittman/dotfiles
 - dbittman/dsplit
 - dbittman/elf-ld.so
 - dbittman/hanabi-ai
 - dbittman/hex-montecarlo
 - dbittman/ising-rust
 - dbittman/learning-languages
 - dbittman/llvm-random
 - dbittman/noted
 - dbittman/oc-compiler
 - dbittman/physics-data
 - dbittman/physics-docs
 - dbittman/physics-senior-thesis
 - dbittman/rqotd
 - dbittman/rust-test-kernel
 - dbittman/seakernel-refactor
 - dbittman/sesh
 - dbittman/ship
 - dbittman/slack-xkcd
 - dbittman/snake
 - dbittman/statics-solver
 - dbittman/swarm
 - dbittman/talk-mmap-everything
 - dbittman/twizzler
 - dbittman/various

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
