### ISSUE TITLE
Opt-out request for DrMcCoy

### ISSUE THREAD

**Issue by DrMcCoy** [bigcode-project/opt-out-v2#253]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - DrMcCoy/OLDscummvm-darkseed2
 - DrMcCoy/OpenM128-Lib
 - DrMcCoy/STLTally
 - DrMcCoy/darkseed2-tools
 - DrMcCoy/osgameclones
 - DrMcCoy/tg3442_firewall
 - DrMcCoy/vgm-player
 - all

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
