### ISSUE TITLE
Opt-out request for xoreos

### ISSUE THREAD

**Issue by DrMcCoy** [bigcode-project/opt-out-v2#254]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - xoreos/gentoo-overlay
 - xoreos/xoreos-docs
 - xoreos/xoreos-web
 - all

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
