### ISSUE TITLE
Opt-out request for benlevyx

### ISSUE THREAD

**Issue by BenjaminLevyQB** [bigcode-project/opt-out-v2#26]
I request that the following data is removed from The Stack:

 - Commits
 - GitHub issue
 - benlevyx/benjaminlevy.ca
 - benlevyx/benlevyx.github.io
 - benlevyx/veronique-leblanc-cv

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.0.1 of The Stack and all future versions. Also your data was not used for the training of StarCoder2.

[PROCESSED]
