### ISSUE TITLE
Opt-out request for daenney

### ISSUE THREAD

**Issue by daenney** [bigcode-project/opt-out-v2#264]
I request that the following data is removed from The Stack:

 - all

All commits, all repositories, all issues, **all everything**.

I'd also like to point out you've amongst other things included the repository that holds my blog, which is definitely not licensed in a way that permits you to use it in random datasets or for (AI) model training.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
