### ISSUE TITLE
Opt-out request for LinuxUserGD

### ISSUE THREAD

**Issue by LinuxUserGD** [bigcode-project/opt-out-v2#266]
I request that the following data is removed from The Stack:

 - LinuxUserGD/3DPresentation
 - LinuxUserGD/gdev
 - LinuxUserGD/godot-gdscript-ports
 
...

See https://github.com/bigcode-project/opt-out-v2/issues/31

According to https://huggingface.co/spaces/bigcode/in-the-stack

> Yes, there is code from 3 repositories in The Stack:
> LinuxUserGD/3DPresentation
> LinuxUserGD/gdev
> LinuxUserGD/godot-gdscript-ports

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.0.1 of The Stack and all future versions. Also your data was not used for the training of StarCoder2.

[PROCESSED]
