### ISSUE TITLE
Opt-out request for s-ol

### ISSUE THREAD

**Issue by s-ol** [bigcode-project/opt-out-v2#278]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - s-ol/HowDoIOS
 - s-ol/csgo-vscripts
 - s-ol/curv
 - s-ol/docker-urbit
 - s-ol/dotfiles
 - s-ol/dreamer
 - s-ol/gayngine
 - s-ol/git-goodbye
 - s-ol/iynx
 - s-ol/jsshuffle
 - s-ol/klaus
 - s-ol/language-alv
 - s-ol/ld33
 - s-ol/love2d-wheels
 - s-ol/lua-oscpack
 - s-ol/lua-rtmidi
 - s-ol/mmm
 - s-ol/mods
 - s-ol/moonplate
 - s-ol/moonscript-loader
 - s-ol/obs-bmusb
 - s-ol/ofVisualist
 - s-ol/ofxSpout
 - s-ol/openxr-zig
 - s-ol/pReProx
 - s-ol/redirectly
 - s-ol/schedulor
 - s-ol/scopes.vim
 - s-ol/themer
 - s-ol/tinyosc
 - s-ol/torus4d
 - s-ol/up5k
 - s-ol/vcvmods
 - s-ol/vid2flip.ink
 - s-ol/vision-training-kit
 - s-ol/watch-cad
 - all

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
