### ISSUE TITLE
Opt-out request for pietsch

### ISSUE THREAD

**Issue by pietsch** [bigcode-project/opt-out-v2#279]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - pietsch/Catmandu-Wikidata
 - pietsch/Data-Munging
 - pietsch/DataCite-Metadata-Creator-Django
 - pietsch/business--isbn
 - pietsch/elastic-search-installer
 - pietsch/html5slides
 - pietsch/loganalyse
 - pietsch/oval
 - pietsch/rbace
 - pietsch/schema

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
