### ISSUE TITLE
Opt-out request for arnowelzel

### ISSUE THREAD

**Issue by arnowelzel** [bigcode-project/opt-out-v2#282]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - arnowelzel/HL7
 - arnowelzel/Pebble-Casio-WV58DE
 - arnowelzel/PhotoSwipe
 - arnowelzel/arnowelzel.github.io
 - arnowelzel/gitlist
 - arnowelzel/logreader
 - arnowelzel/netdata_ts3_plugin
 - arnowelzel/nextcloud-keeweb
 - arnowelzel/swipebox

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
