### ISSUE TITLE
Opt-out request for yellowsink

### ISSUE THREAD

**Issue by yellowsink** [bigcode-project/opt-out-v2#283]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - yellowsink/AdventOfCode2020
 - yellowsink/AnonDrop
 - yellowsink/FDP
 - yellowsink/FsharpTodoApp
 - yellowsink/LunaCord
 - yellowsink/Microsoft95Keygen
 - yellowsink/NetherConverter
 - yellowsink/PainOfPython
 - yellowsink/PowerSolver
 - yellowsink/ServerColumns-PowercordFix
 - yellowsink/ShuntingYardAlgorithm
 - yellowsink/SmolCord
 - yellowsink/SongLinker
 - yellowsink/SourceMapInstaller
 - yellowsink/Super-Hexagon-SilvaGunner-Edition
 - yellowsink/WacomAreaX11
 - yellowsink/WeatherLine
 - yellowsink/Ytdl-Gui
 - yellowsink/fsharp-discord-bot
 - yellowsink/gofetch
 - yellowsink/hetalia_stitched
 - yellowsink/huffman
 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

oh and by the way
> One of our goals in this project is to give people agency over their source code by letting them decide whether or not it should be used to develop and evaluate machine learning models, as we acknowledge that not all developers may wish to have their data used for that purpose.

if this was true you would be opt IN.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
