### ISSUE TITLE
Opt-out request for krono

### ISSUE THREAD

**Issue by krono** [bigcode-project/opt-out-v2#287]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: 1197440/tobias
 - krono/CrayonsInfo
 - krono/Grease
 - krono/MaterialDesignLite
 - krono/Melanin
 - krono/PySOM
 - krono/RSqueak
 - krono/SIGPLAN.github.io
 - krono/Squeak-Fonts
 - krono/Squeak-Trunk-Deps
 - krono/SqueakJS
 - krono/SqueakSSL-build
 - krono/ZurbSeaside
 - krono/apt-package-whitelist
 - krono/are-we-fast-yet
 - krono/builderCI
 - krono/camtester
 - krono/cctrl
 - krono/cop2016-sidewayscomp
 - krono/dltest
 - krono/dotfiles
 - krono/endianness
 - krono/glass
 - krono/hausbar
 - krono/klein
 - krono/map-keys-on-attach
 - krono/metacello-work
 - krono/nocommand
 - krono/openbsd
 - krono/programming-experience
 - krono/pycket
 - krono/pycket-bench
 - krono/redcard
 - krono/self
 - krono/slapd
 - krono/squeak-ci
 - krono/squeak.org
 - krono/squeaksource3
 - krono/sshfp-to-tinydns
 - krono/tex4ebook
 - krono/tinySelf
 - krono/toggleBluetooth
 - krono/x509hostmatch

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
