### ISSUE TITLE
Opt-in request

### ISSUE THREAD

**Issue by cheld** [bigcode-project/opt-out-v2#29]
Hi,

I checked a few Github organizations/accounts and only some repositories have been included. It seemed that archived projects where included while active projects are not. I did not understand the logic why a project is included or not. Could you plese explain or point me to documentation?

Thanks

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.0.1 of The Stack and all future versions. Also your data was not used for the training of StarCoder2.

[PROCESSED]
