### ISSUE TITLE
Opt-out request for simonrepp

### ISSUE THREAD

**Issue by simonrepp** [bigcode-project/opt-out-v2#291]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - simonrepp/derive-beta
 - simonrepp/dualtitles
 - simonrepp/engst
 - simonrepp/journeyvienna.at
 - simonrepp/playvienna-web
 - simonrepp/playvienna.com
 - simonrepp/rspec-cheki
 - simonrepp/vienneseblend.org

Also, quoting from your site(s):

- "(...) One of our goals in this project is to give people agency over their source code by letting them decide whether or not it should be used to develop and evaluate LLMs"

- "(...) BigCode is an open scientific collaboration working on the responsible development and use of large language models for code"

- "(...) Finally, we require that people who download the dataset agree to use the most recent allowed version in order to incorporate the removal requests."

So your idea of "responsible development" and "giving people agency" is that you first use their work without asking, and if they happen to find out (not from you, of course, you didn't do a thing towards informing me) they can retrospectively request to have their work excluded *in future versions* only? And you honestly think that the bits and pieces of my work that you already released in your old datasets are not going to be used anymore because you nicely ask for that via some toothless agreement?

Honestly, I am left speechless by the impertinence and naiveté of all that. Shame on you for pulling off such a cheap farce.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
