### ISSUE TITLE
Opt-out request for barbeque

### ISSUE THREAD

**Issue by barbeque** [bigcode-project/opt-out-v2#292]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - barbeque/3dodump
 - barbeque/Android-Animation-Demo
 - barbeque/AssertEventIsReceivedNetFramework
 - barbeque/Changelog
 - barbeque/ControlGlobbingSandbox
 - barbeque/DbgShell2
 - barbeque/DropDownButtonBinding
 - barbeque/Http.fs
 - barbeque/Image-Procesing
 - barbeque/Jumpy
 - barbeque/Learning
 - barbeque/LiveChartsPrototype
 - barbeque/Nondisplayable.Extras
 - barbeque/RemotePC8801
 - barbeque/SD2SP2
 - barbeque/SN76489-Tester-Code
 - barbeque/ScrollChart
 - barbeque/SlidingWindowControl
 - barbeque/XYPlot
 - barbeque/ab-budget-survey
 - barbeque/actuallybot
 - barbeque/ajax-status-demo
 - barbeque/aoc-2018
 - barbeque/asyncdemo
 - barbeque/barbeque.github.io
 - barbeque/battery-groups
 - barbeque/book
 - barbeque/calgary-rust.github.io
 - barbeque/capture-winforms-in-wpf-image
 - barbeque/catquery
 - barbeque/chimera
 - barbeque/chip8.rs
 - barbeque/cjsw-scrape
 - barbeque/clean-mibbit-log
 - barbeque/conspire
 - barbeque/demonstrato
 - barbeque/derp-octo-archer
 - barbeque/docker-compose-demo
 - barbeque/dumb-yield-return-tricks
 - barbeque/duplicate-attrs
 - barbeque/easings
 - barbeque/edmunds-long-term-parse
 - barbeque/elm-date-range-picker
 - barbeque/elm-decode-example
 - barbeque/elm-graphics-demo
 - barbeque/elm-onselect
 - barbeque/elm-radio-form
 - barbeque/elm-sortable-table
 - barbeque/elm-tic-tac-toe
 - barbeque/garage-organizer
 - barbeque/gems
 - barbeque/gh60
 - barbeque/gif-slicer
 - barbeque/gl-goodies
 - barbeque/glossy-demos
 - barbeque/go-sdl-demo
 - barbeque/hello-nim-sdl
 - barbeque/hibachi
 - barbeque/highcharts-in-electron
 - barbeque/holiday-compiler
 - barbeque/i-hate-football
 - barbeque/image-feeler
 - barbeque/irssi-log-cleanup
 - barbeque/jQuery-Autocomplete
 - barbeque/johnny-voxville
 - barbeque/kijiji-map
 - barbeque/leadedsolder-kicad
 - barbeque/learning-angular
 - barbeque/learning-d
 - barbeque/learning-gloss
 - barbeque/meane
 - barbeque/my-crow-services
 - barbeque/n88-basic-reference
 - barbeque/nes-rom-expander
 - barbeque/old-mac-facts
 - barbeque/old-subaru-ecudump
 - barbeque/parts-hoarder
 - barbeque/patterns
 - barbeque/pc6001-disk-tools
 - barbeque/pc88-disk-tools
 - barbeque/pc8801mkII-floppy-adapter
 - barbeque/pc8801mkII-vga
 - barbeque/pc98-disk-tools
 - barbeque/pc98-reset
 - barbeque/pc9821-floppy-adapter
 - barbeque/play-random-wav-vbscript
 - barbeque/playing-with-hopac
 - barbeque/poorth
 - barbeque/processing
 - barbeque/pymod
 - barbeque/pyparsing-demos
 - barbeque/python-spy
 - barbeque/quasi88-port
 - barbeque/rails-traps
 - barbeque/raytracer3
 - barbeque/razor-fiddle
 - barbeque/reallyunstuff
 - barbeque/relative-bytetext-search
 - barbeque/render-pipe
 - barbeque/roam
 - barbeque/rusefi
 - barbeque/rust-3d
 - barbeque/rust-inbuilt-traits-demo
 - barbeque/scad
 - barbeque/slack-lunch-pail
 - barbeque/static-image-to-gif
 - barbeque/stm32f0xx-getting-started
 - barbeque/tet.rs
 - barbeque/threejs-experiments
 - barbeque/tire-calculator
 - barbeque/tire-search
 - barbeque/top40
 - barbeque/trying-timex
 - barbeque/tumblr-pipe
 - barbeque/vga-breakout-board
 - barbeque/voxelhose
 - barbeque/well-actually
 - barbeque/x68000-floppy-tools
 - barbeque/xdms

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
