### ISSUE TITLE
Opt-out request for znuh

### ISSUE THREAD

**Issue by znuh** [bigcode-project/opt-out-v2#294]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - znuh/STM32_SkeletonProject
 - znuh/STM32_VCP
 - znuh/at91bootstrap
 - znuh/cb-utils
 - znuh/corona-watch
 - znuh/dpad
 - znuh/ircbot.lua
 - znuh/microbit-exposure-simulator
 - znuh/numcon
 - znuh/rockpi-pcie
 - znuh/sc-util
 - znuh/unsorted
 - znuh/wsapi_basic_auth
 - all existing and future projects/code/etc.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
