### ISSUE TITLE
Opt-out request for mro

### ISSUE THREAD

**Issue by mro** [bigcode-project/opt-out-v2#296]
I request that the following data is removed from The Stack and StackOverflow:

 - all
 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - mro/32c3
 - mro/33c3
 - mro/Denkmaeler
 - mro/FestivalScraper
 - mro/Hanya
 - mro/MSCollectionViewCalendarLayout
 - mro/RedlandDemo
 - mro/ShaarliGo
 - mro/ShaarliHasFun
 - mro/ablopac
 - mro/aladin1001
 - mro/bayern-stoppt-ceta.org
 - mro/census-de-2011-rdf
 - mro/dashpodder
 - mro/datorcurling
 - mro/europarl
 - mro/guide-traunstein-ara
 - mro/iOS-OTA
 - mro/iPhoneDemo-handleOpenURL
 - mro/id3v2
 - mro/jugm-p2d
 - mro/librdf.ios
 - mro/librdf.objc
 - mro/librdf.sqlite
 - mro/megalithicireland2osm
 - mro/piccolo2d.site
 - mro/reiser1895
 - mro/revecter
 - mro/rsync-backup
 - mro/xkcd936

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
