### ISSUE TITLE
Please remove some of my repos

### ISSUE THREAD

**Issue by justinhartman** [bigcode-project/opt-out-v2#3]
I request that the following data is removed from The Stack:

 - justinhartman/howto
 - justinhartman/nix
 - justinhartman/whyaddicted
 
There are many more repos included in the stack but I'm more than happy for the rest to be indexed. It's just these that I'd prefer not included.

Thanks for all the great work you're doing.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.0.1 of The Stack and all future versions. Also your data was not used for the training of StarCoder2.

[PROCESSED]
