### ISSUE TITLE
Opt-out request for dhaine

### ISSUE THREAD

**Issue by dhaine** [bigcode-project/opt-out-v2#308]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - dhaine/CoMaCAN
 - dhaine/ExData_Plotting1
 - dhaine/ExData_Plotting2
 - dhaine/ProgrammingAssignment2
 - dhaine/RepData_PeerAssessment1
 - dhaine/clinicR
 - dhaine/clinicR-meeting
 - dhaine/cohortBias
 - dhaine/coursera-ML-project
 - dhaine/episensr.app
 - dhaine/episensr_shiny
 - dhaine/getting_cleaning_data
 - dhaine/ialsa_gh
 - dhaine/leaflet_project
 - dhaine/milkPrice
 - dhaine/plotBias
 - dhaine/plotly_project
 - dhaine/quovid
 - dhaine/swc-epi-r
 - dhaine/ver

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
