### ISSUE TITLE
Opt-out request for mbarker84

### ISSUE THREAD

**Issue by mbarker84** [bigcode-project/opt-out-v2#315]
I request that the following data is removed from The Stack and StackOverflow:

ALL repositories owned by mbarker84, including:
 - mbarker84/bwcr
 - mbarker84/code-challenge
 - mbarker84/code-class
 - mbarker84/css-irl
 - mbarker84/design-challenge
 - mbarker84/dinosaur-park
 - mbarker84/eleventy-starter
 - mbarker84/fi-prototype-new
 - mbarker84/fi-wireframes
 - mbarker84/filive-hack
 - mbarker84/gamekeeper
 - mbarker84/gamekeeper-2
 - mbarker84/gatsby-first-project
 - mbarker84/gatsby-first-site
 - mbarker84/gatsby-new-project
 - mbarker84/gatsby-starter-netlify-cms
 - mbarker84/grid-demos
 - mbarker84/gulp-portfolio
 - mbarker84/high-light-theme
 - mbarker84/itcss-compass
 - mbarker84/layout-generator
 - mbarker84/london-web
 - mbarker84/my-blog
 - mbarker84/new-craft-project
 - mbarker84/percy-example
 - mbarker84/personal-site
 - mbarker84/polkadot
 - mbarker84/pros-cons
 - mbarker84/react-native-app
 - mbarker84/sawit
 - mbarker84/susy-project
 - mbarker84/talks
 - mbarker84/the-gamekeeper
 - mbarker84/vue-press
 - mbarker84/vue-test

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
