### ISSUE TITLE
Remove my data. This is a disgraceful way to treat people's data.

### ISSUE THREAD

**Issue by patrickgrey** [bigcode-project/opt-out-v2#316]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - patrickgrey/11ty-image-test
 - patrickgrey/2018-clients-finn-grey-fasta
 - patrickgrey/ATC-PHRA-V3
 - patrickgrey/IANS-DEV-FRONT-END-TEST
 - patrickgrey/IANS-DEV-STYLE-GUIDE
 - patrickgrey/IANS-DEV-js-libraries
 - patrickgrey/NMO-ATFCM-AO
 - patrickgrey/NMO-ATFCM-OPS-E
 - patrickgrey/NMO-IFPS-FPL-E
 - patrickgrey/NMO-IFPS-INTRO-E
 - patrickgrey/_video-player
 - patrickgrey/aye-fyne
 - patrickgrey/bowman-stewart
 - patrickgrey/components
 - patrickgrey/ec-ians-2014-ACAS
 - patrickgrey/ec-ians-2014-ACAS-demo
 - patrickgrey/ec-ians-2014-GA-test-01
 - patrickgrey/ec-ians-2014-new-lms-design
 - patrickgrey/ec-ians-2014-new-lms-design-pages
 - patrickgrey/ec-ians-2015-ATC-ACAS
 - patrickgrey/ec-ians-2015-ATC-APDB-remote
 - patrickgrey/ec-ians-2015-url-manager
 - patrickgrey/ians-dev-prototype
 - patrickgrey/large-file-test-01
 - patrickgrey/lsc-netlify-cms
 - patrickgrey/netlify-review-test
 - patrickgrey/patrickgrey
 - patrickgrey/patrickgrey-scss
 - patrickgrey/patrickgrey.1.1
 - patrickgrey/patrickgrey.github.io
 - patrickgrey/pg-2014-test-threejs-demo
 - patrickgrey/pg-2014-test-threejs-gulp
 - patrickgrey/pg-clients-2014-jane-walker-gulp-webapp
 - patrickgrey/pg-clients-2015-paul-clelland
 - patrickgrey/pg-clients-2015-paul-clelland-pages
 - patrickgrey/pg-clients-2015-pg
 - patrickgrey/pg-clients-2015-pg-projects-fartlet
 - patrickgrey/pg-clients-2015-vanquish-medical
 - patrickgrey/pg-clients-2015-vanquish-medical-demo
 - patrickgrey/pg-clients-2016-paul-clelland
 - patrickgrey/pg-clients-2017-be-influence
 - patrickgrey/pg-clients-2017-be-vue-1
 - patrickgrey/pg-clients-2017-plan-for-bikes
 - patrickgrey/pg-learning-2015-treehouse-javascript-ajax-api
 - patrickgrey/pg-learning-2015-treehouse-javascript-gulp
 - patrickgrey/pg-learning-2015-treehouse-javascript-node-api
 - patrickgrey/pg-learning-2015-treehouse-javascript-objects-quiz
 - patrickgrey/pg-learning-2015-treehouse-wordpress-childTheme-1
 - patrickgrey/pg-learning-2015-treehouse-wordpress-theme-gulp
 - patrickgrey/pg-learning-2018-js-es6-web-bos
 - patrickgrey/pg-projects-2016-fartlet
 - patrickgrey/pgTest1
 - patrickgrey/website
 - patrickgrey/youtube-analytics

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
