### ISSUE TITLE
Opt-out request for karschsp

### ISSUE THREAD

**Issue by karschsp** [bigcode-project/opt-out-v2#321]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - karschsp/a1c
 - karschsp/band-names
 - karschsp/beerval
 - karschsp/chili
 - karschsp/d7-release-announcement
 - karschsp/d8-theming-guide
 - karschsp/dkicker
 - karschsp/drumblr
 - karschsp/drumblr_make
 - karschsp/flickr_json
 - karschsp/install-solr
 - karschsp/js30
 - karschsp/magic-8-ball
 - karschsp/php7-centos7-mysql5.6
 - karschsp/quicksetups
 - karschsp/quickstart-vmware
 - karschsp/security-reports
 - karschsp/snapinfraction.com
 - karschsp/stiffarm
 - karschsp/tapwatchr
 - karschsp/travisbox
 - karschsp/vagrant-centos-lamp
 - karschsp/vagrant-lamp
 - karschsp/vagrant-lamp-centos64
 - karschsp/vagrant-ubuntu-lamp
 - karschsp/vagrant-vtx-dev-vm
 - karschsp/vph-lamp

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
