### ISSUE TITLE
Opt-out request for chriskirknielsen

### ISSUE THREAD

**Issue by chriskirknielsen** [bigcode-project/opt-out-v2#325]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: chriskirknielsen
 - chriskirknielsen/2018
 - chriskirknielsen/2020
 - chriskirknielsen/chriskirknielsen
 - chriskirknielsen/gulp-vetocss
 - chriskirknielsen/srcsetsizes
 - chriskirknielsen/vetocss
 - chriskirknielsen/visubezier
 - all

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
