### ISSUE TITLE
Opt-out request for jgarber623

### ISSUE THREAD

**Issue by jgarber623** [bigcode-project/opt-out-v2#326]
I never opted in to this, you chuds.

I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - jgarber623/11ty-website
 - jgarber623/CashCash
 - jgarber623/RadioRadio
 - jgarber623/RouterRouter
 - jgarber623/RouterRouter.git
 - jgarber623/TemplateTemplate
 - jgarber623/absolutely
 - jgarber623/activateActiveX
 - jgarber623/aria-collapsible
 - jgarber623/aria-collapsible.git
 - jgarber623/authenticate.computer
 - jgarber623/authorization-endpoint-ruby
 - jgarber623/barcampdc.org
 - jgarber623/craft-webmention-client
 - jgarber623/delicious-data-convertor
 - jgarber623/devdocs-electron
 - jgarber623/devdocs-fluid-icon
 - jgarber623/device-provisioning
 - jgarber623/docker-forensics-tools
 - jgarber623/docs.getchip.cc
 - jgarber623/dotfiles
 - jgarber623/google-cloud-build-slack-webhook
 - jgarber623/grpc-bookmarks-demo
 - jgarber623/homebrew-cask-fonts
 - jgarber623/homebrew-extras
 - jgarber623/indieweb-endpoints.cc
 - jgarber623/instapaper-fluid-icon
 - jgarber623/jasonandsamara.com
 - jgarber623/javascript-debounce
 - jgarber623/jekyll-netlify-headers
 - jgarber623/jordankasper.com
 - jgarber623/jquery-googleanalytics
 - jgarber623/jquery-modal
 - jgarber623/jquery-selectReplace
 - jgarber623/link-header-parser-ruby
 - jgarber623/micromicro
 - jgarber623/micropub-endpoint-ruby
 - jgarber623/nodejs-playground
 - jgarber623/openstates.org
 - jgarber623/packages-txt
 - jgarber623/redirect-uri-ruby
 - jgarber623/sinatra-param
 - jgarber623/sixtwothree.org
 - jgarber623/spaceholder.cc
 - jgarber623/svgeez
 - jgarber623/token-endpoint-ruby
 - jgarber623/watched-box
 - jgarber623/webmention-cli
 - jgarber623/webmention-endpoint-ruby
 - jgarber623/webmention-verification-ruby
 - jgarber623/webmention.sixtwothree.org
 - jgarber623/windex
 - jgarber623/youtube-fluid-icon

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
