### ISSUE TITLE
Opt-out request for urschrei

### ISSUE THREAD

**Issue by urschrei** [bigcode-project/opt-out-v2#329]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: urschrei
 - urschrei/Ahab
 - urschrei/HH-Expunge
 - urschrei/LSP
 - urschrei/MultiMarkdown
 - urschrei/Plowman
 - urschrei/Shapely
 - urschrei/WIREs
 - urschrei/cleantwitter
 - urschrei/conda-feedstock
 - urschrei/convertbng
 - urschrei/coorblimey
 - urschrei/dipy-wheels
 - urschrei/edit_my_tilde
 - urschrei/flask-bootstrap
 - urschrei/geojson_breakage_example
 - urschrei/geojson_d3
 - urschrei/geojson_example
 - urschrei/greggs
 - urschrei/hansort
 - urschrei/hexagrams
 - urschrei/hexcover
 - urschrei/hovertube
 - urschrei/interviewcode
 - urschrei/jenks
 - urschrei/kaggle-titanic
 - urschrei/linalg
 - urschrei/lonlat_bng
 - urschrei/markdown.tmbundle
 - urschrei/minimal_cross_manylinux
 - urschrei/open-location-code
 - urschrei/openstreetmap-landscape
 - urschrei/patterns
 - urschrei/peg-multimarkdown-latex-support
 - urschrei/polylabel-rs
 - urschrei/polylabel_cmd
 - urschrei/polyline
 - urschrei/polyline-ffi
 - urschrei/pretadata
 - urschrei/proj-sys
 - urschrei/project-euler
 - urschrei/puppet-postgresql
 - urschrei/pypolyline
 - urschrei/python-autopxd
 - urschrei/pyzotero
 - urschrei/rdp
 - urschrei/revere
 - urschrei/router_comparison
 - urschrei/rust-geo
 - urschrei/rust-polyline
 - urschrei/rust_anybar
 - urschrei/rust_fizzbuzz
 - urschrei/rustfest
 - urschrei/simplification
 - urschrei/spatialindex
 - urschrei/spatialindex-sys
 - urschrei/sublime-rust
 - urschrei/tedist
 - urschrei/travis-cargo
 - urschrei/tweetmute
 - urschrei/tweetstodb
 - urschrei/walkindublin
 - urschrei/zonebuilder-rust

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
