### ISSUE TITLE
Opt-out request for dotproto

### ISSUE THREAD

**Issue by dotproto** [bigcode-project/opt-out-v2#331]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: 4959520
 - StackOverflow: Simeon Vincent
 - StackOverflow: simeon-vincent
  - dotproto/beep.ist
 - dotproto/checkers2
 - dotproto/chrome-extensions-samples
 - dotproto/chromium
 - dotproto/dotproto
 - dotproto/dotproto.com
 - dotproto/extension-manifest-converter
 - dotproto/gimli
 - dotproto/gitter-extension-server
 - dotproto/gloggy
 - dotproto/io-sync
 - dotproto/labs
 - dotproto/lookout
 - dotproto/markdown-it-table
 - dotproto/mqtt-js
 - dotproto/ordinary
 - dotproto/partial-template
 - dotproto/paul.kinlan.me
 - dotproto/pong-js
 - dotproto/pong-stream
 - dotproto/promises-talk
 - dotproto/rmurphey
 - dotproto/snap-today
 - dotproto/todo-wc
 - dotproto/twitch-overlay

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
