### ISSUE TITLE
Opt-out request for rottenbytes

### ISSUE THREAD

**Issue by rottenbytes** [bigcode-project/opt-out-v2#332]
I request that the following data is removed from The Stack:

 - Commits
 - GitHub issue
 - rottenbytes/Cuisine
 - rottenbytes/OpenBSD
 - rottenbytes/chef-google
 - rottenbytes/collectd-mod-pf
 - rottenbytes/es-dumper
 - rottenbytes/haproxy.vim
 - rottenbytes/hdfs-cleanup
 - rottenbytes/ledger-app-store-api
 - rottenbytes/marionette-collective
 - rottenbytes/module-nginx
 - rottenbytes/monero-miner
 - rottenbytes/pkg
 - rottenbytes/ruby-ar
 - rottenbytes/ruby-cisco
 - rottenbytes/ruby-deb
 - rottenbytes/scripts
 - rottenbytes/snominator
 - rottenbytes/trappiste
 - rottenbytes/tzindex-exporter
 - rottenbytes/varnishops
 - rottenbytes/visage
 - rottenbytes/vizir

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
