### ISSUE TITLE
Opt-out request for decibyte

### ISSUE THREAD

**Issue by decibyte** [bigcode-project/opt-out-v2#334]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - decibyte/drf-method-example
 - decibyte/kort
 - decibyte/krist.li
 - decibyte/node-bittorrent-tracker
 - decibyte/nunjucks-trans
 - decibyte/sharetodiaspora.github.io
 - decibyte/smsh
 - decibyte/SqueezeMe
 - decibyte/btprox
 - decibyte/cryptoparty.dk
 - decibyte/django-audit-log
 - decibyte/django-auditlog-modeltranslation-testcase
 - decibyte/django-rest-framework
 - decibyte/django-softdelete-testcase

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
