### ISSUE TITLE
Opt-out request for alister

### ISSUE THREAD

**Issue by alister** [bigcode-project/opt-out-v2#338]
I request that the following data is removed from The Stack and StackOverflow:

 - StackOverflow: 6216

 - all
 - all Commits
 - all GitHub issue(s)

 - alister/AzineMailgunWebhooksBundle
 - alister/GovUKFTBundle
 - alister/MrMrsSmith-Calculator
 - alister/PhpMetrics
 - alister/ReservedNamesBundle
 - alister/WirelessLogic-TechTest-2020
 - alister/airport-code-initials
 - alister/alister.github.com
 - alister/alister.github.io
 - alister/babylon-promorules-2020
 - alister/beanstalkd-demo
 - alister/caxton
 - alister/dotfiles
 - alister/expenses-avenger
 - alister/faker-extensions
 - alister/guard-puppet-lint
 - alister/guard-tutorial
 - alister/jobstxt.org
 - alister/oauth2-client-bundle
 - alister/php-dns
 - alister/php-in-london
 - alister/php-redisearch
 - alister/phpstorm-settings
 - alister/puppet-ab
 - alister/puppet-composer
 - alister/puppet-dropbox
 - alister/puppet-sublimetext2
 - alister/rails3-omniauth-multi_tutsplus
 - alister/rector
 - alister/resume
 - alister/station-initials
 - alister/station-initials_v2
 - alister/sublime-phpunitck
 - alister/sublimine2-config
 - alister/sublimine3-config
 - alister/symfony-application-tests
 - alister/todotxt-parser

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
