### ISSUE TITLE
Opt-out request for phacks

### ISSUE THREAD

**Issue by phacks** [bigcode-project/opt-out-v2#342]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: phacks
 - phacks/Earnest
 - phacks/FISH
 - phacks/MMSEProject
 - phacks/MarketplaceEnhanced
 - phacks/TeXaS
 - phacks/TwitterSearch
 - phacks/awesome-new
 - phacks/comment-tu-tappelles-deja
 - phacks/gatsby-code-repl-samples
 - phacks/gatsby-line-highlighting-kitchen-sink
 - phacks/gatsby-memory-leak-repro
 - phacks/gatsby-source-meetup
 - phacks/hackatron
 - phacks/marketplace
 - phacks/nereo-cli
 - phacks/orbit-levels-p5-visualization
 - phacks/phacks.dev
 - phacks/phacks.github.io
 - phacks/rails-view-components-storybook
 - phacks/react-trainings-huge-dataset
 - phacks/showcase-for-discogs
 - phacks/theatres-parisiens
 - phacks/theodo-standards
 - phacks/travisCI-test
 - phacks/uber-cities
 - phacks/vim-zenroom2
 - phacks/vscode-isin-code
 - phacks/welovespeed.com

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
