### ISSUE TITLE
Opt-out request for Armavica

### ISSUE THREAD

**Issue by Armavica** [bigcode-project/opt-out-v2#343]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - Armavica/DiffEqBase.jl
 - Armavica/argmin
 - Armavica/argmin-core
 - Armavica/bebop
 - Armavica/codejam
 - Armavica/coloring
 - Armavica/dwm-patched
 - Armavica/indicatif
 - Armavica/mrsudoku
 - Armavica/newsboat
 - Armavica/pathfinding
 - Armavica/raytracing
 - Armavica/rustlex
 - Armavica/st-patched
 - Armavica/subpar
 - Armavica/tsp
 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
