### ISSUE TITLE
Opt-out request for theAdhocracy

### ISSUE THREAD

**Issue by theAdhocracy** [bigcode-project/opt-out-v2#344]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: theAdhocracy
 - theAdhocracy/craft-redactor-cp
 - theAdhocracy/impromptu
 - theAdhocracy/netlify-plugin-to-all-events
 - theAdhocracy/portfolio
 - theAdhocracy/sb-example
 - theAdhocracy/talentpoint.github.io
 - theAdhocracy/theadhocracy.github.io
 - theAdhocracy/tp-pattern-library

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
