### ISSUE TITLE
Opt-out request for rangermeier

### ISSUE THREAD

**Issue by rangermeier** [bigcode-project/opt-out-v2#349]
I request that the following data is removed from The Stack and StackOverflow:

 - rangermeier/LESS-Format
 - rangermeier/celery-prometheus-exporter
 - rangermeier/celery-redis-sentinel
 - rangermeier/flaskberry
 - rangermeier/perfect-scrollbar
 - rangermeier/php-spellcheck
 - rangermeier/postcss-custom-properties
 - rangermeier/pythonquiz
 - rangermeier/require-css-example
 - rangermeier/subkoord
 - rangermeier/vue-bem-directive
 - rangermeier/vue-pure-lightbox
 - rangermeier/webpack-babel-multi-target-plugin

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
