### ISSUE TITLE
Opt-out request for dmhowcroft

### ISSUE THREAD

**Issue by dmhowcroft** [bigcode-project/opt-out-v2#354]
If you had asked permission beforehand, I would have probably shared most of these repos happily. However, opt-out is not acceptable and I would now like to remove it from your datasets. If you want to use people's data for something other than the original purpose for which they shared it, it's preferable to ask *before* you use it rather than after.

I request that the following data is removed from The Stack and StackOverflow:

 - dmhowcroft/EASL
 - dmhowcroft/RNNLG
 - dmhowcroft/academic-chat
 - dmhowcroft/char-replace
 - dmhowcroft/cnl-surface-realization
 - dmhowcroft/dmhowcroft
 - dmhowcroft/highres
 - dmhowcroft/hpy_utilities
 - dmhowcroft/mcrt
 - dmhowcroft/nbstripout
 - dmhowcroft/ordinal-models
 - dmhowcroft/spellpy

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
