### ISSUE TITLE
Opt-out request for andres-moreno

### ISSUE THREAD

**Issue by andres-moreno** [bigcode-project/opt-out-v2#362]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - andres-moreno/DO-deployment
 - andres-moreno/hy-lang
 - andres-moreno/instaparse-demo
 - andres-moreno/looping-is-recursion
 - andres-moreno/one-function-to-rule-them-all
 - andres-moreno/p-p-p-pokerface
 - andres-moreno/random-quotes
 - andres-moreno/shadow-cljs-demo
 - andres-moreno/sudoku
 - andres-moreno/tribute
 - andres-moreno/twitchtv-demo
 - andres-moreno/weather
 - andres-moreno/wikipedia-viewer

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
