### ISSUE TITLE
Opt-out request for selfawaresoup

### ISSUE THREAD

**Issue by selfawaresoup** [bigcode-project/opt-out-v2#366]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue

 - selfawaresoup/aesthr-infinite-mountains
 - selfawaresoup/configurations
 - selfawaresoup/elasticsearch-intro
 - selfawaresoup/m8di
 - selfawaresoup/mintrahl
 - selfawaresoup/project-euler-problems
 - selfawaresoup/sculpin-node-aws
 - selfawaresoup/twitter-archive-tools

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by selfawaresoup** [comment]
Also, shame on you for making people opt-out in the first place. Opt-in should be the default for this kind of thing.

**Comment by selfawaresoup** [comment]
BTW, some of these repositories do not have licenses at all, meaning their copyright is just my own with no license to use the material for anything.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
