### ISSUE TITLE
Opt-out request for PerfectlyNormal

### ISSUE THREAD

**Issue by PerfectlyNormal** [bigcode-project/opt-out-v2#371]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: PerfectlyNormal
 - PerfectlyNormal/HangFire.SimpleInjector
 - PerfectlyNormal/NJsonApiCore
 - PerfectlyNormal/SolarLogger
 - PerfectlyNormal/Sourcypants
 - PerfectlyNormal/axlsx_rails
 - PerfectlyNormal/batsd
 - PerfectlyNormal/cinch
 - PerfectlyNormal/eastblue-blag
 - PerfectlyNormal/holidays
 - PerfectlyNormal/hypher.js
 - PerfectlyNormal/ideal-tribble
 - PerfectlyNormal/integrity-hooks
 - PerfectlyNormal/jquery-ui-autocomplete-html
 - PerfectlyNormal/literate-computing-machine
 - PerfectlyNormal/local_time
 - PerfectlyNormal/mindset-scorm
 - PerfectlyNormal/mm-nested-attributes
 - PerfectlyNormal/mm-versionable
 - PerfectlyNormal/ng2-signalr-dist
 - PerfectlyNormal/ngx-bootstrap
 - PerfectlyNormal/paperclip
 - PerfectlyNormal/public_suffix_service
 - PerfectlyNormal/report_card
 - PerfectlyNormal/scorm
 - PerfectlyNormal/smailer
 - PerfectlyNormal/softie
 - PerfectlyNormal/sprockets
 - PerfectlyNormal/swf_fu
 - PerfectlyNormal/texrack
 - PerfectlyNormal/tinymce-build
 - PerfectlyNormal/tinymce-rails-imageupload
 - PerfectlyNormal/tinymce-rails-imageupload-demo3
 - PerfectlyNormal/turbo-trouble
 - PerfectlyNormal/wymeditor-rails

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
