### ISSUE TITLE
Opt-out request for cdzombak

### ISSUE THREAD

**Issue by cdzombak** [bigcode-project/opt-out-v2#377]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - cdzombak/10foot6in
 - cdzombak/345
 - cdzombak/BuyVMManager-iOS
 - cdzombak/CAENLabStatus-iOS
 - cdzombak/CDZCLIApplication
 - cdzombak/CDZLinkOpenManager
 - cdzombak/CDZQRScannerThatDoesntSuck
 - cdzombak/CDZUIKitAutoLayoutDebugging
 - cdzombak/ChrisTracker
 - cdzombak/Code-Of-Conduct
 - cdzombak/LightingDatasheets
 - cdzombak/OpenList
 - cdzombak/PhotoData
 - cdzombak/TwitterUserOpenSearch
 - cdzombak/UIKeyboardCoView
 - cdzombak/WindowStack
 - cdzombak/ZeroWidthSpace-iOS
 - cdzombak/a2-foia-rss
 - cdzombak/a2node-starter-heroku
 - cdzombak/abduction
 - cdzombak/aircraft-image-service
 - cdzombak/article-history-thingy
 - cdzombak/bookmark-archiver
 - cdzombak/campfire-adium-message-style
 - cdzombak/cdzombak.github.com
 - cdzombak/chilledcow-scrobbler
 - cdzombak/cidr-tools
 - cdzombak/colab
 - cdzombak/computers.ninja
 - cdzombak/crashcourse
 - cdzombak/cron_ebooks
 - cdzombak/dmx-hardware
 - cdzombak/dns-auditor
 - cdzombak/dns-migrator
 - cdzombak/dotfiles
 - cdzombak/dotfiles-archived
 - cdzombak/explor
 - cdzombak/feedbin-auto-archiver
 - cdzombak/feedbin-stars-to-email
 - cdzombak/frequencyoftoday-generator
 - cdzombak/fuckingtimezones.com
 - cdzombak/garagedoorctl
 - cdzombak/geocode-service
 - cdzombak/gmail-cleaner
 - cdzombak/haskevinfixedmasteryet
 - cdzombak/hosts-timer
 - cdzombak/howyourdaywas
 - cdzombak/hubot-groupme-http
 - cdzombak/instapaper-auto-archiver
 - cdzombak/instapaper-reader
 - cdzombak/kd8vhl.net
 - cdzombak/lampctl
 - cdzombak/lightweight-healthcheck
 - cdzombak/linux-buildscripts
 - cdzombak/little-photo-printer
 - cdzombak/man-asardone
 - cdzombak/mastopurge
 - cdzombak/nativefier-app-template
 - cdzombak/numbers_station_bot
 - cdzombak/nyt-on-abramson-2014-05-14
 - cdzombak/oauth-pin-client
 - cdzombak/omni-applescripts
 - cdzombak/omnifocus-bugs
 - cdzombak/osx-androidemulator-kernelpanics
 - cdzombak/osx-automation
 - cdzombak/osx-kernelpanics
 - cdzombak/osx-services
 - cdzombak/phototools
 - cdzombak/pi-am2301a-influx-logger
 - cdzombak/pi-hts221-bmp280-influx-logger
 - cdzombak/pialarm
 - cdzombak/processing-exercises
 - cdzombak/pyinstapaper
 - cdzombak/qs-public-dropbox-link
 - cdzombak/rdio-availability
 - cdzombak/remove-keybase-finder-favorite
 - cdzombak/restart-slack
 - cdzombak/rsync-match
 - cdzombak/sirens_tweetbot
 - cdzombak/slack-emoji
 - cdzombak/speed-ios
 - cdzombak/ssh-example
 - cdzombak/strikescope
 - cdzombak/string-types-talk
 - cdzombak/swagger-editor-app
 - cdzombak/tab-lists-ext
 - cdzombak/tba
 - cdzombak/thingshub
 - cdzombak/timer
 - cdzombak/tweet
 - cdzombak/twentyfifteen-arborwx-child
 - cdzombak/unshorten
 - cdzombak/urlsession-df-demo
 - cdzombak/vacuum
 - cdzombak/verbosity
 - cdzombak/vimium-ari
 - cdzombak/whereischris
 - cdzombak/xcode_plugin_management
 - cdzombak/zerowidthspace.me
 - cdzombak/zsh-notify

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
