### ISSUE TITLE
Opt-out request for 6a68

### ISSUE THREAD

**Issue by 6a68** [bigcode-project/opt-out-v2#38]
I request that the following data is removed from The Stack:

 - Commits
 - GitHub issue
 - 6a68/6a68.github.com
 - 6a68/6a68.github.io
 - 6a68/buzzies-hydromorphy
 - 6a68/connect-fonts-example
 - 6a68/dat
 - 6a68/explore
 - 6a68/express-simple-p3p
 - 6a68/get-iam-creds
 - 6a68/immutable-js
 - 6a68/meatvox
 - 6a68/quantified-geek-self
 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.0.1 of The Stack and all future versions. Also your data was not used for the training of StarCoder2.

[PROCESSED]
