### ISSUE TITLE
Opt-out request for davidbenque

### ISSUE THREAD

**Issue by davidbenque** [bigcode-project/opt-out-v2#380]
I request that the following data is removed from The Stack and StackOverflow:

 - davidbenque/5MKSE-Exploration
 - davidbenque/CFS-m-
 - davidbenque/Counting-the-Future
 - davidbenque/Entities-of-Interest
 - davidbenque/Researchers-Say
 - davidbenque/trump-stock-tips

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
