### ISSUE TITLE
Opt-out request for keithjgrant

### ISSUE THREAD

**Issue by keithjgrant** [bigcode-project/opt-out-v2#381]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: keithjgrant

all keithjgrant repositories, including:
 - keithjgrant/Micropub
 - keithjgrant/SKB
 - keithjgrant/atom-config
 - keithjgrant/csswg-drafts
 - keithjgrant/dotfiles
 - keithjgrant/grunt-connect-proxy
 - keithjgrant/keithjgrant-com-build
 - keithjgrant/keithjgrant.com
 - keithjgrant/kolache-site
 - keithjgrant/node-format-microformat
 - keithjgrant/omnibear
 - keithjgrant/omnibear-site
 - keithjgrant/patternfly-next
 - keithjgrant/patternfly-react
 - keithjgrant/pivotal-ui
 - keithjgrant/postcss-cpm
 - keithjgrant/postcss-scope
 - keithjgrant/sidecar-2
 - keithjgrant/slides.keithjgrant.com
 - keithjgrant/sokoban-inversion
 - keithjgrant/sublime-text-settings
 - keithjgrant/talk-cfps

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
