### ISSUE TITLE
Opt-out request for heiglandreas

### ISSUE THREAD

**Issue by heiglandreas** [bigcode-project/opt-out-v2#385]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: heiglandreas
 - heiglandreas/CalendarAggregator
 - heiglandreas/ComposerRequireChecker
 - heiglandreas/Converter
 - heiglandreas/DateFormatter
 - heiglandreas/DateFormatterI18n
 - heiglandreas/DateIntervalComparator
 - heiglandreas/GetTogether
 - heiglandreas/HybridAuth
 - heiglandreas/IteratorTrait
 - heiglandreas/JUnitDiff
 - heiglandreas/ModuleManager
 - heiglandreas/NewLanguageFeaturesIUntilPhp56
 - heiglandreas/OrgHeiglAsterisk
 - heiglandreas/OrgHeiglColor
 - heiglandreas/OrgHeiglContact
 - heiglandreas/OrgHeiglDeploy
 - heiglandreas/OrgHeiglFileFinder
 - heiglandreas/OrgHeiglGeolocation
 - heiglandreas/OrgHeiglMailproxy
 - heiglandreas/Org_Heigl_Ghostscript
 - heiglandreas/Org_Heigl_Hyphenator
 - heiglandreas/PdoTimezoneHelper
 - heiglandreas/Psr7_Wrapper
 - heiglandreas/RedLining
 - heiglandreas/ShortURL
 - heiglandreas/TextStatistics
 - heiglandreas/Tokenizer
 - heiglandreas/UTCDateTime
 - heiglandreas/ValueObjects
 - heiglandreas/WebHookHandler
 - heiglandreas/X-Clacks-Overhead
 - heiglandreas/ZendLdapBundle
 - heiglandreas/auth
 - heiglandreas/authLdap
 - heiglandreas/binaryImagemagick
 - heiglandreas/callingallpapers-api
 - heiglandreas/callingallpapers-api_old
 - heiglandreas/callingallpapers-cli
 - heiglandreas/callingallpapers.com
 - heiglandreas/captainhook-rejectpush
 - heiglandreas/captainhook-validateauthor
 - heiglandreas/clock
 - heiglandreas/collector
 - heiglandreas/community-naming
 - heiglandreas/devpackages
 - heiglandreas/devstructure
 - heiglandreas/devstructure-installer
 - heiglandreas/doc-check
 - heiglandreas/doc_callingallpapers_api
 - heiglandreas/error_focus
 - heiglandreas/eventsManagerOptInConfirm
 - heiglandreas/gallery
 - heiglandreas/gamification
 - heiglandreas/geo
 - heiglandreas/geolocation
 - heiglandreas/githook_addtime
 - heiglandreas/gpgsigncode
 - heiglandreas/heiglandreas.github.io
 - heiglandreas/hhvmtest
 - heiglandreas/holidayChecker
 - heiglandreas/htmltopdflib
 - heiglandreas/hybridauthDummyProjectSingleProvider
 - heiglandreas/intl-format
 - heiglandreas/joindinaudit
 - heiglandreas/keep-a-changelog
 - heiglandreas/keyed_archive_parser
 - heiglandreas/keyprinter
 - heiglandreas/ldap2openId
 - heiglandreas/ldapauth
 - heiglandreas/ldapi
 - heiglandreas/lingulab
 - heiglandreas/mancmetfeed2
 - heiglandreas/money
 - heiglandreas/opencfp
 - heiglandreas/org.heigl.daterange
 - heiglandreas/org.heigl.docblockchecker
 - heiglandreas/password
 - heiglandreas/pdf-date-time
 - heiglandreas/pdfexamples
 - heiglandreas/pdftextretriever
 - heiglandreas/pdfunit
 - heiglandreas/pdfwrapper
 - heiglandreas/pharplugin
 - heiglandreas/phergie-logger-plugin
 - heiglandreas/phingdeploy
 - heiglandreas/php-docblock-checker
 - heiglandreas/php-document-store
 - heiglandreas/php-mock
 - heiglandreas/php-resources
 - heiglandreas/phpcs
 - heiglandreas/phpunitstub
 - heiglandreas/phpvideotoolkittest
 - heiglandreas/piwik
 - heiglandreas/plugin-LoginLdap
 - heiglandreas/pronto
 - heiglandreas/rabbitmq-cli-consumer
 - heiglandreas/sapif
 - heiglandreas/searchldap
 - heiglandreas/slackinvitemodule
 - heiglandreas/slides
 - heiglandreas/slim-json-helpers
 - heiglandreas/systems
 - heiglandreas/travisDeployTest
 - heiglandreas/txtextcontrol-reportingcloud-php
 - heiglandreas/ugrm-data
 - heiglandreas/website
 - heiglandreas/wordpressAjaxComments
 - heiglandreas/wordpressWrapper
 - heiglandreas/wp-cli
 - heiglandreas/wp_bootstrap

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
