### ISSUE TITLE
Opt-out request

### ISSUE THREAD

**Issue by stefanbohacek** [bigcode-project/opt-out-v2#386]
I request that the following data is removed from The Stack:

- stefanbohacek/MyColorPalettes
- stefanbohacek/SiteSummary-Dashboard
- stefanbohacek/alignment
- stefanbohacek/dm-retweet-twitterbot
- stefanbohacek/glitch-projects
- stefanbohacek/hello-around-the-world
- stefanbohacek/lma___bot
- stefanbohacek/location-weather-api
- stefanbohacek/makeovermonday
- stefanbohacek/my-twitterbots
- stefanbohacek/node-web-console
- stefanbohacek/nyc-film-permits
- stefanbohacek/princeton-corpus-of-political-emails
- stefanbohacek/redacted
- stefanbohacek/status_withheld
- stefanbohacek/transposer1000
- stefanbohacek/weather-web-app
- stefanbohacek/what_capital
- botwiki/botmakers.org
- botwiki/botwiki-browser-extension
- botwiki/botwiki-wp-theme
- botwiki/fediverse-bot
- botwiki/generative-twitterbot
- botwiki/glitch-fediverse-bot
- botwiki/sidekick
- botwiki/twitterbot
- botwiki/twitterbots
- donation-match-party/donationmatchparty
- any past or future repositories created under the stefanbohacek account or any GitHub organization where I am the owner (you figure that one out)

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
