### ISSUE TITLE
Opt-out request for fhemberger

### ISSUE THREAD

**Issue by fhemberger** [bigcode-project/opt-out-v2#390]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: frederic
 - fhemberger/chrome-prometheus-formatter
 - fhemberger/docker-alpine-glibc
 - fhemberger/dotfiles
 - fhemberger/dssim-bin
 - fhemberger/dude
 - fhemberger/good-influx
 - fhemberger/hapi-jsonapi
 - fhemberger/hapi.docset
 - fhemberger/homebrew-validns
 - fhemberger/imagemin-gm
 - fhemberger/irclog-beautifier
 - fhemberger/joi-browserify
 - fhemberger/jquerypp
 - fhemberger/jssecurity-www
 - fhemberger/letter
 - fhemberger/manifest-validator
 - fhemberger/minica
 - fhemberger/pacman-check-arch-news
 - fhemberger/powwow
 - fhemberger/rpi4_alpine_netboot
 - fhemberger/svnlog
 - fhemberger/talks
 - fhemberger/vagrant-recipes
 - fhemberger/wharfie-alpine-glibc
 - fhemberger/wharfie-jenkins2-demo

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
