### ISSUE TITLE
Opt-out request for AndrewRadev

### ISSUE THREAD

**Issue by AndrewRadev** [bigcode-project/opt-out-v2#395]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: andrew-radev
 - AndrewRadev/BurgasConf-2014
 - AndrewRadev/VarnaConf-2015
 - AndrewRadev/ack.vim
 - AndrewRadev/andrews_nerdtree.vim
 - AndrewRadev/android_notes
 - AndrewRadev/arduino_experiments
 - AndrewRadev/awesome-config
 - AndrewRadev/better_netrw.vim
 - AndrewRadev/bufferize.vim
 - AndrewRadev/cargo-local
 - AndrewRadev/cargo-open
 - AndrewRadev/ctags_reader
 - AndrewRadev/cucumber-vimscript
 - AndrewRadev/daily-sites
 - AndrewRadev/dealwithit.vim
 - AndrewRadev/declarators
 - AndrewRadev/deleft.vim
 - AndrewRadev/discotheque.vim
 - AndrewRadev/do-after
 - AndrewRadev/dot-shell
 - AndrewRadev/dotfiles
 - AndrewRadev/dsf.vim
 - AndrewRadev/edit_archive.vim
 - AndrewRadev/ember_tools.vim
 - AndrewRadev/evans
 - AndrewRadev/gamedev_experiments
 - AndrewRadev/ghundle
 - AndrewRadev/ginitpull.vim
 - AndrewRadev/gnugo.vim
 - AndrewRadev/golang-experiments
 - AndrewRadev/green-cubes
 - AndrewRadev/gtkrs-tutorials
 - AndrewRadev/hello-rusty-web
 - AndrewRadev/id3-image
 - AndrewRadev/id3.vim
 - AndrewRadev/image-processing
 - AndrewRadev/inline_edit.vim
 - AndrewRadev/libmarks
 - AndrewRadev/linediff.vim
 - AndrewRadev/modsearch.vim
 - AndrewRadev/mount_archive
 - AndrewRadev/multichange.vim
 - AndrewRadev/onchange.vim
 - AndrewRadev/paste_middleware.vim
 - AndrewRadev/progressor
 - AndrewRadev/qftools.vim
 - AndrewRadev/quickmd
 - AndrewRadev/quickmd.py
 - AndrewRadev/quickpeek.vim
 - AndrewRadev/randfiles
 - AndrewRadev/rimplement.vim
 - AndrewRadev/rtranslate.vim
 - AndrewRadev/rust-bookworm
 - AndrewRadev/rust-editor
 - AndrewRadev/rust-eliza
 - AndrewRadev/rust-spotiferris
 - AndrewRadev/rust_wrap.vim
 - AndrewRadev/sanesecurityonline
 - AndrewRadev/scripts
 - AndrewRadev/sideways.vim
 - AndrewRadev/simple_bookmarks.vim
 - AndrewRadev/simple_gl
 - AndrewRadev/splitjoin.vim
 - AndrewRadev/subtitles.vim
 - AndrewRadev/switch.vim
 - AndrewRadev/tagalong.vim
 - AndrewRadev/tagfinder.vim
 - AndrewRadev/tty-pager
 - AndrewRadev/undoquit.vim
 - AndrewRadev/uri_mapper
 - AndrewRadev/vim-eco
 - AndrewRadev/vim-golang
 - AndrewRadev/vim-learning-website
 - AndrewRadev/vsnips.vim
 - AndrewRadev/waiting-on-rails
 - AndrewRadev/whitespaste.vim
 - AndrewRadev/writable_search.vim
 - AndrewRadev/xmonad-config
 - AndrewRadev/xruntime.vim
 - AndrewRadev/yankwin.vim
 - all

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
