### ISSUE TITLE
Opt-out request for laenger

### ISSUE THREAD

**Issue by laenger** [bigcode-project/opt-out-v2#396]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: laenger
 - laenger/JobDslGradleProject
 - laenger/SeparatedListAdapter
 - laenger/android-test-issue
 - laenger/claus
 - laenger/maven-releases
 - laenger/together-mvp

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
