### ISSUE TITLE
Opt-out request for Laiot

### ISSUE THREAD

**Issue by Laiot** [bigcode-project/opt-out-v2#397]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - Laiot/Advent-Of-Code-2019
 - Laiot/AoC-2020-py
 - Laiot/AoC19
 - Laiot/CovidProv
 - Laiot/Filum-Ariadnae
 - Laiot/Hydra
 - Laiot/MemoRecBot
 - Laiot/Movie-Barcode-Generator
 - Laiot/Progetto-Reti-Logiche-2018-9
 - Laiot/WAHBot
 - Laiot/Wayfinder

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
