### ISSUE TITLE
Opt-out request for peturdainn

### ISSUE THREAD

**Issue by peturdainn** [bigcode-project/opt-out-v2#398]
I request that the following data is removed from The Stack

 - Commits
 - GitHub issue
  - peturdainn/Longitude
 - peturdainn/PHPTombo
 - peturdainn/Xiaomi-Dafang-Software

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
