### ISSUE TITLE
Opt-out request for jaimerodas

### ISSUE THREAD

**Issue by jaimerodas** [bigcode-project/opt-out-v2#400]
I request that the following data is removed from The Stack and StackOverflow:

 - jaimerodas/attache
 - jaimerodas/busqueda-react
 - jaimerodas/countdown
 - jaimerodas/cuantofaltapara
 - jaimerodas/dineritos
 - jaimerodas/documinion
 - jaimerodas/dotfiles
 - jaimerodas/examen-talento
 - jaimerodas/fechitas
 - jaimerodas/guarda-facturas
 - jaimerodas/jaimerodas.github.io
 - jaimerodas/prueba-expediente
 - jaimerodas/quinielitas
 - jaimerodas/quinielitas-viejo
 - jaimerodas/scraper_talento
 - jaimerodas/uinames

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
