### ISSUE TITLE
Opt-out request for emerssso

### ISSUE THREAD

**Issue by emerssso** [bigcode-project/opt-out-v2#401]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: Emerssso
 - emerssso/Cognitive-Speech-STT-Android
 - emerssso/Hats
 - emerssso/HelloJKF
 - emerssso/KnitMath
 - emerssso/SRBase
 - emerssso/StrictExtras
 - emerssso/angular_tour_of_heroes
 - emerssso/blue_rose_character_creator
 - emerssso/gs-extensions-winboot
 - emerssso/hedgebase
 - emerssso/hedgelog
 - emerssso/hedgelog-functions
 - emerssso/livetweet

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
