### ISSUE TITLE
Opt-out request for benboecker

### ISSUE THREAD

**Issue by benboecker** [bigcode-project/opt-out-v2#403]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - benboecker/Android-ListView-Example
 - benboecker/AspectImageView
 - benboecker/CachedDateFormatter
 - benboecker/CoreDataStack
 - benboecker/CoreGraph
 - benboecker/EmptyStateController
 - benboecker/Inject
 - benboecker/Logger
 - benboecker/ben-boecker.de
 - benboecker/css-numeric-variants
 - benboecker/wind

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
