### ISSUE TITLE
Opt-out request for jackhistorynorton

### ISSUE THREAD

**Issue by jackhistorynorton** [bigcode-project/opt-out-v2#409]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - jackhistorynorton/1101_fa21
 - jackhistorynorton/1102_fa21
 - jackhistorynorton/Minnesota-History
 - jackhistorynorton/east_asian_history
 - jackhistorynorton/history_1101
 - jackhistorynorton/history_1102
 - jackhistorynorton/world_history_1
 - jackhistorynorton/world_history_1_fall_20
 - jackhistorynorton/world_history_2
 - jackhistorynorton/world_history_2_fall_19
 - jackhistorynorton/world_history_2_fall_20

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
