### ISSUE TITLE
Opt-out request

### ISSUE THREAD

**Issue by ThainBBdL** [bigcode-project/opt-out-v2#413]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - ThainBBdL/ThainBBdL
 - ThainBBdL/guitar-tuner
 - ThainBBdL/polyfill-service

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
