### ISSUE TITLE
Opt-out request for bennylope

### ISSUE THREAD

**Issue by bennylope** [bigcode-project/opt-out-v2#415]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: bennylope
 - bennylope/activecampaign
 - bennylope/async-django
 - bennylope/batlog
 - bennylope/bennylope.github.com
 - bennylope/census
 - bennylope/ciafactbook
 - bennylope/commitme
 - bennylope/cookiecutter-django
 - bennylope/cookiecutter-djangopackage
 - bennylope/datasciencecoursera
 - bennylope/dj-form-mapper
 - bennylope/dj-geocoding
 - bennylope/dj-wordpress
 - bennylope/django-addendum
 - bennylope/django-ajaxify
 - bennylope/django-alfresco
 - bennylope/django-anchor
 - bennylope/django-contact-recipients
 - bennylope/django-cumulus
 - bennylope/django-extensions
 - bennylope/django-filer-gallery
 - bennylope/django-firstclass
 - bennylope/django-icase
 - bennylope/django-lokoj
 - bennylope/django-organizations
 - bennylope/django-richenum
 - bennylope/django-scaffold
 - bennylope/django-shop
 - bennylope/django-simple-auth
 - bennylope/django-site-broadcasts
 - bennylope/django-site-contacts
 - bennylope/django-taggit-labels
 - bennylope/django_ci_project
 - bennylope/drain.rb
 - bennylope/elm-csv
 - bennylope/fdecimal
 - bennylope/flake8-codeclimate
 - bennylope/flake8-csv
 - bennylope/garland
 - bennylope/geneva-data
 - bennylope/geocodio-php
 - bennylope/houston
 - bennylope/janus-config
 - bennylope/janus-customizer
 - bennylope/jupyter-python3-functional
 - bennylope/magwitch
 - bennylope/memcachier-docs
 - bennylope/mock-django
 - bennylope/premium-select
 - bennylope/pydiscourse
 - bennylope/pygeocodio
 - bennylope/smartystreets.py
 - bennylope/standalone-blog-app
 - bennylope/string-distance-exercises
 - bennylope/stripe-testing
 - bennylope/studieshaveshown.org
 - bennylope/sysenv
 - bennylope/woopra.py

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
