### ISSUE TITLE
Opt-out request for kimadactyl

### ISSUE THREAD

**Issue by kimadactyl** [bigcode-project/opt-out-v2#416]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - kimadactyl/HulmeHistory
 - kimadactyl/afmcr
 - kimadactyl/alliscalm.net
 - kimadactyl/christopherpurves
 - kimadactyl/dearfriend-presentation
 - kimadactyl/dearfriend-rails
 - kimadactyl/dearfriend.org.uk
 - kimadactyl/flimnite
 - kimadactyl/foley
 - kimadactyl/gfsc
 - kimadactyl/gifGallery-server
 - kimadactyl/gofg-db
 - kimadactyl/homelessness-presentation
 - kimadactyl/initiative-consulting
 - kimadactyl/janefoale_static
 - kimadactyl/kate-foale
 - kimadactyl/katescuttings
 - kimadactyl/lgbt-helpline-scotland
 - kimadactyl/lgbthistoryfestival
 - kimadactyl/mafn
 - kimadactyl/mafn-db
 - kimadactyl/msaphase
 - kimadactyl/thesis
 - kimadactyl/touchdown
 - kimadactyl/vennerator

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
