### ISSUE TITLE
Opt-out request for oerdnj

### ISSUE THREAD

**Issue by oerdnj** [bigcode-project/opt-out-v2#417]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: oerdnj
 - oerdnj/451Reporter
 - oerdnj/HohhaDynamicXOR
 - oerdnj/bp
 - oerdnj/ceske-sluzby
 - oerdnj/cyrus-imapd
 - oerdnj/deb.sury.org
 - oerdnj/dns-oarc-keysigning
 - oerdnj/dns-root-data
 - oerdnj/dns-violations
 - oerdnj/dnsoquic
 - oerdnj/draft-deploying-dnssec-crypto-algs
 - oerdnj/draft-ietf-dnsop-algorithm-update
 - oerdnj/draft-ietf-dnssec-algorithm-update
 - oerdnj/draft-ixfr-only
 - oerdnj/draft-sury-dnsop-cname-plus-dname
 - oerdnj/draft-sury-dnsop-deprecate-obsolete-resource-records
 - oerdnj/draft-sury-dnssec-nsec3-siphash
 - oerdnj/draft-sury-siphash-for-tsig
 - oerdnj/eet-metrics
 - oerdnj/haproxy-mod-vhost-ldap
 - oerdnj/letsencrypt-misc
 - oerdnj/lpeg_patterns
 - oerdnj/luajit
 - oerdnj/mmdblua
 - oerdnj/mod-vhost-ldap
 - oerdnj/oerdnj.github.io
 - oerdnj/omniauth-mojeid-discourse
 - oerdnj/pkg-dnsruby
 - oerdnj/pkg-php
 - oerdnj/rapache
 - oerdnj/rfc2845bis
 - oerdnj/sablona-tex-ff-uk
 - oerdnj/sassphp
 - oerdnj/serve-stale
 - oerdnj/tidy-html5
 - oerdnj/xml2rfc

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
