### ISSUE TITLE
Opt-out request for mae829

### ISSUE THREAD

**Issue by mae829** [bigcode-project/opt-out-v2#418]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - mae829/BleuStudio
 - mae829/Culturati2015
 - mae829/FamilyStyleBuffet
 - mae829/Ill-literate
 - mae829/Instabooth
 - mae829/MochilasoTheme
 - mae829/NewRiverCommittee
 - mae829/google-sheets-map
 - mae829/magazine-cover-generator
 - mae829/restaurants-map
 - mae829/url-shortener
 - mae829/github-actions-for-packages

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
