### ISSUE TITLE
Opt-out request for zkat

### ISSUE THREAD

**Issue by zkat** [bigcode-project/opt-out-v2#420]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - zkat/DWG.Directories
 - zkat/UPPERCASE-NPM
 - zkat/ama
 - zkat/ariadne
 - zkat/auditmated
 - zkat/bacon-browser
 - zkat/big-brain
 - zkat/cacache
 - zkat/cacache-rs
 - zkat/chatoid
 - zkat/chownr-rs
 - zkat/cipm
 - zkat/cl-devil
 - zkat/cl-event2
 - zkat/cl-ffmpeg
 - zkat/cl-form
 - zkat/cl-openal
 - zkat/clap
 - zkat/clutter
 - zkat/clutterscript
 - zkat/common-brick
 - zkat/conserv
 - zkat/destealify
 - zkat/dist-upgrade
 - zkat/doitlive
 - zkat/dynvar
 - zkat/electron-collider
 - zkat/engine-q
 - zkat/esm
 - zkat/exa
 - zkat/facile
 - zkat/fairyfloss
 - zkat/figgy-pudding
 - zkat/fl-protocols
 - zkat/friendfavor
 - zkat/genderrolls
 - zkat/genfun
 - zkat/git-build-demo
 - zkat/graceful-request
 - zkat/happy-birthday
 - zkat/ink-select-input
 - zkat/ink-text-input
 - zkat/json-parse-better-errors
 - zkat/kdl-net
 - zkat/logloc
 - zkat/make-fetch-happen
 - zkat/marked-man
 - zkat/maybe-hugs
 - zkat/misc
 - zkat/mona
 - zkat/mona-combinators
 - zkat/mona-csv
 - zkat/mona-date
 - zkat/mona-internals
 - zkat/mona-json
 - zkat/mona-parse
 - zkat/mona-parse-stream
 - zkat/mona-strings
 - zkat/moonprismpower
 - zkat/my-precious
 - zkat/node-otp
 - zkat/normally-open-closed
 - zkat/npm-pick-manifest
 - zkat/nu_scripts
 - zkat/okimdone
 - zkat/packageshadingprototype
 - zkat/pacote
 - zkat/pattycake
 - zkat/presentations
 - zkat/project-system
 - zkat/proposal-as-patterns
 - zkat/proposal-collection-literals
 - zkat/proposal-first-class-protocols
 - zkat/proto
 - zkat/protocols
 - zkat/protoduck
 - zkat/provide-any
 - zkat/qdd
 - zkat/rls-vscode
 - zkat/shortening
 - zkat/ssri
 - zkat/ssri-rs
 - zkat/storychat
 - zkat/sykosomatic
 - zkat/talks
 - zkat/test
 - zkat/testing-nuget-setup
 - zkat/thisdiagnostic
 - zkat/tswrp
 - zkat/tswrp-relationship-map
 - zkat/turron
 - zkat/until-it-dies
 - zkat/yashmup

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
