### ISSUE TITLE
Opt-out request for Oprax

### ISSUE THREAD

**Issue by Oprax** [bigcode-project/opt-out-v2#421]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - Oprax/Javaquarium
 - Oprax/ansible-deployment
 - Oprax/backup-utils
 - Oprax/bag-innovation
 - Oprax/calendar-site
 - Oprax/dnscontrol
 - Oprax/docker-ansible
 - Oprax/docker-debian
 - Oprax/docker-gcc
 - Oprax/docker-logstash-oracle
 - Oprax/docker-php
 - Oprax/docker-python
 - Oprax/dotfiles
 - Oprax/paintux
 - Oprax/pidom
 - Oprax/projet-web
 - Oprax/sampling
 - Oprax/simplex
 - Oprax/site-isn
 - Oprax/whohostwho
 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
