### ISSUE TITLE
Opt-out request for shawngraham

### ISSUE THREAD

**Issue by shawngraham** [bigcode-project/opt-out-v2#425]
I request that the following data is removed from The Stack

 - Commits
 - GitHub issue
 - shawngraham/101atron
 - shawngraham/3907o-landing
 - shawngraham/5702w-source-md-files
 - shawngraham/5702w-w18
 - shawngraham/Analog-Simulation--Shit-Like-That.
 - shawngraham/CCAD
 - shawngraham/Fleshing-out-the-Bones
 - shawngraham/Gaze
 - shawngraham/Handwriting-Parsing-App
 - shawngraham/Instagram-scraping
 - shawngraham/Ms.Coll.851-Diary-of-a-trip-on-the-Nile-River
 - shawngraham/MyWiki
 - shawngraham/Open-Context-Site-Diaries
 - shawngraham/RunSFM
 - shawngraham/ScriptScrape-Twitter
 - shawngraham/WAHR
 - shawngraham/abm3
 - shawngraham/abmtoys
 - shawngraham/academic-kickstart
 - shawngraham/academic-kickstart-3
 - shawngraham/academic-kickstart-4
 - shawngraham/aha2015-tweets
 - shawngraham/anasazi
 - shawngraham/archae-topic-models
 - shawngraham/archstopmo
 - shawngraham/bad-archaeology
 - shawngraham/binder-etudier
 - shawngraham/blerg
 - shawngraham/bm-data
 - shawngraham/book
 - shawngraham/cdh2020
 - shawngraham/chi
 - shawngraham/chi-lab
 - shawngraham/classeur-downloader
 - shawngraham/classifier-experiments
 - shawngraham/coro-hall-test
 - shawngraham/crane-experiments
 - shawngraham/cv-generator
 - shawngraham/dataminingjournals
 - shawngraham/demo
 - shawngraham/dhcu-notebook-example
 - shawngraham/dhcu-source
 - shawngraham/dhcu-teaching
 - shawngraham/dhmuse
 - shawngraham/dhmuse-21-student-work
 - shawngraham/dhmuse-notebooks
 - shawngraham/dhsi2016
 - shawngraham/digh5000
 - shawngraham/digh5000-notes
 - shawngraham/digitalarchaeology-test
 - shawngraham/digitalpedagogy
 - shawngraham/discoursesoftheft
 - shawngraham/dry-run-pykwiki
 - shawngraham/earls
 - shawngraham/elegy-for-George-Floyd
 - shawngraham/etudier
 - shawngraham/example-faillog-hist3814
 - shawngraham/example-for-hiryon
 - shawngraham/exercise
 - shawngraham/exposetest
 - shawngraham/ffmprovisr
 - shawngraham/fonseca-bust-storymap
 - shawngraham/fysm1405a
 - shawngraham/gitMuseum
 - shawngraham/gollum-experiment
 - shawngraham/graham-for-keywords
 - shawngraham/gravestone-rideau
 - shawngraham/hello-world
 - shawngraham/highschoolhistorygaming
 - shawngraham/hist3814-manual
 - shawngraham/hist3814-summer2017
 - shawngraham/hist3907b-hq
 - shawngraham/hist3908
 - shawngraham/hist4916
 - shawngraham/hist5702x
 - shawngraham/hist5702x-w2014
 - shawngraham/hist5706
 - shawngraham/historicalfriction
 - shawngraham/hj2017
 - shawngraham/hypothesisr
 - shawngraham/iSchool-Workshop
 - shawngraham/image-recognition
 - shawngraham/image-sonification
 - shawngraham/insta-dead-article
 - shawngraham/jupyter-notebooks
 - shawngraham/kg
 - shawngraham/macroscope-data
 - shawngraham/mdlee12.github.com
 - shawngraham/minecraft
 - shawngraham/nanohistory
 - shawngraham/netlogo
 - shawngraham/notebook
 - shawngraham/notebooks
 - shawngraham/obsidian-digiarch-lab-notebook
 - shawngraham/ocdsb
 - shawngraham/odate-draft
 - shawngraham/open-drafts
 - shawngraham/open-notebook-source-md
 - shawngraham/organigram
 - shawngraham/presentations
 - shawngraham/pykwiki
 - shawngraham/random-cstm
 - shawngraham/random-models
 - shawngraham/renpy-projects
 - shawngraham/ricescheduler
 - shawngraham/roman-amphitheaters
 - shawngraham/saa2015
 - shawngraham/saa2017tweets
 - shawngraham/scriv-opennotes
 - shawngraham/shawngraham.github.io
 - shawngraham/some-api-notebooks
 - shawngraham/spatialarchaeology
 - shawngraham/stanford-tmt-scripts
 - shawngraham/taph
 - shawngraham/tb-cuvisit
 - shawngraham/testingstuff
 - shawngraham/twarc
 - shawngraham/twine-stuff
 - shawngraham/whatisdigitalhumanities
 - shawngraham/wordvectors

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
