### ISSUE TITLE
Opt-out request for gribnoysup

### ISSUE THREAD

**Issue by gribnoysup** [bigcode-project/opt-out-v2#430]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - gribnoysup/angular-todo-app
 - gribnoysup/aoc2020
 - gribnoysup/bday-present
 - gribnoysup/bs-search-and-generator
 - gribnoysup/changeiq-cli
 - gribnoysup/create-microbundle-module
 - gribnoysup/critters
 - gribnoysup/diy-dog-search
 - gribnoysup/game-of-life-but-no-ifs
 - gribnoysup/googleme
 - gribnoysup/gorg
 - gribnoysup/gribnoysup.github.io
 - gribnoysup/html-webpack-inline-source-plugin-with-custom-sourcemap
 - gribnoysup/image-saver
 - gribnoysup/jpng.svg
 - gribnoysup/micro-react-ssr-boilerplate
 - gribnoysup/nfield-api
 - gribnoysup/nfield-data-downloader
 - gribnoysup/node-mongodb-native
 - gribnoysup/planogram-layout-maker
 - gribnoysup/razzle-microapp-experiment
 - gribnoysup/react-yandex-maps
 - gribnoysup/rollup
 - gribnoysup/server-util
 - gribnoysup/setup-polly-jest
 - gribnoysup/single-page-application-optimization-tips
 - gribnoysup/steady
 - gribnoysup/vue-plum-ui
 - gribnoysup/web-performance-playground
 - gribnoysup/webpack-dev-server
 - gribnoysup/webpack-perf-output
 - gribnoysup/wunderbar

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
