### ISSUE TITLE
Opt-out request for onebrightlight (former handle)

### ISSUE THREAD

**Issue by furioursus** [bigcode-project/opt-out-v2#443]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: user:1763544
 - onebrightlight/craft
 - onebrightlight/craft-reroute
 - onebrightlight/credit-card-amortization
 - onebrightlight/crush
 - onebrightlight/jsd4
 - onebrightlight/maven
 - onebrightlight/mykal.codes
 - onebrightlight/oblheadless
 - onebrightlight/onebrightlight
 - onebrightlight/onebrightlight-craft3
 - onebrightlight/rinconchiro
 - onebrightlight/sfgov-exercise
 - onebrightlight/theirwords
 - onebrightlight/theirwords.online
 - onebrightlight/vs-code-twig-for-craft-2

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
