### ISSUE TITLE
Opt-out request for equill

### ISSUE THREAD

**Issue by equill** [bigcode-project/opt-out-v2#449]
I demand that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - equill/cl-4store
 - equill/datadog-snmp
 - equill/docker-sbcl
 - equill/dotvim
 - equill/equill.github.io
 - equill/ipaddress
 - equill/mark-and-render
 - equill/neo4cl
 - equill/netdescribe
 - equill/ox
 - equill/ox-4store
 - equill/rg-graphql
 - equill/rg-node

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

I never consented to its inclusion. Opt-out is *not* consent.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
