### ISSUE TITLE
Opt-out request for BenDMyers

### ISSUE THREAD

**Issue by BenDMyers** [bigcode-project/opt-out-v2#450]
I request that the following data is removed from The Stack and StackOverflow:

- all
 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - BenDMyers/ARIA_Toggle_Example
 - BenDMyers/Advanced_React_and_Redux
 - BenDMyers/AdventOfCode2016
 - BenDMyers/Advent_Of_Code_2020
 - BenDMyers/Alt_Hover
 - BenDMyers/Basic_React_Calendar
 - BenDMyers/BefungeVisualizer
 - BenDMyers/Blog_Redesign_2020
 - BenDMyers/Cidercade_OnTap_Alerter
 - BenDMyers/DevMatch
 - BenDMyers/ElectronCodelab
 - BenDMyers/Electron_for_Desktop_Apps
 - BenDMyers/FinishLine
 - BenDMyers/Go_The_Complete_Developers_Guide
 - BenDMyers/Merge
 - BenDMyers/Modern_React_With_Redux
 - BenDMyers/Movie_List
 - BenDMyers/Movie_List_API
 - BenDMyers/Movie_List_Admin_API
 - BenDMyers/Movie_List_Admin_UI
 - BenDMyers/Neon_Clock
 - BenDMyers/ReactJSDallas_Beginners_Guide_to_Eleventy
 - BenDMyers/React_Todos
 - BenDMyers/Simple_Ink_Starter
 - BenDMyers/Soundboard
 - BenDMyers/a11y.surf
 - BenDMyers/blog
 - BenDMyers/community-calendar
 - BenDMyers/cs4153
 - BenDMyers/cs4183
 - BenDMyers/css-art
 - BenDMyers/d638
 - BenDMyers/eleventy-plugin-twitch-chat
 - BenDMyers/gatsby-ecommerce-site
 - BenDMyers/generate-comparators
 - BenDMyers/portfolio

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
