### ISSUE TITLE
Opt-out request for pingevt

### ISSUE THREAD

**Issue by pingevt** [bigcode-project/opt-out-v2#452]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - pingevt/360-inspections
 - pingevt/ad-eng-cms
 - pingevt/bowlmaster
 - pingevt/cci-gulp-test
 - pingevt/church
 - pingevt/d8-missing-parts
 - pingevt/five-min-site
 - pingevt/givingreport
 - pingevt/pai.works
 - pingevt/pingevt.github.io
 - pingevt/quartermaster
 - pingevt/werky

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
