### ISSUE TITLE
Opt-out request for Dr-G

### ISSUE THREAD

**Issue by Dr-G** [bigcode-project/opt-out-v2#455]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - Dr-G/.github
 - Dr-G/.github-1
 - Dr-G/.github-2
 - Dr-G/Dr-G.github.io
 - Dr-G/HARK
 - Dr-G/learning-python
 - Dr-G/pymc3
 - all

_Note_: Opt-out is a crummy approach to this.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
