### ISSUE TITLE
Opt-out request for zanchey

### ISSUE THREAD

**Issue by zanchey** [bigcode-project/opt-out-v2#458]
I require that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: Zanchey
 - zanchey/homebrew-core
 - zanchey/mbsgit
 - zanchey/pbsqlite
 - zanchey/python-zeep
 - all

You should know better.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
