### ISSUE TITLE
Opt-out request for gekitsu

### ISSUE THREAD

**Issue by gekitsu** [bigcode-project/opt-out-v2#465]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - gekitsu/vim-logo-redesign

Furthermore, I would like to note that merely providing an opt-out is not consensual practise. Consent is *only* given deliberately, therefore it mandates asking for it beforehand. This is entirely disgraceful.

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
