### ISSUE TITLE
Opt-out request for arayebrown

### ISSUE THREAD

**Issue by arayebrown** [bigcode-project/opt-out-v2#466]
I request that the following data is removed from The Stack and StackOverflow:

 - arayebrown/dotfiles
 - arayebrown/ember-simple-auth
 - arayebrown/planner
 - arayebrown/ui-goodies

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
