### ISSUE TITLE
Opt-out request for pief

### ISSUE THREAD

**Issue by pief** [bigcode-project/opt-out-v2#473]
I request that the following data is removed from The Stack:

 - Commits
 - GitHub issue
 - pief/PiStripe_uHAT
 - pief/bahnhofsfotos
 - pief/cfgmgmtcamp.eu
 - pief/docker
 - pief/docker-roundcube
 - pief/seaslic
 - pief/silverstripe-homepagefordomain
 - pief/zwave

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
