### ISSUE TITLE
Remove my data from The Stack

### ISSUE THREAD

**Issue by aawood** [bigcode-project/opt-out-v2#477]
I request that the following data is removed from The Stack:

 - Commits
 - GitHub issue
 - aawood/T2D-behavior-tut
 - aawood/T2D-tutorial
 - aawood/iso
 - aawood/krawl
 - aawood/torque2d
 
...

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
