### ISSUE TITLE
Opt-out request for choan

### ISSUE THREAD

**Issue by choan** [bigcode-project/opt-out-v2#480]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - choan/abc.tmbundle
 - choan/cap_social_buttons
 - choan/choan.tmbundle
 - choan/compass-cssfault
 - choan/epubcheck
 - choan/fretboards
 - choan/jquery.filterprojects
 - choan/js_dom_serializer
 - choan/jshoulda-tmbundle
 - choan/lilypond.tmbundle
 - choan/lilypond_generators
 - choan/newjs
 - choan/note_frequencies
 - choan/s7
 - choan/sass_js
 - choan/string_tensions
 - choan/sugartest.tmbundle
 - choan/wagon
 - choan/xslt-tmbundle

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
