### ISSUE TITLE
Opt-out request for cleentfaar

### ISSUE THREAD

**Issue by cleentfaar** [bigcode-project/opt-out-v2#484]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - cleentfaar/CLArchiverBundle
 - cleentfaar/CLConanConsoleBundle
 - cleentfaar/CLDecoratorBundle
 - cleentfaar/CLDocDataOrderApiBundle
 - cleentfaar/CLMailerBundle
 - cleentfaar/CLSlackBundle
 - cleentfaar/CLTriggerBundle
 - cleentfaar/CilexFilesystemServiceProvider
 - cleentfaar/CleentfaarCIBundle
 - cleentfaar/CleentfaarSelect2Bundle
 - cleentfaar/CleentfaarSudokuBundle
 - cleentfaar/CleentfaarThreeJsBundle
 - cleentfaar/FMIoBundle
 - cleentfaar/Faker
 - cleentfaar/PKCommandExtraBundle
 - cleentfaar/TreeHouseBaseApiBundle
 - cleentfaar/TreeHouseCacheBundle
 - cleentfaar/address-parser
 - cleentfaar/archivist
 - cleentfaar/buckaroo-bundle
 - cleentfaar/conveyor
 - cleentfaar/decorator
 - cleentfaar/devr
 - cleentfaar/docdata-orderapi
 - cleentfaar/doctrine-extensions
 - cleentfaar/dotfiles
 - cleentfaar/high-quality-bundles-project
 - cleentfaar/mailer-bundle
 - cleentfaar/mailer-swiftmailer
 - cleentfaar/nicer
 - cleentfaar/pharly
 - cleentfaar/php-sdk
 - cleentfaar/progen-worker-base
 - cleentfaar/prototype-bundle
 - cleentfaar/prototype-library
 - cleentfaar/queue-bundle
 - cleentfaar/resolver
 - cleentfaar/simplr
 - cleentfaar/simplr-core
 - cleentfaar/standards
 - cleentfaar/statistico-bundle
 - cleentfaar/table
 - cleentfaar/table-renderer-ascii
 - cleentfaar/tissue
 - cleentfaar/windmill

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
