### ISSUE TITLE
Opt-out request for pimterry

### ISSUE THREAD

**Issue by pimterry** [bigcode-project/opt-out-v2#487]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: https://stackoverflow.com/users/68051/tim-perry
 - pimterry/50plus2
 - pimterry/And-now-for-something-completely-different
 - pimterry/Building-resilient-infrastructure-with-CouchDB
 - pimterry/Cloud-Everything
 - pimterry/How-to-build-a-database
 - pimterry/Intro-to-open-source
 - pimterry/JSErrorCollector.NET
 - pimterry/JavaScript-Is-Going-Places
 - pimterry/Metawear-SampleAndroidApp
 - pimterry/React-Todo-Demo
 - pimterry/Rust-101
 - pimterry/TetheringStatusMonitor
 - pimterry/Web-components-and-microservices-are-the-same-thing
 - pimterry/What-not-to-do-with-databases
 - pimterry/What-the-hell-are-web-components
 - pimterry/Your-Build-Smells
 - pimterry/Your-Web-Stack-Would-Betray-You-In-An-Instant
 - pimterry/alephant-logger
 - pimterry/arduino-demos
 - pimterry/balloons
 - pimterry/bespoke-bullets
 - pimterry/busmearound
 - pimterry/chai-fetch
 - pimterry/chai-style
 - pimterry/chutzpah
 - pimterry/comparably
 - pimterry/concomitant
 - pimterry/dev-bot
 - pimterry/dev-bot-tool
 - pimterry/docker-heroku-python3
 - pimterry/docker-node-karma-selenium
 - pimterry/docker-selenium-chrome-ftp
 - pimterry/dropbox-ignore
 - pimterry/ember-document-title
 - pimterry/fetch-readablestream
 - pimterry/git-confirm
 - pimterry/github-org-feed-page
 - pimterry/grunt-coveralls
 - pimterry/hackference-karaoke
 - pimterry/hackthepolice-2013
 - pimterry/helpmegive
 - pimterry/heroku-sinatra-project-template
 - pimterry/hipchat-filterer
 - pimterry/http-extensions
 - pimterry/http-server-mock
 - pimterry/instagram-to-journey
 - pimterry/intro-to-typescript
 - pimterry/jenkins-hipchat-plugin
 - pimterry/jest
 - pimterry/js-libp2p-websockets
 - pimterry/js-test-runner
 - pimterry/knockout-bindings-autorequire
 - pimterry/knockout-dependency-graph
 - pimterry/lambda-git
 - pimterry/loglevel
 - pimterry/mepage
 - pimterry/metawear-accelerometer
 - pimterry/metawear-repl
 - pimterry/module-structure-graph
 - pimterry/multistage-demos
 - pimterry/national-hack-the-government-2014
 - pimterry/netty-website
 - pimterry/node-tls-crash
 - pimterry/notes
 - pimterry/openapi-directory
 - pimterry/personal-site-feed
 - pimterry/phonegap-build-plugin-test
 - pimterry/photo-frame
 - pimterry/pipeline-notifier
 - pimterry/pointsarenttime.com
 - pimterry/prebuild
 - pimterry/qtile-config
 - pimterry/questionmaster
 - pimterry/require-ko-template
 - pimterry/room-reminder
 - pimterry/rpi-backlight
 - pimterry/rtm-to-todoist
 - pimterry/rustls-native-certs
 - pimterry/sauce-tunnel
 - pimterry/server-components-express
 - pimterry/server-components-static
 - pimterry/sinon-chrome
 - pimterry/slide-clicker
 - pimterry/speak
 - pimterry/status
 - pimterry/tim-perry.co.uk
 - pimterry/tim.fyi
 - pimterry/typed-promisify-all
 - pimterry/typesafe-get
 - pimterry/valid-email
 - pimterry/win-detect-browsers
 - pimterry/win-version-info
 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
