### ISSUE TITLE
Opt-out request for josiahcarlson

### ISSUE THREAD

**Issue by josiahcarlson** [bigcode-project/opt-out-v2#49]
https://stack.dataportraits.org/ shows that code from all of my Github repositories are included in The Stack, even LGPL 2.1 and 3.0 repositories. However, the LGPL repositories do not seem to be attributed to me, or listed in The Stack here: https://huggingface.co/spaces/bigcode/in-the-stack .

I request that the following data is removed from The Stack:

 - Commits related to:
 - GitHub issues related to:
 - josiahcarlson/rom
 - josiahcarlson/rpqueue
 - josiahcarlson/parse-crontab
 - josiahcarlson/jobs
 - josiahcarlson/mprop
 - josiahcarlson/timezone-utlis
 - josiahcarlson/yogatable

As they ARE NOT permissively licensed, and ARE NOT Apache 2.0 licensed.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.0.1 of The Stack and all future versions. Also your data was not used for the training of StarCoder2.

[PROCESSED]
