### ISSUE TITLE
Oops! You've accidentally committed a Piracy!

### ISSUE THREAD

**Issue by callionica** [bigcode-project/opt-out-v2#497]
You should delete all the data you hold since you've (accidentally, I'm sure) hoovered up a load of code from private repos that is not permissively licensed.

As an example, I refer you to callionica/Landmarks which has never been permissively licensed (as the licence for the project states very clearly).

You might also like to be aware that your form for checking whether data is in your dataset on huggjngface is case-sensitive (an oversight again)

Delete all my code from all your datasets.

Thanks!

**Comment by callionica** [comment]
And here's a link to one of my files that you're presumably hosting on softwareheritage.org:

https://archive.softwareheritage.org/browse/content/sha1_git:4a70e7a9a52825d0c24c73abe157624493ea2ae2/?origin_url=https://github.com/callionica/landmarks&path=LICENSE

The text of that file:

"This is NOT free software. All rights reserved by @callionica.
Contact @callionica (on GitHub or Twitter) if you would like to make use of this software."

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
