### ISSUE TITLE
Opt-out request for ArmsOfSorrow/CarePackage17 

### ISSUE THREAD

**Issue by CarePackage17** [bigcode-project/opt-out-v2#503]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: ArmsOfSorrow
 - ArmsOfSorrow/armsofsorrow.github.io
 - ArmsOfSorrow/callflasher
 - ArmsOfSorrow/gstreamer-android-qt-app
 - ArmsOfSorrow/parsing-experiments
 - ArmsOfSorrow/ui-experiments
 - ArmsOfSorrow/unity3d-sys
 - ArmsOfSorrow/win32-cargo-generate
 - CarePackage17/testlib
 - CarePackage17/unity-plugin
 - CarePackage17/win32-d3d-template

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
