### ISSUE TITLE
Opt-out request for scott-gr

### ISSUE THREAD

**Issue by scott-gr** [bigcode-project/opt-out-v2#505]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - scott-gr/Staying-in-Tonight-Generator
 - scott-gr/advent-of-code-2020
 - scott-gr/coding-quiz-gt-hw
 - scott-gr/dndshop
 - scott-gr/google-books
 - scott-gr/gt-password-generator
 - scott-gr/my-portfolio
 - scott-gr/oakhurst-dog-park
 - scott-gr/readme-generator
 - scott-gr/shareon
 - scott-gr/superhero-api
 - scott-gr/vercel-badge
 - scott-gr/weather-forecast-dashboard-gt
 - scott-gr/work-Scheduler-gt-hw

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
