### ISSUE TITLE
Opt-out request for Doshirae

### ISSUE THREAD

**Issue by Doshirae** [bigcode-project/opt-out-v2#507]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - Doshirae/Articles
 - Doshirae/Nestor
 - Doshirae/dotfiles
 - Doshirae/schmilblick

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
