### ISSUE TITLE
Opt-out request for Holo-Krzysztof

### ISSUE THREAD

**Issue by Holo-Krzysztof** [bigcode-project/opt-out-v2#511]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - Holo-Krzysztof/SpatialMappingCrashRepro
 - Holo-Krzysztof/WebRTC.Android
 - Holo-Krzysztof/webrtc-uwp-issue-90
 - Holo-Krzysztof/webrtc-uwp-sdk-wiki

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
