### ISSUE TITLE
Opt-out request for edm00se

### ISSUE THREAD

**Issue by edm00se** [bigcode-project/opt-out-v2#512]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - edm00se/3edesign
 - edm00se/AnAppOfIceAndFire
 - edm00se/BP101-A-Modernized-Developer-Workflow-With-Domino-and-XPages
 - edm00se/BeardAppBlender
 - edm00se/BlueChalkySoup
 - edm00se/Ice-And-Fire-On-Bluemix
 - edm00se/Task-Runners-With-Domino
 - edm00se/UnpAndroidCameraWeirdness
 - edm00se/about
 - edm00se/aframe-demo
 - edm00se/ama
 - edm00se/amp-hacks
 - edm00se/awesome-board-games
 - edm00se/beer-debt-mk2
 - edm00se/blog-posted-dates
 - edm00se/bower-vs-npm-dep-compare
 - edm00se/create-vue-parcel
 - edm00se/cs-net-3
 - edm00se/demo
 - edm00se/dev-blog-book
 - edm00se/dev-dog
 - edm00se/dino-sprint-namer
 - edm00se/edm00se.github.io
 - edm00se/emoji-transmogrifier
 - edm00se/express-app-fun
 - edm00se/express-domino-nsf
 - edm00se/franz-recipe-watson-workspace
 - edm00se/gemcityjs
 - edm00se/generator-presto-preso
 - edm00se/generator-xsp
 - edm00se/gridsome-plugin-remark-embed
 - edm00se/homebrew-core
 - edm00se/iot-pi
 - edm00se/misc
 - edm00se/misc-arch
 - edm00se/modernize-ng1
 - edm00se/mouse-trap
 - edm00se/netlify-plugin-gridsome-cache
 - edm00se/node-dora
 - edm00se/node-dora-cli
 - edm00se/npm-edm00se
 - edm00se/npm-ericmccormick
 - edm00se/olympic-time
 - edm00se/open-pip
 - edm00se/openshift-koken
 - edm00se/parcel-ie11-issue-demo
 - edm00se/parcel-plugin-goodie-bag
 - edm00se/parcel-plugin-workbox
 - edm00se/parcel-v2-demo
 - edm00se/personal-mock-url-shortener
 - edm00se/plugins
 - edm00se/pointing-sound-board
 - edm00se/prettier-eslint
 - edm00se/projects
 - edm00se/proxy-simple-docker-compose-node-redis-demo
 - edm00se/serverless-starter
 - edm00se/simple-action-scheduled-demo
 - edm00se/simple-docker-compose-node-redis-demo
 - edm00se/skylines
 - edm00se/spectrum-speed
 - edm00se/svelte3-parcel-starter
 - edm00se/sweaty-mcsweaterson-alexa-skill
 - edm00se/typing-for-my-kid
 - edm00se/urls
 - edm00se/uses
 - edm00se/vue-markdown-bookmarklet
 - edm00se/vue-parcel-starter
 - edm00se/vue-webpack-simple-example
 - edm00se/xsltproc4domino

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
