### ISSUE TITLE
Opt-out request for chartjes

### ISSUE THREAD

**Issue by chartjes** [bigcode-project/opt-out-v2#522]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - chartjes/PHPBrowserMobProxy
 - chartjes/ailoads-kinto
 - chartjes/atthekeyboard
 - chartjes/blog
 - chartjes/blog-strategy
 - chartjes/chartjes.github.io
 - chartjes/djaml
 - chartjes/grumpy-learning
 - chartjes/grumpy-node
 - chartjes/ibl-delphi
 - chartjes/liesitoldmykids
 - chartjes/nyancat-phpunit-resultprinter
 - chartjes/php-tricorder
 - chartjes/tecken-loadtests
 - chartjes/wat-tek13
 - chartjes/webreg
 - chartjes/workshop

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
