### ISSUE TITLE
Opt-out request for vasilisvg

### ISSUE THREAD

**Issue by vasilisvg** [bigcode-project/opt-out-v2#526]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - vasilisvg/Blok-web
 - vasilisvg/CSS-and-CSS3-Sublime-snippets
 - vasilisvg/Exclusive-Design-Expo
 - vasilisvg/Responsive-Patterns
 - vasilisvg/blok-web2
 - vasilisvg/blokweb-issues
 - vasilisvg/bringhurst-studies
 - vasilisvg/crazy-vh-test
 - vasilisvg/decimal-clock
 - vasilisvg/exclusive-design-workshops
 - vasilisvg/food
 - vasilisvg/french-time
 - vasilisvg/frontend-final-final-ewchtwaar
 - vasilisvg/frontend-herkansing-grmbl
 - vasilisvg/frontendvoordesigners
 - vasilisvg/geek-time
 - vasilisvg/greek-time
 - vasilisvg/ish
 - vasilisvg/layout-studies
 - vasilisvg/look--no-media-queries
 - vasilisvg/master-mapping
 - vasilisvg/mine
 - vasilisvg/nerd-ratio
 - vasilisvg/responsive-typographic-grids
 - vasilisvg/six-key-typing
 - vasilisvg/tools
 - vasilisvg/tschicholds-figures
 - vasilisvg/type-scale

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
