### ISSUE TITLE
Opt-out request for luffycodes

### ISSUE THREAD

**Issue by luffycodes** [bigcode-project/opt-out-v2#53]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - luffycodes/CompetitiveProgramming
 - luffycodes/DSP_Family_Tree
 - luffycodes/ELEC576
 - luffycodes/ELEC577
 - luffycodes/ELEC578
 - luffycodes/GRE_Word2vec_SmartSentenceGetter
 - luffycodes/Multilevel-IRT-Project-Report
 - luffycodes/OpenNMT
 - luffycodes/SpojRecommendationSystem
 - luffycodes/Weka_Haskell
 - luffycodes/neptune

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.0.1 of The Stack and all future versions. Also your data was not used for the training of StarCoder2.

[PROCESSED]
