### ISSUE TITLE
Opt-out request for ThatGeoGuy

### ISSUE THREAD

**Issue by ThatGeoGuy** [bigcode-project/opt-out-v2#531]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - ThatGeoGuy/ENGO500-Webserver
 - ThatGeoGuy/ENGO699-CV-Project
 - ThatGeoGuy/chicken-graphs
 - ThatGeoGuy/chicken-miniKanren
 - ThatGeoGuy/srfi-113
 - ThatGeoGuy/srfi-116
 - ThatGeoGuy/srfi-117
 - ThatGeoGuy/srfi-121
 - ThatGeoGuy/srfi-128
 - ThatGeoGuy/srfi-196-chicken

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
