### ISSUE TITLE
Opt-out request for mudphone

### ISSUE THREAD

**Issue by mudphone** [bigcode-project/opt-out-v2#537]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - mudphone/EveryElixirPatternMatchingExampleEver
 - mudphone/Exercise
 - mudphone/Folding
 - mudphone/FunctionalReactivePixels
 - mudphone/FunctionalSwift
 - mudphone/GameOfLifeStarters
 - mudphone/GuestbookDemo
 - mudphone/HairyExtension
 - mudphone/HaskellBook
 - mudphone/HawaiiDataPipeline
 - mudphone/Hoex
 - mudphone/Honolulu
 - mudphone/HoplonNavbarSvgProblem
 - mudphone/HowToUseNSTask
 - mudphone/JSConfHI_HIandAI
 - mudphone/KineDots
 - mudphone/Kinect-Ruby-Processing
 - mudphone/Lelepua
 - mudphone/LiberatorDemo
 - mudphone/LiveBus
 - mudphone/MakingThingsSeeExamples
 - mudphone/MetaprogrammingElixir
 - mudphone/MyFirstLisp
 - mudphone/Om-Tutorial-Intermediate
 - mudphone/Om-Tutorial-with-Browser-REPL
 - mudphone/PDCBlinker
 - mudphone/PhoenixBootHoplon
 - mudphone/PhoenixDistilleryBuild
 - mudphone/PhoenixTV
 - mudphone/ProgrammingElixir
 - mudphone/ProgrammingInHaskell
 - mudphone/Quake-Log-Parser
 - mudphone/Quick
 - mudphone/QuilOpenCVDemo
 - mudphone/RBinger
 - mudphone/RUBYP5StarterKit
 - mudphone/RWReativePlayground
 - mudphone/ReagentDiffusion
 - mudphone/ReportingDemo
 - mudphone/Resizer
 - mudphone/SICP-Book
 - mudphone/Shocka
 - mudphone/ShowAloha
 - mudphone/SigSheet
 - mudphone/SignDemo
 - mudphone/Simple-Motion-Tracking
 - mudphone/SpaceRun
 - mudphone/Swift-10-20
 - mudphone/ThinkingFunctionallyWithHaskell
 - mudphone/UHMobileHackathonLightningTalk
 - mudphone/Vogr
 - mudphone/WarmingUpWithEmber
 - mudphone/basic_activerecord
 - mudphone/bingo
 - mudphone/bowman
 - mudphone/captionation
 - mudphone/census
 - mudphone/chipo
 - mudphone/clj-idioms
 - mudphone/clojure_basics
 - mudphone/dac_overhead
 - mudphone/dac_processing_experiments
 - mudphone/embedded-hoplon-example
 - mudphone/fuzzyviz
 - mudphone/haa_apps
 - mudphone/iCloudCoreDataExample
 - mudphone/iDoula
 - mudphone/ikouclojure
 - mudphone/iphone_wheel_experiment
 - mudphone/kinect-twodee-mover
 - mudphone/kinectforepointandbox2d
 - mudphone/lake-lapse
 - mudphone/learn-c-the-hard-way
 - mudphone/learninginteractivity
 - mudphone/little-clojurian
 - mudphone/lumidoug
 - mudphone/missiles
 - mudphone/mudjars
 - mudphone/mudphone-s-everyday-terminal-helpers
 - mudphone/mudphone_js_helpers
 - mudphone/nand2tetris
 - mudphone/noted
 - mudphone/offshore
 - mudphone/om-async
 - mudphone/pork
 - mudphone/property_based_testing
 - mudphone/rubyquiz
 - mudphone/rumbl
 - mudphone/spaceviking
 - mudphone/spad
 - mudphone/ADFEmailLookupDemo
 - mudphone/AgencyAgencyConf
 - mudphone/Agora
 - mudphone/Chit
 - mudphone/ClojureWest2014
 - mudphone/CodeSchoolBulletinNgApp
 - mudphone/ElixirChat

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
