### ISSUE TITLE
Opt-out request for barryrowlingson

### ISSUE THREAD

**Issue by barryrowlingson** [bigcode-project/opt-out-v2#539]
I request that the following data is removed from The Stack and StackOverflow:

 - all
 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - barryrowlingson/CARBayesST
 - barryrowlingson/LEBLiverpool
 - barryrowlingson/PrevMap
 - barryrowlingson/amy
 - barryrowlingson/barrymisc
 - barryrowlingson/caramellar
 - barryrowlingson/changer
 - barryrowlingson/circlefitter
 - barryrowlingson/conferencer
 - barryrowlingson/covid19uk
 - barryrowlingson/dispensr
 - barryrowlingson/ebola
 - barryrowlingson/exceedingly
 - barryrowlingson/first
 - barryrowlingson/florida_zika_outbreak
 - barryrowlingson/formr
 - barryrowlingson/foss4g2013
 - barryrowlingson/geninvgamma
 - barryrowlingson/geomap
 - barryrowlingson/geospatialplus
 - barryrowlingson/geostat-prediction
 - barryrowlingson/geostat2017
 - barryrowlingson/geoutils
 - barryrowlingson/inkyback
 - barryrowlingson/kofnGA
 - barryrowlingson/lektor-static-search
 - barryrowlingson/maptember
 - barryrowlingson/multimala
 - barryrowlingson/openlayr
 - barryrowlingson/osgeoatlas
 - barryrowlingson/osgeouk
 - barryrowlingson/phlab
 - barryrowlingson/phlabr
 - barryrowlingson/polyline-to-geojson
 - barryrowlingson/prescribing-viz
 - barryrowlingson/pythonr
 - barryrowlingson/pytml
 - barryrowlingson/qgis-location-lab-plugin
 - barryrowlingson/r-mapping-2016-1
 - barryrowlingson/rcoursenotes
 - barryrowlingson/rdocr
 - barryrowlingson/rqgismapping
 - barryrowlingson/rtmodel
 - barryrowlingson/rtopojson
 - barryrowlingson/rwfs
 - barryrowlingson/samplezone
 - barryrowlingson/shapeygraph
 - barryrowlingson/spatsurv
 - barryrowlingson/spatsurvvis
 - barryrowlingson/splatr
 - barryrowlingson/sportyR
 - barryrowlingson/svgPanZoom
 - barryrowlingson/telemetr
 - barryrowlingson/the-unix-workbench
 - barryrowlingson/tmap
 - barryrowlingson/travistest
 - barryrowlingson/trmm
 - barryrowlingson/vectype
 - barryrowlingson/what3wordr
 - barryrowlingson/workshop-skeleton

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
