### ISSUE TITLE
Opt-out request for nuprl

### ISSUE THREAD

**Issue by arjunguha** [bigcode-project/opt-out-v2#54]
I request that the following data is removed from The Stack and StackOverflow:

 - nuprl/TypeWeaver

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by arjunguha** [comment]
This is a benchmark, and was used in the StarCoder paper. So best not to train on it. :)

**Comment by lvwerra** [comment]
This has been removed in version v2 and future versions and was not used for StarCoder2 training.

**Comment by lvwerra** [comment]
This has been removed in version v2.0.1 of The Stack and all future versions and was not used for StarCoder2 training.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.0.1 of The Stack and all future versions. Also your data was not used for the training of StarCoder2.

[PROCESSED]
