### ISSUE TITLE
Opt-out request for jonathonfletcher

### ISSUE THREAD

**Issue by jonathonfletcher** [bigcode-project/opt-out-v2#540]
I request that the following data is removed from The Stack and StackOverflow:

 - all
 - Commits
 - GitHub issue
 - jonathonfletcher/BiteSizeBayes
 - jonathonfletcher/extemporelang.github.io
 - jonathonfletcher/misc_medium
 - jonathonfletcher/openbsd-notes
 - jonathonfletcher/peregrine

Additionally:

 - Any Past, Present, or Future GitHub repositories, issues, resources, any other user-generatored content for the GitHub username jonathonfletcher

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
