### ISSUE TITLE
Opt-out request for Ceralor

### ISSUE THREAD

**Issue by Ceralor** [bigcode-project/opt-out-v2#549]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - Ceralor/ConvertTo-Youtube
 - Ceralor/SNP4AutoITv3
 - Ceralor/djangthulu
 - Ceralor/flask-telescope-old
 - Ceralor/get_dick.py
 - Ceralor/ha-eufy_vacuum
 - Ceralor/hass-pyscript-hue_assistant
 - Ceralor/hass_dsame
 - Ceralor/pelican-simple-fa
 - Ceralor/pelimoji
 - Ceralor/picartopush_old
 - Ceralor/picartotgbot.stream-old
 - Ceralor/samdbadge
 - Ceralor/southern-company-api
 - Ceralor/voipms_sms
 - Ceralor/xlauncher
 - pelican-plugins/pelimoji
 - All future repositories from Ceralor
 - all

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
