### ISSUE TITLE
Opt-out request for kenballus

### ISSUE THREAD

**Issue by kenballus** [bigcode-project/opt-out-v2#55]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - kenballus/BrainFuck
 - kenballus/CactusQuest
 - kenballus/SDL-SWITCH
 - kenballus/binary-bomb-lab
 - kenballus/braiinfuck
 - kenballus/chip8
 - kenballus/code-golf.io
 - kenballus/covid-county-ranking
 - kenballus/cpx_irrecord
 - kenballus/cpxtennis
 - kenballus/ecc-reductions
 - kenballus/gp-presentation
 - kenballus/groebner-fun
 - kenballus/mi424wr-rev-i-dts
 - kenballus/openwrt-mi424wr-rev-i
 - kenballus/quaternions

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.0.1 of The Stack and all future versions. Also your data was not used for the training of StarCoder2.

[PROCESSED]
