### ISSUE TITLE
Opt-out request for bryal

### ISSUE THREAD

**Issue by bryal** [bigcode-project/opt-out-v2#551]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - bryal/HelioCon
 - bryal/bryal.xyz
 - bryal/compression
 - bryal/d3d11-rs
 - bryal/dxgi-rs
 - bryal/godot-pong
 - bryal/guix-config
 - bryal/llvmer
 - bryal/luminance-rs
 - bryal/my-conf
 - bryal/se-rs-ial
 - bryal/serial-win-rs
 - bryal/shmub
 - bryal/spatiality
 - bryal/termios.rs
 - bryal/winapi-rs

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
