### ISSUE TITLE
Opt-out request for KitchenStories

### ISSUE THREAD

**Issue by rbdr** [bigcode-project/opt-out-v2#558]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - KitchenStories/DeepLinkKit
 - KitchenStories/EasyTipView
 - KitchenStories/Elissa
 - KitchenStories/JWTDecode.swift
 - KitchenStories/LTNavigationBar
 - KitchenStories/VGParallaxHeader
 - KitchenStories/VersionsTracker
 - KitchenStories/browser-deeplink
 - KitchenStories/clean-arch-poll
 - KitchenStories/pre-commit-hooks
 - KitchenStories/python-ultron-client
 - KitchenStories/vue-smoothscroll

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by loubnabnl** [comment]
Hi @rbdr, thanks for the opt-out request. Are you one of the main contributors to the repos you listed? Usually, it's easiest for us to check the validity of an opt-out request if it comes from the main contributors to the orgs.

**Comment by rbdr** [comment]
I’m the admin of the org, and engineering director at the company that the org belongs to.

**Comment by loubnabnl** [comment]
Thanks for your reply!

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
