### ISSUE TITLE
Opt-out request for rbdr

### ISSUE THREAD

**Issue by rbdr** [bigcode-project/opt-out-v2#560]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - rbdr/GMailinator
 - rbdr/Helvetiblackboard
 - rbdr/Historias-por-N--S-o-Vocal
 - rbdr/Paper2DTutorial
 - rbdr/Pico-Engine
 - rbdr/abuguet
 - rbdr/abuguetchat
 - rbdr/api-notation.tmLanguage
 - rbdr/argon
 - rbdr/blinking_lights
 - rbdr/blog
 - rbdr/chilaquiles
 - rbdr/cobalt
 - rbdr/cologne
 - rbdr/dasein
 - rbdr/dead-drop
 - rbdr/dotfiles
 - rbdr/dumb-monitor
 - rbdr/ephemeral-post
 - rbdr/exiv2node
 - rbdr/express-helpers
 - rbdr/fortunabot
 - rbdr/frames
 - rbdr/frontend_challenge
 - rbdr/fyr
 - rbdr/generador-de-insultos
 - rbdr/heart
 - rbdr/hubot-insultos
 - rbdr/jsdoc-augmented-template
 - rbdr/lgtm
 - rbdr/lissajous-brain
 - rbdr/lissajous-renderer
 - rbdr/lua-talk
 - rbdr/mallard
 - rbdr/moire-toy
 - rbdr/ogat
 - rbdr/oh-my-zsh
 - rbdr/petitcochon
 - rbdr/prezto
 - rbdr/productivity_frame
 - rbdr/react-experiments
 - rbdr/recordit-url-builder-js
 - rbdr/robot-captcha
 - rbdr/snes_learning
 - rbdr/sorting-hat
 - rbdr/sorting-hat-renderer
 - rbdr/sumo
 - rbdr/super-polarity
 - rbdr/tellurium
 - rbdr/temporal-storage
 - rbdr/tomato-sauce
 - rbdr/toy
 - rbdr/twitter-affection-histogram

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
