### ISSUE TITLE
Opt-out request for cbiffle

### ISSUE THREAD

**Issue by cbiffle** [bigcode-project/opt-out-v2#563]
I request that the following data is removed from The Stack:

- all
- all future repos created under this user, I explicitly do not grant you the right to include them in a training set due to your confusion of "opt out" with consent. 
 - cbiffle/G3Firmware
 - cbiffle/Swamp-Thing
 - cbiffle/agealyzer-rust
 - cbiffle/avrgcc-macosx-makefile
 - cbiffle/brittle-kernel
 - cbiffle/cargo-per-package-target-repro-case
 - cbiffle/catibo
 - cbiffle/clash-prelude
 - cbiffle/cobble-build
 - cbiffle/emb.rs
 - cbiffle/etl
 - cbiffle/etl-test
 - cbiffle/flabbergast-hs
 - cbiffle/httpd1
 - cbiffle/kallisti
 - cbiffle/kicad-pcb-libs
 - cbiffle/lilos1
 - cbiffle/m4vgalib
 - cbiffle/m4vgalib-demos
 - cbiffle/propasm
 - cbiffle/pushr-for-android
 - cbiffle/reference
 - cbiffle/rs80
 - cbiffle/rtiow-rust
 - cbiffle/s3g-toolkit
 - cbiffle/sds011-reader
 - cbiffle/stm32h7-rs
 - cbiffle/tock
 - cbiffle/visit-diff
 - cbiffle/xmonad-config
 - cbiffle/zola

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
