### ISSUE TITLE
Opt-out request for obmarg

### ISSUE THREAD

**Issue by obmarg** [bigcode-project/opt-out-v2#567]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - obmarg/asdf-elm
 - obmarg/asdf-purescript
 - obmarg/bipbuffer
 - obmarg/cerberus_to_swagger
 - obmarg/chunnel
 - obmarg/cpp11csm
 - obmarg/cppshould
 - obmarg/ctrlp-funky
 - obmarg/docker-elixir
 - obmarg/docker-fake-gcs-server
 - obmarg/docker-logstash-http-kibana
 - obmarg/docker-monitoring
 - obmarg/docker-python-web
 - obmarg/docker-rust-nightly
 - obmarg/dotfiles
 - obmarg/elk
 - obmarg/elm-slow-test
 - obmarg/erlang_port
 - obmarg/exfmt
 - obmarg/exometer_datadog
 - obmarg/exrm_test
 - obmarg/exunit_fixtures
 - obmarg/flask-should-dsl
 - obmarg/flask-transit
 - obmarg/flycheck-elixir-dogma
 - obmarg/flycheck-hjson
 - obmarg/gae-logstash-http
 - obmarg/git-lead-time
 - obmarg/gitgene
 - obmarg/gntp
 - obmarg/growlproxy
 - obmarg/hjson-mode
 - obmarg/homebrew-tap
 - obmarg/http-types
 - obmarg/imitate
 - obmarg/interactive-video
 - obmarg/jefe
 - obmarg/k8s-certbot-google-dns
 - obmarg/kazan
 - obmarg/mmm-ale
 - obmarg/nix-plexmediaserver
 - obmarg/pi_project_rpi3
 - obmarg/plug_fprof
 - obmarg/plumbum
 - obmarg/pureon
 - obmarg/purescript
 - obmarg/purescript-ffi-utils
 - obmarg/purescript-node-github
 - obmarg/pypod
 - obmarg/pyvis
 - obmarg/quicksilver.vim
 - obmarg/redbadger
 - obmarg/rename-flac
 - obmarg/resumr
 - obmarg/rust-emlib
 - obmarg/seed-app-time-tracker
 - obmarg/serverconfig
 - obmarg/serverless-purescript
 - obmarg/sqlite_ecto2
 - obmarg/sqlitex
 - obmarg/stackdriver-logger
 - obmarg/synchg
 - obmarg/toolz
 - obmarg/vassal
 - obmarg/wiremock-rs
 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
