### ISSUE TITLE
Opt-out request for fuwwy

### ISSUE THREAD

**Issue by itsfolf** [bigcode-project/opt-out-v2#571]
I request that the following data is removed from The Stack:

 - all
 
_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.
...

**Comment by loubnabnl** [comment]
Hi @itsfolf, thanks for the opt-out request. What's your connection to the @fuwwy account? Usually, it's easiest for us to check the validity of an opt-out request if it comes from the account itself.

**Comment by itsfolf** [comment]
> Hi @itsfolf, thanks for the opt-out request. What's your connection to the @fuwwy account? Usually, it's easiest for us to check the validity of an opt-out request if it comes from the account itself.

@fuwwy was my previous username, some repositories are included under this alias. As a confirmation, github should redirect you when attempting to access those.

**Comment by loubnabnl** [comment]
I see, thanks for the prompt reply!

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
