### ISSUE TITLE
Opt-out request for ionspin

### ISSUE THREAD

**Issue by ionspin** [bigcode-project/opt-out-v2#575]
I request that the following data is removed from The Stack and:

 - ionspin/avr-arduino-zig
 - ionspin/awesome-kotlin
 - ionspin/compose-jb
 - ionspin/deeplearning4j
 - ionspin/kotlin-multiplatform-bignum
 - ionspin/kotlin-multiplatform-crypto
 - ionspin/kotlin-multiplatform-libsodium
 - ionspin/kotlinx.coroutines
 - ionspin/kotlinx.serialization
 - ionspin/lazysodium-java
 - ionspin/skiko
 - ionspin/svd4zig
 - ionspin/zig
 - ionspin/zig-network
 - all

Also do not include any future repositories or code.

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
