### ISSUE TITLE
Opt-out request for dhasenan

### ISSUE THREAD

**Issue by dhasenan** [bigcode-project/opt-out-v2#579]
I request that the following data is removed from The Stack:

- dhasenan/BeefyRunner
- dhasenan/DIPs
- dhasenan/DMDScript
- dhasenan/MoarTinkers
- dhasenan/PokemonRandomizer
- dhasenan/SDC
- dhasenan/Yaeb
- dhasenan/antlr-d
- dhasenan/couchdb-d
- dhasenan/cruddyorm
- dhasenan/csspolicy
- dhasenan/damask
- dhasenan/datefmt
- dhasenan/dirtle_computercraft
- dhasenan/dmd
- dhasenan/dmidifile
- dhasenan/dpq2
- dhasenan/drunken-nemesis
- dhasenan/epub
- dhasenan/fanfiction.ebook
- dhasenan/ffn
- dhasenan/keybinder
- dhasenan/komenci
- dhasenan/locallexicon
- dhasenan/maybemaybemaybebotbotbot
- dhasenan/meredith
- dhasenan/neiaprocgen
- dhasenan/newer_testament
- dhasenan/pierce
- dhasenan/silvermirror
- dhasenan/softie
- dhasenan/subtex
- dhasenan/subtex-vim
- dhasenan/unit-threaded
- dhasenan/urld
- dhasenan/vibethrift

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
