### ISSUE TITLE
Opt-out request for yamafaktory

### ISSUE THREAD

**Issue by yamafaktory** [bigcode-project/opt-out-v2#582]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - yamafaktory/.emacs.d
 - yamafaktory/.zimrc
 - yamafaktory/CSSTest
 - yamafaktory/Sigma.io
 - yamafaktory/attic-schedule
 - yamafaktory/buble-react-rollup-starter
 - yamafaktory/cargo-deny
 - yamafaktory/course-landing-page
 - yamafaktory/docker-flowtype
 - yamafaktory/e2e-parser
 - yamafaktory/elements
 - yamafaktory/extend-package-scripts-example
 - yamafaktory/git-chart-js
 - yamafaktory/hjik
 - yamafaktory/jest-glamor-react
 - yamafaktory/jql
 - yamafaktory/livepal
 - yamafaktory/lumberjack-theme-emacs
 - yamafaktory/lumberjack.vim
 - yamafaktory/nixos-configuration
 - yamafaktory/pattern-guard
 - yamafaktory/polymer-game
 - yamafaktory/reflex-starter
 - yamafaktory/roost
 - yamafaktory/ruster
 - yamafaktory/stephendiehl.com
 - yamafaktory/vscode
 - yamafaktory/yamafaktory.github.io
 - yamafaktory/yume

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
