### ISSUE TITLE
Opt-out request for MetaSyntactical

### ISSUE THREAD

**Issue by dkreuer** [bigcode-project/opt-out-v2#586]
I am owner of the organization MetaSyntactical on GitHub. I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - MetaSyntactical/Io
 - MetaSyntactical/Mime
 - MetaSyntactical/ansible-role-mattermost
 - MetaSyntactical/composer-codesniffer-hooks
 - MetaSyntactical/composer-plugin-license-check
 - MetaSyntactical/google-directions-client
 - MetaSyntactical/http-transport
 - MetaSyntactical/http-transport-guzzle
 - MetaSyntactical/inmemory-logger
 - MetaSyntactical/jConfigurationCenter
 - MetaSyntactical/jquery-ui-notification-center
 - MetaSyntactical/lib-php-icalendar
 - MetaSyntactical/listr-go
 - MetaSyntactical/php-soap-client-options
 - MetaSyntactical/psr-cache
 - MetaSyntactical/symfony-coding-standard
 - MetaSyntactical/symfony-mime
 - MetaSyntactical/xml-tools
 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
