### ISSUE TITLE
Opt-out request for brockmuellers

### ISSUE THREAD

**Issue by brockmuellers** [bigcode-project/opt-out-v2#59]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - brockmuellers/brockmuellers.github.io
 - brockmuellers/learning
 - brockmuellers/spotify-backup
 - brockmuellers/techwizard
 - brockmuellers/video-concat
 - brockmuellers/watch-products

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by tealamore** [comment]
@lvwerra how are you prioritizing which requests are completed first? i saw you closed my request that i made in march, yet there are multiple requests open from december of last year

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
