### ISSUE TITLE
Opt-out request for alyssarosenzweig

### ISSUE THREAD

**Issue by alyssarosenzweig** [bigcode-project/opt-out-v2#596]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - alyssarosenzweig/2.02SWF
 - alyssarosenzweig/CServe
 - alyssarosenzweig/JITScratch
 - alyssarosenzweig/MMOKickstart
 - alyssarosenzweig/Windows.js
 - alyssarosenzweig/ap0110
 - alyssarosenzweig/bamboo-lite
 - alyssarosenzweig/core-defender
 - alyssarosenzweig/intra
 - alyssarosenzweig/ld30
 - alyssarosenzweig/tiny-blog
 - alyssarosenzweig/wings-legacy
 - alyssarosenzweig/ystatus

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
