### ISSUE TITLE
Opt-out request for gbradley

### ISSUE THREAD

**Issue by gbradley** [bigcode-project/opt-out-v2#598]
I request that the following data is removed from The Stack and StackOverflow:

 - gbradley/ApertureToBlip
 - gbradley/BB.js
 - gbradley/BlipJS
 - gbradley/SupportBee-Apps
 - gbradley/Template
 - gbradley/WebEdit.js
 - gbradley/blipperific
 - gbradley/dbdiff
 - gbradley/enigma.js
 - gbradley/ignite-js
 - gbradley/jpeg.js
 - gbradley/laravel-api-resource
 - gbradley/laravel-test
 - gbradley/react-dispatcher
 - gbradley/updown

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
