### ISSUE TITLE
Opt-out request for aayars

### ISSUE THREAD

**Issue by aayars** [bigcode-project/opt-out-v2#599]
I request that the following data is removed from The Stack:

 - Commits
 - GitHub issue
 - aayars/GhettoPrefs
 - aayars/RagingClue
 - aayars/comrade
 - aayars/globaldbi
 - aayars/noise-maps
 - aayars/noisemaker
 - aayars/noisemakerbot
 - aayars/py-noisemaker
 - aayars/seitan

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
