### ISSUE TITLE
Opt-out request for dojoteef

### ISSUE THREAD

**Issue by dojoteef** [bigcode-project/opt-out-v2#60]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - dojoteef/XVim
 - dojoteef/dotfiles
 - dojoteef/loltorch
 - dojoteef/lualol
 - dojoteef/neomake-autolint
 - dojoteef/tmux-navigate
 - dojoteef/ttq
 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
