### ISSUE TITLE
Opt-out request for Lizzip

### ISSUE THREAD

**Issue by Lizzip** [bigcode-project/opt-out-v2#602]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - Lizzip/7dfps
 - Lizzip/BaconGameJam-LightsOut
 - Lizzip/HnS
 - Lizzip/LD27
 - Lizzip/PlayCanvas-LevelGenerators
 - Lizzip/SocketServer
 - Lizzip/animal_crossing_checklist
 - Lizzip/canvas
 - Lizzip/inside_track
 - Lizzip/peacemaker
 - Lizzip/pottermunge
 - Lizzip/redgreen
 - Lizzip/screeps
 - Lizzip/stormancer_playcanvas

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
