### ISSUE TITLE
Opt-out request for zpx01

### ISSUE THREAD

**Issue by zpx01** [bigcode-project/opt-out-v2#61]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - zpx01/auto_nuclear_seg
 - zpx01/flow
 - zpx01/image-ml
 - zpx01/pulsar-classifier
 - zpx01/react-movie-rating
 - zpx01/react-task-tracker
 - zpx01/zpx01

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
