### ISSUE TITLE
Please remove 2 out of the 5 projects that you scooped up.

### ISSUE THREAD

**Issue by TrechNex** [bigcode-project/opt-out-v2#611]
I request that the following data is removed from The Stack:

 - TrechNex/mastodome-legacy
 - TrechNex/gimp-macos-build
 
_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.
...

My other projects (bobbrowse, openrams, scorchos) are permissively licensed and predate any agreements that I signed with my current employer in May 2018, so they are permitted for use in LLM training sets.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
