### ISSUE TITLE
Opt-out request for bigethan

### ISSUE THREAD

**Issue by bigethan** [bigcode-project/opt-out-v2#616]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - bigethan/RedisPaste
 - bigethan/SafariNote
 - bigethan/WebApp
 - bigethan/action-default-reviewer
 - bigethan/atom-server-side-include-syntax
 - bigethan/better-outlook-web-access
 - bigethan/cronitor-caller
 - bigethan/feather-app
 - bigethan/gender-decoder
 - bigethan/geo
 - bigethan/github-action-testing
 - bigethan/github-fluid-userscript
 - bigethan/google-agenda-email
 - bigethan/hologram-addons
 - bigethan/hugo-easy-amp
 - bigethan/manager-fortunes
 - bigethan/newtab
 - bigethan/nutritional-yeast
 - bigethan/pandora-userscript-fluid
 - bigethan/pick-a-winner
 - bigethan/private-note
 - bigethan/rendr
 - bigethan/social-command
 - bigethan/stack-cleaner
 - bigethan/stash-userscript-fluid
 - bigethan/toy_app
 - bigethan/tunisian-flashcards
 - bigethan/webpagetest-charts-api
 - bigethan/wiimoter
 - bigethan/wtfsf

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
