### ISSUE TITLE
Opt-out request for JeremyStarTM

### ISSUE THREAD

**Issue by JeremyStarTM** [bigcode-project/opt-out-v2#617]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: JeremyStarTM
 - JeremyStarTM/MsgSystemForMinecraft

**Comment by JeremyStarTM** [comment]
btw. would be nice if this stuff would be opt-in, not opt-out.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]

**Comment by JeremyStarTM** [comment]
Would have been even better if my data wasn't even included in the first place.
