### ISSUE TITLE
Opt-out request for miraz12

### ISSUE THREAD

**Issue by miraz12** [bigcode-project/opt-out-v2#62]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - miraz12/AI-2017
 - miraz12/Allocator
 - miraz12/BackToVulkan
 - miraz12/Engine
 - miraz12/Projects
 - miraz12/Ray-tracer
 - miraz12/TDDD97
 - miraz12/TNM048
 - miraz12/TNM086
 - miraz12/Vast2017
 - miraz12/VulkanFun
 - miraz12/ukCodeSample

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
