### ISSUE TITLE
Opt-out request for avernois

### ISSUE THREAD

**Issue by avernois** [bigcode-project/opt-out-v2#620]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - avernois/KataBowling-java
 - avernois/KataNumberToLCD-java
 - avernois/KataRomanNumerals-java
 - avernois/KataTennis-java
 - avernois/PebbleTalkTimer
 - avernois/PebbleTextWatch-fr
 - avernois/Rio
 - avernois/Sky-Castle-Game-Timer
 - avernois/ardFeedback
 - avernois/ardFeedback-control
 - avernois/bbc-dojo
 - avernois/bbc.onsenfout.net
 - avernois/blink4java
 - avernois/blog.crafting-labs.fr
 - avernois/charts-play
 - avernois/devfriendlyplaces
 - avernois/devopensud.github.io
 - avernois/elm
 - avernois/esp-painting
 - avernois/la_semaine_de_168_heures
 - avernois/ledmatrix4j
 - avernois/ledstrip4j
 - avernois/pres-codingdojo
 - avernois/presentations
 - avernois/prez-software_craftsmanship
 - avernois/training-php
 - avernois/wmit-lite
 - avernois/yowie

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
