### ISSUE TITLE
Opt-out request for aputinski

### ISSUE THREAD

**Issue by aputinski** [bigcode-project/opt-out-v2#627]
I request that the following data is removed from The Stack:

- aputinski/abbyputinski.com
- aputinski/adamputinski.com
- aputinski/butane
- aputinski/heroku-buildpack-npm-github
- aputinski/heroku-buildpack-npmrc
- aputinski/ignition-swift
- aputinski/react-lorem-component
- aputinski/rebound-swift
- aputinski/tableview

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
