### ISSUE TITLE
Opt-out request for spicycode

### ISSUE THREAD

**Issue by spicycode** [bigcode-project/opt-out-v2#632]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - spicycode/HE-MACS
 - spicycode/Parts_The_Clonus_Horror
 - spicycode/Vimlander-2-The-Quickening
 - spicycode/bash-your-head-in
 - spicycode/beholder
 - spicycode/dotfiles
 - spicycode/emacs
 - spicycode/hardcore_forking_action
 - spicycode/hello-world-1
 - spicycode/i_contest_this_contest_sir
 - spicycode/inspector
 - spicycode/liminal
 - spicycode/marketing
 - spicycode/micronaut
 - spicycode/micronaut-rails
 - spicycode/placeholder
 - spicycode/pow
 - spicycode/react-key-handler
 - spicycode/spicy-config
 - spicycode/spicycode.github.com
 - spicycode/the_metric_system
 - spicycode/thingsapp
 - spicycode/vim

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
