### ISSUE TITLE
Opt-out request for joachim-n

### ISSUE THREAD

**Issue by joachim-n** [bigcode-project/opt-out-v2#634]
I request that the following data is removed from The Stack and StackOverflow:

- all
 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - joachim-n/action_link
 - joachim-n/automultisites
 - joachim-n/composer-manifest
 - joachim-n/console-with-di
 - joachim-n/cream-dev
 - joachim-n/devel
 - joachim-n/dm
 - joachim-n/dorgflow
 - joachim-n/drupal-core-composer
 - joachim-n/drupal-core-development-project
 - joachim-n/drupal-form-builder-oo
 - joachim-n/drupalcamp2012
 - joachim-n/drupalcon-europe-2020-lazy-builders
 - joachim-n/git-aliases-drupal
 - joachim-n/git-house-guidelines
 - joachim-n/git-pitch-demo
 - joachim-n/help.github.com
 - joachim-n/infinitescrollaaaaaaaaaaaaaargh
 - joachim-n/signup

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
