### ISSUE TITLE
Opt-out request for telent

### ISSUE THREAD

**Issue by telent** [bigcode-project/opt-out-v2#637]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - telent/alarum
 - telent/albatross
 - telent/biscuit
 - telent/chamber
 - telent/cliki
 - telent/clj-dojo-quil
 - telent/defone
 - telent/dolores
 - telent/dotfiles
 - telent/elastichosts-api
 - telent/epsilon
 - telent/exlibris
 - telent/fenestra
 - telent/formby
 - telent/gadgetbee
 - telent/gadgnix
 - telent/goldleaf-example
 - telent/insensate
 - telent/lectito
 - telent/letsencruft
 - telent/lineant-potter
 - telent/lizard
 - telent/log-mark-i
 - telent/luaradio
 - telent/meddle
 - telent/moss
 - telent/muddle
 - telent/my-way
 - telent/nixelec
 - telent/nixos-configs
 - telent/nixwrt
 - telent/nnpp
 - telent/nuxx
 - telent/pacioli
 - telent/paxton
 - telent/phonograph
 - telent/projectr
 - telent/puppetize-noetbook
 - telent/radiop
 - telent/scanner-button
 - telent/septeql
 - telent/squeeze-cd-nfsroot
 - telent/swarm
 - telent/telent.blog
 - telent/texticl
 - telent/thin-prefork
 - telent/twitling
 - telent/upd

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

If you'd _asked_ I might have opted in, but this opt-out is sharp practice and I do not wish to participate

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
