### ISSUE TITLE
Opt-out request for tklengyel

### ISSUE THREAD

**Issue by tklengyel** [bigcode-project/opt-out-v2#64]
I request that the following data is removed from The Stack:

 - Commits
 - GitHub issue
 - tklengyel/AFLplusplus
 - tklengyel/MalShare-Toolkit
 - tklengyel/actaeon
 - tklengyel/codeql-action
 - tklengyel/drakvuf-ci
 - tklengyel/kernel-fuzzer-for-xen-project
 - tklengyel/meta-secure-core
 - tklengyel/tklengyel.github.io
 - tklengyel/valgrind-xen-patch
 - tklengyel/vmi-honeymon
 - tklengyel/xen-flashclone
 - tklengyel/xen-test-framework
 - tklengyel/xen-uefi
 - tklengyel/xtf

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
