### ISSUE TITLE
Opt-out request for alightgoesout

### ISSUE THREAD

**Issue by alightgoesout** [bigcode-project/opt-out-v2#641]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - alightgoesout/AdviceTracer
 - alightgoesout/AjMetrics
 - alightgoesout/AjMutator
 - alightgoesout/Vidock
 - alightgoesout/advent2018
 - alightgoesout/advent2019
 - alightgoesout/advent2020
 - alightgoesout/atoms
 - alightgoesout/brick-ci
 - alightgoesout/gradle-aspectj
 - alightgoesout/homepage
 - alightgoesout/prezto
 - alightgoesout/pure-mintty
 - alightgoesout/reactp
 - alightgoesout/shopping-list
 - alightgoesout/ut.js

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
