### ISSUE TITLE
Opt-out request for Mr-Andersen

### ISSUE THREAD

**Issue by Mr-Andersen** [bigcode-project/opt-out-v2#645]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - Mr-Andersen/09-remastered
 - Mr-Andersen/17.03.2016
 - Mr-Andersen/ESP-client
 - Mr-Andersen/Keygen_robot
 - Mr-Andersen/Laby
 - Mr-Andersen/adaptive_integrate
 - Mr-Andersen/async-telegram-bot
 - Mr-Andersen/concat_z
 - Mr-Andersen/db_query
 - Mr-Andersen/dblangparser
 - Mr-Andersen/game-of-life-ocl
 - Mr-Andersen/grapher
 - Mr-Andersen/integrate
 - Mr-Andersen/lazy-buffer
 - Mr-Andersen/notify-tg
 - Mr-Andersen/parse-quote
 - Mr-Andersen/typed-expr

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
