### ISSUE TITLE
Opt-out request for nnnell / internell

### ISSUE THREAD

**Issue by nnnell** [bigcode-project/opt-out-v2#647]
I request that the following data is removed from The Stack:

 - Commits
 - GitHub issue
 - all

**Comment by lvwerra** [comment]
Hi @nnnell, thanks for the opt-out request. What's your connection to the @j15n account? Usually, it's easiest for us to check the validity of an opt-out request if it comes from the account itself.

**Comment by nnnell** [comment]
@lvwerra My mistake, sorry! I was juggling a few different handles at the time — should be @nnnell and @internell.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
