### ISSUE TITLE
Opt-out request for edalzell

### ISSUE THREAD

**Issue by edalzell** [bigcode-project/opt-out-v2#652]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - edalzell/Statamic-Download
 - edalzell/iCal
 - edalzell/private-eye
 - edalzell/show-once
 - edalzell/spock
 - edalzell/statamic-akismet
 - edalzell/statamic-blade
 - edalzell/statamic-buck
 - edalzell/statamic-charge
 - edalzell/statamic-content
 - edalzell/statamic-currency
 - edalzell/statamic-entry
 - edalzell/statamic-fathom
 - edalzell/statamic-feed
 - edalzell/statamic-full_urls
 - edalzell/statamic-history
 - edalzell/statamic-is_image
 - edalzell/statamic-linked
 - edalzell/statamic-misc-validators
 - edalzell/statamic-mousetrap
 - edalzell/statamic-pinboard
 - edalzell/statamic-powertools
 - edalzell/statamic-profiler
 - edalzell/statamic-query
 - edalzell/statamic-rss
 - edalzell/statamic-settings
 - edalzell/statamic-short_url
 - edalzell/statamic-stripe
 - edalzell/statamic-tailwind
 - edalzell/statamic-trix
 - edalzell/statamic-twitter
 - edalzell/statamic-variable
 - edalzell/statamic-version
 - edalzell/statamic-wordpress-importer
 - edalzell/statamic-xmlrpc
 - edalzell/statamic-zapier
 - edalzell/statamicv1-pinboard
 - edalzell/v2-addons
 - edalzell/workshop
 - edalzell/worldofstatamic.website

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
