### ISSUE TITLE
Opt-out request for rougier

### ISSUE THREAD

**Issue by rougier** [bigcode-project/opt-out-v2#66]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - rougier/-Re-Assortative-matching-and-search
 - rougier/2019_replication_HastingsPowell_1991
 - rougier/2021-Dataviz
 - rougier/CNCC-2019
 - rougier/CompNeuroCourse-2019
 - rougier/ESN-WM
 - rougier/ICLR-2019
 - rougier/JCGT-2013
 - rougier/JCGT-2014a
 - rougier/JCGT-2014b
 - rougier/LinuxMag-HS-2014
 - rougier/PinokioProject
 - rougier/RLDM2015
 - rougier/ReScience
 - rougier/ReScience-submission-template
 - rougier/Reimplementation-SUPERTREX
 - rougier/Review-momentum-illustration
 - rougier/SpatialCompetition
 - rougier/TYRC-apple
 - rougier/URFIST-Book
 - rougier/VSOM
 - rougier/alien-life
 - rougier/array-list
 - rougier/bibliography
 - rougier/datoviz
 - rougier/decision-making
 - rougier/delayed-neural-field
 - rougier/diversity-in-reproducibility
 - rougier/doi2bib
 - rougier/dynd-python
 - rougier/emacs-gtd
 - rougier/emacs-octicons
 - rougier/euroscipy-2013
 - rougier/ex-sdl-freetype-harfbuzz
 - rougier/fractal_dimension_analysis
 - rougier/freetype-py
 - rougier/gl-agg
 - rougier/gl-history
 - rougier/glsl-experiments
 - rougier/glsl-parser
 - rougier/glumpy-website
 - rougier/helpme
 - rougier/homepage
 - rougier/homepage-old
 - rougier/iclr_2019
 - rougier/la-rochelle-2017
 - rougier/less-is-more
 - rougier/libdynd
 - rougier/linear-poisson-disk
 - rougier/loops-tutorial
 - rougier/matplotlib-3d
 - rougier/non_stationary_bandit
 - rougier/numpy-100
 - rougier/numpy-list
 - rougier/planets
 - rougier/pyroom
 - rougier/python-history
 - rougier/python-visualization-landscape
 - rougier/r5
 - rougier/rescience-editorial-2019
 - rougier/rescience-hor
 - rougier/rescience-rrpr2018
 - rougier/reservoirtarte
 - rougier/rougier
 - rougier/scikit-learn.github.io
 - rougier/scipy-badges
 - rougier/scipy-crash-course
 - rougier/scipy-lecture-notes
 - rougier/scipy-repo
 - rougier/shadergraph
 - rougier/ten-rules
 - rougier/unknown-pleasures
 - rougier/workshop_cellular_automaton
 - rougier/youtube-dl
 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
