### ISSUE TITLE
Opt-out request for Kansattica

### ISSUE THREAD

**Issue by Kansattica** [bigcode-project/opt-out-v2#663]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: Grace https://stackoverflow.com/users/5587653/grace
 - Kansattica/FluencyOnline
 - Kansattica/GrowerAndShower
 - Kansattica/Hash-Class-Test
 - Kansattica/JavaPaintGui
 - Kansattica/Kansattica.github.io
 - Kansattica/LispGenealogy
 - Kansattica/Matching-Strings
 - Kansattica/MinimumDistancePython
 - Kansattica/Polygon-Bisector
 - Kansattica/RollingFastFourierTransform
 - Kansattica/SubwayTooter
 - Kansattica/TailgateLeague
 - Kansattica/TankYou
 - Kansattica/dotfiles
 - Kansattica/fivethirtyeightriddler
 - Kansattica/mastodial
 - Kansattica/post-analyzer
- all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
