### ISSUE TITLE
Opt-out request for tristanseifert

### ISSUE THREAD

**Issue by tristanseifert** [bigcode-project/opt-out-v2#664]
I request that the following data is removed from The Stack and StackOverflow:

 - all

I’d like to add that opt-out isn't consent: if you can't manage to build up your data set by asking people, you don't deserve to have the data to begin with. Do better.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
