### ISSUE TITLE
Opt-out request for fockjef

### ISSUE THREAD

**Issue by fockjef** [bigcode-project/opt-out-v2#67]
I request that the following data is removed from The Stack and StackOverflow:

 - fockjef/canyouhackit
 - fockjef/cme-data
 - fockjef/dehz
 
_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
