### ISSUE TITLE
Opt-out request for prymitive

### ISSUE THREAD

**Issue by prymitive** [bigcode-project/opt-out-v2#670]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - prymitive/bootstrap-breadcrumbs
 - prymitive/bootstrap-breadcrumbs-test
 - prymitive/breadcrumbs-test
 - prymitive/karma
 - prymitive/kthxbye
 - prymitive/pumpkin
 - prymitive/unsee
 - prymitive/upaas
 - prymitive/upaas-client
 - prymitive/upaas-router

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
