### ISSUE TITLE
Opt-out is abusive

### ISSUE THREAD

**Issue by holsta** [bigcode-project/opt-out-v2#671]
I request that ALL following data is removed from The Stack:

holsta/dotfiles
holsta/gw_menu
holsta/mblaze
holsta/mongers.org
holsta/mystuff
holsta/snakeoil.dk
holsta/unix-faq.dk

How dare you even take my work?

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
