### ISSUE TITLE
Opt out CategoryOfJessica

### ISSUE THREAD

**Issue by ghost** [bigcode-project/opt-out-v2#673]
I request that the following data is removed from The Stack:

-  CategoryOfJessica/adventures_in_vectors
- CategoryOfJessica/cloudsole-angular
- CategoryOfJessica/codearbitr
- CategoryOfJessica/django-skeleton
- CategoryOfJessica/haskell-tetris
- CategoryOfJessica/idea-rust
- CategoryOfJessica/jakemick.github.com
- CategoryOfJessica/kaggle
- CategoryOfJessica/mumu
- CategoryOfJessica/pycoevolve
- CategoryOfJessica/pylearn2
- CategoryOfJessica/risp
- CategoryOfJessica/time

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
