### ISSUE TITLE
Opt-out request for kinnison

### ISSUE THREAD

**Issue by kinnison** [bigcode-project/opt-out-v2#683]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - kinnison/bounce
 - kinnison/casplay
 - kinnison/crev-proofs
 - kinnison/dotfiles
 - kinnison/enumber
 - kinnison/external-brain
 - kinnison/frango
 - kinnison/gir
 - kinnison/git-sync
 - kinnison/git-testament
 - kinnison/gloo
 - kinnison/haskell-conway
 - kinnison/infrafish
 - kinnison/infrafish-mailconfig
 - kinnison/lua-lace
 - kinnison/marked-yaml
 - kinnison/nixos-hosts
 - kinnison/pikchr
 - kinnison/proc-macro-workshop
 - kinnison/rpgp
 - kinnison/rust-clippy
 - kinnison/rustdoc-stripper
 - kinnison/shared-storage
 - kinnison/sudoku
 - kinnison/tower-grpc
 - kinnison/wordle
 - kinnison/yew

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
