### ISSUE TITLE
Opt-out request: my entire account

### ISSUE THREAD

**Issue by stephenmartindale** [bigcode-project/opt-out-v2#688]
I request that the following data is removed from The Stack:

 - all
 - everything associated with my entire GitHub username
 - everything I contribute, anywhere, ever, or ever have
 
_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.
...

"Opt out" is *not* a mechanism for consent. I did not consent for my creative works to be used in your data-set.

I judge the use of my works to be an abuse. Desist. Never harvest my contributions, again.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
