### ISSUE TITLE
Opt-out request for lindakatcodes

### ISSUE THREAD

**Issue by lindakatcodes** [bigcode-project/opt-out-v2#692]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - lindakatcodes/100-days-of-code
 - lindakatcodes/AoCd8
 - lindakatcodes/StampInventory
 - lindakatcodes/adventOfCode2016
 - lindakatcodes/beginner-javascript
 - lindakatcodes/budget-app
 - lindakatcodes/crypto-tools
 - lindakatcodes/learnwithjason.dev
 - lindakatcodes/lindakat-blogs
 - lindakatcodes/lindakatblogs
 - lindakatcodes/lindakatcodes
 - lindakatcodes/logolinks
 - lindakatcodes/minisites
 - lindakatcodes/node-course-files
 - lindakatcodes/portfolio
 - lindakatcodes/reactive-state-ngrx
 - lindakatcodes/rust-projects
 - lindakatcodes/startpage
 - lindakatcodes/tandem-trivia
 - lindakatcodes/thisDot-ghUserSearch
 - lindakatcodes/travelAgency
 - lindakatcodes/unit-testing-vm

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
