### ISSUE TITLE
Opt-out request for astatide

### ISSUE THREAD

**Issue by astatide** [bigcode-project/opt-out-v2#697]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - astatide/QTMatPlot
 - astatide/actos-dashboard
 - astatide/calliope.net
 - astatide/chapel-python-orchestration
 - astatide/chonglabscripts
 - astatide/chplUUID
 - astatide/chpllog
 - astatide/h5com
 - astatide/netctl-auto-gnome
 - astatide/p53-amber-westpa
 - astatide/westpa
 - astatide/westpa-docker
 - astatide/westpa2018analysis
 - astatide/westpa_tutorials

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by astatide** [comment]
As an aside: for a company that bills itself as ethical, why are you pulling the same unethical stuff as Microsoft here?

**Comment by astatide** [comment]
I am glad you opened up that my data was included, but opt out is blatantly unethical.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
