### ISSUE TITLE
Opt-out request for fabio-melo

### ISSUE THREAD

**Issue by fabio-melo** [bigcode-project/opt-out-v2#699]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - fabio-melo/APA-heuristics
 - fabio-melo/CinemaLib
 - fabio-melo/Cinemascopio
 - fabio-melo/Class-Assignments-and-Projects
 - fabio-melo/Compa
 - fabio-melo/Compiler
 - fabio-melo/Feicebuque
 - fabio-melo/ICG
 - fabio-melo/Noise-IoT
 - fabio-melo/NumericalCalculus
 - fabio-melo/SARI
 - fabio-melo/SortingAlgorithms
 - fabio-melo/VLC_MultiProxy
 - fabio-melo/audionet
 - fabio-melo/compasso-node
 - fabio-melo/instaru-client
 - fabio-melo/instaru-server
 - fabio-melo/photoria

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
