### ISSUE TITLE
Opt-out request for alxsimon

### ISSUE THREAD

**Issue by alxsimon** [bigcode-project/opt-out-v2#700]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - alxsimon/Hybrid_fitness_Fisher_geometric_model
 - alxsimon/Scripts
 - alxsimon/Teaser
 - alxsimon/assembly_10x
 - alxsimon/container_admix_genomes
 - alxsimon/insdc-pipeline
 - alxsimon/ms_myt_demo
 - alxsimon/personal_website

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
