### ISSUE TITLE
Opt-out request for madsbuch

### ISSUE THREAD

**Issue by madsbuch** [bigcode-project/opt-out-v2#701]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - madsbuch/CUDA_PSO
 - madsbuch/applicationCourse
 - madsbuch/atm-example
 - madsbuch/blog
 - madsbuch/elm-chat
 - madsbuch/fibonacci
 - madsbuch/finansmaskinen
 - madsbuch/fog
 - madsbuch/haskell-nn
 - madsbuch/issue_racer
 - madsbuch/lambda
 - madsbuch/madsbuch.com
 - madsbuch/ppl-playground
 - madsbuch/presentations
 - madsbuch/probabilistic-programming-report
 - madsbuch/pvc-os-notes
 - madsbuch/scalable-ml-service
 - madsbuch/second-brain-demo
 - madsbuch/snippets
 - madsbuch/storebox-api
 - madsbuch/thesis
 - madsbuch/types-and-time-experiments
 - madsbuch/usebounce

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
