### ISSUE TITLE
Opt-out request for mikemerritt

### ISSUE THREAD

**Issue by mikemerritt** [bigcode-project/opt-out-v2#704]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - mikemerritt/LaravelTodo
 - mikemerritt/NodeMVC
 - mikemerritt/NodeRest
 - mikemerritt/Rails4-Boilerplate-App
 - mikemerritt/SRG
 - mikemerritt/cloudsearch
 - mikemerritt/fish-config
 - mikemerritt/rails-api-starter
 - mikemerritt/rails5-react-jasmine
 - mikemerritt/react-hooks-example
 - mikemerritt/react-redux-starter
 - mikemerritt/rest-api-starter

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
