### ISSUE TITLE
Opt-out request for durranee

### ISSUE THREAD

**Issue by durranee** [bigcode-project/opt-out-v2#705]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - durranee/3AI-BnB
 - durranee/Airport-Challenge-CSharp
 - durranee/Battle
 - durranee/Boris-bikes2
 - durranee/CV
 - durranee/Chitter-Python
 - durranee/Coursera
 - durranee/Deloitte_Raindrops_Tech_Test
 - durranee/FizzBuzz
 - durranee/FizzBuzz-JS
 - durranee/JavaAirport
 - durranee/Shepard
 - durranee/Tech-Test--Database-Server
 - durranee/Tic-Tac-Toe
 - durranee/bank-account-tech-test-CSharp
 - durranee/bank-tech-test
 - durranee/bookmark-manager
 - durranee/bookmark_manager
 - durranee/boris_bike_project
 - durranee/bowling-challenge
 - durranee/chitter-challenge
 - durranee/clmystery
 - durranee/country_maps
 - durranee/ctest
 - durranee/database-server-Tech-Test
 - durranee/instagram-challenge
 - durranee/oyster-card
 - durranee/sky_billing
 - durranee/student-directory
 - durranee/thermostat-challenge

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
