### ISSUE TITLE
Opt-out request for mfkp

### ISSUE THREAD

**Issue by mfkp** [bigcode-project/opt-out-v2#706]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: powers
 - mfkp/ACEToolKit
 - mfkp/Dat-What-She-Say
 - mfkp/HexClock-android
 - mfkp/HexClock-iOS
 - mfkp/VideoStreamer
 - mfkp/Waveform.me
 - mfkp/active_admin_jcrop
 - mfkp/backtrace
 - mfkp/chrome-nfc
 - mfkp/drinkrobot
 - mfkp/gassy
 - mfkp/getrepresented
 - mfkp/grabmycard
 - mfkp/hbizzle
 - mfkp/intercom2frontapp
 - mfkp/menu_image_processor
 - mfkp/mfkp-devtools-theme
 - mfkp/pigz
 - mfkp/pro-forma
 - mfkp/promo
 - mfkp/rgb-quiz
 - mfkp/stopfriendspam
 - mfkp/swing
 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
