### ISSUE TITLE
Opt-out request for nigelbarink

### ISSUE THREAD

**Issue by nigelbarink** [bigcode-project/opt-out-v2#71]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - nigelbarink/AchingAbbey_android
 - nigelbarink/Datastructes_ProblemSolving
 - nigelbarink/LD38Source
 - nigelbarink/LudumDare30Source
 - nigelbarink/LudumDare32Source
 - nigelbarink/LudumDare33Source
 - nigelbarink/LudumDare35Source
 - nigelbarink/LudumDare36Source
 - nigelbarink/LudumDare37Source
 - nigelbarink/LudumDare40
 - nigelbarink/Ludumdare41
 - nigelbarink/MR.Face
 - nigelbarink/MiniLD38Source
 - nigelbarink/ProjectMightySpud
 - nigelbarink/PythonScripts
 - nigelbarink/R3c0v3r
 - nigelbarink/Vigenere_cipher
 - nigelbarink/Zavia_GameEngine
 - nigelbarink/aching-abbey-server
 - nigelbarink/nigelbarink.github.io
 - nigelbarink/simply_ava

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
