### ISSUE TITLE
Opt-out request for seichter

### ISSUE THREAD

**Issue by seichter** [bigcode-project/opt-out-v2#714]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - seichter/CMake-Toolchain-Collection
 - seichter/CompleteProject
 - seichter/Game
 - seichter/QuizGame
 - seichter/Rockover
 - seichter/Test005
 - seichter/TooN
 - seichter/bvrpn
 - seichter/d2relay
 - seichter/grdx
 - seichter/kfusion
 - seichter/pyimgfolder
 - seichter/sandbox
 - seichter/technoboot
 - seichter/uvrpn

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
