### ISSUE TITLE
Opt-out request for alexrudy

### ISSUE THREAD

**Issue by alexrudy** [bigcode-project/opt-out-v2#723]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - alexrudy/AOC2019
 - alexrudy/AoC2017
 - alexrudy/AoC2018
 - alexrudy/Cauldron
 - alexrudy/ClapBot
 - alexrudy/ControlTheory
 - alexrudy/FTR
 - alexrudy/Flox
 - alexrudy/Instapaper-Liked-Article-Posts
 - alexrudy/KOPy
 - alexrudy/KeckTeX
 - alexrudy/OSIRISDB
 - alexrudy/OsirisDRP
 - alexrudy/ShaneAOTelemetry
 - alexrudy/Zeeko
 - alexrudy/adventofcode2016
 - alexrudy/alexrudy-theme
 - alexrudy/alexrudy.net
 - alexrudy/aopy
 - alexrudy/astropy
 - alexrudy/astropyephem
 - alexrudy/beaker
 - alexrudy/cf-setter
 - alexrudy/dotfiles
 - alexrudy/dstk
 - alexrudy/elk-compose
 - alexrudy/flask-coffee2js
 - alexrudy/lumberjack
 - alexrudy/mkadsbib
 - alexrudy/mpfit-astropy
 - alexrudy/pushover
 - alexrudy/pyobserver
 - alexrudy/pystellar
 - alexrudy/sklyaml
 - alexrudy/sqla_model_context
 - alexrudy/supertunnel
 - alexrudy/tox-server
 - alexrudy/urlsplit

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
