### ISSUE TITLE
Opt-out request for MrPetovan

### ISSUE THREAD

**Issue by MrPetovan** [bigcode-project/opt-out-v2#729]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: `hypolite-petovan`
 - `MrPetovan/Borderlines`
 - `MrPetovan/friendica-addons`
 - All

Also I shouldn't have had to do this.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
