### ISSUE TITLE
Opt-out request for gretel

### ISSUE THREAD

**Issue by gretel** [bigcode-project/opt-out-v2#734]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: jitter
 - gretel/ExpressLRS
 - gretel/MIDIsync
 - gretel/OpenSMTPD
 - gretel/SmplLggr
 - gretel/TickTock
 - gretel/as3xmppclient
 - gretel/autobitch
 - gretel/chef-cookbooks
 - gretel/comfortable-mexican-sofa
 - gretel/distance
 - gretel/dotenv
 - gretel/dotfiles
 - gretel/dynamo-autoscale-fork
 - gretel/exhibitor
 - gretel/http-stress
 - gretel/jquery-smooth-scroll-rails
 - gretel/lubrick
 - gretel/openbsd-wip
 - gretel/pragmaprompt
 - gretel/squeegee
 - gretel/squeegee-run
 - gretel/wa-ansible
 - gretel/wa-extract
 - gretel/wa-peco
 - gretel/wachsamkeit
 - gretel/wipy-mqtt-motion

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
