### ISSUE TITLE
Opt-out request for cblades

### ISSUE THREAD

**Issue by cblades** [bigcode-project/opt-out-v2#740]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - cblades/Readit
 - cblades/Slider
 - cblades/StopWatch
 - cblades/Vector-Library-in-C
 - cblades/bluebirdtracker
 - cblades/dup
 - cblades/ficusjs
 - cblades/tcex
 - cblades/Greyscale
 - cblades/Java-DNS-Resolver
 - cblades/Java-Email-Client
 - cblades/List-in-C
 - cblades/MIPS-projects
 - cblades/Modern-Art-Generator
 - cblades/Paint-Clone-in-Java
 - cblades/Raytracer

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
