### ISSUE TITLE
Opt-out request for mxamber

### ISSUE THREAD

**Issue by mxamber** [bigcode-project/opt-out-v2#75]
I request and demand that any and all data created or authored by me is removed from The Stack, including but not limited to:

 - all GitHub commits by me
 - all GitHub issues opened by me, or comments I contributed to GitHub issues
 - all GitHub repositories maintained, created, owned, or managed by me, especially including (but not limited to) repositories included by your own admission as per the screenshot below: mxamber/AO3scrape, mxamber/DavidSarifBot, mxamber/ScrapingFromOurOwn, mxamber/TimelineTool, mxamber/bmpurge, mxamber/brexit-meme-bot, mxamber/shash, mxamber/twitter_convo_view.
 - any and all other data, content, code, resources, media, etc. created by me
 
![image](https://github.com/bigcode-project/opt-out-v2/assets/13611718/bec566ab-e6f9-4a76-9b71-b66d237099d7)

**Comment by mxamber** [comment]
Furthermore, I must point out that some of my repositories that you included were *not* licensed under any free licenses (not MIT, not GPL, nothing = all copyright retained). Including these for processing and redistribution in altered form in a way that is not covered by fair use is a violation of applicable intellectual property law.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
