### ISSUE TITLE
Opt-out request for squaregoldfish

### ISSUE THREAD

**Issue by squaregoldfish** [bigcode-project/opt-out-v2#750]
What on earth made you think this was a reasonable way to behave?

I require that the following data is removed and excluded from The Stack, StackOverflow, and any other projects, current or future, that you or any of your associates create:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - squaregoldfish/CDI_Generator
 - squaregoldfish/CatalogCleaner
 - squaregoldfish/DLA
 - squaregoldfish/GloegeMcKinley
 - squaregoldfish/Hurricane-CO2-Flux
 - squaregoldfish/KPI
 - squaregoldfish/LongWebcam
 - squaregoldfish/PixelSorter
 - squaregoldfish/QC_Routines
 - squaregoldfish/SQLite.jl
 - squaregoldfish/UEA-SI
 - squaregoldfish/blink_apps
 - squaregoldfish/bradshaw-tracks
 - squaregoldfish/gimp-plugins
 - squaregoldfish/jsColorScale
 - squaregoldfish/mediasummary
 - squaregoldfish/pco2_autocorrelation
 - squaregoldfish/socat
 - squaregoldfish/squaregoldfish.co.uk
 - squaregoldfish/statuspi

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
