### ISSUE TITLE
Opt-out request for armintoepfer

### ISSUE THREAD

**Issue by armintoepfer** [bigcode-project/opt-out-v2#751]
I request that the following data is removed from The Stack and StackOverflow:

 - armintoepfer/BAMExtract
 - armintoepfer/ConsensusCore2
 - armintoepfer/QuasiViz
 - armintoepfer/bam-io-throughput
 - armintoepfer/bauhaus
 - armintoepfer/fastpool
 - armintoepfer/ggeyecandy
 - armintoepfer/homebrew-science
 - armintoepfer/minimap2
 - armintoepfer/minimap2-meson
 - armintoepfer/pbccs
 - armintoepfer/pbmm2
 - armintoepfer/pitchfork
 - armintoepfer/uhu
 - armintoepfer/xavier

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
