### ISSUE TITLE
Opt-out request for BjerknesClimateDataCentre

### ISSUE THREAD

**Issue by squaregoldfish** [bigcode-project/opt-out-v2#753]
What on earth made you think this was a reasonable way to behave?

I require that the following data is removed and excluded from The Stack, StackOverflow, and any other projects, current or future, that you or any of your associates create.

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - BjerknesClimateDataCentre/CDI_Generator
 - BjerknesClimateDataCentre/ICOS-Labelling
 - BjerknesClimateDataCentre/SOCAT_ICOS_Uploader
 - BjerknesClimateDataCentre/glodap
 - BjerknesClimateDataCentre/QuinCe

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by raggi** [comment]
just a friendly passer by, you might want to actually put some license text in your repos, the only license text i could find was MIT in one of those repositories.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
