### ISSUE TITLE
Opt-out request for phooky

### ISSUE THREAD

**Issue by phooky** [bigcode-project/opt-out-v2#76]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - phooky/Apple-410
 - phooky/Avr24bMath
 - phooky/BlinkyTape
 - phooky/Crystal
 - phooky/Dome
 - phooky/EgglarmClock
 - phooky/Fractals
 - phooky/Github-to-Lighthouse-Issue-Migrator
 - phooky/PRU_template
 - phooky/PumaArm
 - phooky/SolidConway
 - phooky/VT100-Hax
 - phooky/VisualExperiments
 - phooky/Washing-Machine
 - phooky/bootarooni
 - phooky/contact-tracing-ble
 - phooky/ds_store
 - phooky/esp32-ttgo
 - phooky/golang
 - phooky/inventory
 - phooky/model_slice
 - phooky/phovena
 - phooky/space-automation
 - phooky/spacebrew-python-examples
 - phooky/usb-mspgcc
 - phooky/vidshifter
 - phooky/vlogging
 - phooky/winoneforthegiffer

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
