### ISSUE TITLE
Opt-out request for tsbehlman

### ISSUE THREAD

**Issue by tsbehlman** [bigcode-project/opt-out-v2#761]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - tsbehlman/Condensed
 - tsbehlman/FastMin
 - tsbehlman/Injector
 - tsbehlman/Matcher
 - tsbehlman/Pinlet
 - tsbehlman/SwiftOniguruma
 - tsbehlman/bayer-dithering
 - tsbehlman/hackernews
 - tsbehlman/hackernews-ios
 - tsbehlman/line-scanner
 - tsbehlman/live-wallpaper
 - tsbehlman/micro-http-router
 - tsbehlman/node-worker-threads-pool
 - tsbehlman/ocean-floor
 - tsbehlman/reactive-jsx
 - tsbehlman/ring-buffer
 - tsbehlman/rusty-iterator-utils
 - tsbehlman/shrinkability
 - tsbehlman/slim-cover
 - tsbehlman/slim-firebase-mock
 - tsbehlman/stocks-app-surplus
 - tsbehlman/transformer
 - tsbehlman/traveler
 - tsbehlman/tslint-eslint-rules
 - tsbehlman/webgl-bokeh-effect
 - tsbehlman/what-the-pack

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
