### ISSUE TITLE
Opt-out request for mattmassicotte

### ISSUE THREAD

**Issue by mattmassicotte** [bigcode-project/opt-out-v2#764]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: mattie
 - mattmassicotte/CITestApp
 - mattmassicotte/ScrollJumping
 - mattmassicotte/Three.tmbundle
 - mattmassicotte/ViewLayoutTest
 - mattmassicotte/bootloader-tutorial
 - mattmassicotte/c-dependecies
 - mattmassicotte/chime
 - mattmassicotte/config
 - mattmassicotte/kernel-tutorial
 - mattmassicotte/osin-cassandra-store
 - mattmassicotte/rake-compile
 - mattmassicotte/rake-multifile
 - mattmassicotte/spark
 - mattmassicotte/three
 - mattmassicotte/three-core-collection
 - mattmassicotte/three-core-event
 - mattmassicotte/three-core-execution
 - mattmassicotte/three-core-io
 - mattmassicotte/three-core-network

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
