### ISSUE TITLE
Opt-out request for rricard

### ISSUE THREAD

**Issue by rricard** [bigcode-project/opt-out-v2#766]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - rricard/MobileSync
 - rricard/MotionScience
 - rricard/ReducTyped
 - rricard/agendas
 - rricard/ansible-coreos
 - rricard/atomstore
 - rricard/bs-graphql-bindings
 - rricard/caffeface
 - rricard/create-react-app
 - rricard/crx-rt-fx
 - rricard/disque-jockey
 - rricard/dot
 - rricard/dotatom
 - rricard/esswag
 - rricard/firewatch-hot-syntax
 - rricard/graph-quill
 - rricard/graph-spec
 - rricard/graphql-cli
 - rricard/graphql-cli-codegen
 - rricard/hashcode16
 - rricard/koa-swagger
 - rricard/lispster
 - rricard/mdmirror
 - rricard/miniscience
 - rricard/mongoose-fs
 - rricard/multireact
 - rricard/pl-graphql
 - rricard/playwithtensor
 - rricard/proposal-destructuring-private
 - rricard/prose-feed
 - rricard/reactive-graphql
 - rricard/resume
 - rricard/rricard.github.io
 - rricard/sspawn
 - rricard/winit

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
