### ISSUE TITLE
Opt-out request for apposada

### ISSUE THREAD

**Issue by apposada** [bigcode-project/opt-out-v2#770]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: apposada
 - apposada/pristine
 - apposada/translate_ids
 - apposada/whusblah

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
