### ISSUE TITLE
Opt-out request for cess11

### ISSUE THREAD

**Issue by cess11** [bigcode-project/opt-out-v2#771]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - cess11/d3stuff
 - cess11/dogquotes
 - cess11/dotfiles
 - cess11/factorlang
 - cess11/jolada
 - cess11/pil-tinies
 - cess11/rackvol
 - cess11/single-user-dungeon
 - cess11/slimb
 - cess11/xrxs

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
