### ISSUE TITLE
Opt-out request for danderson

### ISSUE THREAD

**Issue by danderson** [bigcode-project/opt-out-v2#784]
I request that the following data is removed from The Stack:

 - Commits
 - GitHub issue
 - danderson/caddy-builder
 - danderson/charts
 - danderson/client-go
 - danderson/conduits
 - danderson/coreadm
 - danderson/damnitisp
 - danderson/davetf
 - danderson/docker-containers
 - danderson/dotfiles
 - danderson/ee-usb-switch
 - danderson/gipam
 - danderson/go-kdl
 - danderson/go.universe.tf
 - danderson/gotmpl
 - danderson/homelab
 - danderson/ingress-nginx
 - danderson/intern
 - danderson/iris
 - danderson/k8s-from-scratch
 - danderson/kcpu
 - danderson/kidraw
 - danderson/kind
 - danderson/landscape
 - danderson/nat
 - danderson/natprobe
 - danderson/netlify-multi-branch-deploy-test
 - danderson/nix-codelab
 - danderson/nixos-hardware
 - danderson/nixpkgs
 - danderson/node_exporter
 - danderson/packer
 - danderson/pomerium
 - danderson/pxe
 - danderson/py-remoteexec
 - danderson/raceway
 - danderson/redo
 - danderson/rollersk8s
 - danderson/saltplayground
 - danderson/syscallz-rs
 - danderson/tailscale-aur
 - danderson/tftp
 - danderson/tlswrapper
 - danderson/tuntap
 - danderson/winfirewall
 - danderson/wireguard-go
 - all

This request also applies to all future activity on github associated with user "danderson", including but not limited to repositories, issues, pull requests and pages across the entire site.

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
