### ISSUE TITLE
Opt-out request for AnshumanTripathi

### ISSUE THREAD

**Issue by AnshumanTripathi** [bigcode-project/opt-out-v2#789]
I request that the following data is removed from The Stack:

- Commits
- GitHub issue
- AnshumanTripathi/CampusMapApp
- AnshumanTripathi/Data-Structures
- AnshumanTripathi/DataStructures
- AnshumanTripathi/FirebaseAndroid
- AnshumanTripathi/FlipkartAutomation
- AnshumanTripathi/HackerRank
- AnshumanTripathi/HelloDocker
- AnshumanTripathi/JavaSpring
- AnshumanTripathi/JavaWebServer
- AnshumanTripathi/KafkaConnectJDBC
- AnshumanTripathi/Math-Quiz-iOS
- AnshumanTripathi/MathQuizApp
- AnshumanTripathi/MobileSensorCloudEngine
- AnshumanTripathi/RestaurantApplication
- AnshumanTripathi/RxJavaQuering
- AnshumanTripathi/Selenium
- AnshumanTripathi/ShoppingMallLoyalty
- AnshumanTripathi/ShortURL
- AnshumanTripathi/TwitterPrototype
- AnshumanTripathi/alfred
- AnshumanTripathi/iReport
- AnshumanTripathi/maven-dependency-parser

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
