### ISSUE TITLE
Opt-out request for ftrvxmtrx

### ISSUE THREAD

**Issue by ftrvxmtrx** [bigcode-project/opt-out-v2#79]
I request that the following data is removed from The Stack:

 - Commits
 - GitHub issue
 - ftrvxmtrx/9tetris
 - ftrvxmtrx/Soundpipe
 - ftrvxmtrx/alock
 - ftrvxmtrx/aur-ocaml
 - ftrvxmtrx/build
 - ftrvxmtrx/cam2wav
 - ftrvxmtrx/emark
 - ftrvxmtrx/front9port_nix
 - ftrvxmtrx/glextwrapgen
 - ftrvxmtrx/gochipmunk
 - ftrvxmtrx/gopencl
 - ftrvxmtrx/gopg
 - ftrvxmtrx/gotaglib
 - ftrvxmtrx/groke
 - ftrvxmtrx/inclean
 - ftrvxmtrx/klocations
 - ftrvxmtrx/libcplml_vi
 - ftrvxmtrx/libfsevent
 - ftrvxmtrx/lolq
 - ftrvxmtrx/lschuck
 - ftrvxmtrx/m68k_9p
 - ftrvxmtrx/mavg
 - ftrvxmtrx/my-audio-experiments
 - ftrvxmtrx/nix-zx
 - ftrvxmtrx/omagic
 - ftrvxmtrx/omgfsm
 - ftrvxmtrx/oopenal
 - ftrvxmtrx/openal_src_notify
 - ftrvxmtrx/pq
 - ftrvxmtrx/progsdat
 - ftrvxmtrx/projecteuler-problems-ocaml
 - ftrvxmtrx/qvmgen
 - ftrvxmtrx/spigot-nix
 - ftrvxmtrx/testingo
 - ftrvxmtrx/zasm-4.0
 - ftrvxmtrx/zasm-4.0-libraries
 - all

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
