### ISSUE TITLE
Opt-out request for jship

### ISSUE THREAD

**Issue by jship** [bigcode-project/opt-out-v2#797]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - jship/Chivalruckus
 - jship/Hazmat
 - jship/ShipGL
 - jship/VimConfig
 - jship/autoexporter
 - jship/dlist-implementations
 - jship/dotfiles
 - jship/env-codewars
 - jship/filecache
 - jship/gchq-shading-puzzle2015
 - jship/glPortfolio
 - jship/haskell-beginners
 - jship/haskell-eventlogs-talk
 - jship/haskell-handles-talk
 - jship/hexy
 - jship/hexy-foundation
 - jship/hs-memory
 - jship/jship.github.io
 - jship/language-puppet
 - jship/logging-effect-extra
 - jship/ltree-dev-talk
 - jship/metronome
 - jship/mortgage-utils
 - jship/named
 - jship/nomyx-library
 - jship/okasaki-party
 - jship/overhang
 - jship/pep
 - jship/postgresql-tx
 - jship/snippets
 - jship/tao
 - jship/tasty-th
 - jship/tc-yolo
 - jship/ubee-utils
 - jship/vagrant-haskell-minimal
 - jship/win32

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
