### ISSUE TITLE
Opt-out request for 96312

### ISSUE THREAD

**Issue by 96312** [bigcode-project/opt-out-v2#8]
I request that the following data is removed from The Stack:

 - Commits
 - GitHub issue
 - 96312/simplify

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.0.1 of The Stack and all future versions. Also your data was not used for the training of StarCoder2.

[PROCESSED]
