### ISSUE TITLE
Removal Request

### ISSUE THREAD

**Issue by BrodyB** [bigcode-project/opt-out-v2#802]
I request that the following data is removed from The Stack:

- BrodyB/AllinOne
- BrodyB/FrontierPatronShootout
- BrodyB/GGJ2015
- BrodyB/HandyTools

I did not give consent to my work being used in such a manner. Thank you.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
