### ISSUE TITLE
Opt-out request for Brod8362

### ISSUE THREAD

**Issue by Brod8362** [bigcode-project/opt-out-v2#803]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - Brod8362/6502emu
 - Brod8362/SLOND
 - Brod8362/YoutubeDownloader
 - Brod8362/aoc2019
 - Brod8362/artifact-of-order
 - Brod8362/betterweather
 - Brod8362/breagg
 - Brod8362/cpp-for-dummies
 - Brod8362/customhudplugin
 - Brod8362/discord-bot
 - Brod8362/discord-bot-2
 - Brod8362/discordplugin
 - Brod8362/dreamwiki-syntax
 - Brod8362/elytraui
 - Brod8362/gbdev-test
 - Brod8362/hyperpong
 - Brod8362/i3blocklets
 - Brod8362/inheritable
 - Brod8362/ktane-password
 - Brod8362/lenovo-outlet-parser
 - Brod8362/linuxsync-app
 - Brod8362/linuxsync-client
 - Brod8362/modbot
 - Brod8362/mpdX
 - Brod8362/mtag
 - Brod8362/pipeline
 - Brod8362/sokoban
 - Brod8362/targetballfactory
 - Brod8362/vulture
 - Brod8362/yt2cd

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
