### ISSUE TITLE
Opt-out request for mavenraven

### ISSUE THREAD

**Issue by mavenraven** [bigcode-project/opt-out-v2#806]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - mavenraven/Samples
 - mavenraven/active_finite
 - mavenraven/alerter
 - mavenraven/bosh-bootloader
 - mavenraven/bosh-classroom
 - mavenraven/bosh-school
 - mavenraven/cacheddownloader
 - mavenraven/cc_v3
 - mavenraven/cell-deps-release
 - mavenraven/cf-deployment
 - mavenraven/cff
 - mavenraven/chronic-haskell
 - mavenraven/cisiren
 - mavenraven/cloudfoundry-installer
 - mavenraven/cloudfoundry-installer-base-image
 - mavenraven/cloudfoundry-installer-ci
 - mavenraven/concourse
 - mavenraven/concourse-docker-compose
 - mavenraven/csvToMaps
 - mavenraven/digestive-functors-validations
 - mavenraven/digital-ocean-crawler
 - mavenraven/etcd-release
 - mavenraven/familiar_os
 - mavenraven/fixedwidth2csv
 - mavenraven/ghost_blog_image_downloader
 - mavenraven/github-draft-release-resource
 - mavenraven/greenhouse-install-script-generator
 - mavenraven/hhunspell
 - mavenraven/if_warden
 - mavenraven/ios-server
 - mavenraven/la-bouche
 - mavenraven/lattice-tour
 - mavenraven/mm
 - mavenraven/mouser-match
 - mavenraven/mouser-match-rails
 - mavenraven/msdn-downloader
 - mavenraven/nested-docker-container
 - mavenraven/pack
 - mavenraven/rust-starter
 - mavenraven/sixties-graph
 - mavenraven/slackSQL
 - mavenraven/static_benchmark
 - mavenraven/tinder_for_toes
 - mavenraven/tmux-screen
 - mavenraven/trains
 - mavenraven/validations
 - mavenraven/validations-checkers
 - mavenraven/vitess
 - mavenraven/watch_code
 - mavenraven/weave-scope-release
 - mavenraven/windows-config-notes
 - mavenraven/windows_app_lifecycle
 - mavenraven/youtube-dl-web

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
