### ISSUE TITLE
Opt-out request for codemac

### ISSUE THREAD

**Issue by codemac** [bigcode-project/opt-out-v2#810]
I request that the following data is removed from The Stack and StackOverflow:

- all
 - Commits
 - GitHub issue
 - StackOverflow: codemac
 - codemac/adventofcode
 - codemac/blogit
 - codemac/codemac.github.com
 - codemac/config
 - codemac/cs2606p2
 - codemac/cs2606p3
 - codemac/datecut
 - codemac/dbug
 - codemac/docker-client-image
 - codemac/es-shell
 - codemac/focus-org
 - codemac/gotribe
 - codemac/grunt-docker-image
 - codemac/guix-pkgs
 - codemac/hriki
 - codemac/lips
 - codemac/ministat
 - codemac/nixos
 - codemac/ohio
 - codemac/r7rs-benchmarks
 - codemac/sigbuffer
 - codemac/statmac
 - codemac/tagmail
 - codemac/todo-py
 - codemac/yosumiru

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
