### ISSUE TITLE
Opt-out request for houthacker

### ISSUE THREAD

**Issue by houthacker** [bigcode-project/opt-out-v2#811]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - houthacker/dotfiles
 - houthacker/hdb
 - houthacker/hhdb
 - houthacker/hla
 - houthacker/libinspectfs
 - houthacker/lumberjack-parent
 - houthacker/mdbtools-java
 - houthacker/mysql-async-notifications
 - houthacker/reactive
 - houthacker/sentry-java-plugins
 - houthacker/sentry-php
 - houthacker/skaar
 - houthacker/skaar-modular
 - houthacker/storage-notifications
 - houthacker/wc-webhooks

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
