### ISSUE TITLE
Opt-out request for wiedi

### ISSUE THREAD

**Issue by wiedi** [bigcode-project/opt-out-v2#816]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - wiedi/CloudStack
 - wiedi/Xevres
 - wiedi/avalanche
 - wiedi/brainwash
 - wiedi/btccm
 - wiedi/core-cfg
 - wiedi/core-mail-api-cli
 - wiedi/core-proxy
 - wiedi/core-uplink
 - wiedi/coursera
 - wiedi/django
 - wiedi/django-netmgt
 - wiedi/dovecot-core-authd
 - wiedi/fpmc-js
 - wiedi/freamware
 - wiedi/free
 - wiedi/frupic
 - wiedi/gridomatic
 - wiedi/hashlink
 - wiedi/illumos-webman
 - wiedi/kumquat
 - wiedi/led-hive
 - wiedi/libmaia
 - wiedi/lightstep-tracer-python
 - wiedi/limeade
 - wiedi/limeade3
 - wiedi/mellorimon
 - wiedi/mi-core-mailapi
 - wiedi/mi-core-mbox
 - wiedi/mi-demo
 - wiedi/mibed
 - wiedi/munin_master_admin
 - wiedi/niemandsland
 - wiedi/node-dedupqueue
 - wiedi/node-niuri
 - wiedi/node-radiance
 - wiedi/nothingreallymatrix
 - wiedi/paranoiapoodle
 - wiedi/pkgsrc-wip
 - wiedi/pkgsrc-wip-1
 - wiedi/rcmdr
 - wiedi/slibtool
 - wiedi/smartos-munin-plugins
 - wiedi/soup-io-items
 - wiedi/trivialfix
 - wiedi/trollo
 - wiedi/unhardlink
 - wiedi/vpnadm
 - wiedi/xenbackup
 - wiedi/xenstats

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
