### ISSUE TITLE
Opt-out request for TAG-Epic

### ISSUE THREAD

**Issue by TAG-Epic** [bigcode-project/opt-out-v2#819]
I request that the following data is removed from The Stack:

 - all
 
_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.
...

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]

**Comment by TAG-Epic** [comment]
@lvwerra please remove *any* of my code from previous releases as well. I did not consent to my code being used in your data set *at all*. If you are gonna do the asshole thing and not even ask me before you share my code for AI shit, at least remove my code *completely*.
