### ISSUE TITLE
Opt-out request for Floby

### ISSUE THREAD

**Issue by Floby** [bigcode-project/opt-out-v2#82]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - Floby/Echo
 - Floby/Fake-images-please
 - Floby/JSONStream
 - Floby/Node-Websockets-Test
 - Floby/Purple
 - Floby/TermKit
 - Floby/comprise.flo.by
 - Floby/covidtracker-tools
 - Floby/crossroad
 - Floby/docker-akeneo
 - Floby/dodo.flo.by
 - Floby/dotfiles
 - Floby/dumbal.flo.by
 - Floby/elo-calculator
 - Floby/elo-calculator-app
 - Floby/ember-named-outlet-test
 - Floby/ember-simple-auth-auth0
 - Floby/estimate
 - Floby/event-sourced-dumbal
 - Floby/floby.github.com
 - Floby/front-compass
 - Floby/fusker
 - Floby/gwvault
 - Floby/hashtag-influenceur
 - Floby/homebrew-hello
 - Floby/hoxy
 - Floby/jest-expect-error
 - Floby/jest-retries
 - Floby/jest-wtf
 - Floby/kanso
 - Floby/key-file-storage
 - Floby/lambda-left-pad
 - Floby/lazyboss
 - Floby/level-promise
 - Floby/log-file-watcher
 - Floby/mocha-rest-interface
 - Floby/module-boilerplate
 - Floby/module-highlight
 - Floby/mosic
 - Floby/nigel
 - Floby/node-blue
 - Floby/node-bulkage
 - Floby/node-cache-depend
 - Floby/node-catstream
 - Floby/node-deep-getset
 - Floby/node-dojo
 - Floby/node-dummy-streaming-array-parser
 - Floby/node-duplex-maker
 - Floby/node-envie
 - Floby/node-exist
 - Floby/node-geste
 - Floby/node-http-measuring-client
 - Floby/node-json-tokenizer
 - Floby/node-ka-ching
 - Floby/node-meme
 - Floby/node-micro-sleep
 - Floby/node-microauth2
 - Floby/node-milf
 - Floby/node-musette
 - Floby/node-object-iterator
 - Floby/node-office-music
 - Floby/node-pipeline-walker
 - Floby/node-prophet
 - Floby/node-services-as-promised
 - Floby/node-sse-reader
 - Floby/node-sse-writer
 - Floby/node-stream-blackhole
 - Floby/node-stream-qsort
 - Floby/node-stream-sink
 - Floby/node-stream-write-read
 - Floby/node-umzug-dynamodb-storage
 - Floby/node-url-assembler
 - Floby/node-voice
 - Floby/node-wirenock
 - Floby/nodejsparis-addons
 - Floby/nodejsparis-express-hapi
 - Floby/nodejsparis-streams
 - Floby/npm2dock
 - Floby/npmake
 - Floby/npmd-peers
 - Floby/obs-bodypix-filter
 - Floby/oroshi
 - Floby/peasy
 - Floby/quickie-node
 - Floby/react-json-rules-engine
 - Floby/shi-flo-by
 - Floby/snipmate-nodejs
 - Floby/terraform-npm
 - Floby/terraform-provider-keycloak
 - Floby/twss.js
 - Floby/vim-config
 - Floby/vim-css-color
 - Floby/vitemadose
 - Floby/vitemadose-front
 - Floby/vnc-over-gif
 - Floby/www.flo.by
 - Floby/zmq-stream

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
