### ISSUE TITLE
Opt-out request for Firedrake

### ISSUE THREAD

**Issue by Firedrake** [bigcode-project/opt-out-v2#820]
I request that the following data is removed from The Stack and StackOverflow:

 - Firedrake/Geo-OSM-Imager
 - Firedrake/acme-tiny-wrapper
 - Firedrake/aikakirja
 - Firedrake/cosmogenesis
 - Firedrake/discworld-rpg
 - Firedrake/fullback
 - Firedrake/mpd-tools
 - Firedrake/nobraketracker
 - Firedrake/postoffice-fixup
 - Firedrake/skutil
 - all

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
