### ISSUE TITLE
Opt-out request for happybeing

### ISSUE THREAD

**Issue by happybeing** [bigcode-project/opt-out-v2#822]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - happybeing/SPARQL-endpoints-lists
 - happybeing/decorum-lib
 - happybeing/mashlib
 - happybeing/rfcs
 - happybeing/safe_web_app_quick_start_completed
 - happybeing/solid-plume
 - happybeing/svelte-go-wasm-experiments
 - happybeing/svelte-tags-input
 - happybeing/svelte-wasi-with-rust

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]

**Comment by happybeing** [comment]
I hadn't read about it seen an option to remove 'all', and so wish to update to ensure that is applied.

'all'

Thanks
