### ISSUE TITLE
Opt-out request for kevincrane

### ISSUE THREAD

**Issue by kevincrane** [bigcode-project/opt-out-v2#823]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - kevincrane/catfacts
 - kevincrane/cmu-mse-costcode
 - kevincrane/cryptochallenges
 - kevincrane/distsys-f13
 - kevincrane/dotfiles
 - kevincrane/flaskblog
 - kevincrane/kevcrablog
 - kevincrane/mailarep
 - kevincrane/nachos-csci402
 - kevincrane/spotbot-playlister
 - kevincrane/startupeng
 - kevincrane/wikimap
 - kevincrane/windowsill

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

*P.S.* With all due respect, fuck you guys. Siphoning up my repos without permission is fucked up and I know you that you know it. Show a little goddamn respect for people for once you ghouls.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]

**Comment by kevincrane** [comment]
@lvwerra I'd like to clarify that you deleted my data from all versions previous to v2.1 as well please. I never agreed to be part of your training, and unless you're paying me for my work then I don't want it included.

**Comment by kevincrane** [comment]
And if you can't delete my previous data, then what is the best way to receive money from you? Obviously I'm not letting you profit off of my work for free.
