### ISSUE TITLE
Opt-out request for seamusriordan

### ISSUE THREAD

**Issue by seamusriordan** [bigcode-project/opt-out-v2#828]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - seamusriordan/Exposing-Novel-Quark-and-Gluon-Effects-in-Nuclei
 - seamusriordan/G4MC
 - seamusriordan/XrmPlay
 - seamusriordan/XrmPlay452
 - seamusriordan/advent-of-code-2020-day-1
 - seamusriordan/advent-of-code-2020-day-2
 - seamusriordan/advent-of-code-2020-day-3
 - seamusriordan/advent-of-code-2020-day-8
 - seamusriordan/advent-of-code-day-01
 - seamusriordan/advent-of-code-day-02
 - seamusriordan/advent-of-code-day-03
 - seamusriordan/advent-of-code-day-04
 - seamusriordan/advent-of-code-day-05
 - seamusriordan/advent-of-code-day-06
 - seamusriordan/advent-of-code-day-4
 - seamusriordan/anagemdecode
 - seamusriordan/analyzer
 - seamusriordan/angular-testing-session
 - seamusriordan/bubbleExtract
 - seamusriordan/c200_controls
 - seamusriordan/coronav2
 - seamusriordan/csharpcore
 - seamusriordan/draftbuddy
 - seamusriordan/draftbuddy_python
 - seamusriordan/fizzbuzzWithSereres
 - seamusriordan/gilded-rose-clojure
 - seamusriordan/go-conways-life
 - seamusriordan/goLoopTDD
 - seamusriordan/hrstrans
 - seamusriordan/mlbscores
 - seamusriordan/pickaxe
 - seamusriordan/pprana
 - seamusriordan/prexRayTrace
 - seamusriordan/raytrace
 - seamusriordan/react-conways-life
 - seamusriordan/remoll_lih
 - seamusriordan/romannumeraladder-kata
 - seamusriordan/rxjs-demo
 - seamusriordan/sgdq-2019-schedule-grabber
 - seamusriordan/twobounce
 - seamusriordan/waterfall-kata
 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
