### ISSUE TITLE
Opt-out request for postmechanical

### ISSUE THREAD

**Issue by postmechanical** [bigcode-project/opt-out-v2#830]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - postmechanical/AwesomeMenu
 - postmechanical/LPMFetchedResultsDisplayManager
 - postmechanical/MSCachedAsyncViewDrawing
 - postmechanical/animationoptions
 - postmechanical/cocoaslopes-2013
 - postmechanical/cowboy-wisdom-swiftui
 - postmechanical/elevation-map
 - postmechanical/giphy-search
 - postmechanical/github-xcode-bot-builder
 - postmechanical/medly-code-challenge
 - postmechanical/memory-game
 - postmechanical/next-portfolio
 - postmechanical/patient-survey
 - postmechanical/simple-mobile-ticketing-task
 - postmechanical/swift-1
 - postmechanical/toothbrush-timer
 - postmechanical/word-search

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
