### ISSUE TITLE
Opt-out request for braids

### ISSUE THREAD

**Issue by braids** [bigcode-project/opt-out-v2#832]
I request that the following data is removed from The Stack and StackOverflow:

- all

**Comment by braids** [comment]
From https://www.softwareheritage.org/2023/10/19/swh-statement-on-llm-for-code/

> 3. Mechanisms should be established, where possible, for authors to exclude their archived code from the training inputs before model training begins. 

Providing only an opt-out system when my code has already been included in training data is a direct violation of Software Heritage' LLM principles.

**Comment by braids** [comment]
Hey! Why the fuck did you release v2.0.1 and my shit is **still** in it? Get my code out of your fucking LLM now.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]

**Comment by braids** [comment]
Cool that only took you a full month. Maybe if you had done opt-in in the first fucking place you wouldn't be dealing with this shit.
