### ISSUE TITLE
Opt-out request for florianeckerstorfer

### ISSUE THREAD

**Issue by florianeckerstorfer** [bigcode-project/opt-out-v2#834]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - florianeckerstorfer/4sqtokml
 - florianeckerstorfer/HttpEcho
 - florianeckerstorfer/Loveboard
 - florianeckerstorfer/Raptorize-for-Safari
 - florianeckerstorfer/SecretSanta
 - florianeckerstorfer/Snaphe
 - florianeckerstorfer/SublimeFilterLines
 - florianeckerstorfer/alfred-fillerama
 - florianeckerstorfer/alfred-iterm2-tabs
 - florianeckerstorfer/alfred-itunes
 - florianeckerstorfer/alfred-type-text
 - florianeckerstorfer/applescripts
 - florianeckerstorfer/applications
 - florianeckerstorfer/apprecorder
 - florianeckerstorfer/capitals
 - florianeckerstorfer/console-import-standard
 - florianeckerstorfer/const.sh
 - florianeckerstorfer/csvexcel
 - florianeckerstorfer/data-import-extra
 - florianeckerstorfer/demo-application
 - florianeckerstorfer/disable-snapengage.safariextension
 - florianeckerstorfer/domcss.js
 - florianeckerstorfer/domlight.js
 - florianeckerstorfer/dotfiles
 - florianeckerstorfer/dotfiles-old
 - florianeckerstorfer/download-site
 - florianeckerstorfer/dracula-theme
 - florianeckerstorfer/eleventy-plugin-remark
 - florianeckerstorfer/fetchfile
 - florianeckerstorfer/florian.ec
 - florianeckerstorfer/florianeckerstorfer.com
 - florianeckerstorfer/focusontheuser-safari
 - florianeckerstorfer/foop-exercises
 - florianeckerstorfer/foursquare-php
 - florianeckerstorfer/gatsby-plugin-advanced-feed
 - florianeckerstorfer/gatsby-remark-a11y-emoji
 - florianeckerstorfer/get-from
 - florianeckerstorfer/gifstream.florian.ec
 - florianeckerstorfer/grunt-sculpin
 - florianeckerstorfer/grunt-symfony2
 - florianeckerstorfer/guard-sculpin
 - florianeckerstorfer/gulp-anybar
 - florianeckerstorfer/homebrew-fe
 - florianeckerstorfer/ir-exercises
 - florianeckerstorfer/launchbar-actions
 - florianeckerstorfer/minmaxpos-polyfill
 - florianeckerstorfer/mysql-bash-completion
 - florianeckerstorfer/namespacify
 - florianeckerstorfer/passwordplease-alfred
 - florianeckerstorfer/passwordplease-php
 - florianeckerstorfer/plum-excel
 - florianeckerstorfer/popclipextensions
 - florianeckerstorfer/rdio-star-current-song
 - florianeckerstorfer/react-simple-image
 - florianeckerstorfer/react-tutorial
 - florianeckerstorfer/remark-a11y-emoji
 - florianeckerstorfer/repro-remark-a11y-emoji-next-mdx
 - florianeckerstorfer/scss_lint_reporter_junit
 - florianeckerstorfer/seldom.js
 - florianeckerstorfer/serialdom.js
 - florianeckerstorfer/shrt.at
 - florianeckerstorfer/subfony
 - florianeckerstorfer/subl-handler
 - florianeckerstorfer/sublime-config
 - florianeckerstorfer/sublime-grunt
 - florianeckerstorfer/sublime-mockery
 - florianeckerstorfer/sublime-phex
 - florianeckerstorfer/sublime-php
 - florianeckerstorfer/sublime-symfony2
 - florianeckerstorfer/symfony-bower-bootstrap
 - florianeckerstorfer/symfony-tools
 - florianeckerstorfer/tld-data
 - florianeckerstorfer/tutorial-gh-actions-aws-branch-deploy
 - florianeckerstorfer/viefood
 - florianeckerstorfer/vlc-disable-notifications
 - florianeckerstorfer/xn--mn8h5e.ws
 - florianeckerstorfer/xn--mn8hhf.ws

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
