### ISSUE TITLE
Opt-out request for kura

### ISSUE THREAD

**Issue by kura** [bigcode-project/opt-out-v2#836]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - kura/2sshfp
 - kura/adjective-animals
 - kura/amisecure
 - kura/apache-ip-digest
 - kura/apt-security
 - kura/atom-updater
 - kura/atom.io
 - kura/batfish
 - kura/blackhole.go
 - kura/blackhole.twisted
 - kura/blossom
 - kura/cyno-tracker
 - kura/deiman
 - kura/denyhosts-unban
 - kura/depends.in
 - kura/dotfiles
 - kura/eve-signature
 - kura/git-bash-functions
 - kura/gobozo
 - kura/homebrew-completions
 - kura/kindling
 - kura/kura.github.io
 - kura/mailenv-bootstrap
 - kura/nectar
 - kura/nectar-mta
 - kura/openresty-upstream-dns-example
 - kura/orbweaver
 - kura/postfix-mgmt
 - kura/purl
 - kura/pyannotate
 - kura/pybozo
 - kura/rabbitmq-munin
 - kura/rabbitmq-nagios
 - kura/rainbow-codes
 - kura/rainbowstream
 - kura/raspberrypi-mirror-scripts
 - kura/simplemta
 - kura/solr-munin
 - kura/tor-shields
 - kura/tugboat-bash-completion
 - kura/yarg

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
