### ISSUE TITLE
Opt-out request for yo-bj

### ISSUE THREAD

**Issue by yo-bj** [bigcode-project/opt-out-v2#837]
I request that the following data is removed from The Stack:

[yo-bj/Sierra-SQL](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/yo-bj/Sierra-SQL)

[yo-bj/dataviz](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/yo-bj/dataviz)

[yo-bj/dpla-dedupe](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/yo-bj/dpla-dedupe)

[yo-bj/hellotestworld](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/yo-bj/hellotestworld)

[yo-bj/organizer-manual](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/yo-bj/organizer-manual)

[yo-bj/sersol-localholdings](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/yo-bj/sersol-localholdings)

[yo-bj/sufia-app](https://archive.softwareheritage.org/browse/origin/visits/?origin_url=https://github.com/yo-bj/sufia-app)

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
