### ISSUE TITLE
Opt-out request for ismaRP

### ISSUE THREAD

**Issue by ismaRP** [bigcode-project/opt-out-v2#838]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - ismaRP/IRPBioinfCourse
 - ismaRP/MALDIpqi
 - ismaRP/MLCourse
 - ismaRP/MSMSdeamidation
 - ismaRP/MassUpUtils
 - ismaRP/SynBio_IBModels
 - ismaRP/SynBio_ODEmodels
 - ismaRP/a_spanish_book
 - ismaRP/binfHTA
 - ismaRP/deamidation
 - ismaRP/globeDataSci
 - ismaRP/myTest

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
