### ISSUE TITLE
Opt-out request for mkhl

### ISSUE THREAD

**Issue by mkhl** [bigcode-project/opt-out-v2#845]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - mkhl/Blurminal
 - mkhl/DashMate.tmbundle
 - mkhl/FastScripts.hgs
 - mkhl/JavaScript-Tern-Completion.tmbundle
 - mkhl/MKMacros
 - mkhl/autopairs.tea
 - mkhl/bash.sugar
 - mkhl/bin
 - mkhl/cli-www
 - mkhl/color-theme-espresso
 - mkhl/color-theme-quiet-light
 - mkhl/complate-bootstrap
 - mkhl/complate-stream
 - mkhl/dock-items.hgs
 - mkhl/dogs
 - mkhl/dotfiles
 - mkhl/dprox
 - mkhl/drag-stuff
 - mkhl/emacs
 - mkhl/ensime-node
 - mkhl/eslint-plugin-typescript-issue-no-unused-vars-parameter-properties
 - mkhl/espresso-tutti-colori.tmtheme
 - mkhl/extract-sourcemap
 - mkhl/faucet-pipeline
 - mkhl/faucet-pipeline-adapter
 - mkhl/faucet-pipeline-js
 - mkhl/faucet-pipeline-rot13
 - mkhl/faucet-pipeline-static
 - mkhl/faucet-pipeline.github.io
 - mkhl/finder-sidebar.hgs
 - mkhl/github.tmtheme
 - mkhl/go-tmbundle
 - mkhl/haskell.sugar
 - mkhl/homebrew-cask
 - mkhl/homebrew-custom
 - mkhl/hub
 - mkhl/iBlog
 - mkhl/issue-firefox-cache-content-range
 - mkhl/luhnybin
 - mkhl/megazoomer
 - mkhl/mkhl.github.com
 - mkhl/monocle.hgs
 - mkhl/nothing.tmtheme
 - mkhl/plan9port
 - mkhl/quiet-light.foam
 - mkhl/quiet-light.tmtheme
 - mkhl/rollup-plugin-cleanup
 - mkhl/run-script.hgs
 - mkhl/rust.tmbundle
 - mkhl/services.hgs
 - mkhl/smart-folders.hgs
 - mkhl/tabtab
 - mkhl/terminaltabswitching
 - mkhl/textmate.tmbundle
 - mkhl/thesis
 - mkhl/thor.tmbundle
 - mkhl/tm-syntax-inspector
 - mkhl/vimr
 - mkhl/xplor

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
