### ISSUE TITLE
Opt-out request for cvu232

### ISSUE THREAD

**Issue by tokorobin** [bigcode-project/opt-out-v2#853]
I request that the following data is removed from The Stack and StackOverflow:

- all

**Comment by lvwerra** [comment]
Hi @tokorobin, thanks for your opt-out request. Could you specify your relation with the @cvu232 account? Usually it's easiest for us the verify the validity of an opt-out request if it comes from the associated account.

**Comment by cvu232** [comment]
Oh, sorry! @cvu232 is my personal account. I accidentally replied with my work account, @tokorobin, apologies for the mixup!

**Comment by lvwerra** [comment]
No worries, will remove data associated with @cvu232 from the dataset!

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
