### ISSUE TITLE
Opt-out request for @johncalvinyoung

### ISSUE THREAD

**Issue by johncalvinyoung** [bigcode-project/opt-out-v2#856]
I request that the following data is removed from The Stack:

 - Commits
 - GitHub issue
 - johncalvinyoung/academy
 - johncalvinyoung/asset-rack
 - johncalvinyoung/bornloved

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
