### ISSUE TITLE
Opt-out request for oneeyedman

### ISSUE THREAD

**Issue by oneeyedman** [bigcode-project/opt-out-v2#857]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - oneeyedman/11ty-static
 - oneeyedman/Chuck-Progress-Bar-for-Jira
 - oneeyedman/GuessTheNumberReact
 - oneeyedman/Guilds
 - oneeyedman/Hello-Soldier
 - oneeyedman/Lemonade-kit.git
 - oneeyedman/S3.6-ex03
 - oneeyedman/Width-Snitch
 - oneeyedman/acordeon
 - oneeyedman/advent-of-code-2018
 - oneeyedman/advent-of-code-2019
 - oneeyedman/amiloquemegustaescocinar
 - oneeyedman/bash-stuff
 - oneeyedman/butterchuck
 - oneeyedman/canvas
 - oneeyedman/checkbox-accesible
 - oneeyedman/checkbox-legal
 - oneeyedman/ciclos-de-vida
 - oneeyedman/ciclos-de-vida-sin-unicornios
 - oneeyedman/clarke-s3-ZASS
 - oneeyedman/days-left
 - oneeyedman/dibujo-artistico-aplicado-al-front
 - oneeyedman/dorcas-s3-evaluacion-final-oneeyedman
 - oneeyedman/drum-kit
 - oneeyedman/e-s3-repaso-intermedio
 - oneeyedman/ejemplo-de-funcion-para-crear-elementos
 - oneeyedman/ejercicio-repaso-m2-coco
 - oneeyedman/emailSignatureGenerator
 - oneeyedman/eventos2
 - oneeyedman/ficha-de-personaje
 - oneeyedman/filtro-por-genero
 - oneeyedman/fork-you
 - oneeyedman/hdata
 - oneeyedman/isAndroid
 - oneeyedman/jasones
 - oneeyedman/learnTypescritpStarterKit
 - oneeyedman/m2-evaluacion-intermedia-pascualbeatriz
 - oneeyedman/mariet
 - oneeyedman/mini-hangman
 - oneeyedman/notify-yourself
 - oneeyedman/pairs
 - oneeyedman/paquito
 - oneeyedman/patito
 - oneeyedman/pokedex
 - oneeyedman/por-mis-props
 - oneeyedman/print-stuff
 - oneeyedman/project-template
 - oneeyedman/ramiro
 - oneeyedman/react-hooks
 - oneeyedman/repaso-flexbox-y-position
 - oneeyedman/repo-de-prieba
 - oneeyedman/repo_chungo
 - oneeyedman/repovacio
 - oneeyedman/s3.9-e02
 - oneeyedman/sesion2-11-ejercicio-cuatroh
 - oneeyedman/skills-everywhere
 - oneeyedman/smile-me
 - oneeyedman/states-in-react
 - oneeyedman/street-pagination-with-unicorns
 - oneeyedman/sublime-text-replacement-icon
 - oneeyedman/sublime-text-settings
 - oneeyedman/sublime-text-snippets
 - oneeyedman/terms
 - oneeyedman/test-2
 - oneeyedman/twitch-live-viewers
 - oneeyedman/unicorn-street-slider
 - oneeyedman/videoBG
 - oneeyedman/vue-in-65-minutes
 - oneeyedman/wtf
 - oneeyedman/xmas-tree

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
