### ISSUE TITLE
Opt-out request for ExoSkye

### ISSUE THREAD

**Issue by ExoSkye** [bigcode-project/opt-out-v2#858]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - ExoSkye/COVIDHeatmap
 - ExoSkye/EpiSim-Rework
 - ExoSkye/GY521
 - ExoSkye/Genres
 - ExoSkye/RGB4D
 - ExoSkye/ReMania-NF
 - ExoSkye/SFMLTemplate
 - ExoSkye/language-speed-test
 - ExoSkye/sdsclient-cpp

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
