### ISSUE TITLE
Opt-out request for spacenomads

### ISSUE THREAD

**Issue by oneeyedman** [bigcode-project/opt-out-v2#859]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - spacenomads/Asteroids.git
 - spacenomads/BarlosWeekendStreetCodeChallenge
 - spacenomads/Nebulae
 - spacenomads/Silex-Skeleton
 - spacenomads/What-the-time
 - spacenomads/asteroids
 - spacenomads/attributr
 - spacenomads/burrocracia
 - spacenomads/cssgrid
 - spacenomads/flexbox
 - spacenomads/float-time-for-Alfred
 - spacenomads/formacion-html-css
 - spacenomads/introduccion-svg
 - spacenomads/lemonade-email-signature
 - spacenomads/mis-oraciones
 - spacenomads/pantallas-retina-y-unidades
 - spacenomads/posicionamiento
 - spacenomads/profile
 - spacenomads/rocket
 - spacenomads/settings-and-stuff
 - spacenomads/the-eyes
 - spacenomads/ticketTime
 - spacenomads/today
 - spacenomads/waffly
 - spacenomads/ypirqi-for-alfred

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
