### ISSUE TITLE
Opt-out request for wyatt8740

### ISSUE THREAD

**Issue by wyatt8740** [bigcode-project/opt-out-v2#861]
I request that the following data is removed from The Stack and StackOverflow:

 - all
 - Commits
 - GitHub issue
 - StackOverflow: wyatt8740

Remove absolutely everything from me. All of it. ***And don't collect it or anything new again from my accounts.***

Consent is not opt out. Stop doing this. You have made me very angry that now I have to go through multiple github accounts and do this.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
