### ISSUE TITLE
Opt-out request for ruthtillman

### ISSUE THREAD

**Issue by ruthtillman** [bigcode-project/opt-out-v2#864]
I request that the following data is removed from The Stack and StackOverflow:

 - ruthtillman/EAS-TagLibraries
 - ruthtillman/archival.github.io
 - ruthtillman/batch-extract-ead-to-csv
 - ruthtillman/book-processing
 - ruthtillman/dacs
 - ruthtillman/ead3-stylesheets
 - ruthtillman/fcrepo_wrapper
 - ruthtillman/hedgewitch
 - ruthtillman/local-reconciliation-project
 - ruthtillman/mycoderef
 - ruthtillman/processing-batch-ingest
 - ruthtillman/psu-landgrabu-data
 - ruthtillman/ruthtillman.github.io
 - ruthtillman/starter_traject
 - ruthtillman/subjectreconscripts

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
