### ISSUE TITLE
Opt-out request for cz8s

### ISSUE THREAD

**Issue by cz8s** [bigcode-project/opt-out-v2#866]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - cz8s/HubSpot-Nagios-Plugins
 - cz8s/aleph-exporter
 - cz8s/aleph-exporter-1
 - cz8s/artillery-plugin-prometheus
 - cz8s/cooking-recipes
 - cz8s/cucumber-nagios
 - cz8s/dashing_jenkins
 - cz8s/fit
 - cz8s/git-lightningtalk
 - cz8s/gocd-metrics
 - cz8s/gocd-tests
 - cz8s/gpg_key_expiration_check
 - cz8s/ipv6-lightningtalk
 - cz8s/jabber_hilight_notify.pl
 - cz8s/jenkins-datadog-plugin
 - cz8s/kanboard
 - cz8s/leap_doc
 - cz8s/lgr-stopwatch
 - cz8s/localofficeday.github.io
 - cz8s/madmin
 - cz8s/mailpile-chrome-app
 - cz8s/pace
 - cz8s/pace-barcode-scanner
 - cz8s/pixelated_dashboard
 - cz8s/puppet-prometheus
 - cz8s/puppet-prometheus_reporter
 - cz8s/python-ant-downloader
 - cz8s/selfschleuder
 - cz8s/thoughtworks-wot

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
