### ISSUE TITLE
Opt-out request for namespace-ee

### ISSUE THREAD

**Issue by lnagel** [bigcode-project/opt-out-v2#869]
I request that the following data is removed from The Stack:

namespace-ee/ant-design

namespace-ee/cordova-background-geolocation-SampleApp

namespace-ee/deployer-django

namespace-ee/django-drip-marketing

namespace-ee/django-electron-pdf

namespace-ee/invoice-template

namespace-ee/namespace-ee

namespace-ee/namespace-ee.github.io

namespace-ee/pakipoint-php

namespace-ee/react-calendar-timeline

namespace-ee/tickets-api-docs

namespace-ee/wagtailfroala
 
_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.
...

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
