### ISSUE TITLE
Opt-out request for edgarogh and our org (+ inclusion of all rights reserved code)

### ISSUE THREAD

**Issue by edgarogh** [bigcode-project/opt-out-v2#88]
I request that the following data is removed from The Stack:

 - all
 - Everything in [WartaPoirier-corp](https://github.com/WartaPoirier-corp) too, you're stealing some _all rights reserved_ code from us

I'm actually flabbergasted that you'd care to check for GPL license but feel like it's OK to take code that doesn't have a license file, as if that puts it in the public domain...

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
