### ISSUE TITLE
Opt-out request for stuarthicks

### ISSUE THREAD

**Issue by stuarthicks** [bigcode-project/opt-out-v2#892]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - stuarthicks/AgileDictionary
 - stuarthicks/bmx
 - stuarthicks/cidrr
 - stuarthicks/docker-ca-certs
 - stuarthicks/dotfiles
 - stuarthicks/etc
 - stuarthicks/euler-rs
 - stuarthicks/figure
 - stuarthicks/giffr
 - stuarthicks/goat
 - stuarthicks/homebrew-brews
 - stuarthicks/libmxfpp
 - stuarthicks/marklogic-java-xquery-stubs
 - stuarthicks/otp
 - stuarthicks/stuarthicks.github.io
 - stuarthicks/studious-robot
 - stuarthicks/tstools
 - stuarthicks/wiki
 - stuarthicks/xquery-stubbing
 - stuarthicks/youten
 - stuarthicks/zoidbot
 - stuarthicks/zsh-fancy-ctrl-z
 - stuarthicks/zsh-go
 - all

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
