### ISSUE TITLE
Opt-out request for brandtoliver

### ISSUE THREAD

**Issue by brandtoliver** [bigcode-project/opt-out-v2#895]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - brandtoliver/Computational_Tools
 - brandtoliver/Group-1
 - brandtoliver/SocialGraphs
 - brandtoliver/Stock-Market-prediction-using-ML-and-LDA-on-twitter-data
 - brandtoliver/brandtoliver.github.io
 - brandtoliver/brew-api
 - brandtoliver/covid19_mobility_africa
 - brandtoliver/plinvest
 - brandtoliver/to_pc

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
