### ISSUE TITLE
Opt-out request for ziebam

### ISSUE THREAD

**Issue by ziebam** [bigcode-project/opt-out-v2#897]
I request that the following data is removed from The Stack:

 - Commits
 - GitHub issue
 - ziebam/auto_project_builder
 - ziebam/chords_scraper
 - ziebam/game_of_life
 - ziebam/metrics_tracker
 - ziebam/simoldation

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
