### ISSUE TITLE
Opt-out request for g0dkar

### ISSUE THREAD

**Issue by g0dkar** [bigcode-project/opt-out-v2#9]
I request that the following data is removed from The Stack:

 - Commits
 - GitHub issue
 - g0dkar/abntex-ifpi
 - g0dkar/baixemaisram
 - g0dkar/bcpoc
 - g0dkar/g0dkar
 - g0dkar/mit-license
 - g0dkar/spring-api-comparator
 - g0dkar/tep-ifpi-2015-1
 - g0dkar/utils
 - g0dkar/vraptor-metrics
 - g0dkar/web-resume
 - g0dkar/websocket-debugger
 - g0dkar/xpto-planning

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.0.1 of The Stack and all future versions. Also your data was not used for the training of StarCoder2.

[PROCESSED]
