### ISSUE TITLE
Opt-out request for samuraisam

### ISSUE THREAD

**Issue by samuraisam** [bigcode-project/opt-out-v2#906]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - samuraisam/AngularGeo
 - samuraisam/IZGrowlManager
 - samuraisam/MoarVM
 - samuraisam/RIDE
 - samuraisam/angular-db
 - samuraisam/asyncio-aggregator
 - samuraisam/cassbounce
 - samuraisam/chief
 - samuraisam/chishop
 - samuraisam/clj-signing
 - samuraisam/ember-indexeddb-adapter
 - samuraisam/go-metrics-stathat
 - samuraisam/graphite-metrics
 - samuraisam/ipython-desktop
 - samuraisam/lazybeaver-server
 - samuraisam/lexical_uuid
 - samuraisam/media-nommer
 - samuraisam/messing-around-with-go
 - samuraisam/om-next-starter
 - samuraisam/p6-pb
 - samuraisam/p6-rethinkdb
 - samuraisam/padlock
 - samuraisam/pants
 - samuraisam/paranoidmail
 - samuraisam/pycassa
 - samuraisam/roast
 - samuraisam/rules_clojure
 - samuraisam/rust-image
 - samuraisam/sam-video
 - samuraisam/simple-timer
 - samuraisam/slacker
 - samuraisam/time_uuid

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
