### ISSUE TITLE
Opt-out request for ahugon

### ISSUE THREAD

**Issue by ahugon** [bigcode-project/opt-out-v2#912]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - ahugon/curarium-scripts
 - ahugon/dpla-query-builder
 - ahugon/neverwinter-masterwork
- all

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
