### ISSUE TITLE
Opt-out request for padraic-padraic

### ISSUE THREAD

**Issue by padraic-padraic** [bigcode-project/opt-out-v2#915]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - padraic-padraic/AnxietyFlask
 - padraic-padraic/FreeFL
 - padraic-padraic/NotEnoughQuantum
 - padraic-padraic/PK_ICHack
 - padraic-padraic/QDSim
 - padraic-padraic/RandomCircuits
 - padraic-padraic/SimpleSweeps
 - padraic-padraic/StabilizerCPP
 - padraic-padraic/StabilizerRank
 - padraic-padraic/StabilizerSim
 - padraic-padraic/StaticFlask
 - padraic-padraic/UROP
 - padraic-padraic/ucl-latex-thesis-templates

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
