### ISSUE TITLE
Opt-out request for futzle

### ISSUE THREAD

**Issue by futzle** [bigcode-project/opt-out-v2#918]
I insist that the following data is removed from The Stack:

 - Commits
 - GitHub issue
 - all
 
_Note_: I doubt a human is reading these issues but I hope I’m wrong. Keep your spicy autocomplete off my work.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
