### ISSUE TITLE
Opt-out request for cadadr

### ISSUE THREAD

**Issue by cadadr** [bigcode-project/opt-out-v2#921]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - cadadr/analything
 - cadadr/cadadr
 - cadadr/cadadr.github.io
 - cadadr/configuration
 - cadadr/debian-config-metapackage
 - cadadr/emacs.d
 - cadadr/paper-theme
 - cadadr/python-environment
 - cadadr/tildegit-solene-vger
 - cadadr/txtweb
 - cadadr/user-config
 - cadadr/vendored-elisp
 - cadadr/vim-sunflower
 - cadadr/www

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
