### ISSUE TITLE
Opt-out request for XeroOl

### ISSUE THREAD

**Issue by XeroOl** [bigcode-project/opt-out-v2#922]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - XeroOl/Alcazar
 - XeroOl/GroupGame
 - XeroOl/Portal-Chunk-Finder
 - XeroOl/Puzzle-League
 - XeroOl/SeedLogParser
 - XeroOl/StrongholdFileGenerator
 - XeroOl/bootstrap-test
 - XeroOl/factory-game
 - XeroOl/lcg-reverse
 - XeroOl/lum
 - XeroOl/mirin-package-manager
 - XeroOl/notitg-mirin
 - XeroOl/notitg-xgml
 - XeroOl/notitg-xgml-addons
 - XeroOl/notitgwiki
 - XeroOl/obfusort
 - XeroOl/panel-attack
 - XeroOl/python-instant
 - XeroOl/sm5-mirin
 - XeroOl/xero-mod-loader

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
