### ISSUE TITLE
Opt-out request for scottythered

### ISSUE THREAD

**Issue by scottythered** [bigcode-project/opt-out-v2#923]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - scottythered/ASpace-Reporting-Cleanup
 - scottythered/ArchivesSnake
 - scottythered/Copyright-Matching-Project
 - scottythered/OpenRefine-Workshop
 - scottythered/RDSA-Scopus-Analysis
 - scottythered/Tweet-Relief
 - scottythered/absolute-basics-of-jupyter
 - scottythered/alma-P2E-migration
 - scottythered/apclearing
 - scottythered/aspace-comma-endings
 - scottythered/aspace-derive-box-numbers
 - scottythered/asseta_code
 - scottythered/chemical-agent
 - scottythered/exiegfried
 - scottythered/exlibris-status-api
 - scottythered/intro-to-pandas
 - scottythered/pybursar
 - scottythered/spotify-sniffer
 - scottythered/staticAid
 - scottythered/you-should-make-a-glam-bot

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
