### ISSUE TITLE
Opt-out request for mozkeeler

### ISSUE THREAD

**Issue by mozkeeler** [bigcode-project/opt-out-v2#924]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - mozkeeler/DontHarassMeBro
 - mozkeeler/FirefoxCertificateManager
 - mozkeeler/badvestments
 - mozkeeler/certacus
 - mozkeeler/certificatetransparency
 - mozkeeler/cryptopals
 - mozkeeler/ctjs
 - mozkeeler/dumpshake
 - mozkeeler/euterpe
 - mozkeeler/ev-checker
 - mozkeeler/family-safety-telemetry
 - mozkeeler/fantasizr-slack
 - mozkeeler/mozkeeler.github.io
 - mozkeeler/nss-symkey
 - mozkeeler/nssthreading
 - mozkeeler/ooppkcs11
 - mozkeeler/pandemic-rs
 - mozkeeler/preduce
 - mozkeeler/pycert
 - mozkeeler/redjacket
 - mozkeeler/rust-cascade
 - mozkeeler/rvlvvr-client
 - mozkeeler/spacefac.es
 - mozkeeler/sunlight
 - mozkeeler/tabman

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
