### ISSUE TITLE
Opt-out request for jfbramlett

### ISSUE THREAD

**Issue by jfbramlett** [bigcode-project/opt-out-v2#931]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - jfbramlett/eclipse-che
 - jfbramlett/faker
 - jfbramlett/go-data-loader
 - jfbramlett/go-dynamic-attributes
 - jfbramlett/go-dynamic-runner
 - jfbramlett/go-experiment
 - jfbramlett/gradle-plugin
 - jfbramlett/grpc-example
 - jfbramlett/infinite-scroll
 - jfbramlett/java-tests
 - jfbramlett/nwp-platform-go
 - jfbramlett/nwp-platformv2
 - jfbramlett/python-ouath2
 - jfbramlett/secret-management
 - jfbramlett/service-registry
 - jfbramlett/sirius_python
 - jfbramlett/testframework-cpp
 - jfbramlett/throttle-connectionpool-cpp
 - jfbramlett/version_sample

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
