### ISSUE TITLE
Opt-out request for nspyrison

### ISSUE THREAD

**Issue by nspyrison** [bigcode-project/opt-out-v2#932]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - nspyrison/tourr2vr
 - nspyrison/user2018
 - nspyrison/zmeers.github.io
 - nspyrison/CHI_DU_survey
 - nspyrison/CV
 - nspyrison/Confirmation
 - nspyrison/DimensionReduction
 - nspyrison/ETC3555
 - nspyrison/FIT5147_exampleEdaProj
 - nspyrison/Main_Dev
 - nspyrison/PoC_WebGL_shiny
 - nspyrison/VAST_Challenge_2020
 - nspyrison/citation_habits_ieee
 - nspyrison/confirmation_talk
 - nspyrison/experiment
 - nspyrison/geo_like_me
 - nspyrison/gravitas
 - nspyrison/higgs-boson
 - nspyrison/melb_datathon2020
 - nspyrison/mid_candidature
 - nspyrison/mid_canidature
 - nspyrison/mon_bus_doct_colloq_2018
 - nspyrison/nspyrison_netlify
 - nspyrison/rfacebook_eyewatch
 - nspyrison/rmd-cv
 - nspyrison/sharla.party
 - nspyrison/spinifex_paper
 - nspyrison/spinifex_study
 - nspyrison/tidy_tuesday_national_parks
 - nspyrison/tourr

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
