### ISSUE TITLE
Opt-out request for austin-millan

### ISSUE THREAD

**Issue by austin-millan** [bigcode-project/opt-out-v2#933]
I request that the following data is removed from The Stack:

 - Commits
 - GitHub issue
- austin-millan/MTH356-Notes
- austin-millan/PomoDoneApp
- austin-millan/WAVE-Steganography
- austin-millan/bamboohr-scraper
- austin-millan/crypto-kitty-core
- austin-millan/firefox_config
- austin-millan/go-python-example
- austin-millan/interactive-brokers-openapi
- austin-millan/mandelbulber2-ubuntu
- austin-millan/oldschool-runescape-launcher
- austin-millan/osrs-account-creator
- austin-millan/plex-flask-webhook
- austin-millan/plex-justwatch-webhook
- austin-millan/proxychains-config-generator
- austin-millan/python-terrascript
- austin-millan/react-ssr-sample-golang
- austin-millan/robinhood-client
- austin-millan/robinhood-openapi
- austin-millan/runemate-bot-template
- austin-millan/runemate-bots
- austin-millan/runescape-bot
- austin-millan/runescape-runemate-bundle
- austin-millan/speed-reader-go
- austin-millan/tdameritrade-openapi
- austin-millan/ticker-symbols
- austin-millan/tribalwars-hull-calculator
- austin-millan/tribalwars-pro-tools
- austin-millan/twocaptcha
- austin-millan/useful-scripts
- austin-millan/webull-client
 
_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.
...

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
