### ISSUE TITLE
Opt-out request for viiibe

### ISSUE THREAD

**Issue by fl0werpowers** [bigcode-project/opt-out-v2#935]
I request that the following data is removed from The Stack:

 - all

I used to have the username "viiibe" so my projects are listed under that username. I don't want them to be present under this username either.
 
P.S. For how unspectacular my code is, you're some absolute scumbags for scraping my code without my consent. Fuck off with that shit.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
