### ISSUE TITLE
Opt-out request for achasveachas

### ISSUE THREAD

**Issue by achasveachas** [bigcode-project/opt-out-v2#944]
I request that the following data is removed from The Stack and StackOverflow:

 - All
 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - achasveachas/Algorithms
 - achasveachas/FlyLog
 - achasveachas/GitHub-cleaner
 - achasveachas/Igros-math-trick
 - achasveachas/Interviewing
 - achasveachas/Python
 - achasveachas/SQL-bear-organizer-lab-v-000
 - achasveachas/achasveachas.github.io
 - achasveachas/alternate-side-bot
 - achasveachas/alternate-side-bot-twilio
 - achasveachas/anagram-detector-v-000
 - achasveachas/angular-hello-world-lab-v-000
 - achasveachas/angular-multiple-controllers-lab-v-000
 - achasveachas/app-tracker
 - achasveachas/austin_crime
 - achasveachas/badges-and-schedules-v-000
 - achasveachas/bootstrap-image-carousel-code-along-v-000
 - achasveachas/cancan_lab-v-000
 - achasveachas/careers-blogging-v-000
 - achasveachas/careers-welcome-v-000
 - achasveachas/cartoon-collections-v-000
 - achasveachas/chat-with-the-rabbi
 - achasveachas/chromium
 - achasveachas/codeland
 - achasveachas/collections_practice-v-000
 - achasveachas/compatibility-list-api
 - achasveachas/compatibility-list-client
 - achasveachas/corneal
 - achasveachas/coronavirus-tweeter
 - achasveachas/create-store-lab-v-000
 - achasveachas/dansdeals
 - achasveachas/deal_test
 - achasveachas/deli-counter-v-000
 - achasveachas/developer
 - achasveachas/ehm_track
 - achasveachas/exceptiona-realty
 - achasveachas/exercism-progress
 - achasveachas/exiting-loops-lab-v-000
 - achasveachas/finstagram
 - achasveachas/flatiron-bnb-methods-v-000
 - achasveachas/freddit
 - achasveachas/freddit-jq
 - achasveachas/freddit-test
 - achasveachas/garden-integration-tests
 - achasveachas/git-remote-code-along
 - achasveachas/golang-book
 - achasveachas/head-first-PHP
 - achasveachas/hug-bot
 - achasveachas/javascript-closures-v-000
 - achasveachas/javascript-course-assessment-v-000
 - achasveachas/javascript-first-class-functions-lab-v-000
 - achasveachas/javascript-intro-to-css-v-000
 - achasveachas/javascript-objects-lab-v-000
 - achasveachas/javascript-objects-v-000
 - achasveachas/js-basics-online-shopping-lab-v-000
 - achasveachas/js-deli-counter-v-000
 - achasveachas/js-jquery-basics-lab-v-000
 - achasveachas/js-tictactoe-rails-api-v-000
 - achasveachas/js-weather-api-ajax-v-000
 - achasveachas/key-for-min-value-v-000
 - achasveachas/laravel_todo
 - achasveachas/learn-expert-common-errors
 - achasveachas/learncpp
 - achasveachas/learningdotnet
 - achasveachas/linked-list-lab-v-000
 - achasveachas/oo-email-parser-v-000
 - achasveachas/oo-tic-tac-toe-q-000
 - achasveachas/personal-site
 - achasveachas/pitgama
 - achasveachas/pragma
 - achasveachas/prime-ruby-v-000
 - achasveachas/project-euler-10001st-prime-q-000
 - achasveachas/project-euler-collatz-q-000
 - achasveachas/project-euler-even-fibonacci-q-000
 - achasveachas/project-euler-largest-palindrome-product-q-000
 - achasveachas/project-euler-largest-prime-factor-q-000
 - achasveachas/project-euler-multiples-3-5-q-000
 - achasveachas/project-euler-power-digit-sum-q-000
 - achasveachas/project-euler-smallest-multiple-q-000
 - achasveachas/project-euler-sum-square-difference-q-000
 - achasveachas/pronoun_highlighter
 - achasveachas/question-API
 - achasveachas/rails-amusement-park-v-000
 - achasveachas/rails-github-api-v-000
 - achasveachas/rails-long-running-tasks-readme-v-000
 - achasveachas/rails_challenge
 - achasveachas/react-actions-lab-v-000
 - achasveachas/react-components-v-000
 - achasveachas/react-container-components-lab-v-000
 - achasveachas/react-create-element-v-000
 - achasveachas/react-event-system-lab-v-000
 - achasveachas/react-forms-lab-v-000
 - achasveachas/react-jsx-v-000
 - achasveachas/react-passing-props-lab-v-000
 - achasveachas/react-props-and-state-lab-v-000
 - achasveachas/react-spy-on-render
 - achasveachas/react-type-ahead-wikipedia-search-lab-v-000
 - achasveachas/react-yt-tutorial-dashboard
 - achasveachas/redux-pets-store-example
 - achasveachas/redux-thunk-lab-v-000
 - achasveachas/refactoring-workshop
 - achasveachas/reverse-each-word-v-000
 - achasveachas/roger
 - achasveachas/ruby-collaborating-objects-lab-v-000
 - achasveachas/ruby-inheritance-lab-v-000
 - achasveachas/ruby-music-library-cli-v-000
 - achasveachas/sinatra-ar-crud-lab-v-000
 - achasveachas/sinatra-basic-sessions-lab-v-000
 - achasveachas/sinatra-mvc-lab-v-000
 - achasveachas/sinatra-nested-forms-v-000
 - achasveachas/sinatra_igros
 - achasveachas/sinatribes
 - achasveachas/solidus_gateway
 - achasveachas/solidus_paybright
 - achasveachas/sql-library-lab-v-000
 - achasveachas/square_array-v-000
 - achasveachas/tdd-app
 - achasveachas/tic-tac-toe-rb-q-000
 - achasveachas/todo-mvc
 - achasveachas/torahandtech
 - achasveachas/triangle-classification-v-000
 - achasveachas/triplebyte
 - achasveachas/ttt-7-valid-move-q-000
 - achasveachas/ttt-game-status-q-000
 - achasveachas/ttt-with-ai-project-v-000
 - achasveachas/twilio_cat_facts
 - achasveachas/windows-tools-release
 - achasveachas/yechiel-kalmenson-resume
 - achasveachas/yt-tutorial-dashboard

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
