### ISSUE TITLE
Opt-out request for UWbadgers16

### ISSUE THREAD

**Issue by john-cabaj** [bigcode-project/opt-out-v2#951]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - UWbadgers16/BrainwaveAuthentication
 - UWbadgers16/DataStructures
 - UWbadgers16/DecisionTree
 - UWbadgers16/DecisionTreeJava
 - UWbadgers16/PhotoEnhancement
 - UWbadgers16/sim-R10K-pure

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
