### ISSUE TITLE
Opt-out request for Rezmason

### ISSUE THREAD

**Issue by Rezmason** [bigcode-project/opt-out-v2#954]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: Rezmason
 - Rezmason/Derivey
 - Rezmason/GoodiesFromTal-Heim
 - Rezmason/MacinTS
 - Rezmason/WebSaver
 - Rezmason/box2d
 - Rezmason/engram
 - Rezmason/gh_pages_module_imports
 - Rezmason/hat
 - Rezmason/i_solated
 - Rezmason/know_thyself
 - Rezmason/massinova_recovery
 - Rezmason/matrix
 - Rezmason/openfl-html5-dom
 - Rezmason/rezmason_limechat_theme
 - Rezmason/rm_logo_3d
 - Rezmason/wireworldas3

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
