### ISSUE TITLE
Opt-out request for bobmcwhirter

### ISSUE THREAD

**Issue by bobmcwhirter** [bigcode-project/opt-out-v2#957]
I request that the following data is removed from The Stack:

 - Commits
 - GitHub issue

bobmcwhirter/Toes
bobmcwhirter/arquillian.github.com
bobmcwhirter/awestruct
bobmcwhirter/awestruct2
bobmcwhirter/birdanalysis
bobmcwhirter/bob.mcwhirter.org
bobmcwhirter/bundler2rpm
bobmcwhirter/cfr14
bobmcwhirter/connect-keycloak
bobmcwhirter/connect-keycloak-example
bobmcwhirter/core-management
bobmcwhirter/craptastic
bobmcwhirter/defmt
bobmcwhirter/deltacloud-client-java
bobmcwhirter/deltacloud-client-ruby
bobmcwhirter/deltacloud-docs
bobmcwhirter/deltacloud-driver-ec2
bobmcwhirter/deltacloud-driver-mock
bobmcwhirter/deltacloud-framework
bobmcwhirter/drogue-wasm
bobmcwhirter/epd-waveshare
bobmcwhirter/fungal
bobmcwhirter/gitbook-plugin-include-codeblock
bobmcwhirter/hawkular-agent
bobmcwhirter/incomplete-unsafe
bobmcwhirter/jboss-deployers
bobmcwhirter/jboss-haze
bobmcwhirter/jboss-rails-support
bobmcwhirter/jitescript
bobmcwhirter/jruby-maven-plugins
bobmcwhirter/jsengine
bobmcwhirter/keycloak-authenticated-client
bobmcwhirter/keycloak-client
bobmcwhirter/maven-plugins
bobmcwhirter/module-info
bobmcwhirter/my-app
bobmcwhirter/oddthesis.org
bobmcwhirter/ovirtex
bobmcwhirter/plectrum
bobmcwhirter/rubyunderground.org
bobmcwhirter/scratch-drogue-device-example
bobmcwhirter/smallrye-config
bobmcwhirter/stm32-data
bobmcwhirter/stm32-metapac
bobmcwhirter/stm32f4xx-hal
bobmcwhirter/stompbreak
bobmcwhirter/swarm-preso
bobmcwhirter/thorntail
bobmcwhirter/tileotron
bobmcwhirter/torquespec
bobmcwhirter/vertx-activemq-jmsclient-module
bobmcwhirter/vertx-activemq-module
bobmcwhirter/vertx-infinispan-module
bobmcwhirter/vertx-quartz-module
bobmcwhirter/vfs
bobmcwhirter/wildfly-boot
bobmcwhirter/wildfly-swarm-fraction-plugin
bobmcwhirter/wildfly-swarm-howto
bobmcwhirter/wildfly-swarm-keycloak

_Note_: opt-out is not consent

**Comment by bobmcwhirter** [comment]
Ping... Is this resolved?

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
