### ISSUE TITLE
Opt-out request for nulligor

### ISSUE THREAD

**Issue by nulligor** [bigcode-project/opt-out-v2#961]
I request that the following data is removed from The Stack.

 - nulligor/chars-counterattack
 - nulligor/drillr
 - nulligor/nulligor.github.io
 - nulligor/pmapv
 - nulligor/poop-killer
 - nulligor/project-euler
 - nulligor/stamps
 - nulligor/ygo-psone-clone

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
