### ISSUE TITLE
Opt-out request for matomatical

### ISSUE THREAD

**Issue by matomatical** [bigcode-project/opt-out-v2#963]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - matomatical/8bIT-Project
 - matomatical/AI-and-society
 - matomatical/AI-projectB
 - matomatical/AI2016-notes
 - matomatical/CS-project1
 - matomatical/CS2016-tests
 - matomatical/Goatlang-Compiler
 - matomatical/Reflections
 - matomatical/RoPaSci-360-tournament
 - matomatical/SML-project-1
 - matomatical/alarm-clock
 - matomatical/algorithms
 - matomatical/cse-graph-layout
 - matomatical/diega-vu
 - matomatical/expectiles
 - matomatical/fancy-hrule
 - matomatical/gmm-em-algorithm
 - matomatical/hackchat-plus-ff
 - matomatical/life
 - matomatical/memograph-decks
 - matomatical/neuRL
 - matomatical/poke-julian
 - matomatical/qotd
 - matomatical/quote-framer
 - matomatical/reMarkable-kaitai
 - matomatical/simple-search
 - matomatical/tabular-distRL
 - matomatical/waterman
 - all

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
