### ISSUE TITLE
Opt-out request for taliastocks

### ISSUE THREAD

**Issue by taliastocks** [bigcode-project/opt-out-v2#966]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: https://stackoverflow.com/users/506511/talia-stocks
 - taliastocks/dotfiles
 - taliastocks/itsmoredangerous
 - taliastocks/nonstdlib
 - taliastocks/ptest
 - taliastocks/sound
 - sibilance (organization)
 - all

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
