### ISSUE TITLE
Opt-out request for durka

### ISSUE THREAD

**Issue by durka** [bigcode-project/opt-out-v2#968]
I demand that the following data is immediately removed from all past, current and future versions of The Stack and StackOverflow:

 - all

This opt-out request covers all data that I have currently, previously, and in the future on Github. You did not ask for consent to create this dataset. This is a gross violation of ethics and user trust. Do better.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
