### ISSUE TITLE
Opt-out request for TheWatcher

### ISSUE THREAD

**Issue by TheWatcher** [bigcode-project/opt-out-v2#972]
I request that the following data is removed from The Stack and StackOverflow:

 - TheWatcher/Aviary
 - TheWatcher/GitLab-API-Basic
 - TheWatcher/GooCompleter
 - TheWatcher/Laundry
 - TheWatcher/MultiSelect
 - TheWatcher/REST-Client
 - TheWatcher/ScrollSpy
 - TheWatcher/calendar_tools
 - TheWatcher/correcthorsebatterystaple
 - TheWatcher/grbl-laser
 - TheWatcher/irclogs
 - TheWatcher/logbot3
 - TheWatcher/orb
 - TheWatcher/pihole-facebook
 - TheWatcher/sheet2table
 - TheWatcher/surv_tools
 - TheWatcher/titor
 - TheWatcher/webperl

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
