### ISSUE TITLE
Opt-out request for lioman

### ISSUE THREAD

**Issue by lioman** [bigcode-project/opt-out-v2#973]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - lioman/KirAndCDN
 - lioman/angular-bug
 - lioman/css-frameworks
 - lioman/gamificationPoll
 - lioman/gedit-wakatime
 - lioman/geodesic_circle
 - lioman/isso
 - lioman/logos
 - lioman/mapstats
 - lioman/ng-chrome
 - lioman/ng-firefox
 - lioman/pinax-stripe
 - lioman/punch
 - lioman/python-safety
 - lioman/show_vagrant_box
 - lioman/todoro
 - lioman/typescript-book
 - lioman/vertSysVagrant
 - lioman/vimrc

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
