### ISSUE TITLE
Opt-out request for florisre

### ISSUE THREAD

**Issue by florisre** [bigcode-project/opt-out-v2#978]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - florisre/Arabisch-SS19
 - florisre/Avicenna
 - florisre/mathe-algebra
 - florisre/modelltheorie

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
