### ISSUE TITLE
Opt-out request for partulaj

### ISSUE THREAD

**Issue by partulaj** [bigcode-project/opt-out-v2#983]
I request that the following data is removed from The Stack:

 - Commits
 - GitHub issue
 - partulaj/edelgard
 - partulaj/iutvalence-android-meteo
 - partulaj/iutvalence-java-tp-2014-g1A-binome6
 - partulaj/iutvalence-junit-tp-2014-g1A-binome6
 - partulaj/iutvalence-multiagent-fourmis
 - partulaj/iutvalence-python-mangacollection

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
