### ISSUE TITLE
Opt-out request for JonRowe

### ISSUE THREAD

**Issue by JonRowe** [bigcode-project/opt-out-v2#984]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - JonRowe/Catwalk
 - JonRowe/ElixirHackNight-01-2014
 - JonRowe/FiberPool
 - JonRowe/H5F
 - JonRowe/HighInFiber
 - JonRowe/Jekyll_Issue_Reproduction
 - JonRowe/MongoAdaptor
 - JonRowe/NRG-TV-Team
 - JonRowe/SYD-HOB
 - JonRowe/aruba
 - JonRowe/bamboo
 - JonRowe/basics-extra
 - JonRowe/battleship
 - JonRowe/blog
 - JonRowe/bundler-issue
 - JonRowe/busbar
 - JonRowe/codetriage
 - JonRowe/connect-level
 - JonRowe/database_cleaner
 - JonRowe/demo_absinthe_null_bug
 - JonRowe/docker-ci
 - JonRowe/dogma
 - JonRowe/dotfiles
 - JonRowe/dpl
 - JonRowe/dragonfly
 - JonRowe/ecto
 - JonRowe/elm-dygraphs
 - JonRowe/elm-jwt
 - JonRowe/emojis
 - JonRowe/ex_aws_http_test_adaptor
 - JonRowe/exercism_exercises
 - JonRowe/expect
 - JonRowe/gda-react-demo
 - JonRowe/github-webhook-auth
 - JonRowe/grab
 - JonRowe/graph-demo
 - JonRowe/hadoop-hacknight
 - JonRowe/honk
 - JonRowe/hub
 - JonRowe/jonrowe-dot-dev.github.com
 - JonRowe/jonrowe.github.com
 - JonRowe/kiwirubynz-2017
 - JonRowe/lastfm-stalker
 - JonRowe/learnyousomethings.com
 - JonRowe/locomotion
 - JonRowe/merb_couchstrap
 - JonRowe/middleman
 - JonRowe/middleman-asmiddleware
 - JonRowe/middleman-sprockets
 - JonRowe/minibase
 - JonRowe/mongo-configure
 - JonRowe/mongomapper
 - JonRowe/n2k_backpack
 - JonRowe/nyan-cat-formatter
 - JonRowe/oauth2-provider
 - JonRowe/page_up
 - JonRowe/pg_adaptor
 - JonRowe/ping_pong
 - JonRowe/plug-test
 - JonRowe/postgres-notification-issue
 - JonRowe/pr
 - JonRowe/puffing-billy
 - JonRowe/que
 - JonRowe/rack-logs
 - JonRowe/rack-neverlocal
 - JonRowe/rack-nullsession
 - JonRowe/rack-when
 - JonRowe/rails-controller-testing
 - JonRowe/rails4_rspec_error
 - JonRowe/riot-code-demo
 - JonRowe/rollbax-error-example
 - JonRowe/rspec-core
 - JonRowe/rspec-retry
 - JonRowe/rspec-tests
 - JonRowe/rubyconfau2014-zerotohero
 - JonRowe/rubyconfau2015-rspec-plusplus
 - JonRowe/rubywarrior
 - JonRowe/setsumei
 - JonRowe/sidekiq-restart
 - JonRowe/simplecov-inline-html
 - JonRowe/speedtrack
 - JonRowe/teacup
 - JonRowe/warden-always-authenticate
 - JonRowe/warden-redirect
 - JonRowe/warden-test-issue-16
 - JonRowe/warden_omniauth
 - JonRowe/webstub
 - JonRowe/wrapup
 - JonRowe/zuckermo

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
