### ISSUE TITLE
Opt-out request for rspec

### ISSUE THREAD

**Issue by JonRowe** [bigcode-project/opt-out-v2#985]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - rspec/docker-ci
 - rspec/rspec
 - rspec/rspec-activemodel-mocks
 - rspec/rspec-autotest
 - rspec/rspec-core
 - rspec/rspec-dev
 - rspec/rspec-expectations
 - rspec/rspec-its
 - rspec/rspec-legacy_formatters
 - rspec/rspec-mocks
 - rspec/rspec-monorepo-migration
 - rspec/rspec-monorepo-prototype
 - rspec/rspec-rails
 - rspec/rspec-support

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
