### ISSUE TITLE
Opt-out request for Rekyt

### ISSUE THREAD

**Issue by Rekyt** [bigcode-project/opt-out-v2#990]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - Rekyt/Advanced_R
 - Rekyt/BIOL548O.github.io
 - Rekyt/Bioregionalization
 - Rekyt/FD
 - Rekyt/Lynch-lab-Report
 - Rekyt/RBIEN
 - Rekyt/Rare7
 - Rekyt/WitOMI
 - Rekyt/ade4
 - Rekyt/apibunny
 - Rekyt/applied_sp_data
 - Rekyt/biblio
 - Rekyt/blogdown_source
 - Rekyt/climateStability
 - Rekyt/dependency
 - Rekyt/divr
 - Rekyt/donnees
 - Rekyt/drakepkgexample
 - Rekyt/eml_reader
 - Rekyt/fdcoexist
 - Rekyt/fddimensionality_ms
 - Rekyt/functional_biogeo_practical
 - Rekyt/funrar
 - Rekyt/funrar.metrics
 - Rekyt/gff_retriever
 - Rekyt/git-playground
 - Rekyt/iNEXT
 - Rekyt/intro_ggplot2_figures
 - Rekyt/keygen
 - Rekyt/letsR
 - Rekyt/lynchlabpresentation2014
 - Rekyt/mamm_funrar
 - Rekyt/nobelprizes
 - Rekyt/outlieR
 - Rekyt/planets
 - Rekyt/poster_alientraitgaps_sfe_metz_2022
 - Rekyt/rangeBuilder
 - Rekyt/rekyt.github.io
 - Rekyt/report-ecofog-2015
 - Rekyt/report-isem-2014
 - Rekyt/report-template
 - Rekyt/rhub
 - Rekyt/rprojroot
 - Rekyt/rromeo
 - Rekyt/rwdpa
 - Rekyt/ssdms_saturation_richness
 - Rekyt/stat_rethinking
 - Rekyt/taxo_harmonization
 - Rekyt/vcr
 - Rekyt/zoontutorials
 - all

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
