### ISSUE TITLE
Opt-out request for gerbercj

### ISSUE THREAD

**Issue by gerbercj** [bigcode-project/opt-out-v2#994]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - gerbercj/.emacs.d
 - gerbercj/adventofcode
 - gerbercj/challenge
 - gerbercj/cs171-hw0-gerber-chris
 - gerbercj/cs171-hw1-gerber-chris
 - gerbercj/cs171-hw2-gerber-chris
 - gerbercj/cs171-hw3-gerber-chris
 - gerbercj/cs171-hw4-gerber-chris
 - gerbercj/cscie34
 - gerbercj/dotfiles
 - gerbercj/fpm
 - gerbercj/mobilelocal
 - gerbercj/nsa
 - gerbercj/ritualistic

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
