### ISSUE TITLE
Opt-out request for dg01d

### ISSUE THREAD

**Issue by dg01d** [bigcode-project/opt-out-v2#997]
I request that the following data is removed from The Stack and StackOverflow:

 - Commits
 - GitHub issue
 - StackOverflow: <INSERT_STACKOVERFLOW_USERNAME_HERE>
 - dg01d/AfterBore
 - dg01d/KnownLike
 - dg01d/KnownPnut
 - dg01d/SearchLink.popclipext
 - dg01d/austere-hugo-theme
 - dg01d/bitbar-worldcup
 - dg01d/bobfarm
 - dg01d/covid-bitbar
 - dg01d/mp.el
 - dg01d/nanopub
 - dg01d/reproach
 - dg01d/world_cup_json

_Note_: If you don't want all resources to be included just remove the elements from the list above. If you would like to exclude all repositories and resources just add a single element "all" to the list.

**Comment by lvwerra** [comment]
Your opt-out request has been processed and your data was removed in version v2.1 of The Stack and all future versions.

[PROCESSED]
